### ISSUE TITLE
[Bug] When updating library, library update is not in order 

### ISSUE THREAD

**Issue by vipzzx** [jobobby04/TachiyomiSY#100]
## Device information
* Tachiyomi version: r229
* Android version: 10
* Device: Note9

## Steps to reproduce
1. Update library
2. Check library

### Expected behavior
Library update should be in order where the ones on top are the newest update. 

### Actual behavior
Not in order. 

## Other details
![20200912_125841.jpg](https://user-images.githubusercontent.com/59638889/93000687-fe5f9d80-f4f7-11ea-8648-68b963d2a537.jpg)

**Comment by jobobby04** [comment]
Updates are based on when you got the updates, not when they are released, I dont think I am going to change that
🤷‍♂️

**Comment by vipzzx** [comment]
Yeah but I actually got all the updates already except for the 1st and 3rd one. After another library update the 3rd one appeared at that spot. Then when I manually refreshed the 1st manga ch 7.5 showed up on the top.

**Comment by jobobby04** [comment]
I am leaning toward that being a extension issue, I cant see any reason why that would happen

**Comment by vipzzx** [comment]
Hmm don't seem to have that problem on stable ![Screenshot_20200912-132531_Tachiyomi.jpg](https://user-images.githubusercontent.com/59638889/93001208-6fed1b00-f4fb-11ea-9ea1-2028d2932998.jpg)
