### ISSUE TITLE
Add Migration show entry like Tachiyomi does

### ISSUE THREAD

**Issue by molitar** [jobobby04/TachiyomiSY#1007]
### Describe your suggested feature

Can we please get a show entry option in migration just like the official Tachiyomi has?  Right now it is impossible to find which site has the latest chapters when you have to migrate.

### Other details

Current Process
1. Wait to migrate finish finding first site to migrate
2. Click on it and see if it same or more chapters
3. If it has less than you have to manual search
4. Select another site 
5. Check if it has more or same chapters
6. click on manual search (wait for search again)

This is really ridiculous to find a new site that has the manga.  Tachiyomi immediately goes to manual search screen and you click on selection and show entry and immediately see number of chapters.  This is a single search so it does not repeatedly scrap all sites causing a ton of searches so you can find a site to migrate.  Can you please adopt this feature in manual search so we can find the new site to migrate it to without wasteful scrapping of sites?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
The original migration entry like Tachiyomi is still there:
After the migration search which showing original manga on the left and suggested migration on the right, hit the three dot button on the right and select "Search manually"

**Comment by NeKoOuO** [comment]
"I think this kind of feature should be raised as an official issue. It seems more appropriate that way."

**Comment by molitar** [comment]
Actually it is in the official Tachiyomi.  When you do migration it has a show entry so you can see how many chapters before you do the migration.

**Comment by jobobby04** [comment]
I don't feel like this is a needed feature, the current migration gives you all the features of the main Tachi one + bulk support. Change the settings in the pre-migration if you want the source with the most chapters
