### ISSUE TITLE
Automatically download all cover when restore from backup

### ISSUE THREAD

**Issue by ikhoeyZX** [jobobby04/TachiyomiSY#1008]
### Describe your suggested feature

it would be better if i can automatically download all cover without scrolling 2230 manga in library and it took more than 2 hour to complete this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
"I feel like this is a bit idealistic."

**Comment by jobobby04** [comment]
I don't think this is possible, I imagine it would increase backup restore time by a lot and I would rather keep it as performant as possible
