### ISSUE TITLE
downloads freeze when one page left

### ISSUE THREAD

**Issue by ldominguez91** [jobobby04/TachiyomiSY#1012]
### Steps to reproduce

Select volume
Download

### Expected behavior

The download it's complete

### Actual behavior

Download everything but it stops at the last page 
![Screenshot_20240114-125523~2](https://github.com/jobobby04/TachiyomiSY/assets/134753121/b45507d2-0a66-4881-8df5-81ac5c59b322)

### Tachiyomi version

1.10.1

### Android version

android 0

### Device

tablet lenovo

### Other details

It happens with some volumes, not with all

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a source issue

**Comment by NeKoOuO** [comment]
@ldominguez91 [Report here](https://github.com/keiyoushi/extensions-source/issues/new?template=01_report_issue.yml)
