### ISSUE TITLE
Add read latest chapter and mark all as read buttons

### ISSUE THREAD

**Issue by squee666** [jobobby04/TachiyomiSY#1014]
### Describe your suggested feature

Have the show unread count button in bottom right/left
Then touching it opens the latest unread chapter, I know j2k does this at least.

Also have a button beside the download button in an entry that lets me mark all chapters as read. It's much easier than holding a chapter marking all previous as read then swiping said chapter as read.
Saves time when adding new/old entries, migrating etc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Either tap and hold or swipe, I don't think adding another button will help UX.

Also we have migration so you shouldn't be manually migrating entries.

In general design changes are not currently planned.

**Comment by squee666** [comment]
Fair enough but at least having a button to read latest unread chapter directly from library
 would be very convenient j2k allows this but sy doesn't unless I'm missing something.
It doesn't clutter UI and is very practical example image shown
![Screenshot_20240115-025133](https://github.com/jobobby04/TachiyomiSY/assets/628576/a4e272d7-1f62-4ab3-ae8d-407cbe54c108)

**Comment by squee666** [comment]
correction its even advertised as a feature on j2k's github

![image](https://github.com/jobobby04/TachiyomiSY/assets/628576/9f29aa68-dc2e-4fcd-938c-6c91d17e0d7a)

**Comment by jobobby04** [comment]
Your talking about the continue reading button, thats available in SY under the filter icon in the library.

**Comment by squee666** [comment]
okay apologies yeah thats exaclty what i meant busy migrating and somethings are enable by default or require tweaking
