### ISSUE TITLE
Pica Comic extension bad base-64

### ISSUE THREAD

**Issue by KuanKan410** [jobobby04/TachiyomiSY#1015]
### Steps to reproduce

When TachiyomiSY is installed and first opened, the exstension is able to use after I input my username and password of picacomic. But when I opened for the second time, the extension shows "IllegalArgumentException: bad base-64"

### Expected behavior

I can watch manga from picacomic.

### Actual behavior

In webview, it shows
```
{
  "code": 400,
  "error": "1001",
  "message": "the format of accept header is invalid"
}
``` 

### Tachiyomi version

TachiyomiSY 1.10.1

### Android version

Android 13

### Device

OnePlus 8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Source issues should be reported at their repository

**Comment by NeKoOuO** [comment]
> ### Steps to reproduce
> 
> When TachiyomiSY is installed and first opened, the exstension is able to use after I input my username and password of picacomic. But when I opened for the second time, the extension shows "IllegalArgumentException: bad base-64"
> 
> ### Expected behavior
> 
> I can watch manga from picacomic.
> 
> ### Actual behavior
> 
> In webview, it shows
> ```
> {
>   "code": 400,
>   "error": "1001",
>   "message": "the format of accept header is invalid"
> }
> ``` 
> 
> 
> ### Crash logs
> 
> _No response_
> 
> ### Tachiyomi version
> 
> TachiyomiSY 1.10.1
> 
> ### Android version
> 
> Android 13
> 
> ### Device
> 
> OnePlus 8 pro
> 
> ### Other details
> 
> _No response_
> 
> ### Acknowledgements
> 
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> - [X] I have written a short but informative title.
> - [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
> - [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
> - [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
> - [X] I have updated all installed extensions.
> - [X] I will fill out all of the requested information in this form.

https://github.com/keiyoushi/extensions-source/issues/new?template=01_report_issue.yml Report here
