### ISSUE TITLE
Downloadable Chapters Cant Show

### ISSUE THREAD

**Issue by mawrand** [jobobby04/TachiyomiSY#1016]
### Steps to reproduce

So, when i migrate from Tachiyomi to TachiyomiSY i can migrate all backup Library. But the problem is, when i try to search Chapters already downloaded in Tachiyomi before. The Chapters not showing on TachiyomiSY.

Im already move the data into Download Folder for TachiyomiSY, but still cant show it 

### Expected behavior

It supposed to read all downloaded chapter.

### Actual behavior

The downloaded chapters not showing at all

### Tachiyomi version

1.10.1

### Android version

Android 12

### Device

Redmi Note 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
More -> Settings -> Advanced -> Invalidate Download index

**Comment by mawrand** [comment]
> More -> Settings -> Advanced -> Invalidate Download index

Thanks sir, it works for me.
