### ISSUE TITLE
App crashes when you scroll down chapters while having tags scroll sideways

### ISSUE THREAD

**Issue by JRodster** [jobobby04/TachiyomiSY#1017]
### Steps to reproduce

1) Go into a manga that has a long list of tags (so that you can keep the tags scrolling sideways by swiping rapidly from right to left) and enough chapters (so you can scroll down).
2) Rapidly swipe the tags from right to left, to make them scroll for a bit.
3) While the tags are still scrolling, rapidly scroll to go down the chapter list.
4) TachiyomiSY crashes right after.

![Screenshot_20240114-233819_02](https://github.com/jobobby04/TachiyomiSY/assets/60984975/68b7656b-2247-4796-9e10-97f0daca500a)

### Expected behavior

The app shouldn't crash, and you should be able to keep scrolling down the chapter list.

### Actual behavior

The app suddenly crashes and exits.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/13936267/tachiyomi_crash_logs.txt)

### Tachiyomi version

1.10.1

### Android version

Android 11

### Device

OnePlus 8

### Other details

I blocked out some of the major readily-identifiable manga details (especially things like title and description text) in the attached image, just in case.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Dammit compose
