### ISSUE TITLE
[Feature Request] ' in library ' tag while browsing sources and manga cover preview

### ISSUE THREAD

**Issue by Saurzen** [jobobby04/TachiyomiSY#102]
' In library ' tag stands out more than dim Manga covers. 
Well manga cover preview would be nice. 
Already feature are available on neko and j2k.
U could integrate two themes like one like neko and other like tachiyomi. 
![806529877_167223](https://user-images.githubusercontent.com/47153405/93017991-68586f80-f5ea-11ea-9d2c-f6c67f984e15.jpg)
![107918158_321715](https://user-images.githubusercontent.com/47153405/93017996-6a223300-f5ea-11ea-8107-61a4ac3b59af.jpg)

**Comment by joseph619** [comment]
Manga cover preview is already available

**Comment by jobobby04** [comment]
I dont really feel a need for this, I will only add it to SY if it gets added to the main Tachiyomi
