### ISSUE TITLE
Stop download on the background when lock the screen after some time

### ISSUE THREAD

**Issue by dtantono** [jobobby04/TachiyomiSY#1020]
### Steps to reproduce

1. download the mangas
2. lock the screen
3. it says downloading
4. Couple of hours later, it stops downloading

### Expected behavior

it should downloading until it finished

### Actual behavior

it stops downloading

### Tachiyomi version

1.10.1

### Android version

Android 11

### Device

Xperia 1 iii

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
"It is possible that you just didn't switch to the backstage resident mode."
Try **Settings -> Advanced -> Background activity**

**Comment by dtantono** [comment]
do you mean battery optimization part?

**Comment by NeKoOuO** [comment]
> do you mean enable battery optimization part?

Yep ,did you try it?
