### ISSUE TITLE
[**Hide**] Categories

### ISSUE THREAD

**Issue by Kalip514** [jobobby04/TachiyomiSY#1027]
### Describe your suggested feature

I would very much like to hide my NSFW categories from prying eyes. . . . 

Not hide manga. . . . 
Not hide Manhwa. . . .
Not hide NSFW sources. . . . .

Hide Categories. . . . 

TQ

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
This function has been available for a long time

**Comment by Kalip514** [comment]
REALLY !!! Tell me how !!!

I try to find it but i just can't find it

**Comment by Kalip514** [comment]
> This function has been available for a long time

REALLY !!! Tell me how !!!

I try to find it but i just can't find it

**Comment by NeKoOuO** [comment]
You just need to make good use of the filter function **Library -> Filter -> Lewd**

**Comment by Kalip514** [comment]
> You just need to make good use of the filter function Try **Library -> Filter -> Lewd**

Ok. . . . It just hide my manga/manhwa. . . . not the categories. . . .  BUT !!!

this could work, I just need to create a categories name [ Read Later ] while filter **Lewd** is on but the content inside is FULL of NSFW

Its just I right now my categories is like Manga / Manhwa / [H]

But this still works. . . . Its not **HIDE CATEGORIES** that I want but still nice enough. . . . 

Thanks *NeKoOuo
