### ISSUE TITLE
Remove "unable to resolve host" popup by default unless user tries to refresh the series manually

### ISSUE THREAD

**Issue by zainzaidi37** [jobobby04/TachiyomiSY#1028]
### Describe your suggested feature

SY works nicely but it would be great if it doesn't show the "unable to resolve host" popup unless we refresh the series. It works like this in tachi/mihon and would be great if it's implemented in SY too.

Like if you try viewing a series without internet, even if you have downloaded chapters, you face this annoying pop-up.

For demonstration, I'm attaching two images. First image is SY, second is tachi/mihon:
![image](https://github.com/jobobby04/TachiyomiSY/assets/148543148/877071b4-0c2a-488d-9382-803a480931ee)
![image](https://github.com/jobobby04/TachiyomiSY/assets/148543148/7235e7ed-fac9-48ad-8328-57d5b251c45d)

### Other details

If accepted, I hope this fix can be implemented throughout the extensions including EHentai one, which is created especially for SY. Thanks! 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Efreak** [comment]
Possible better idea: don't try to make network connections when the device isn't online (WiFi or data). This might require an extra permission, or the existing permissions for Internet access might be enough.

**Comment by jobobby04** [comment]
Its popping up because you are having a connection issue
