### ISSUE TITLE
Plz Improve Ui Like j2k

### ISSUE THREAD

**Issue by AbdelrahmanElnezamy121** [jobobby04/TachiyomiSY#1029]
### Describe your suggested feature

new modern ui

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
No
