### ISSUE TITLE
[Feature Request] <migrate download>

### ISSUE THREAD

**Issue by SanOtaku09** [jobobby04/TachiyomiSY#103]
If tachiyomi name ch downloads with chapter numbers instead of source title.
Than tachiyomi can even migrate download 
So here the thing you need to mod 
When migrating change folder name to the name of current source 
and also 
name downloaded ch with chapter number instead of source title and tachiyomi will be able to migrate downloads too
Cause tachiyomi look for download at startup. 
So it should work

It will help allot cause my allot of downloads get wasted just because i have to migrate from one source to another

**Comment by joseph619** [comment]
This isn't really doable, there is a new Migrate to Local coming in future. You can use that instead.

**Comment by jobobby04** [comment]
Its not really possible, sources usually do not give chapter numbers, only how they are ordered
