### ISSUE TITLE
Bring back "Per-category Display" from v1.9.4

### ISSUE THREAD

**Issue by anrg77** [jobobby04/TachiyomiSY#1031]
### Describe your suggested feature

I don't know if this is already planned to be brought back after completing shifting to Mihon

If Category 1 >Display >Cover only grid // then it should only affect Category 1 only and not all other categories

![V1 9 4](https://github.com/jobobby04/TachiyomiSY/assets/96700422/16a5289e-4b53-47cc-8ba5-dda1af8ea873)
![v1 9 4 Different Per- category display settings](https://github.com/jobobby04/TachiyomiSY/assets/96700422/d5ecef99-1edd-4fa2-bf7f-af8e701b7c60)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
No plans to bring it back
