### ISSUE TITLE
Possibility to import from tachiyomi backup

### ISSUE THREAD

**Issue by angeousta** [jobobby04/TachiyomiSY#1034]
### Describe your suggested feature

Possibility to import from a tachiyomi backup

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
100% you just didn't try it.
