### ISSUE TITLE
Updates not working

### ISSUE THREAD

**Issue by xicor22** [jobobby04/TachiyomiSY#1037]
### Steps to reproduce

1. Open the app and click on the three dots on the top right
2. click on update library

### Expected behavior

After clicking the update library button, an updating library in app toast should pop up with a notification and in 2-3 minutes, my library should be updated with new chapters (updates from manga's/manhua's that i have started)

### Actual behavior

After clicking the update library button, an in-app toast pops up saying "updating library" and a notification comes up regarding the library update but after a second the notification disappears and the update stops. Individual update on Manga/manhua does work.  

### Crash logs

The app doesn't experience any crashes itself only the update process stops so instead of app crash logs, I'm providing my device logs.
[log.txt](https://github.com/jobobby04/TachiyomiSY/files/13985793/log.txt)

### Tachiyomi version

1.10.2

### Android version

Android 14

### Device

Realme Narzo 30

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AnuragAR7** [comment]
Faced the same issue today. Try Backing up, Reinstalling and Restoring it worked for me.

**Comment by DemiAi** [comment]
Try turning off all the smart update settings and restart the app. That works for me when the manga isn't updating.

**Comment by jobobby04** [comment]
https://github.com/jobobby04/TachiyomiSY/issues/1011#issuecomment-1890998040

**Comment by xicor22** [comment]
Update : After reinstalling the app again and restoring the backup, everything's working as it should.
