### ISSUE TITLE
[Feature Request] Download upon adding manga to library.

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#104]
## Why/User Benefit/User Problem

(So, right now whenever I add new manga to the library, usually I queued it immediately for download.) 

(It would be much better to have an option when you add new manga you will be asked to whether to download or not, rather than doing it from (download>All/Custom).

## What/Requirements
(A Toggle option on `setting>library>(whatever it would be called)`, when it's enabled next steps is new manga is added so, we will be asked if we wanna download it or not (`**Yes** to download and **No** to Skip`), And when disabled, you won't be asked to download and will be done normally.

Thanks👍

**Comment by joseph619** [comment]
Should also add option for how many chapters to download automatically (ie 1, 5, 10 or all chapters)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/jobobby04/TachiyomiSY/issues/104#event-13607245255

@Mano5JP, why?

**Comment by Mano5JP** [comment]
@RokeJulianLockhart wdym?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/jobobby04/TachiyomiSY/issues/104#issuecomment-2246141818

@Mano5JP, why have you closed this FR as https://github.com/jobobby04/TachiyomiSY/issues?q=is%3Aissue+is%3Aclosed+reason%3A%22not+planned%22?

**Comment by Mano5JP** [comment]
That was something I wanted when I requested. Now we have smart downloads. Maybe there's a need for it, Issue FR if you like.
