### ISSUE TITLE
Third party extension won't update 

### ISSUE THREAD

**Issue by Blackklegend** [jobobby04/TachiyomiSY#1046]
### Steps to reproduce

Install a third party extension
Trust it 
Try to update

### Expected behavior

It should update normally 

### Actual behavior

It won't update 

### Tachiyomi version

preview 542

### Android version

android 13

### Device

Motorola edge 20

### Other details

I believe it's something with the new trust system since some work and some don't for whatever reason that is. Also I'm not sure if it's just a fork issue or tachi issue so I reported here instead of mihon GitHub but I can move it there if needed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Turhvjbufv** [comment]
Known bug prob fixed in next update

**Comment by drewbitt** [comment]
There's no fix for this in any branch, do you just mean it's planned? Maybe this was posted to discord? @Turhvjbufv

**Comment by drewbitt** [comment]
This was not resolved in 1.10.3/1.10.4 piggybacking off Mihon's v0.16.2 `Updating extension not reflecting correctly`, FYI

**Comment by jobobby04** [comment]
Was a Mihon issue, is probably fixed by now

**Comment by drewbitt** [comment]
No, this is not fixed with any published version of TachiyomiSY. Please re-open.

**Comment by jobobby04** [comment]
If it still happens to you, join the [discord](https://discord.gg/mihon) and show examples in the support chat. It should be fixed

**Comment by jobobby04** [comment]
More info:
Any extension not updating falls into either:
* Not replaced with new/repo version of the extension
* Visual bug (which was fixed with 0.16.3+)

Otherwise, it's a mix of random things:
* Chinaphone issues
  * MIUI Optimization needing to be turned off
  * Changing the Installer to Legacy
* Needing to tap on the Notification to install update
* Having two repos with different version numbers for the same extension

**Comment by drewbitt** [comment]
I'll try that in the next update. I just have 10+ extensions all with updates. I will update them, get prompted to install the update in a notification, accept, and then it will remain as needing an update. Every now and then I will get 1 of the 10+ extensions to actually update, and it will be listed as untrusted below the updates which I will then trust, but the rest of them will remain broken. 

 I don't have a Discord, but I'll debug this in more detail if I raise the issue again.
