### ISSUE TITLE
TachiyomiSY Android 7 Support?

### ISSUE THREAD

**Issue by ZeroOVi** [jobobby04/TachiyomiSY#1048]
### Describe your suggested feature

As many of you may know, Mihon no longer provides support for Android 7, which is sad but understandable. So, I was wondering until when TachiyomiSY will continue to support Android 7?. I was also wondering if, after TachiyomiSY decides to discontinue support for Android 7, it could release occasional updates, perhaps every six months or every year, to incorporate major new features into the application on Android 7. Is it possible?.

Thanks for this great app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
No way
Use old version

**Comment by drewbitt** [comment]
Android 7 is 8 years old. The fact that any app at all still supports an 8 year old OS is amazing; on iOS you're lucky with 3. There's no reason for this app to continue targeting Android 7 once it becomes 10+ years old.

**Comment by jobobby04** [comment]
I don't see myself dropping Android 7 anytime soon(its not much of a issue to support it). But once I do remove it, I will not support it in any way. Maintaining old versions of apps is not something I'm interested in.
