### ISSUE TITLE
Malfunctioning title edition for local manga

### ISSUE THREAD

**Issue by wsu808** [jobobby04/TachiyomiSY#1049]
### Steps to reproduce

1. Move manga to local folder (with no metadata, only images/cbz)
2. Refresh (because cover is not showing) » .nomedia and .noxml are added
3. Add to library 
4. Edit title 
5. Refresh » ComicInfo.xml is added
6. Edit title » Title in ComicInfo.xml NOT updated
7. Refresh » **previous** title loaded from ComicInfo, info.json created with **new** title
8. Edit title » info.json updated with newest title, ComicInfo intact with oldest title
9. Refresh » oldest title from ComicInfo loaded
10. Manually remove ComicInfo and Refresh » newest title loaded from info.json, ComicInfo created with newest title, info.json removed
11. Edit title --> go to step7
12. 

### Expected behavior

Title is set to the value from latest edit

### Actual behavior

title loaded from one of files: ComicInfo or info.json that are not consequently updated

### Tachiyomi version

1.10.2

### Android version

Android 11

### Device

Redmi 9

### Other details

P.S. Removing both meta files doesn't change title back to folder name but still loads last used title somehow.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Should be fixed in the next build
