### ISSUE TITLE
Randomly corrupted download index 

### ISSUE THREAD

**Issue by MrDfour** [jobobby04/TachiyomiSY#1050]
### Steps to reproduce

Sometimes after the program has been closed for a random period of time the download index corrupts and the extensions won't work but just momentarily. Except the download index, you need to force the recheck else the downloads won't show up at all
![Screenshot_20240124-134818_TachiyomiSY](https://github.com/jobobby04/TachiyomiSY/assets/103494853/e394b787-114f-46ac-a762-95ce7068d839)
![Uploading Screenshot_20240124-134956_TachiyomiSY.png…]()

### Expected behavior

The downloads should be shown, not needing to force recheck every time 

### Actual behavior

The download index corrupts and needs to be rebuilded

### Crash logs

![Screenshot_20240124-134936_Material Files](https://github.com/jobobby04/TachiyomiSY/assets/103494853/52109aea-0326-4395-8bd1-7963d8c2c7b0)

### Tachiyomi version

1.10.2

### Android version

13

### Device

Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by nopeorino** [comment]
I also have this issue occuring regularly on a Sony Xperia 5 IV on android 14 and version 1.10.5

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/31e5ba4caf0cdef0d368a7764ef3345d47585c0a
