### ISSUE TITLE
Extensions not detected at startup

### ISSUE THREAD

**Issue by MrDfour** [jobobby04/TachiyomiSY#1051]
### Steps to reproduce

Sometimes when the app as been in the background for an unspecified time, when opening it back and a Manga entry shows up, the extension seems to not be avaliable. The problem solves itself getting out of the entry
![Screenshot_20240124-194317_TachiyomiSY](https://github.com/jobobby04/TachiyomiSY/assets/103494853/501d080e-776f-462e-b51d-eacabf6da828)

### Expected behavior

The app should not show a missing extension when it is installed 

### Actual behavior

The app doesn't recognize the extension momentarily 

### Tachiyomi version

1.10.2

### Android version

Android 13

### Device

Poco X3 Pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by wsu808** [comment]
Similar thing happens when opening a chapter from notifications.  

It shows toast with "Source not installed/available" and minimize app.  
If you open recent apps and click on TachiyomiSY it will open the chapter though. (sometimes it will display toast again and you need to try a few times)

**Comment by pavonismc** [comment]
I am having the same problem

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/31e5ba4caf0cdef0d368a7764ef3345d47585c0a
