### ISSUE TITLE
MangaGeko SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by Pheonix-Flames** [jobobby04/TachiyomiSY#1052]
### Steps to reproduce

1. Open MangaGeko Source

### Expected behavior

It should show the List of Manga

### Actual behavior

It is showing SSLPeerUnverifiedException 
![Screenshot_2024-01-25-20-35-39-73_a603e4da04bada03cae438f177815547](https://github.com/jobobby04/TachiyomiSY/assets/105352597/5055486a-9b04-478e-bd77-e97d22389d92)

### Tachiyomi version

1.10.3

### Android version

Android 11

### Device

Realme 3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Report source issues where you got the extension.

**Comment by Pheonix-Flames** [comment]
> Report source issues where you got the extension.

Where ?

**Comment by jobobby04** [comment]
¯\\_(ツ)_/¯

**Comment by NeKoOuO** [comment]
> > Report source issues where you got the extension.
> 
> Where ?

Google bro
