### ISSUE TITLE
Create a New Extension Repository 

### ISSUE THREAD

**Issue by Pheonix-Flames** [jobobby04/TachiyomiSY#1053]
### Describe your suggested feature

The old extension Repository is gone and I am unable to Download any extention now

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Find your own.
