### ISSUE TITLE
添加内置的 cronet 以使用 host_resolver_rules 规避 DNS 污染，或使用 QUIC 实现直连，以帮助部分地区用户更好的使用

### ISSUE THREAD

**Issue by BEIVSIQIN** [jobobby04/TachiyomiSY#1054]
### Describe your suggested feature

在部分地区ehentai网站受到DNS污染/阻断，希望能添加内置的 cronet 以使用 host_resolver_rules 规避 DNS 污染，或使用 QUIC 实现直连，以帮助部分地区用户更好的使用。
In some areas（like China）, the ehentai website is DNS polluted/blocked, and we hope to add a built-in cronet to use host_resolver_rules to circumvent DNS pollution, or use QUIC to achieve direct connection to help users in some regions better use.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Its probably better to use the DNS Over HTTPS setting or use a VPN. Stuff like this is best left to System apps.
