### ISSUE TITLE
Move Local manga folder to shared Tachiyomi folder (again)

### ISSUE THREAD

**Issue by jareddo-kun** [jobobby04/TachiyomiSY#1056]
### Describe your suggested feature

It'd be really great if the path for the local mangas is NOT consolidated within the downloads folder only.

Instead of storing it at `~\[Storage Location]\local`, local data should be located at:
・`\sdcard\Tachiyomi\local`; and
・`\storage\emulated\0\Tachiyomi\local`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Having everything in one folder makes the development expierence much easier, I have no plans to change this.

**Comment by jareddo-kun** [comment]
You could really just use [this thing](https://github.com/Jays2Kings/tachiyomiJ2K/blob/master/app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt) (very easy, it does its job pretty good, would make the app less bulky compared to current sy local handling system)

**Comment by jobobby04** [comment]
SY has been updated to Android 34, which has a much more restrictive filesystem api. The previous implementation has to be overhauled to what we have now to make Local work.
