### ISSUE TITLE
Auto-Update feature like J2K.

### ISSUE THREAD

**Issue by Nihal621** [jobobby04/TachiyomiSY#1060]
### Describe your suggested feature

Need auto updating entries feature like J2K when the update automatically starts in the moment entering the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Thats actually probably a bug on J2k where it can't update in the background like its supposed to.

**Comment by Nihal621** [comment]
> Thats actually probably a bug on J2k where it can't update in the background like its supposed to.



> Thats actually probably a bug on J2k where it can't update in the background like its supposed to.

Im not talking bout any issue in J2K man. Im just requesting  auto-update feature like J2K in SY.

**Comment by Nihal621** [comment]
> > Thats actually probably a bug on J2k where it can't update in the background like its supposed to.
> 
> > Thats actually probably a bug on J2k where it can't update in the background like its supposed to.
> 
> Im not talking bout any issue in J2K man. Im just requesting auto-update feature like J2K in SY.

The library automatically updated the moment i enter the app. Why its not same with SY?

**Comment by jobobby04** [comment]
Because its not meant to work like that, its meant to update in the background and the user can come back to the updates whenever. If you want it to update after opening the app, start a manual update instead

**Comment by Nihal621** [comment]
> Because its not meant to work like that, its meant to update in the background and the user can come back to the updates whenever. If you want it to update after opening the app, start a manual update instead

Oh so the primary function is that update is supposed to happen though i don see it?  And J2K is exception right now?

**Comment by jobobby04** [comment]
Yep, your phone might be killing J2K in the background so it can't properly start a update, since its killed.
