### ISSUE TITLE
Download indicator not working 

### ISSUE THREAD

**Issue by lewdpatriot** [jobobby04/TachiyomiSY#1062]
### Steps to reproduce

Download a/few chapters 

### Expected behavior

It should show which chapters are downloaded and show number of downloaded chapters on the cover when the setting is turned on.
![IMG_20240130_154125](https://github.com/jobobby04/TachiyomiSY/assets/63286528/1c072353-15b6-4131-9f5b-588b470375b7)

### Actual behavior

There is no indicator for downloaded chapters 
![IMG_20240130_154211](https://github.com/jobobby04/TachiyomiSY/assets/63286528/c24fcc51-46a7-4b1e-8534-d011f9d187dd)
![IMG_20240130_154152](https://github.com/jobobby04/TachiyomiSY/assets/63286528/0c487e2a-04da-4730-88dd-9da53b55c545)

### Tachiyomi version

1.10.2

### Android version

Android 11

### Device

Realme 6i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
https://github.com/jobobby04/TachiyomiSY/issues/931#issuecomment-1742196880
