### ISSUE TITLE
For some reason the application does not update my mangas/comics

### ISSUE THREAD

**Issue by daniel95000** [jobobby04/TachiyomiSY#1066]
### Steps to reproduce

1. Update category
2. The mangas are updated
3. Not all manga are updated

### Expected behavior

All the mangas should have been updated

### Actual behavior

For some reason the application does not update some manga/comics for me if I do not directly go to review the manga itself.

These mangas are classified as "lewd" so I don't know if it has anything to do with that.

### Tachiyomi version

1.10.2

### Android version

Android 13

### Device

X10 tablet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by daniel95000** [comment]
Check and they are not marked as completed. I don't have smart updates activated either.

**Comment by drewbitt** [comment]
I also have this at times. It will refresh with no update but if I click into it and refresh, I will get an update.

**Comment by jobobby04** [comment]
https://github.com/jobobby04/TachiyomiSY/issues/1011#issuecomment-1890998040
