### ISSUE TITLE
Acomics.ru doesn't work 

### ISSUE THREAD

**Issue by RikCost** [jobobby04/TachiyomiSY#1067]
### Steps to reproduce

1. Open some comics from acomics.ru
2. Try update information
3. 
![Screenshot_2024-02-02-21-56-09-436_eu kanade tachiyomi sy](https://github.com/jobobby04/TachiyomiSY/assets/69048938/579d2b33-e553-4a02-a4a7-64904951bf2e)
![Screenshot_2024-02-02-21-56-12-446_eu kanade tachiyomi sy](https://github.com/jobobby04/TachiyomiSY/assets/69048938/ff9fc117-0ea9-4fa6-a58c-0cc6498c4517)

### Expected behavior

I can read comics

### Actual behavior

I can't read comics

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/14144169/tachiyomi_crash_logs.txt)

### Tachiyomi version

1.10.2

### Android version

12 SKQ1.211006.001

### Device

POCOX3 PRO

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Source issues should be reported to the repo you got them from.
