### ISSUE TITLE
The Exhentai shows no results found on the first page. 

### ISSUE THREAD

**Issue by DualWing** [jobobby04/TachiyomiSY#1073]
### Steps to reproduce

Selecting the Exhentai extention fails to load anything and all exhentai favorites show no pages error.

E-Hentai working fine. 

### Expected behavior

Expected to have normal behavior. 

### Actual behavior

![Screenshot_20240207_122022](https://github.com/jobobby04/TachiyomiSY/assets/156249277/1a3bbeb4-4fb8-4e1f-b80c-27aaafdcfe0f)

### Tachiyomi version

1.10.2 (standard, 7e151dd, 62, 2024-01-18T04:32Z)

### Android version

13 (SDK 33; build TP1A.220624.014 release-keys)

### Device

Vivo V2302

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DualWing** [comment]
Forgot to add that WebView still allows me to be in my EXh account. Am still logged in, Igneous is correct.

**Comment by DualWing** [comment]
> Did you try to relogin and used the option to add igneous cookie, and added that cookie?

As per my previous comment, yes, WebView still functions fine and I am still logged in to Exhentai. It's the main tachiyomi function that doesn't work.

**Comment by KiryuKai** [comment]
> Thought that you meant that you logged in using WebView, @KiryuKai you closed the same issue as completed how did you fix it

I disabled ExHentai and enabled it again. It asked me to log again and got fixed.
![Exhentai](https://github.com/jobobby04/TachiyomiSY/assets/159195323/6d8e992d-3290-4e99-988a-d04dd19718c6)

**Comment by DualWing** [comment]
I did that several times with mobile data when the issue occurred and it changed nothing. All with custom Igneous. 

I have just tried it one more time on wifi but also without adding custom Igneous and it seems to have fixed the issue.
