### ISSUE TITLE
Can't download when `Password protect downloads` is on

### ISSUE THREAD

**Issue by ff546** [jobobby04/TachiyomiSY#1076]
### Steps to reproduce

1. Set CBZ archive password
2. Enable `Password protect downloads`
3. Try downloading chapter

### Expected behavior

Downloads normally with password applied to the cbz archive.

### Actual behavior

Gives `java.io.FileNotFoundException`. But only when `Password protect downloads` is on. When turned off, it downloads normally but the cbz is of course not encrypted.

### Crash logs

[logs.txt](https://github.com/jobobby04/TachiyomiSY/files/14276390/logs.txt)

### Tachiyomi version

1.10.2

### Android version

Android 9

### Device

Samsung Note 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Can you give the latest release/build a try?

**Comment by ff546** [comment]
Tried `1.10.4`, still didn't work :disappointed:

**Comment by jobobby04** [comment]
It will be fixed in the next release because of #1084

**Comment by ff546** [comment]
Btw, what happens to the chapters previously downloaded? They remain unencrypted right?

Is there a way to encrypt them the same way the app does? I can use linux programs if needed.

**Comment by Shamicen** [comment]
> Is there a way to encrypt them the same way the app does? I can use linux programs if needed.

We use normal zip archive encryption you could use winrar for example to password protect your existing chapters. 7zip should work as well but i never tested it.

**Comment by ff546** [comment]
@Shamicen that might be true for the standard zip encryption but I was hoping to use the `AES 256` one...
