### ISSUE TITLE
Yaoi manga online not working 

### ISSUE THREAD

**Issue by Lionharth** [jobobby04/TachiyomiSY#1077]
### Steps to reproduce

1. Go to any Manga on the Yaoi Manga Online extension
2. There will be one chapter and when clicked it will display "no pages found" 

### Expected behavior

It should get the manga

### Actual behavior

It fails

### Tachiyomi version

1.10.2

### Android version

Android 14 with one ui 6.0

### Device

Galaxy s23 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Source issues go in the relevant repo
