### ISSUE TITLE
[Feature Request] Keep consistent padding for zoomed in cover on both sides

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#108]
## What/Requirements
Kept the consistent padding for zoom out position when zooming in, on both sides.  Same as J2K

![ezgif-6-76b8536ba73f](https://user-images.githubusercontent.com/34897862/93411835-0148ee00-f86a-11ea-839d-b9b849354b37.gif)

**Comment by joseph619** [comment]
This will be fixed if/when this is addressed 

https://github.com/tachiyomiorg/tachiyomi/issues/5301

**Comment by jobobby04** [comment]
Not my problem anymore :thonkergunz:
