### ISSUE TITLE
[Feature Request] Remove sources from Default English/All after they are added to a custom category

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#109]
## Why/User Benefit/User Problem
Users will not see duplicates of source in English/All after it's added to a custom category.

## What/Requirements
Remove source from Default English/All category when source is added to a new Category, just like how Categories for manga work in Library.

**Comment by jobobby04** [comment]
Added in https://github.com/jobobby04/TachiyomiSY/commit/4bd88fa19412a1eed99b801b8e0c75df0d2e170c
