### ISSUE TITLE
Automatic Update failure

### ISSUE THREAD

**Issue by Nihal621** [jobobby04/TachiyomiSY#1091]
### Steps to reproduce

Doesnt automatically update when entering app on daily basis

### Expected behavior

Should automatically update when opening app in daily basis 

### Actual behavior

I always have to manually update every entries since i downloaded SY. It seems to not update entries on its own when entering the app in 24 hours.

### TachiyomiSY version

1.10.4

### Android version

Android 10

### Device

Redmi 9a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
https://github.com/jobobby04/TachiyomiSY/issues/1011#issuecomment-1890998040
