### ISSUE TITLE
Add a feature enabling the migration of mangas that have failed to receive updates.

### ISSUE THREAD

**Issue by Pheonix-Flames** [jobobby04/TachiyomiSY#1092]
### Describe your suggested feature

Implement an automated migration feature in the manga library update process. This feature should detect titles with failed updates, suggest alternative sources, and provide users with an option to approve migrations, reducing manual effort and enhancing user experience. Include error logs for transparency.

### Other details

After I update my manga collection, I end up with this list of titles that didn't update properly due to a bunch of errors. To sort it out, I've got to go on a hunt and move them manually to another place, and trust me, with over 2,000 manga in my library, that's no walk in the park. Right now, 150 manga are throwing errors, and dealing with all that manual migration is just not practical. I'm sure there are many others like me, juggling hundreds of manga titles and stuck doing this hands-on migration for the ones that didn't quite make it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I'd say this is too advanced and outside the scope of what SY is meant to do. I'm going to close this because of that.

**Comment by cuong-tran** [comment]
Maybe just add a feature to group all error mangas together in Migration screen, then users can use current Migration to do it themselves
