### ISSUE TITLE
Every extention is not detecting with third party extensions.

### ISSUE THREAD

**Issue by Uneducated-cat** [jobobby04/TachiyomiSY#1093]
### Steps to reproduce

1.adding third party extensions from GitHub.
2.Refreshing extension list.
3.detecting only some extentions.

### Expected behavior

All extensions are not detected.

### Actual behavior

All extensions should be detected it is detected by minho not tachiyomiSY

### TachiyomiSY version

1.10.4

### Android version

Android 14

### Device

Iqoo nei 6 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
You should provide which third party extensions repo you are failing with.
