### ISSUE TITLE
Automatic CAPTCHA solving not working 

### ISSUE THREAD

**Issue by NeKoOuO** [jobobby04/TachiyomiSY#1096]
### Steps to reproduce

1.use extension that used CAPTCHA on their website (newtoki)
2.refresh the chapters
3.but it shows Solve Captcha with WebView

### Expected behavior

It should be solved automatically 
And i don't have to use webview to solve CAPTCHA 

### Actual behavior

Need solve CAPTCHA with webview 

### TachiyomiSY version

1.10.4

### Android version

13

### Device

Mi 10 ultra 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
I found out that 1.9.0 version delete the auto solver 
Is there any reason to delete this feature? 😔

**Comment by jobobby04** [comment]
Automatic CAPTCHA solving was removed due to bugs and it generally not working. It was a legacy feature from EH.

**Comment by jobobby04** [comment]
Its not something I'm interested in doing

**Comment by NeKoOuO** [comment]
> Its not something I'm interested in doing

Okay…
