### ISSUE TITLE
Add "Attemp to use the first volume cover" to delegated MangaDex

### ISSUE THREAD

**Issue by NoFace33** [jobobby04/TachiyomiSY#1097]
### Describe your suggested feature

Make the "Attemp to use the first volume cover" toggle of MangaDex work on the delegated source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
For reference, the relevant commits that introduced it were eaa7b15baec1759f34693d2dbaad2da870a89dd7 and 9a0c04c679ed8651873bff1c74d65f785375ff79

**Comment by JRodster** [comment]
Adding on to this (here, since it's related), TachiyomiSY is currently not reading the "cover quality" MangaDex setting as well.
