### ISSUE TITLE
MyAnimeList login cannot work on 1.10.5

### ISSUE THREAD

**Issue by dtantono** [jobobby04/TachiyomiSY#1099]
### Steps to reproduce

1. tap more
2. tap tracking
3. tap myanimelist
4. input your username and password
5. Input your 2fa code
6. I got 500 error message
![Screenshot_20240304-124530](https://github.com/jobobby04/TachiyomiSY/assets/29157187/b3fdfbdc-ec35-4a06-875d-f8ae24e6151a)
![Screenshot_20240304-124352](https://github.com/jobobby04/TachiyomiSY/assets/29157187/e8492ebe-a344-4c8a-8deb-0b985ec804a1)

### Expected behavior

it should works

### Actual behavior

I cannot connect to MAL

### TachiyomiSY version

1.10.5

### Android version

Android 11

### Device

Xperia 1 iii

### Other details

I know Mihon release note should fixed this issue. But, it does not worked on this app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
You can see it's a MAL error in the screenshot

**Comment by dtantono** [comment]
@jobobby04 SO that means MAL is not supported right?

**Comment by jobobby04** [comment]
MAL support is working fine, it's mal that is having issues, not SY
