### ISSUE TITLE
[Feature Request] A extra tab for tracking site in browse

### ISSUE THREAD

**Issue by SanOtaku09** [jobobby04/TachiyomiSY#110]
An extra tab for logined tracking site where we can see our all the manga data like 
*No. of manga
*Total read chapter
*and other data present on tracking site
And make changes to them without searching or adding them in library.

Like this app
Its a app for manga tracking sites like mal

![Screenshot_20200918-132928_Kamuy](https://user-images.githubusercontent.com/61407097/93572707-d8347480-f9b3-11ea-8b26-8f03b3364cad.jpg)
![Screenshot_20200918-133106_Kamuy](https://user-images.githubusercontent.com/61407097/93572757-ec787180-f9b3-11ea-909f-e5513232811c.jpg)

**Comment by joseph619** [comment]
This is beyond the scope of this app, it's a manga reader. You are asking for full support for trackers. There are dedicated apps for those.

**Comment by SanOtaku09** [comment]
Ok

**Comment by joseph619** [comment]
If you have no more question, you may close this ticket
