### ISSUE TITLE
Anilist tracker login not working.

### ISSUE THREAD

**Issue by SHADOW-REX** [jobobby04/TachiyomiSY#1103]
### Steps to reproduce

1. Go to tracking in app and select anilist
2. Login to anilist 

### Expected behavior

Anilist tracker should be logged in.

### Actual behavior

Nothing happens and anilist tracker does not get logged in.

### TachiyomiSY version

1.10.5

### Android version

Android 14

### Device

Redmi Note 8 Pro

### Other details

Tried logging in to Anilist on Mihon stable (0.16.4) and it worked as expected. I also tried reinstalling the TachiSY app but no results. 
Opened a new issue since I couldn't reopen #965 

https://github.com/jobobby04/TachiyomiSY/assets/33841315/d813db72-f66d-4c50-a041-ab11131943af

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by resilentstudios** [comment]
The issue also happens with the r547 of the preview candidate, i can confirm Mihon stable allows you to connect Anilist fine too. I had the same issue as #1101 prior to disconnecting, and now unable to connect. I am using the same custom user agent with Mihon.

**Comment by rahaaatul** [comment]
I checked MyAnimeList also, it fails to bind.

https://github.com/jobobby04/TachiyomiSY/assets/86149861/5ac80416-459b-4299-ac05-83247d4d85e8

**Comment by Grafcube** [comment]
I encountered #1101 yesterday and tried unlinking and then re-linking my AniList account, which resulted in this issue exactly as described by everyone else.

I downgraded to 1.10.4 and tried again but the issue persisted. I also tried changing my user agent string but that didn't change anything either.

The tracking in the main Mihon app seems to work fine.

**Comment by Alustg** [comment]
> I encountered #1101 yesterday and tried unlinking and then re-linking my AniList account, which resulted in this issue exactly as described by everyone else.
> 
> I downgraded to 1.10.4 and tried again but the issue persisted. I also tried changing my user agent string but that didn't change anything either.
> 
> The tracking in the main Mihon app seems to work fine.

I got the exact same problem, and it also works fine on main Mihon. My MAL isn't working too, like others said here.

**Comment by Eragonnogare** [comment]
Same issue. Please fix, I beg of you.

**Comment by rahaaatul** [comment]
> My MAL isn't working too, like others said here.

Change your User Agent in advanced settings. Then try again.

**Comment by tmatzxzone** [comment]
same issues with Anilist tracker, already tried default & other user agent still wont work

**Comment by rahaaatul** [comment]
> same issues with Anilist tracker, already tried default & other user agent still wont work

Changing User Agent won't work with anilist.

**Comment by satoon10** [comment]
> Same issue. Please fix, I beg of you.

As an alternative, you can use Mihon, and when the fix is released you export backup from Mihon to TSY

**Comment by SHADOW-REX** [comment]
Changing user agent will only work for issue #1101 and will not work if you've unlinked your anilist account

**Comment by Samk19** [comment]
Facing same issue after the update.....tried to close application logout then re-login but cannot login now......even after successfully verification on anilist login page
App version v1.0.5

**Comment by Mra1k3r0** [comment]
I am also facing the same problem after I updated the app, I hope they fix it as soon as possible.

**Comment by jobobby04** [comment]
Known issue. Locking until fixed

**Comment by jobobby04** [comment]
Fixed in the preview version
