### ISSUE TITLE
Animated pages not working

### ISSUE THREAD

**Issue by Samscryption** [jobobby04/TachiyomiSY#1105]
### Steps to reproduce

1. Open a chapter containing an animated chapter (gif)

### Expected behavior

The gif should be played

### Actual behavior

Instead showed up as an image

### TachiyomiSY version

Dev build 547

### Android version

14

### Device

Samsung Galaxy Tab A7 Lite

### Other details

This wasn't an issue untill version 546 where gifs on every extension started showing up as still images after the update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cmurabito5** [comment]
Manga for reference: 
https://mangadex.org/chapter/69e6bb59-a59c-4202-b04d-5756abf2a47f/5

**Comment by Samscryption** [comment]
**New note:** Animated pages are played correctly as a GIF when the page is set as the cover for the manga.

**Comment by huajideshutiao** [comment]
I also have the same problem.

**Comment by huajideshutiao** [comment]
I also have the same problem.

**Comment by jobobby04** [comment]
Probably related to the Coil3 migration

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/5d1b1408eb78d94912c36cfbe63ee7663f3c1bb4
