### ISSUE TITLE
Internal storage cover problem

### ISSUE THREAD

**Issue by srcsvl** [jobobby04/TachiyomiSY#1107]
### Steps to reproduce

? 

### Expected behavior

Clicking on the Refresh library cover option should add all the bookcase covers in the internal storage

### Actual behavior

No covers have been added

### TachiyomiSY version

R547

### Android version

Android 13

### Device

S23 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Probably a Mihon issue, report it there
