### ISSUE TITLE
Lewd library filter doesn't light the filters button

### ISSUE THREAD

**Issue by BrutuZ** [jobobby04/TachiyomiSY#1109]
### Steps to reproduce

Check the "Lewd" option in library filters (either state)

### Expected behavior

Filters button light up to indicate there are filtered out entries

### Actual behavior

Filters button remains the same color as if there were no filters active

### TachiyomiSY version

r542

### Android version

13

### Device

Generic Tablet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [ ] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [ ] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
What people? And notice what, that you have _a_ filter active that might as well be unread?

________________________________

**Comment by BrutuZ** [comment]
WDYM good luck? It's your device, just don't show them¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

________________________________

**Comment by jobobby04** [comment]
Should be fixed in the next build

**Comment by BrutuZ** [comment]
Caught in the cherry-picking crossfire?
