### ISSUE TITLE
[Feature Request] Prefer to use configured Tracker's manga name to get recommendation.

### ISSUE THREAD

**Issue by DitFranXX** [jobobby04/TachiyomiSY#111]
## Why/User Benefit/User Problem
As the current recommendation works, Recommendation feature is just pass through the title name in the library(`Manga.title`).
But, If the source provides a translated title(non-english, non-romaji). The recommendation feature failed because it won't match any of title. so it fails.
Even I configured the tracker hand by hand too. Because I mentioned, It just pass through.

## What/Requirements
So, Firstly, Look up the currently configured tracker (side of each manga), If matches AniList or MyAnimeList, See the recommendation of it firstly.
If nothing is registered on tracker, then uses current way.

**Comment by joseph619** [comment]
Recs work for any manga regardless of tracker, as tracker only works for manga in library. Also, the recs are chosen in current way because MAL has more manga suggestions than Anilist and Anilist has more+better webtoon suggestions than MAL. Tracker is completely unrelated to it.

**Comment by DitFranXX** [comment]
I don't know what recs is. (When I looked up is, It uses AniList API.)
But It's not just English title. If manga uses Non-English(Maybe some asian language.), The recommendation is broken as it is not matched anything with their dbs.

**Comment by joseph619** [comment]
@she11sh0cked Can you have a look into this bug?

**Comment by jobobby04** [comment]
Added support for using the tracked manga id for the recs
