### ISSUE TITLE
EXH Downloads don't use the retry logic

### ISSUE THREAD

**Issue by BrutuZ** [jobobby04/TachiyomiSY#1110]
### Steps to reproduce

1. Try to download a large gallery (100+ pages like a tankoubon)
2. It will likely get stuck a few pages short of completion because those were on "bad" nodes.

### Expected behavior

Downloader should use the same logic of the Retry button on the reader that gets a new node

### Actual behavior

Download gets stuck in queue and never finishes

### TachiyomiSY version

r542

### Android version

13

### Device

Generic Tablet 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [ ] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [ ] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Should be fixed in the next build
