### ISSUE TITLE
Implement a Feature to Group Manga that Encountered Errors and Failed to Update.

### ISSUE THREAD

**Issue by Pheonix-Flames** [jobobby04/TachiyomiSY#1111]
### Describe your suggested feature

A feature will be added to group manga with update errors into a single list. Users can then easily migrate them to a new source in one go.

### Other details

Given the large number of manga with failed updates (approximately 147 in my case), individually migrating them is impractical and time-consuming. Implementing a feature to group them together for bulk migration would significantly improve efficiency and convenience for users.

If implementing such features proves challenging or unfeasible, please offer an alternative solution to assist me in updating my manga that have failed to update.

Here is my list of manga that are failed to get updated:
For help on how to fix library update errors, see https://mihon.app/docs/guides/troubleshooting/

! No chapters found
  # Mangabat (EN)
    - "kukuku....... He Is The Weakest Of The Four Heavenly Monarchs." I Was Dismissed From My Job, But Somehow I Became The Master Of A Hero And A Holy Maiden
    - A Court Magician, Who Was Focused On Supportive Magic Because His Allies Were Too Weak, Aims To Become The Strongest After Being Banished
    - Akuyaku Reijou, Shomin Ni Ochiru
    - Dungeon Kurashi No Moto Yuusha
    - Dungeon No Osananajimi
    - God Of War Against The Sky
    - I Accidentally Seduced The Male Lead’S Younger Brother
    - I Was Dismissed From The Hero’S Party Because They Don’T Need My Training Skills, So I Strengthened My [Fief] Which I Got As A Replacement For My Retirement Money.
    - Isekai De Kojiin Wo Hiraita Kedo, Naze Ka Darehitori Sudatou To Shinai Ken
    - Isekai Tensei No Boukensha
    - Jigoku No Gouka De Yaka Re Tsuzuketa Shounen. Saikyou No Honou Tsukai To Natte Fukkatsu Suru.
    - Kanan-Sama Is Easy As Hell!
    - Kanojo Mo Kanojo
    - Ore No Ie Ga Maryoku Spot Datta Ken – Sundeiru Dake De Sekai Saikyou
    - Shounin Yuusha Wa Isekai Wo Gyuujiru! – Saibai Skill De Nandemo Fuyashi Chaimasu
    - Teihen Ryoushu No Kanchigai Eiyuutan
    - The Iceblade Magician Rules Over The World
    - The World Is Full Of Monsters Now, Therefor I Want To Live As I Wish
    - Uragirareta S Rank Boukensha No Ore Wa, Aisuru Dorei No Kanojora To Tomoni Dorei Dake No Harem Guild O Tsukuru
    - Welcome To The Impregnable Demon King Castle ~The Black Mage Who Got Kicked Out Of The Hero Party Due To His Unnecessary Debuffs Gets Welcomed By The Top Brass Of The Demon King's Army~
    - Yuusha Party Wo Tsuihou Sareta Beast Tamer, Saikyou Shuzoku Nekomimi Shojo To Deau
    - Zenith
    - “I… Don’T Want To Work Anymore” I Quit Being An Adventurer. Even If You Treat Me Better Now, I Won’T Do It. I Will Never Work Again.

! HTTP error 404
  # ReadM (EN)
    - All-Attribute Martial Arts
    - Almight Network
    - Amazing Ji Jiri
    - An Animal Hospital In The Border Area
    - Ansatsu Skill de Isekai Saikyou: Renkinjutsu to Ansatsujutsu o Kiwameta Ore wa, Sekai o Kage kara Shihai suru
    - Apocalyptic Super System
    - Arafoo Shachiku No Golem Master
    - Attribute Extractor
    - Become Villain In The Game Cultivation
    - Berserk of Gluttony
    - Combine Cube
    - Crimson Karma
    - DEVOURING REALM
    - Dark Sea Era
    - Doomed To Be A King
    - Eiyuu-ou, Bu wo Kiwameru tame Tenseisu
    - Escort Agency Of The Apocalypse
    - Exterminator
    - From the Grave and Back
    - Future break point
    - Genjitsushugisha no Oukokukaizouki
    - Genkai Level 1 kara no Nariagari: Saijaku Level no Ore ga Isekai Saikyou ni Naru made
    - Gwanjeon – Lee Kang-jin
    - Hazure Waku no Joutai Ijou Skill de Saikyou ni Natta Ore ga Subete wo Juurin Suru made
    - Heroic Chronicles of the Three Continents
    - Himekishi ga Classmate!
    - Hiraheishi wa Kako o Yumemiru
    - I Am Carrying Gold From The Post-Apocalyptic World
    - I Became The Wife Of The Monstrous Crown Prince
    - I Brush The Levels From The Mirror
    - I Have A Dragon In My Body
    - I Just Want To Be Killed
    - I'm The One and Only God!
    - Ie ga Moete Jinsei Dou Demo Yoku Natta kara, Nokotta Nakenashi no Kin de Dark Elf no Dorei o Katta
    - If I Die, I will Be Invincible
    - Imprisoned One Million Years: My Disciples Are All Over The World
    - Incoming Mr High Energy
    - Isekai Cheat Survival Meshi
    - Isekai Demo Bunan ni Ikitai Shoukougun
    - Isekai Monster Breeder
    - Isekai Tensei Shitara Aiken ga Saikyou ni Narimashita: Silver Fenrir to Ore ga Isekai Kurashi wo Hajimetara
    - Isekai de Tochi o Katte Noujou o Tsukurou
    - I’ll Resign And Have A Fresh Start In This World
    - I’m Really Not The Demon God’s Lackey
    - Kage no Eiyuu no Nichijou-tan
    - Kanzen Kaihi Healer no Kiseki
    - King of Fire Dragon
    - Kujibiki Tokushou Musou Harem-ken
    - Kuro no Shoukanshi
    - Kyoukai Meikyuu to Ikai no Majutsushi
    - Lan Ke Qi Yuan
    - Legend of the Northern Blade
    - Level 1 no Saikyou kenja
    - Level Up Just By Eating
    - Level up Alone
    - Little Girl x Scoop x Evil Eye
    - Living in This World With Cut & Paste
    - Magi Craft Meister
    - Makenshi no Maken Niyoru Maken no Tame no Harem Life
    - Maou Gakuen no Hangyakusha
    - Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii?
    - Martial Arts Reigns
    - Martial God Asura
    - Marvelous Hero of the Sword
    - Maseki Gurume: Mamono no Chikara o Tabeta Ore wa Saikyou!
    - Milady Just Wants to Relax
    - Mom Please Don’t Come Adventuring With Me! ~The Boy Who Was Raised by the Ultimate Overprotective Dragon, Becomes an Adventurer With His Mother~
    - Musume Janakute, Watashi (Mama) ga Suki Nano?!
    - My Lover Was Stolen, and I Was Kicked Out of the Hero’s Party, but I Awakened to the EX Skill “Fixed Damage” and Became Invincible. Now, Let’s Begin Some Revenge
    - One Hit Teacher, Master Baek
    - Ore wa Mada, Honki o Dashite Inai
    - Ossan, Yuusha to Maou wo Hirou
    - Reborn 80,000 years
    - Rooftop Sword Master
    - Ryuu Kusari No Ori -Kokoro No Uchi No "kokoro"-
    - S Rank Boukensha de aru Ore no Musume-tachi wa Juudo no Father Con deshita
    - Seichou Cheat de Nandemo Dekiru you ni Natta ga, Mushoku dake wa Yamerarenai you desu
    - Seiken Gakuin no Maken Tsukai
    - Sekai Saikyou no Assassin, isekai kizoku ni tensei suru
    - Shingan no Yuusha
    - Someday Will I Be The Greatest Alchemist?
    - Sono Mono. Nochi ni... (NARIIE Shinichirou)
    - Spirit Sword Master
    - Starting with the Transmigration
    - Strongest Cultivation System
    - Super God Card Maker
    - Take The Crown, I Want To Be A King
    - Tensei Kenja no Isekai Raifu ~Daini no Shokugyo wo Ete, Sekai Saikyou ni Narimashita~
    - The Betrayed Hero Who Was Reincarnated As The Strongest Demon Lord
    - The Blade of Evolution-Walking Alone in the Dungeon
    - The Book of Lagier
    - The Earth Savior Selection
    - The Executed Sage Is Reincarnated as a Lich and Starts an All-Out War
    - The Exorcist and the Shikigami of the Twelve Heavenly Generals in Another World
    - The Former Hero Wants To Live Peacefully
    - The Game That Will End Me
    - The Guild Official With The Out-of-the-Way Skill “Shadowy” Is, In Fact, The Legendary Assassin
    - The Hero Who Returned Remains the Strongest in the Modern World
    - The Irregular of the Royal Academy of Magic
    - The King of Misfortune
    - The Lord’s Coins Aren’t Decreasing?!
    - The Marquis Eldest Son’s Lascivious Story
    - The Middle-aged Man Who Just Returned From Another World Melts His Fathercon Daughters With His Paternal Skill
    - The New Gate
    - The Reincarnated Inferior Magic Swordsman
    - The Reincarnated Sage who was abandoned ~I will create the strongest Demon Empire in the Demon Forest~
    - The Reincarnation Magician Of The Inferior Eyes
    - The Strongest Dull Prince’s Secret Battle for the Throne
    - The Unfavorable Job [Appraiser] is Actually the Strongest
    - The Villainess’s Butler: I’ll Crush the Death Flags
    - Tomb Raider King
    - Tou no Kanri o Shite Miyou
    - Training With The Demon King
    - True Education
    - Ultimate Soldier
    - Villainess Level 99 ~I may be the Hidden Boss but I'm not the Demon Lord~
    - Virus Girlfriend
    - Wicked Trapper: Hunter of Heroes
    - Yong Heng Zhi Zun
    - Yuanlong
    - Yuusha Shoutai Kamoku Yuusha Wa Nagisa Renai
  # MergedSource (ALL)
    - Nozomanu Fushi no Boukensha

! Source not found
  # Manhwatop (EN)
    - Matchmaking Baby Princess
  # Bato.to (EN)
    - My Heroic Retirement Life 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Krushx0** [comment]
Another option would be nice if you could tick a box and it will automatically search the manga that has been not found on the same source with the same name or one with one or two word that matches the original tile and compare the result's thumbnails with original thumbnail and merge with it. It happens sometimes that the original manga link die that you added to your library but it still exist with same name or similar one.

**Comment by jobobby04** [comment]
Mihon has plans to add a way to view failed updates, not going to add my own.
