### ISSUE TITLE
can't seem to give storage access

### ISSUE THREAD

**Issue by HikaruIchijyo** [jobobby04/TachiyomiSY#1112]
### Steps to reproduce

No matter what i try to give access it doesn't work. I tried prev build & stable both. Video attached. Idk if i am doing something wrong or nor

https://github.com/jobobby04/TachiyomiSY/assets/38470944/9574b602-a3ba-46aa-8792-c85129e0fa4d

### Expected behavior

It should give access 

### Actual behavior

It doesn't work

### TachiyomiSY version

1.10.5(tried latest prev too, also tried a fork based on sy)

### Android version

OOs13

### Device

one plus 8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Mihon issue, may be fixed in the next few builds
