### ISSUE TITLE
Migrate deletes chapters

### ISSUE THREAD

**Issue by Trinthakis** [jobobby04/TachiyomiSY#1115]
### Steps to reproduce

1. Open comic
2. Select migrate from menu
3. Select source and next arrow
4. Deselect "Delete downloaded" from "Data to include in migration"
5. Press migrate
6. Select accept

### Expected behavior

Comic migrates to new source but keeps old chapters (in my case it is the same source). 

### Actual behavior

Migrate is successful but the chapters are deleted.

### TachiyomiSY version

1.10.5

### Android version

Android 14

### Device

Samsung Galaxy S24 Ultra

### Other details

I've tried with both the check box selected and not selected but the file got deleted either way. I previously had no problem with this but in one of the recent updates to TachiyomiSY it stopped working.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Downloads are not moved because there is no exact matching between chapters for sources. This is intentional as there can be a lot of differences. We provide the delete chapters option to cleanup orphaned downloads
