### ISSUE TITLE
Unable to open comic through link

### ISSUE THREAD

**Issue by huajideshutiao** [jobobby04/TachiyomiSY#1116]
### Steps to reproduce

https://github.com/jobobby04/TachiyomiSY/assets/38980554/d8b864e5-68a6-4b7b-a2c2-1387aabcf035

### Expected behavior

Can open normally like long pressing the link in the second half of the video. 

### Actual behavior

Clicking on the link directly in an external application will prompt loading, and then return to the original interface. 
I have tested nagram and a text editor, both of which have similar issues. 
And if the application does not have a backend process, it will prompt an error when opening the link for the first time.

### TachiyomiSY version

1.10.5

### Android version

Android 14

### Device

redmi k70 pro

### Other details

This issue is also reproduced on pre 547.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by huajideshutiao** [comment]
The following is the intent passed when directly clicking on the link, which may be helpful.

{
    "action": "android.intent.action.VIEW",
    "uri": "https:\/\/exhentai.org\/g\/2857773\/c21c1f3cbe\/",
    "extra": "S.com.android.browser.application_id=xyz.nextalone.nagram\nB.internal=true\nB.create_new_tab=true\n"
}

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/31e5ba4caf0cdef0d368a7764ef3345d47585c0a
