### ISSUE TITLE
Anilist tracker is broken

### ISSUE THREAD

**Issue by ig4e** [jobobby04/TachiyomiSY#1121]
### Steps to reproduce

Try to log in with anilist
Authorize mihon

https://github.com/jobobby04/TachiyomiSY/assets/50212311/527176b9-0e3b-4bcc-9200-9f5ec395f871

Another clip after removing the authorization form anilist 

https://github.com/jobobby04/TachiyomiSY/assets/50212311/43161bd5-ae20-4732-865e-98c3a62b1a02

### Expected behavior

Anilist tracker should login just fine

### Actual behavior

A long load (probably because something failed) and it doesn't log you in

### TachiyomiSY version

1.10.5

### Android version

11

### Device

Redmi note 8 pro

### Other details

App version: 1.10.5 (standard, 6c563d7, 65, 2024-03-02T20:42Z)
Preview build: 0
Android version: 11 (SDK 30; build RP1A.200720.011)
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: begonia (begonia)
Device model: Redmi Note 8 Pro
WebView: Android System WebView 123.0.6312.40

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ig4e** [comment]
> Fixed in the preview version

Where can I find that? Thanks!

**Comment by jobobby04** [comment]
https://github.com/jobobby04/tachiyomisypreview/releases
