### ISSUE TITLE
Cannot login into ExHentai

### ISSUE THREAD

**Issue by Dravengard** [jobobby04/TachiyomiSY#1122]
### Steps to reproduce

1. Try to enable ExHentai in the settings
2. Input password and username in the next screen
3. It loads but leaves me at an empty screen with the background of the exhentai forum website with no way of proceeding

### Expected behavior

It is supposed to load and enable ExHentai in the settings

### Actual behavior

I am left with no way to proceed but to cancel and start over which just leads to the same result

### TachiyomiSY version

1.10.5

### Android version

Android 11

### Device

Tecno Camon 17P

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
Clean Cookie and login again

**Comment by jobobby04** [comment]
Region or account issue. Use a VPN or use some of the advanced options when logging in
