### ISSUE TITLE
Unable to use MAL track

### ISSUE THREAD

**Issue by TheOGDorkLord** [jobobby04/TachiyomiSY#1123]
### Steps to reproduce

1. Go go tracker setting
2. Select MyAnimeList
3. Directed MAL web page 
4. Login into MAL with my account
5. Get redirected and press allow
6. Get sent back to TachiyomiSY, displaying loading circle 
7. After loading tracker setting page reopens
(There is not error message displaying)

### Expected behavior

Expect tick mark next to MAL in tracker settings and being able to click the tracker button on a manga page to track progress on MAL.

### Actual behavior

There is not tick mark next to MAL in tracker setting page. When trying to link manga to track redirects me to tracker settings to link an account to app.

### TachiyomiSY version

1.10.5

### Android version

Android 14

### Device

Samsung S22

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by kyodjinn** [comment]
Go to advanced settings and try changing the default user agent. For me, I deleted the "NT" in "Windows NT 10.0" and it worked.

**Comment by TheOGDorkLord** [comment]
Thanks that worked
