### ISSUE TITLE
Improve picture display mode

### ISSUE THREAD

**Issue by srcsvl** [jobobby04/TachiyomiSY#1125]
### Describe your suggested feature

The ability to stretch pictures on the screen should be added . Right now, just fit to width or fit to height available, 

### Other details

Expand images proportionally to both width and height

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Streching images look horrible, use the smart fit option to fit to width or height based on the image size.
