### ISSUE TITLE
[Bug] Add to MD follows from library not working

### ISSUE THREAD

**Issue by vipzzx** [jobobby04/TachiyomiSY#113]
## Device information
* Tachiyomi version: 1.3.1
* Android version: A10
* Device: Note9

## Steps to reproduce
1. Select MD manga in library or all MD manga
2. Add to MD follows

### Expected behavior
Should add to MD follows

### Actual behavior
Doesn't add to MD follows

## Other details
Additional details and attachments.

**Comment by jobobby04** [comment]
Will reopen if its proven to not work, its working on the devices I tested it on
