### ISSUE TITLE
No pages found + Pages not showing in WebView in (a) specific extension(s)

### ISSUE THREAD

**Issue by lalalasupa0** [jobobby04/TachiyomiSY#1133]
### Steps to reproduce

Open a chapter in source "Olympus Scanlation (Spanish) by [Keiyoushi](https://keiyoushi.github.io/extensions)

### Expected behavior

Should show pages of chapter

### Actual behavior

"Pages not found"

### TachiyomiSY version

1.10.5

### Android version

Android 12

### Device

Samsung S10+

### Other details

In Mihon that source open and load the pages of chapters with no problem, so is a yokai-only issue
This actually happens in TachiJ2K too

When opening the chapter in WebView, the pages are not visible
On the source web you do see the pages

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Extension issue
