### ISSUE TITLE
When is the private installer coming to the stable release? 

### ISSUE THREAD

**Issue by Samscryption** [jobobby04/TachiyomiSY#1134]
### Describe your suggested feature

Private installer has been a feature in the preview versions of TachiSY but still hasn't made it to the stable version. Why?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
SY has no plans to deviate from Mihon regarding this
