### ISSUE TITLE
Browse Search Bar cannot be used

### ISSUE THREAD

**Issue by MarchelGunawan** [jobobby04/TachiyomiSY#1136]
### Steps to reproduce

1. Go to Browse
2. Choose 1 source
3. Klik search and try to type

### Expected behavior

I expect what I type can show up

### Actual behavior

I typing something but nothing comeout even single character

### TachiyomiSY version

1.10.5

### Android version

Harmony OS

### Device

Huawei Matepad 10.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Source specific issue
