### ISSUE TITLE
Allow pinning Saved Searches

### ISSUE THREAD

**Issue by d4rky-pl** [jobobby04/TachiyomiSY#1138]
### Describe your suggested feature

For every extension I use I have special searches set up to filter out all the unwanted kinds of content while still having the results ordered like the Latest section. Currently to access that whenever I browse I need to open the Latest section, then press the Filters, then select my saved search. There's a lot of free screen estate where the Popular / Latest / Filter buttons are, it would be amazing if we could pin our favourite saved searches there to save on the clicks.

### Other details

![IMAGE 2024-03-27 12:21:25](https://github.com/jobobby04/TachiyomiSY/assets/284395/36e6a406-91a2-4ab8-b3d5-943169c65294)
The extra buttons could be placed on the right side of the Filter button

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I won't add it to the top, you can do this though:
- Go to the source feed menu(the menu you get when you click a source)
- Open filters
- Long click a saved search
- Add to feed

This will let you quick select the filter and even show you a preview of the mangas using it
