### ISSUE TITLE
App freezes and crashes when opening it

### ISSUE THREAD

**Issue by PikaBtw** [jobobby04/TachiyomiSY#1139]
### Steps to reproduce

Open the app

### Expected behavior

the app opens normally

### Actual behavior

it crashes or just shows a grey screen followed by "TachiyomiSY keeps stopping" or freezes on the main page then crashes

### Crash logs

can't access them as the app dosen't open

### TachiyomiSY version

1.10.5

### Android version

Android 14

### Device

Google Pixel 7 Pro

### Other details

I've tried downgrading the app to no success, issue started appearing about a week ago

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Kayumii** [comment]
Exactly the same issue here, also on a Pixel 7 pro .. ^^

**Comment by squee666** [comment]
Same on Pixel 6 Pro
been happening over a month the crashes requires a reboot

**Comment by DaviShak** [comment]
Same Issue on Pixel 6 for about 3 days now. Issue seems to pause temporarily after I reset the phone. Also, I am able to "open" the app sometimes but everything is grayed out with no touch response. The only thing I can do is exit by swiping out. Any interaction will result in a black screen.
![Screenshot_20240409-101202](https://github.com/jobobby04/TachiyomiSY/assets/72626375/a9617fd8-df96-4c03-80eb-d34ccc3ad8d4)
![Screenshot_20240409-101149](https://github.com/jobobby04/TachiyomiSY/assets/72626375/87cf6aae-0127-416d-a867-6d58161ed16f)
![Screenshot_20240409-101105](https://github.com/jobobby04/TachiyomiSY/assets/72626375/b60806d0-0c1d-44a5-a1fb-b5bd8f25b711)

**Comment by Alistair1231** [comment]
The preview version seems to work on my pixel 8 
https://github.com/jobobby04/tachiyomisypreview/releases

**Comment by KlayTitan** [comment]
Having the same issue on my Pixel 6A on version 1.10.5

Only works if I restart my phone and eventually it starts crashing again

Tried reinstalling/clearing all data etc.

**Comment by OmegaXzer0** [comment]
> Having the same issue on my Pixel 6A on version 1.10.5
> 
> Only works if I restart my phone and eventually it starts crashing again
> 
> Tried reinstalling/clearing all data etc.

The preview version (linked by Alistair1231) worked for me on my Pixel 6 Pro

**Comment by jobobby04** [comment]
Fixed in the preview.
