### ISSUE TITLE
Hentai2Read can't login in webview

### ISSUE THREAD

**Issue by qorrymarzuki** [jobobby04/TachiyomiSY#1141]
### Steps to reproduce

1. Open browse and choose hentai2read extension.
2. Open in webview.
3. Press login.
4. It just turn into ad page, can't go back to Hentai2read site.

### Expected behavior

It's expected to be able to login so I can see my collection. Some manga can't even be displayed unless I'm logged in.

### Actual behavior

What happens is when I press login, it turns into ad page and can not go back or go the real login site.

### TachiyomiSY version

1.10.5

### Android version

Android 14

### Device

Asus ROG Phone 6

### Other details

In chrome, when I press login, it's also turning into ad page, but the real Hentai2read login site opens up in a new tab. I've tried every ad blocking DNS in my phone while simultaneously using it on the app too. If only it can have multiple tab on the app, this will be solved so easily. Or maybe choose a new real tab when pressing the login button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Can't do anything about that, seems like a source issue.
