### ISSUE TITLE
An Issue with ExHentai

### ISSUE THREAD

**Issue by ArsMagna1337** [jobobby04/TachiyomiSY#1143]
### Steps to reproduce

1. I cleared the cache before opening the app. 
2. I opened the extensions to login to ExHentai.
3. I went to Browse but the doujins aren't there except in WebView and my library. 
4. I get NullPointerException Error whenever I try to open the doujin in the library.

### Expected behavior

The doujin chapters should appear. 

### Actual behavior

NullPointerException happens whenever the doujin is opened in the library and the chapters aren't loaded in. 

Doujins in ExHentai doesn't load, even if searched.

### TachiyomiSY version

1.10.5

### Android version

Android 10

### Device

Huawei Mate 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by JRodster** [comment]
Just experienced the same issue.

Decided to clear cookies and WebView data, and disable and re-enable ExHentai as well (so had to log back into ExHentai right after), and once I did so and went back into my library's ExHentai entries, they were able to load properly.

Not sure why it happened in the first place, though. Just in case, I've attached the log TachiyomiSY placed in my logs folder, might provide some insight?

[2024-03-31-release.log](https://github.com/jobobby04/TachiyomiSY/files/14819106/2024-03-31-release.log)

**Comment by rainbowflesh** [comment]
> Just experienced the same issue.
> 
> Decided to clear cookies and WebView data, and disable and re-enable ExHentai as well (so had to log back into ExHentai right after), and once I did so and went back into my library's ExHentai entries, they were able to load properly.
> 
> Not sure why it happened in the first place, though. Just in case, I've attached the log TachiyomiSY placed in my logs folder, might provide some insight?
> 
> [2024-03-31-release.log](https://github.com/jobobby04/TachiyomiSY/files/14819106/2024-03-31-release.log)

Seems this function cause broken: https://github.com/jobobby04/TachiyomiSY/blob/fb1649125cd4fce6843ede61862de195b393f1d1/app/src/main/java/eu/kanade/tachiyomi/source/online/all/EHentai.kt#L333

**Comment by jobobby04** [comment]
What gallery does this happen on? If its all them, then something is wrong with your login

**Comment by JRodster** [comment]
It was on all of them for me, but for some reason ExHentai and the galleries still loaded properly through SY's WebView (which means my login was still working partially?).

Logging out and logging back in (after clearing cookies and WebView data) fixed things for me, so it must've been something to do with my login. Not sure what caused it to stop working, though.

Just not sure why it was still working through SY's WebView but not through SY's reader. Unless they're separate?

**Comment by jobobby04** [comment]
They can be out-of-sync. If its working now then it should be good.
