### ISSUE TITLE
Seekbar bug on the right-to-left direction

### ISSUE THREAD

**Issue by GitGitu79** [jobobby04/TachiyomiSY#1144]
### Steps to reproduce

1. Use left-to-right reading mode and see the seekbar looking normal.
2. Use the right-to-left mode and see the seekbar still in the left-to-right mode and bugging.

### Expected behavior

Should be moving in reverse direction like the direction implied 

### Actual behavior

When using the right-to-left reading mode the seekbar is still in the left-to-right mode and the dot only appear halfway inside the seekbar.
(See video)

### Crash logs

No crash

### TachiyomiSY version

TachiyomiSY preview r556

### Android version

Android 13

### Device

Samsung Galaxy M12

### Other details

https://github.com/jobobby04/TachiyomiSY/assets/152173286/50214f2c-63a7-4bb5-a299-128bdd811988

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
The seekbar is from Mihon, not a SY issue.
