### ISSUE TITLE
for E-Hentai-setting，Use original images，but The images clarity is the same as the thumbnail

### ISSUE THREAD

**Issue by X012C** [jobobby04/TachiyomiSY#1145]
### Steps to reproduce

as title

### Expected behavior

as title

### Actual behavior

as title

### TachiyomiSY version

1.10.5

### Android version

android14

### Device

xiaomipad6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
You need to have the hath perk on the E-hentai website to get original images.
