### ISSUE TITLE
Next chapter button goes to a different source in chronological order

### ISSUE THREAD

**Issue by vexar0** [jobobby04/TachiyomiSY#1148]
### Steps to reproduce

1. Go to any manga with different variations (Official, other scans)
2. Go to the next chapter while inside of the reader

### Expected behavior

It should go to the next chapter (Chapter 5 (official) > Chapter 6 (official)

### Actual behavior

It goes to the next version for the chapter (Chapter 5 (official) > Chapter 5 (other scan)

### TachiyomiSY version

1.10.5

### Android version

Android 14

### Device

Galaxy S22 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
THis is just how the reader works, click the filter button above the chapter list and disable other scanlators.
