### ISSUE TITLE
[Feature Request] Hide dropdown for autoscroll in reader

### ISSUE THREAD

**Issue by CrepeTF** [jobobby04/TachiyomiSY#115]
<img width="360" alt="Screenshot 2020-09-20 at 20 05 09" src="https://user-images.githubusercontent.com/70870719/93719788-bb976880-fb7c-11ea-9b0f-7a79a6369615.png">
---

## Why/User Benefit/User Problem
This increases visibility of the page - and if the user does not intend to utilise these features they would actually be detrimental to the view.

## What/Requirements
The reader would be the same as now - but no dropdown, there may be a toggle within reader settings or buried within app settings somewhere.

**Comment by joseph619** [comment]
Autoscroll could be turned into a button and placed on top toolbar, like on this mockup

![Uploading Screenshot_20200920-222940.jpg…]()

**Comment by joseph619** [comment]
Wasn't this rejected by Syer? I think he said it's fine as it is.

**Comment by CrepeTF** [comment]
Dunno, plus forgot this was an issue ¯\_(ツ)_/¯
