### ISSUE TITLE
Add an option to update tracking when marked as read.

### ISSUE THREAD

**Issue by kana-shii** [jobobby04/TachiyomiSY#1150]
### Describe your suggested feature

The app only syncs when I get to the last page of the chapter. That's a problem because when I read online, I can't simply mark the chapter as read to have it update the tracker.

### Other details

Example:
![Screenshot_20240404_190305_Ykai](https://github.com/jobobby04/TachiyomiSY/assets/79055104/2f8e4409-823a-4cff-adc3-d0463c912236)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
#1095

**Comment by kana-shii** [comment]
> #1095
ty
didn't see it before
I'll be closing this one as a duplicate
