### ISSUE TITLE
chapter markers

### ISSUE THREAD

**Issue by decade7117** [jobobby04/TachiyomiSY#1157]
### Describe your suggested feature

Add chapter markers please

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
#1095

**Comment by decade7117** [comment]
![Screenshot_20240412-021514434 (1)](https://github.com/jobobby04/TachiyomiSY/assets/78193337/8fd23db6-1ae6-431f-aee3-e697f19f33bf)
I Medan like tthis

**Comment by jobobby04** [comment]
Open the chapters menu and long click or swipe a chapter
