### ISSUE TITLE
[Bug] Hitomi's Deep Linking can't open Hitomi galleries with language set as N/A

### ISSUE THREAD

**Issue by 0klux** [jobobby04/TachiyomiSY#116]
## Device information
App version: 1.3.1 (standard, ffc80c084, 9)
Preview build: 242
Android version: 9 (SDK 28) 
Device brand: motorola
Device manufacturer: motorola
Device model: moto g(6)

## Steps to reproduce
1. Try to open a gallery that has the language set as N/A from Hitomi's website via deep linking.

### Expected behavior
The app ahould be able to open the gallery just fine

### Actual behavior
The app will fail to load the gallery, with the error stating that the "Gallery or Gallery type is unknown"

## Other details
These types of galleries do appear in "Hitomi Unfiltered" source and do work in the app. The problem is only with the deep linking system.

**Comment by jobobby04** [comment]
Fixed in https://github.com/jobobby04/TachiyomiSY/commit/1dfe3890a974eca96b07aca16cfa1042b61a08d1
