### ISSUE TITLE
[Feature request] Combine multiple sources

### ISSUE THREAD

**Issue by Krushx0** [jobobby04/TachiyomiSY#1160]
### Describe your suggested feature

This feature would allow to have one entry in your library but you could have potentially a more complete series viewing experience.

For example x manga have been picked up by a scanlation group and they continued the work of a previously disappeared group but you can only access the previous group work from an aggregator site. Currently you need to pick both and add to your library.
If you could pick for example the new scanlation group's manga to you library and on that manga page in the app you could define more of the same manga from different sources and rank them to fill the missing chapters based on a ranking between these sub sources for potentially a heavily fragmented series.

The ranking would worked like this:
For example the new scanlation group picked up from chapter 120. The rank 1 aggregator site has only 1 to 60 chapters but with higher quality and better translation compared to the ranked 2 aggregator site, which means because it ranked, it will fill it from 1 to 60 the missing chapters. Ranked 2 aggregator site has 1 to 120 chapters, its lower quality but it has the missing chapters that rank 1 has not, so it will fill it from 61 to 119 because rank 1 filled it from 1 to 60 and the main manga in the library already has the 120th chapter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
SY already has this with merging Manga, when in a manga, click the merge icon or overflow menu button.
