### ISSUE TITLE
Allow users to set specific time for library update

### ISSUE THREAD

**Issue by LoneWolf993** [jobobby04/TachiyomiSY#1164]
### Describe your suggested feature

It would be great if we could set specific times when the global library update will run instead of time intervals like 12hrs and 24hrs. To prevent repeated updates quickly a minimum time interval of 6hrs could be made compulsory between two consecutive update times. In conclusion, allowing users to set their own update times will prevent the update time from being pushed back and the updates being done at odd times.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a well known Mihon request, I belive it will be implemented when WorkManager adds a good scheduler api.
