### ISSUE TITLE
Does TachiSY support DNS over QUIC, specifically in the Downloader?

### ISSUE THREAD

**Issue by InInfinitumEtInTenebris** [jobobby04/TachiyomiSY#1165]
### Describe your suggested feature

Notes: using TachiSY Preview 557, Android Beta 1.1

Content: I'm not entirely sure if this is a real problem related to TachiSY or a consequence of QUIC protocol only going through certification recently through the IET (or smth), but the Downloader fails to start. Eg. upon pressing resume (as downloads auto fail), the Downloader auto reverts to resume. 

Info: connecting to Adguard DoQ server (adblocking) through Adguard application (not the Adguard VPN or content blocker). 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
It is possible to use it using [CronNet](https://github.com/google/cronet-transport-for-okhttp/blob/master/README.md), but I currently don't have any plans to implement it. Maybe Mihon will if a issue is opened though.

**Comment by InInfinitumEtInTenebris** [comment]
Hello @jobobby04 . Thank you for the timely response. I was mainly just confused as the reader works perfectly fine with the DoQ. Is it because the reader uses the system webview?

**Comment by jobobby04** [comment]
The reader does not use Webview 😄, it uses our regular OkHttp. I'm not too familiar with these specs, but it may end up using a alternative when a application does not support it.

**Comment by InInfinitumEtInTenebris** [comment]
Thank you for the clarification. I'm not a developer, but I just thought QUIC was interesting (specifically for school, helping with loading times). Thank you for the timely response!
