### ISSUE TITLE
Unable to download or update any extensions on Pixel Fold Android 14

### ISSUE THREAD

**Issue by molitar** [jobobby04/TachiyomiSY#1166]
### Steps to reproduce

Unable to download any extensions on Pixel Fold Android 14

### Expected behavior

Select extension and download. Worked fine on OnePlus 6T Android 11 but I upgraded to a Pixel Fold which is Android 14. So not sure if this is Android 14 problem or Pixel Fold itself. 

### Actual behavior

It says download unsuccessful

### TachiyomiSY version

R557

### Android version

Android 14

### Device

Pixel Fold

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by molitar** [comment]
nm figured it out.. the copy from previous phone as this is a new phone broke something.. completely uninstalled and reinstalled with saved backup. Working now.

Got a question though.

Why do backups not restore Repo setting?  I had a very hard time finding the repo for Kavita and Komga extensions for my Komga server and now I have to hunt it down again.  Second feeds are not saving either.

**Comment by jobobby04** [comment]
Saving repos needs to be done manually since they are in the database now. You can report it to Mihon to add it to backups. Feeds are the same, feel free to create a new issue to add feeds to the database.
