### ISSUE TITLE
Incomplete Sync breaks future syncs

### ISSUE THREAD

**Issue by noggl** [jobobby04/TachiyomiSY#1168]
### Steps to reproduce

1. Set up sync to Google drive
2. Test syncing to another device is working
3. Turn off network or cancel sync while syncing
4. Try to sign again
5. Get error before sync %s: Max to retries reached

### Expected behavior

If an incomplete sink is found, it should be removed on the next sync.

If I could find where tachiyomi is saving to, I'd try just deleting it.

### Actual behavior

Sync never completes, and neither signing out/back in, nor using "clear sync data from Google drive", nor removing access by tachiyomi from your Google account allows syncing again.

### TachiyomiSY version

App version: 1.10.5 (standard, 03f32ebff, 67, 2024-04-15T01:27:58Z) Preview build: 557

### Android version

Android 14

### Device

ROG Phone 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by noggl** [comment]
For reference, I found where the data can be deleted on google's end:
1. Go to https://drive.google.com/drive/settings
2. Click "Manage Apps" on the left side.
3. Find TachiyomiSY
4. Select Disconnect from Drive and Delete Hidden Data (the latter part actually removes the bad sync data).

It still seems like the data should not be getting messed up like this. In a CLI setting, I'd expect to do something like generate a .lock file with data on which device is syncing, and if there is a sync failure the same device could overwrite the bad data on next sync. Even better if a timeout could be specified to allow another device to overwrite the bad data after the .lock is XXX time old.

**Comment by KasukeLp23** [comment]
The same thing has been happening to me for days
