### ISSUE TITLE
Enhancement to Newly existed filter setting option(for chapters)

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#117]
## Device information
* Tachiyomi version: Preview r242
* Android version: A10 OneUI 2.5
* Device: Note 10+

I know I should be doing this on Tachi repo, but I am using **TachiSY** so, Syer 👍🤣👍

## Steps to reproduce
1. Browse>Add any series
2. Stupid steps but, migrate that series
3. Either set a filter/sort for a chapter or let pre-user-defined default be set.

### Expected behavior
1. As the filter is already set for series when it is migrated it should retain its filter setting too.

### Actual behavior
1. Filter is not set, so need to define it again.

## Other details
well, it's not much of a big deal if we weren't using a pre-user-defined filter/sort setting, but that is not the case if the filter is already been set. So need some enhancement to this(https://github.com/jobobby04/TachiyomiSY/commit/763335bd85aa12061ab98f57e2cd648f72f822ed) feature.
For Reference Clip. https://imgur.com/a/6OLZh3O

**Comment by joseph619** [comment]
You are right, you should be making this to Tachi repo. This doesn't seem like a Sy specific feature.

**Comment by Mano5JP** [comment]
Good Day Ainz-Sama & Syer

Weird that is, I check on Tachi Preview this morning and it work fine.

Reference Video Link: https://imgur.com/a/JB0fi2S

Let me know if I need to report on main repo.

Thx

**Comment by jobobby04** [comment]
Added in https://github.com/jobobby04/TachiyomiSY/commit/32748fa05655bf302f5ffb0773e08747fb3118a0

**Comment by Mano5JP** [comment]
Did found when i updated last week. 

Thx syer 🤣
