### ISSUE TITLE
New update broke the full amoled theme

### ISSUE THREAD

**Issue by MagicWizard2345** [jobobby04/TachiyomiSY#1170]
### Steps to reproduce

1. Install the newest version
2. Activate amoled theme
3. Look at the bottom buttons

### Expected behavior

Applied the amoled theme on the app UI

### Actual behavior

Instead of applying the black theme only the center and top gets changed while most of the UI still continues on dark theme

### TachiyomiSY version

TachiyomiSY Dev Build 560

### Android version

12

### Device

S20FE 5G

### Other details

![Screenshot_20240506_111232](https://github.com/jobobby04/TachiyomiSY/assets/101108226/115e08f3-f548-4d01-807d-1e1449d6786b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by sam-gq** [comment]
Fixed after updating mihon r6697
[mihonapp/mihon/#704](https://github.com/mihonapp/mihon/issues/704)
