### ISSUE TITLE
gdrive sync broken after dev build 556

### ISSUE THREAD

**Issue by andrew020211** [jobobby04/TachiyomiSY#1171]
### Steps to reproduce

Updating from dev 556 to version after 556(including 557,559,560)
Set sync to gdrive

### Expected behavior

Press sync on one device(phone), press sync on another device(tablet)
Self,history and etc synced to the other device(tablet) 

### Actual behavior

Press sync on one device(phone), UT says sync complete 
Pree sync on another device(tablet)  it says sync complete, but nothing changes on another device (tablet) 

### TachiyomiSY version

dev build 557,559,570

### Android version

android 14 on both devices 

### Device

Samsung s24+ and Samsung tab s7

### Other details

After rolling back to dev build 556, gdrive sync works again 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by andrew020211** [comment]
Other people have experienced the same issue in syncyomi discord

**Comment by dondeepak** [comment]
I am also facing the same problem sync not working always failed to sync. 
App version: 1.10.5 (standard, 46bf139f0, 67, 2024-05-05T17:21:31Z)
Preview build: 560
Android version: 13 (SDK 33; build TKQ1.221114.001 test-keys)
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: peux (peux_in)
Device model: 2201116SI
WebView: Android System WebView 124.0.6367.123
![Screenshot_2024-05-18-08-56-03-817_eu kanade tachiyomi sy~01](https://github.com/jobobby04/TachiyomiSY/assets/24863950/674eecc0-a93d-4fe9-b490-43ce64941920)

**Comment by NeKoOuO** [comment]
Same issue here

**Comment by CBozsik** [comment]
Sync is working for me in r560 after I followed noggl's comment on #1168 about disconnecting and deleting hidden data from GDrive. Clearing sync data via the button in the TachiyomiSY settings did not resolve the issue.

These may be related issues.

**Comment by andrew020211** [comment]
> Sync is working for me in r560 after I followed noggl's comment on #1168 about disconnecting and deleting hidden data from GDrive. Clearing sync data via the button in the TachiyomiSY settings did not resolve the issue.
> 
> These may be related issues.

This did not solve the problem for me

**Comment by andrew020211** [comment]
> I am also facing the same problem sync not working always failed to sync. 
> App version: 1.10.5 (standard, 46bf139f0, 67, 2024-05-05T17:21:31Z)
> Preview build: 560
> Android version: 13 (SDK 33; build TKQ1.221114.001 test-keys)
> Device brand: Redmi
> Device manufacturer: Xiaomi
> Device name: peux (peux_in)
> Device model: 2201116SI
> WebView: Android System WebView 124.0.6367.123
> ![Screenshot_2024-05-18-08-56-03-817_eu kanade tachiyomi sy~01](https://github.com/jobobby04/TachiyomiSY/assets/24863950/674eecc0-a93d-4fe9-b490-43ce64941920)
> 

This I think is solvable with the method in issue 1168

**Comment by rodrigozangelmi** [comment]
Same here!

**Comment by NeKoOuO** [comment]
@kaiserbh
