### ISSUE TITLE
Temporary category for failed updates

### ISSUE THREAD

**Issue by TimoNotThy** [jobobby04/TachiyomiSY#1172]
### Describe your suggested feature

Currently when manga updates fail you get a notification "X update(s) failed: tap to see details". This details file is a .txt file.
My suggestion is to put 2 buttons in the notification:
-Open txt: does what pressing the notification does at the moment: provides the txt with the reasons why the updates failed.
-Open in library: Opens a temporary category in the library with all the failed manga.
Doing this allows for the manga to easily be migrated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Mihon has plans for failed updates, so going to close this as it will be obsolete when they add it
