### ISSUE TITLE
ExHentai problem

### ISSUE THREAD

**Issue by ElmoShadow** [jobobby04/TachiyomiSY#1176]
### Steps to reproduce

On click ExHentai show nothing

### Expected behavior

ExHentai is empty do not previev galery.
I am log in many timies stil that same.
On web  account working.

Sorry for my bad english.

(Jak ktoś może pomóc napisze po polsku)

### Actual behavior

Nothing search on or view on ExHentai
EHentai working normal on web

### TachiyomiSY version

1.10.5

### Android version

Android 8

### Device

HUAWEI Y7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Exhentai issues could be from multiple things related to your account, its never a app issue though.
![image](https://github.com/jobobby04/TachiyomiSY/assets/17078382/ee71847d-343b-48d6-b307-2ca769a964e6)
