### ISSUE TITLE
add invalidate download index to drop down menu

### ISSUE THREAD

**Issue by Turhvjbufv** [jobobby04/TachiyomiSY#1177]
### Describe your suggested feature

There's the three dots in the top right when on library tab, please add the invalidate download index option there, much easier to access than needing to go into settings and such

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rsa16** [comment]
This request would be better off moved to Mihon rather than here, as it is not a fork focused feature request. If the changes get pushed on Mihon, than it will be merged with TachiyomiSY.
