### ISSUE TITLE
[Feature Request] Porting Clean up cached covers and Clean up non library cache from j2k

### ISSUE THREAD

**Issue by Goku003** [jobobby04/TachiyomiSY#118]
## Why/User Benefit/User Problem
User can free up the space by clearing the cached covers from the internal which are not present in library

## What/Requirements
Two below options needs to be added in Advanced settings
1. Clears the cached covers which were present in library
2. Clears thr cached covers which are not present in library

Attaching the screenshot present in j2k ![Screenshot_20200924-204707.jpg](https://user-images.githubusercontent.com/22503748/94164897-3a571300-fea7-11ea-95a9-f077a7c0a2eb.jpg)

**Comment by jobobby04** [comment]
I'm going to leave this to main tachi
