### ISSUE TITLE
The Ability to Select which Manga/Manhwa/Manhua/Comic is Lewd

### ISSUE THREAD

**Issue by ArchCelestial** [jobobby04/TachiyomiSY#1182]
### Describe your suggested feature

I should be able to select multiple Manga/Manhwa/Manhua/Comics and mark them as either lewd or not lewd. That way some additions can not be already marked as lewd when they aren't.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
You can do that by adding the Lewd tag to the manga with the edit info option on the manga page.

**Comment by ArchCelestial** [comment]
Many of the manhwa/manga in my library are automatically set to lewd even though there is no possible lewd tag attached to them.

**Comment by jobobby04** [comment]
Yes, a lot of tags or sources are used to detect if the manga is lewd, if it is not lewd, remove anything that could make it think it is.

**Comment by ArchCelestial** [comment]
k

**Comment by jobobby04** [comment]
Not without changing the code, I have everything here https://github.com/jobobby04/TachiyomiSY/blob/master/app/src/main/java/exh/util/LewdMangaChecker.kt

**Comment by ArchCelestial** [comment]
thank you
