### ISSUE TITLE
Migration didn't work Properly.

### ISSUE THREAD

**Issue by Yuv-Sama-00** [jobobby04/TachiyomiSY#1187]
### Steps to reproduce

1. Open a manga.
2. Click on migrate from three dots.
3. Selected chapters, in include data to migrate.
4. Select a source.
5. Selected a manga.
6. Chapters didn't get marked as read and not get bookmarked on specific chapters.
7. And other than that like category and tracking works fine!

### Expected behavior

Maybe because there are some duplicate chapters, that's why it won't able to mark a specific chapters on other source.

### Actual behavior

Idk.

### TachiyomiSY version

1.10.5

### Android version

Android 11

### Device

Realme 7i 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Its likely that it wasn't able to match the chapter numbers properly. Migration is not 100% but it works for the most part.
