### ISSUE TITLE
[Bug] Smart background not working 

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#119]
## Device information
* Tachiyomi version: 1.3.1
* Android version: 10
* Device: S10+

## Steps to reproduce
1. Set reader to RTL
2. Set background colour to Smart (based on page) page

### Expected behavior
Open Sousou no Frieren on Mangadex, ch 2 page 20, it should look like this
![Screenshot_20200924-222221_TachiyomiJ2K](https://user-images.githubusercontent.com/34897862/94219678-66799080-feb5-11ea-9aca-1f9560030daf.jpg)

### Actual behavior
It looks like this 
![Screenshot_20200924-222259_TachiyomiSY](https://user-images.githubusercontent.com/34897862/94219723-7d1fe780-feb5-11ea-8ad6-306add3610ec.jpg)

## Other details
Doesn't work as it should like on J2K

**Comment by jobobby04** [comment]
Fixed in https://github.com/jobobby04/TachiyomiSY/commit/96989bfa532585267ed46b827bc19ff38336f2a3
