### ISSUE TITLE
Add "Tag" as a new option for group(ing)!

### ISSUE THREAD

**Issue by Yuv-Sama-00** [jobobby04/TachiyomiSY#1190]
### Describe your suggested feature

It should Grouped all manga according to their tags that they have!
See the image for a quick reference where it locates.

### Other details

![IMG_20240601_150740](https://github.com/jobobby04/TachiyomiSY/assets/166005207/f41aefa3-9a34-4c4a-bb29-442eeec48609)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I've considered this before, and I decided not to include it. This is mainly because many sources = many different tags, and having a lot of tags would make navigation of the library very difficult.
