### ISSUE TITLE
Ipb cookies as alternative login methods for Exhentai

### ISSUE THREAD

**Issue by Letmein221** [jobobby04/TachiyomiSY#1193]
### Describe your suggested feature

The igneous cookie as an alternative login method was nice, but some users still cannot enter Exhentai just with this method.

The addition of both "ipb_member_id" and "ipb_pass_hash" cookies may allow easier alternative logins to ensure users can enter and browse Exhentai.

Maybe add them to the popup that appears for inputting the igneous cookie for example.

Thank you for the support you have given to the app and its continued development.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I'm personally against this, you would only need it if you don't own the account. If you are able to login on any device, you can copy your working igneous cookie to SY using the custom igneous cookie option, and as long as it matches you account, Exhentai will work.

**Comment by Letmein221** [comment]
Ah, damn.

Still, thanks for looking into it.
