### ISSUE TITLE
Inputting igneous cookie does nothing after losing Exhentai access

### ISSUE THREAD

**Issue by Letmein221** [jobobby04/TachiyomiSY#1194]
### Steps to reproduce

Recreation:

1. Turn on "enable Exhentai" in the ehentai settings.
2. Open alternative login options
3. Open igneous cookie input
4. Input cookie

### Expected behavior

Able to fully access Exhentai, see in webview, and able to download and update exhentai entries.

### Actual behavior

-inputting cookie does nothing, no visual confirmation, no returning to the app.

-any previously saved but undownloaded exhentai entry regains their covers, but still cannot access exhentai to get updates for example. This only happens interestingly if an igneous cookie is inputted, then normal ehentai account details are inputted. 

-looking into exhentai's browsing tab results in "no results found. 

-trying to use webview on any exhentai entry or on the browing tab results in a white screen.

-trying to update an exhentai entry results in a "NullPointerException: null" error. The entry also loses its entry type and ratings.

### TachiyomiSY version

1.10.5 (stable)

### Android version

Android 12

### Device

Samsung galaxy note 10 plus

### Other details

-logging off, clearing cookies and webview data, and then logging in with either a newer or older ehentai account does nothing.

-the use of an igneous cookie alongside normal ehentai account credentials apparently allows any undownloaded exhentai entries to regain their covers, which were lost when I lost access to exhentai.

-after trying many user agent strings, I might be able to conclude that an incompatible string is most likely not the problem.

-inputting my ipb and igneous cookies on both my phone's and pc's chrome app allows them to access exhentai, but Tachi-SY is unable to (as it has no apparent ability to accept ipb cookies). This might point to a problem within the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
... you need to login after inputting the igneous cookie. The idea behind it is that it replaces the igneous cookie that E-Hentai returns after logging in.

**Comment by Letmein221** [comment]
Ah, must be my misunderstanding then. Not really that knowledgable on these
things.

Thanks for the help.
