### ISSUE TITLE
There does not appear to be a snyc setting in the emulator

### ISSUE THREAD

**Issue by misaka10843** [jobobby04/TachiyomiSY#1199]
### Steps to reproduce

1. open the apk after installing it
2. click More -> Settings -> Data and Storage
3. the sync setting is not seen

### Expected behavior

![Screenshot_2024-06-06-21-47-37-049_eu kanade tach](https://github.com/jobobby04/TachiyomiSY/assets/69132853/c0327795-6748-4c49-a1a9-f28ea9147e2b)

### Actual behavior

![image](https://github.com/jobobby04/TachiyomiSY/assets/69132853/0eafe636-f8fa-49bb-8c57-6227a53fd54a)

### TachiyomiSY version

1.10.5

### Android version

Android12

### Device

Mumu12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Sync is only in the preview, not stable...

**Comment by misaka10843** [comment]
> Sync is only in the preview, not stable...

oh, i see. i thought the stable version had this feature, too. sorry
