### ISSUE TITLE
[Feature Request] Stop Auto Scroll when app in background

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#121]
## Device information
* Tachiyomi version: r245
* Android version: A10 ONEUI 2.5
* Device: NOTE10+

## Steps to reproduce
1. Open any manga, then enable auto scroll
2. Go to Home-Screen/Lock-Screen/Browse any other apps

### Expected behavior
This should stop auto scroll. 

### Actual behavior
It's still scrolling on background.

## Other details
https://imgur.com/a/YgMZ7Dy

**Comment by jobobby04** [comment]
Added for the next build
