### ISSUE TITLE
Manga Title or Author title doesn't get copied to clipboard after long press in Poco F6

### ISSUE THREAD

**Issue by Lancelot205** [jobobby04/TachiyomiSY#1210]
### Steps to reproduce

In preview r561
When i long press on the author or manga title it doesn't get copied to clipboard,
In fact it is not selected at all ,
If only i do a normal one press then it goes to global search .
This is not a problem on every device this is only prevalent on newly released Poco F6 Indian version 
Other phones doesn't have this issue i checked.

### Expected behavior

Upon long press on the manga title or author title it should be copied to the clipboard 

### Actual behavior

Upon long press nothing happens

### TachiyomiSY version

Preview r561

### Android version

Android 14

### Device

Poco F6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Sounds like a rom issue, not anything we can do if Poco broke the clipboard function.
