### ISSUE TITLE
AVIF Images Do Not Load - Dev Build 561

### ISSUE THREAD

**Issue by GMak9** [jobobby04/TachiyomiSY#1211]
### Steps to reproduce

The error occurs in the reader

### Expected behavior

The image loads and reads correctly

### Actual behavior

The reader does not display the image, only the black screen. 

### TachiyomiSY version

TachiyomiSY preview r561

### Android version

Android 8.1.0

### Device

Samsung Galaxy J7

### Other details

I installed the latest preview version of the App and noticed that the images in .avif format are not displaying correctly. The same does not happen in the latest stable version of the App, not even Mihon and Mihon Preview versions. 
It's also not a network problem, I tested it on 3 different ones and in all of them the same happens(I also tested it on different source extensions) , the loading animation appears, it ends and the screen goes dark, no crash problems. The problem persists even when downloading the chapters. 
The only constant variable seems to me to be a problem in avif or coil.

This may be the case for a different issue: 
Taking advantage I would like to report that the extensions have an extremely slow performance in this version, all the extensions are slow, take at least twice as long to load and some of them seem that they won't even do it no matter how long you wait. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by GMak9** [comment]
After further investigation I found out that it is not an isolated problem of the fork, the same is true of the latest preview version of mihon, Also, after some testing, I was able to come to the conclusion that the problem only occurs in the scroll reading format (Long strip, Long strip with gaps and Webtoon reader mode) 📜: That is, I suggest those with the same problem (black screen in the chapter reader) to disable the function to detect Webtoon and change the reading mode to "paged (vertical)".
*The paged (vertical) reader mode can be a bit of a nuisance because at the end/beginning of each page(in the cap) there is a slight "dash", jump or skip, whatever you want to call it, boring experience.

**Comment by rsa16** [comment]
If you have investigated that this is not an isolated problem with the fork, I would recommend closing this issue.
