### ISSUE TITLE
[Bug] Chapter updates don't appear on update tab if they are from merged sources.

### ISSUE THREAD

**Issue by KurtzPT** [jobobby04/TachiyomiSY#122]
## Device information
* Tachiyomi version: Stable 1.3.1
* Android version: 10
* Device: Samsung Galaxy Tab S7+

## Steps to reproduce
- Have a manga merged with two sources (MergedSource (ALL))
- Wait for a new chapter to be released for that manga
- Search for chapter updates

### Expected behavior
The new  chapter should appear on the "update tab".

### Actual behavior
The new chapter does not appear on the "update tab".

## Other details
This just happens with merged sources (that have the MergedSource (ALL) on it)

**Comment by jobobby04** [comment]
I can see why that happens, ill see what I can do about it

**Comment by jobobby04** [comment]
After 2 years, I have finally fixed this! I fumbled my way through the SQL and was somehow able to get a working SQL statement. It will be fixed in the next build

**Comment by jobobby04** [comment]
😄
