### ISSUE TITLE
Bato.to chapters not showing in the app, despite being available in the website

### ISSUE THREAD

**Issue by mish20011** [jobobby04/TachiyomiSY#1224]
### Steps to reproduce

Search manhwas with season 2 in Bato.to for example Sex stop watch
Look at the chapter number then compare to the website
App is lacking the season 2 chapters
![Screenshot_20240628044907](https://github.com/jobobby04/TachiyomiSY/assets/72195360/ac2ac34a-5516-4ae8-8236-26c708096425)
![Screenshot_20240628044919](https://github.com/jobobby04/TachiyomiSY/assets/72195360/eb292c26-6f04-4fdc-b069-eab8a18a2466)

### Expected behavior

Chapters should show based on whats in the website (like in kotatsu) 
![Screenshot_20240628045633](https://github.com/jobobby04/TachiyomiSY/assets/72195360/9abf7288-29f6-4fe7-8dd2-0266a836f35a)

### Actual behavior

No chapters showing

### TachiyomiSY version

1.10.5

### Android version

12

### Device

Freeyond m5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by rsa16** [comment]
Have you perhaps tried refreshing the page? If you have, and the chapters still do not show, this would seem to be an extension issue rather than an issue with Mihon (or this fork specifically, for that matter). If you would like to, please create an issue through the extension repository source (hint: Keiyoushi).

**Comment by jobobby04** [comment]
Closing because its (probably) a extension issue.
