### ISSUE TITLE
[Feature Request] Option to save and share cover image when expanded (from J2K)

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#123]
## Why/User Benefit/User Problem
When cover image is tapped and expanded, add buttons to save and share the image on top right corner

## What/Requirements
Yoink the feature from J2K

**Comment by jobobby04** [comment]
Added in https://github.com/jobobby04/TachiyomiSY/commit/a4273bb9a2d13ef9bfb870d88657a61952380891
