### ISSUE TITLE
Dark scans extension is not working 

### ISSUE THREAD

**Issue by LittleKnightG** [jobobby04/TachiyomiSY#1234]
### Steps to reproduce

From what I can tell it looks like the URL has been changed when you open it in webview it comes up with page not found. It shows HTTP error 404. However when you go on dots and just normally searching up the website it works. So I think the web view is broken for dark scans plus I think the URL that connects to the extension is wrong 

### Expected behavior

Are dogs open up to the page of the manga or whatever is loading

### Actual behavior

It just comes up with error I think the url link is wrong

### TachiyomiSY version

App version: 1.10.5 (standard, 6c563d7, 65, 2024-03-02T20:42Z) Preview build: 0 Android version: 10 (SDK 29; build VOG-L09 10.1.0.150(C431E19R2P5)) Device brand: HUAWEI Device manufacturer: HUAWEI Device name: HWVOG (VOG-L09EEA) Device model: VOG-L09 WebView: Android System WebView 126.0.6478.186

### Android version

Android 12

### Device

Huawei p30 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Report the issue to your extension repo.

**Comment by LittleKnightG** [comment]
how do i do that i dont know how this works
