### ISSUE TITLE
Kitsu migrated to different domain (from today)

### ISSUE THREAD

**Issue by krakerz** [jobobby04/TachiyomiSY#1245]
### Steps to reproduce

As title says, kitsu.io > kitsu.app (from their twitter official)

### Expected behavior

Tracking for kitsu working

### Actual behavior

Get json error, due changed domain

### TachiyomiSY version

1.10.5

### Android version

13

### Device

IPlay 50 mini pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by krakerz** [comment]
> Fix in SY Preview r562+ with [543de06](https://github.com/jobobby04/TachiyomiSY/commit/543de065a6b734c4e9a9963400cc06574b49af1f)
> 
> Either swap to SY Preview, or wait for a future SY Stable update

i've tried the preview, tracking is fixed, but just to make sure, is the cover url in this pop up modal already changed as well ?
![image](https://github.com/user-attachments/assets/df31d71d-f379-44d0-83ab-1621b8a6dba2)


thanks

**Comment by Smol-Ame** [comment]
> i've tried the preview, tracking is fixed, but just to make sure, is the cover url in this pop up modal already changed as well ?

That's not an app-related issue, it's an issue on Kitsu's end after switching domains (see first & second picture). When Kitsu fixes/switches out those links, it should reflect on the tracker afterwards. It's also broken on their site & you can see that it's using the old link still (see third picture).

![Screenshot_20240818_193326_Firefox Nightly.png](https://github.com/user-attachments/assets/6b348b23-c321-47d1-9d0a-d115af53616c)

![Screenshot_20240818_195114.png](https://github.com/user-attachments/assets/a90d2206-7fcd-4f5d-9f79-d5b09cc4a590)

![20240818_194707.jpg](https://github.com/user-attachments/assets/f4231b27-a140-4f24-834d-45f44f32bc79)

**Comment by krakerz** [comment]
> > i've tried the preview, tracking is fixed, but just to make sure, is the cover url in this pop up modal already changed as well ?
> 
> That's not an app-related issue, it's an issue on Kitsu's end after switching domains (see first & second picture). When Kitsu fixes/switches out those links, it should reflect on the tracker afterwards. It's also broken on their site & you can see that it's using the old link still (see third picture).
> 
> ![Screenshot_20240818_193326_Firefox Nightly.png](https://private-user-images.githubusercontent.com/155411819/358965445-6b348b23-c321-47d1-9d0a-d115af53616c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODk0MDksIm5iZiI6MTcyNDA4OTEwOSwicGF0aCI6Ii8xNTU0MTE4MTkvMzU4OTY1NDQ1LTZiMzQ4YjIzLWMzMjEtNDdkMS05ZDBhLWQxMTVhZjUzNjE2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQxNzM4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODBjNGE2MzQyMzZiN2Q1MWVhYTY4YTI1YjdkMDNlYjQ0MzRmNTA4ODQzNmFjM2E4MjQ5YTRmNjRjYTJjNTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hDkZS1nJYA4sPtRauW5r6PfPO6dVzeH7u6VlNb8AXbg)
> 
> ![Screenshot_20240818_195114.png](https://private-user-images.githubusercontent.com/155411819/358965467-a90d2206-7fcd-4f5d-9f79-d5b09cc4a590.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODk0MDksIm5iZiI6MTcyNDA4OTEwOSwicGF0aCI6Ii8xNTU0MTE4MTkvMzU4OTY1NDY3LWE5MGQyMjA2LTdmY2QtNGY1ZC05Zjc5LWQ1YjA5Y2M0YTU5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQxNzM4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWRmZDdiZDRjYmM1MGY5MTNkOGIwNGFmM2Y2MDljNzBhODk2NjQ1NjJkNGFlMjRlY2FhMTY3MGFjY2NlODUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r5oURTvuR1diWFcI2Fys6XQVcn-9F7wjT5aFJPT4GAM)
> 
> ![20240818_194707.jpg](https://private-user-images.githubusercontent.com/155411819/358965479-f4231b27-a140-4f24-834d-45f44f32bc79.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODk0MDksIm5iZiI6MTcyNDA4OTEwOSwicGF0aCI6Ii8xNTU0MTE4MTkvMzU4OTY1NDc5LWY0MjMxYjI3LWExNDAtNGYyNC04MzRkLTQ1ZjQ0ZjMyYmM3OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQxNzM4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTc3NDlmMzYyMjAxZjlkMmUyZTFkZDA3ZWFiYTU1NjFjMWEyNDkzNzcyYmQ4M2QyZDgzZmE4MjA5NzM4OTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bkg0CprZyKsY5oLvfYqc_MgeoiQaQ2JHQ-r_WKlmnoY)

ah i see, thanks for the enlightment, i'll close this issue then, thanks again
