### ISSUE TITLE
Chapter transition page sometimes disappears without user input

### ISSUE THREAD

**Issue by perokhe** [jobobby04/TachiyomiSY#1250]
### Steps to reproduce

1. Have "Always show chapter transition" enabled
2. Open a chapter and scroll to previous chapters

### Expected behavior

The chapter transition page should show until I scroll again

### Actual behavior

The page disappears without user input and goes to previous/next chapter

### TachiyomiSY version

Preview r562

### Android version

Android 10

### Device

Samsung Note 9

### Other details

https://github.com/user-attachments/assets/91e809ec-6fd8-4d12-a05d-0e64b9851cc2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
(For Syer) I reverted the [codestral cleanup of some double pages code](https://github.com/jobobby04/TachiyomiSY/commit/1a4a2506f4c3a82b8ba36b76c43ccff6f5a99a59) to test & the issue seems partly fixed. Reverting made it no longer jump to the last page of the previous chapter (stays on Chapter Transition), but still displays a loading page text/loading circle overlay.

**Comment by perokhe** [comment]
Yeah, more specifically I think the problem is that the line `if (newPage is ChapterTransition && index == -1)` was changed to just `is ChapterTransition -> {`
https://github.com/jobobby04/TachiyomiSY/commit/1a4a2506f4c3a82b8ba36b76c43ccff6f5a99a59#diff-1e09718bb3bc7e66c42f70eda465d2834556a72c070a57c5de104ca01e74c8c5L360

**Comment by perokhe** [comment]
Fixed with de6cd16
