### ISSUE TITLE
[Feature Request] Tap on the manga title in reader to go to the manga's details (from j2k) 

### ISSUE THREAD

**Issue by Beylers** [jobobby04/TachiyomiSY#126]
Why/User Benefit/User Problem
Very convenient when you want to check manga details after reading. 

## What/Requirements
The feature was added in the 1.0.8 version of j2k.

**Comment by joseph619** [comment]
why not just go back with back button?? This isn't even a feature

**Comment by Beylers** [comment]
The back button doesn't lead to the details part if you read directly from the Library only if you read on the details part.

**Comment by joseph619** [comment]
But it does in SY though, have you actually used Sy?

**Comment by jobobby04** [comment]
Sounds like this doesnt relate to SY much, ill close

**Comment by Beylers** [comment]
I think you misunderstand me. I know that when you are on the Manga page and then resume reading the Manga, when you back out you are back on the Mangas page. If you start reading the Manga through the library page in which every Manga you have, with the little book button on the top right of the the Manga it doesn't lead you to the Manga page when backing out, it leads you to the library, at least for me. Maybe there's an option that I didn't turn on? 

![Screenshot_20201005-215304_TachiyomiSY](https://user-images.githubusercontent.com/13386163/95125389-30f66200-0755-11eb-90b3-6a2f73cb95d5.jpg)

**Comment by jobobby04** [comment]
You can just click the manga if your reading from there, there is almost no point in adding this

**Comment by Beylers** [comment]
I just thought it was a neat feature in j2k, that I would have loved seeing in SY. Some Manga i dont care for their page but others I love checking out the Mangadex page after reading to check the comments through the inapp browser. I always read from the Library page so Mangas that I want to check the comments on, I then have to press the Manga again and then open the inapp browser. In J2k I would click on the title at the top after reading it would open the page and then I would open the inapp browser. Was just a very niche thing that I thought was awesome for most efficiency. I guess it's worth putting it in if there is no interest.

**Comment by jobobby04** [comment]
Ill reopen for now then, maybe I can take a look at it at some point

**Comment by Beylers** [comment]
Ok thank you very much. I love the SY App.

**Comment by joseph619** [comment]
If you really want to read Mangadex comments, you can directly open webview from reader. You dont need to go back to manga info screen.

**Comment by joseph619** [comment]
This has been added already in preview build, should be marked complete for next release
