### ISSUE TITLE
merged source name not appearing below chapter title

### ISSUE THREAD

**Issue by AminurAlam** [jobobby04/TachiyomiSY#1266]
### Steps to reproduce

1. create a merged source
2. view the entry
3. if it appears exit and open it again

### Expected behavior

the name of source appears below chapter title

### Actual behavior

the source name randomly disappears

### TachiyomiSY version

Preview r563

### Android version

Android 14

### Device

Samsung a34

### Other details

https://github.com/user-attachments/assets/b4f66fef-8102-4bb3-a3c1-2d02bebb4d7e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AminurAlam** [comment]
this also affects dowload status indicator

one way to make the info appear is marking a chapter as read

**Comment by jobobby04** [comment]
Should be fixed in the next build

**Comment by AminurAlam** [comment]
it works as expected now :)
