### ISSUE TITLE
Time zone discrepancy 

### ISSUE THREAD

**Issue by Zaverxi** [jobobby04/TachiyomiSY#1267]
### Steps to reproduce

Example:
1. Opening the updates tab
2. Opening the history tab
3. Chapter release dates in individual webtoon entries

Latest Mihon update has this fix but not Tachiyomi 

### Expected behavior

Example: New releases and read history should show the date they're released. Entries released on August 31, 2024 should show August 31, 2024

### Actual behavior

Example: New releases and read history show coming out the day before, such as displaying August 30, 2024 instead of August 31, 2024

### TachiyomiSY version

1.10.5

### Android version

Android 13

### Device

Galaxy A32

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Fixed in Preview, wait for a future update containing said fix
