### ISSUE TITLE
Migrated from original Tachiyomi, trying to install Hitomi extension results in odd failure loop

### ISSUE THREAD

**Issue by purposelycryptic** [jobobby04/TachiyomiSY#1276]
### Steps to reproduce

- Have Extension repo installed
- Go to 'browse' -> 'extensions'
- Scroll past installed extensions, down to Hitomi extension (v.1.4.33)
- Hit the 'install arrow'

### Expected behavior

- Go to 'browse' -> 'extensions'
& Scroll past installed extensions, down to Hitomi extension (v.1.4.33)
- Hit the 'install arrow'
- Appears to go through install process
- Extension appears in 'Installed' list, works like every other extension.

### Actual behavior

- Go to 'browse' -> 'extensions'
- Scroll past installed extensions, down to Hitomi extension (v.1.4.33)
- Hit the 'install arrow'
- Appears to go through install process
- Extension not appear in installed extensions list
- Try to install again
- Now asks if I want to update extension, choose 'yes'
- Appears to go through update process
- Does not appear in installed extensions list
- Retry with Legacy, PackageInstaller and Shizuku Installers, same result

### Crash logs

`App version: 1.10.5 (standard, 6c563d7, 65, 2024-03-02T20:42Z)
Preview build: 0
Android version: 12 (SDK 31; build SP1A.210812.016.G975U1UEU9IXE1)
Device brand: samsung
Device manufacturer: samsung
Device name: beyond2q (beyond2qlteue)
Device model: SM-G975U1
WebView: Android System WebView 128.0.6613.127

--------- beginning of main
09-13 11:20:15.367 5054 5054 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
09-13 11:20:15.368 5054 5054 E USNET : USNET: appName: eu.kanade.tachiyomi.sy
09-13 11:20:15.655 5054 5097 E de.tachiyomi.s: No package ID 78 found for ID 0x780b000f.
09-13 11:20:15.655 5054 5097 E de.tachiyomi.s: No package ID 78 found for ID 0x780b000f.
09-13 11:20:16.117 5054 5054 E de.tachiyomi.s: Invalid ID 0x00000000.
09-13 11:21:25.320 6067 6067 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
09-13 11:21:25.321 6067 6067 E USNET : USNET: appName: eu.kanade.tachiyomi.sy
09-13 11:21:25.501 6067 6125 E de.tachiyomi.s: No package ID 78 found for ID 0x780b000f.
09-13 11:21:25.502 6067 6125 E de.tachiyomi.s: No package ID 78 found for ID 0x780b000f.
09-13 11:21:25.859 6067 6067 E de.tachiyomi.s: Invalid ID 0x00000000.
09-13 11:29:02.442 10967 10967 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
09-13 11:29:02.443 10967 10967 E USNET : USNET: appName: eu.kanade.tachiyomi.sy
09-13 11:29:02.624 10967 11009 E de.tachiyomi.s: No package ID 78 found for ID 0x780b000f.
09-13 11:29:02.624 10967 11009 E de.tachiyomi.s: No package ID 78 found for ID 0x780b000f.
09-13 11:29:03.014 10967 10967 E de.tachiyomi.s: Invalid ID 0x00000000.
09-13 11:29:03.593 10967 10967 E ViewRootImpl@30859d1[MainActivity]: Surface is not valid.
09-13 11:29:03.615 10967 10967 E ViewRootImpl@30859d1[MainActivity]: Surface is not valid.
09-13 11:30:41.214 10967 11120 E StandaloneCoroutine: Failed to install extension 11621 content://eu.kanade.tachiyomi.sy.provider/ext_files/Download/tachiyomi-all.hitomi-v1.4.33.apk
09-13 11:30:41.214 10967 11120 E StandaloneCoroutine: java.lang.RuntimeException: Failed to commit install session 905788419
09-13 11:30:41.214 10967 11120 E StandaloneCoroutine: at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller$processEntry$1.invokeSuspend(SourceFile:243)
09-13 11:30:41.214 10967 11120 E StandaloneCoroutine: at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
09-13 11:30:41.214 10967 11120 E StandaloneCoroutine: at kotlinx.coroutines.DispatchedTask.run(SourceFile:112)
09-13 11:30:41.214 10967 11120 E StandaloneCoroutine: at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
09-13 11:30:41.214 10967 11120 E StandaloneCoroutine: at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
09-13 11:30:41.214 10967 11120 E StandaloneCoroutine: at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
09-13 11:30:41.214 10967 11120 E StandaloneCoroutine: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
09-13 11:30:51.432 10967 11174 E StandaloneCoroutine: Failed to install extension 11622 content://eu.kanade.tachiyomi.sy.provider/ext_files/Download/tachiyomi-all.hitomi-v1.4.33.apk
09-13 11:30:51.432 10967 11174 E StandaloneCoroutine: java.lang.RuntimeException: Failed to commit install session 67319604
09-13 11:30:51.432 10967 11174 E StandaloneCoroutine: at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller$processEntry$1.invokeSuspend(SourceFile:243)
09-13 11:30:51.432 10967 11174 E StandaloneCoroutine: at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
09-13 11:30:51.432 10967 11174 E StandaloneCoroutine: at kotlinx.coroutines.DispatchedTask.run(SourceFile:112)
09-13 11:30:51.432 10967 11174 E StandaloneCoroutine: at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
09-13 11:30:51.432 10967 11174 E StandaloneCoroutine: at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
09-13 11:30:51.432 10967 11174 E StandaloneCoroutine: at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
09-13 11:30:51.432 10967 11174 E StandaloneCoroutine: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
09-13 11:33:35.431 14834 14834 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.`

### TachiyomiSY version

1.10.5

### Android version

Android 12

### Device

Samsung Galaxy S10+

### Other details

Every other extension installs wonderfully, including those restored from OG Tachiyomi (after un/reinstalling them) - did not have Hitomi extension on original Tachiyomi for ages, since it had been broken for a long time.

Everything looks normal, except after the installation finishes, the extension isn't there. Trying it over results in it trying to update the non-existent extension, but still results in nothing, multiple attempts made. 

Tried to find where extensions are stored on device in hope of deleting any potential corrupted version of it that might be causing the issue, but could not locate.

All I can do in-app is hit install, be asked if I want to update the extension, say yes, and repeat at infinitum.

There is clearly some issue shown in the log, but I am not quite sure what exactly it is, and have no clue as to how I would fix it even if I did.

My hope is that someone smarter than me will understand this, and, ideally, even figure out a solution. My deepest gratitude in advance to whomever that may be 🙇‍♂️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
There's a version of that extension still installed on your phone, check your Phone Settings > App list, or check your Samsung Secure Folder application (this is not your File Manager). Also, change it back to the PackageInstaller or whatever
