### ISSUE TITLE
[Feature Request] Uploaders Name hyperlinks to all uploaded content

### ISSUE THREAD

**Issue by OmfgItsJesus** [jobobby04/TachiyomiSY#128]
## Why/User Benefit/User Problem
(explain why this feature should be added)
Huh, why should this be added well it's a simple basic feature normal site has which I miss the only downside I have found about this perfect app. 

## What/Requirements
(explain how this feature would behave)
On Extensions called E-Hentai & Exhentai when u normally open a doujin/manga it shows the information about it. But kinda sucks that the person who uploaded it, the name doesn't Hyperlink you to all the stuff he has uploaded you have to manually type it in each time.

**Comment by jobobby04** [comment]
This was added a while ago.
