### ISSUE TITLE
No results when library search contains colon (:)

### ISSUE THREAD

**Issue by jroovy** [jobobby04/TachiyomiSY#1288]
### Steps to reproduce

1. Add entries that have ":" in title to library (example: Re:Zero)
2. Search for "re:zero" in library

### Expected behavior

Search results should return Re:Zero entries

### Actual behavior

Search results are empty

### TachiyomiSY version

Dev Build 566

### Android version

Android 11

### Device

Motorola G5s Plus

### Other details

![Screenshot_20241017-013244533](https://github.com/user-attachments/assets/99158222-54ab-4d91-a0a7-ce869f9c4c8a)
![Screenshot_20241017-013254006](https://github.com/user-attachments/assets/7cce9b0b-2a0f-49b4-9b78-bfd3e7947c78)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
`:` is a special character in the search, there are sources that use `:` as a separator so it is handled differently from other characters. If you need to search something with a `:`, just remove it from the query and put a space.
