### ISSUE TITLE
Auto Download not queuing up new chapters

### ISSUE THREAD

**Issue by shmightworks** [jobobby04/TachiyomiSY#1292]
### Steps to reproduce

Turn on auto download

### Expected behavior

Auto downloads when new chapters are added

### Actual behavior

Sometimes, some chapters aren't being queued to download.
I can see new chapters availible, but I don't see that chapter added to the queue.
This doesn't happen all the time, I do see time to time new chapters being downloaded, but there are also times when new chapters just sits there not being downloaded.

I haven't figured out if it's particular manga, or if it has to do with if I'm on wifi or mobile data when the library updates.

I understand even if on queue, if I have only download on wifi turned on, it will just sit there until I connect to wifi, but in my case it's not even on queue.

### TachiyomiSY version

r566

### Android version

Android 14

### Device

Samsung A55

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Maybe you have "Skip downloading duplicate read chapters" enabled? Or the category isn't included/excluded from Auto-download?

![Screenshot_20241023_131055_TachiyomiSY](https://github.com/user-attachments/assets/631ec0e4-c862-4c84-8911-42dc0c89f9bc)

**Comment by shmightworks** [comment]
Nope, that's not it.
I have those exact settings.

**Comment by Smol-Ame** [comment]
Where are you seeing these new chapters? In WebView? Or in the chapter list of whatever manga you have saved in your Library?

Maybe you need to give the app permission again, such as Background Usage enabled & Battery Optimization disabled. I don't think it's the following, but just to check I guess, go to your Phone Settings > Developer Options, and see if your settings match mine:

![Screenshot_20240601_165337_Settings](https://github.com/user-attachments/assets/3429a701-b2cb-49c4-8861-615166944196)


Unrelated, but if your version you wrote is correct, you're behind on a version (r567)

**Comment by shmightworks** [comment]
I have the overlays on the library screen to show me how many new chapters are there, and also how many are downloaded.
So on some days, I would see the odd case where I see the new chapter overlay, but I see no corresponding downloaded chapter for it.
I go into the manga, and indeed, there's a new chapter, but it's not downloaded.
I click the download, then it proceed to put it on queue, and it goes on and downloads it.

So the master library updating does happen, it's just for some reason new chapters aren't added to queue to be downloaded.

I do see I can turn on log level to "Extra".  I'd guess I can try that for a few days, and see if I can catch that bug happen, then check the log.
Where would the log file be placed?

**Comment by shmightworks** [comment]
OK, I'm gonna close this for now.
Since turning on the logging, I haven't seen this happen, and still haven't seen it happen even after turning it off.
Maybe recent the updates, or cleaning up of some downloaded files fixed it.
I'll come back if this ever does happen again.
