### ISSUE TITLE
No pages found in EXH Galleries

### ISSUE THREAD

**Issue by zerpiente** [jobobby04/TachiyomiSY#1293]
### Steps to reproduce

1. Open any ExH gallery 
2. Try to read any version of the gallery

### Expected behavior

The gallery should show preview images
The gallery should open normally

### Actual behavior

No previews are shown
A "no pages found error" appears when trying to read

### TachiyomiSY version

App version: 1.10.5 (standard, bbaa74d99, 69, 2024-10-20T05:53:33Z) Preview build: 567

### Android version

Android 14

### Device

Samsung A52

### Other details

Extra details: 
1. the app was updated days ago but only started showing this issue today
2. Galleries that were still saved in cache worked normally
3. Galleries work normally in webview, I am logged in and my account is old enough 
4. No VPN is being used

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by 20kbar** [comment]
Same issue. Already went through most common fixes, occured on multiple devices. Definitely not an isolated case.

**Comment by colpocleisis** [comment]
> 2024-10-25
> 
> * The previously announced backend and DOM changes are now live for a section of the site, let me know if you encounter any issues with this NOT related to outdated scripts.

https://forums.e-hentai.org/index.php?showtopic=244935

This is due to ExH backend changes

**Comment by jobobby04** [comment]
I will be taking a look at it this weekend, I don't expect it to take me too long to fix when I get to it

**Comment by vicokoby** [comment]
This issue has already been resolved at https://github.com/az4521/TachiyomiAZ/commit/b84a2b3e40dc15a6397a1c687a1ee4d6100c751a
Waiting for the new TachiyomiSY build

**Comment by jobobby04** [comment]
It is currently fixed in the latest preview build https://github.com/jobobby04/TachiyomiSYPreview/releases/tag/568
I will be working on a stable release that I hope to get out tomorrow
