### ISSUE TITLE
Constant crash

### ISSUE THREAD

**Issue by kyzuku** [jobobby04/TachiyomiSY#1295]
### Steps to reproduce

Open up app, it will randomly crash.
Also whenever I try to mass download through the top button, could be 2 mangas with 1 new chapter each, or even 5 chapters on a single manga, will go black + freeze then crash. Logs attached. Happened after I updated to latest version.

### Expected behavior

No crashing/freezing

### Actual behavior

Crashing/freezing

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/user-attachments/files/17532407/tachiyomi_crash_logs.txt)

### TachiyomiSY version

1.10.5

### Android version

Android 15

### Device

Google Pixel 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Don't think Android 15 is supported at all. But create a backup file, then update your app into SY Preview, and see if that helps the app not crash as much (from an old Pixel issue)
