### ISSUE TITLE
E-Hentai page duplication

### ISSUE THREAD

**Issue by HisuianZoroark69** [jobobby04/TachiyomiSY#1300]
### Steps to reproduce

Read any chapter on E-Hentai

### Expected behavior

No page was duplicated

### Actual behavior

The number of pages shown on the summary and the preview is still correct. But when get into the chapter, all pages got duplicated.
![ảnh](https://github.com/user-attachments/assets/f015b82f-e2a4-485a-983d-5496a16b5d50)
![ảnh](https://github.com/user-attachments/assets/1a968d8c-f68f-4204-ab47-03c7948c2e54)

### TachiyomiSY version

1.11.0

### Android version

Android 14

### Device

Samsung Galaxy S21 FE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Looks like E-Hentai swapped to the new website changes, does this still happen? Test with a new gallery since your chapter cache may still have the older page-list

**Comment by HisuianZoroark69** [comment]
Yeah it's back to normal now, thanks.
