### ISSUE TITLE
[Feature Request] Divide manga based on tags similar to tracking status

### ISSUE THREAD

**Issue by sukhijapiyush** [jobobby04/TachiyomiSY#131]
## Why/User Benefit/User Problem
It makes it easier to find the manga based on your mood like comedy, tragedy etc in your large library

## What/Requirements
It is present in TachiJ2K and works similar to tracking status division.

**Comment by joseph619** [comment]
This has already been rejected iirc.

**Comment by jobobby04** [comment]
It wont work well. There could be thousands of tags in the library
