### ISSUE TITLE
Downloaded chapters were unindexed / are missing

### ISSUE THREAD

**Issue by Kuuh4** [jobobby04/TachiyomiSY#1316]
### Steps to reproduce

Download chapters
Update app version

### Expected behavior

Downloaded chapters were supposed to still show up

### Actual behavior

Previously downloaded chapters do not show up.
Downloading them again doesn't work.
Downloading new/undowloaded chapters works fine.
Files for all downloaded manga still show up at the app's download folder, as cbz.
New chapters were downloaded to the same folders than the older ones.

### TachiyomiSY version

App version: 1.11.0 (standard, 26cfb4811, 71, 2024-11-08T03:25:38Z) Preview build: 574 

### Android version

Android version: 14 (SDK 34; build UP1A.231005.007.X810XXS3BXE1) 

### Device

Device brand: samsung Device manufacturer: samsung Device model: SM-X810

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Have the app reindex it then?

SY Settings > Advanced > Reindex downloads

**Comment by Kuuh4** [comment]
> Have the app reindex it then?
> 
> SY Settings > Advanced > Reindex downloads

Thank you so much. 
I still find it weird that it de-indexed with this build, so I leave closing this issue to your discretion.
