### ISSUE TITLE
App crashes when opening links from browser

### ISSUE THREAD

**Issue by roblox28** [jobobby04/TachiyomiSY#1317]
### Steps to reproduce

App is set to allow links to "open by default", but allowed links cause app to crash. Conversely, if app's "open by default" is disabled and the individual extension's "open by default" is enabled, the app doesn't crash but also does not provide a direct link to the manga, it just opens the global search with the manga's ID. 

### Expected behavior

App should not crash

### Actual behavior

See above

### Crash logs

[tachiyomi_crash_logs-1.txt](https://github.com/user-attachments/files/17694138/tachiyomi_crash_logs-1.txt)

### TachiyomiSY version

1.11.0

### Android version

Android 12

### Device

Pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is fixed in the latest build 👍
