### ISSUE TITLE
N-hentai previews not working

### ISSUE THREAD

**Issue by Emperorz786** [jobobby04/TachiyomiSY#1321]
### Steps to reproduce

1. Go to nhentai extension
2. Open any new doujin
3. Scroll down to check for previews
4. You will notice that previews aren't showing
![Screenshot_20241113_205625](https://github.com/user-attachments/assets/9b2bec21-2b54-47c8-b900-b29a39d6d74c)

### Expected behavior

The previews for doujins should be shown

### Actual behavior

The previews aren't being shown

### TachiyomiSY version

1.11.0

### Android version

Android 14

### Device

Iqoo Neo 9 pro 

### Other details

The issue started on a particular day and all the updates after that aren't showing previews. But the older doujins are showing previews properly. Interestingly, the issue doesn't exist on e-hentai

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by zalzalzal17** [comment]
I found that nhentai now upload webp format and make preview not available, if nhentai upload jpg format its still working
