### ISSUE TITLE
Unable to open comic through link

### ISSUE THREAD

**Issue by huajideshutiao** [jobobby04/TachiyomiSY#1324]
### Steps to reproduce

To be precise, [the issue(1116)](https://github.com/jobobby04/TachiyomiSY/issues/1116#issue-2188774547) has reappeared once again.

### Expected behavior

null

### Actual behavior

null

### TachiyomiSY version

Preview r574 (26cfb4811, 2024/11/8 11:25)

### Android version

Android 15

### Device

redmi k70 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/c2df6ee54ab417dd78d60873c0a83b5cf91b6424
