### ISSUE TITLE
Crashed after removing a manga from favorites 

### ISSUE THREAD

**Issue by marthLSbrawler** [jobobby04/TachiyomiSY#1334]
### Steps to reproduce

1. Had a manga in my favourites list (Kimi wa Midara na Boku no Joou, I think it was on bato.to English but not certain)
2. Removed from favorites
3. Hit back button on Android
4. App went dark for a second or 2,hit back button again
5. App crashed and brought up crash report
6. Bonus thing, not sure if it makes a difference but had a chapter of another manga downloading apparently 

### Expected behavior

Smooth transition from manga screen to favourites list

### Actual behavior

App crashed and brought up crash report screen

### Crash logs

AndroidRuntime: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{829e2c1 u0 eu.kanade.tachiyomi.sy/androidx.work.impl.foreground.SystemForegroundService}
11-24 22:51:18.546  9069  9069 E AndroidRuntime: 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315)
11-24 22:51:18.546  9069  9069 E AndroidRuntime: 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286)
11-24 22:51:18.546  9069  9069 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
11-24 22:51:18.546  9069  9069 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611)
11-24 22:51:18.546  9069  9069 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-24 22:51:18.546  9069  9069 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
11-24 22:51:18.546  9069  9069 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
11-24 22:51:18.546  9069  9069 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8919)
11-24 22:51:18.546  9069  9069 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-24 22:51:18.546  9069  9069 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
11-24 22:51:18.546  9069  9069 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
--------- beginning of main
11-27 20:42:38.100  8005  8005 E de.tachiyomi.sy: Not starting debugger since process cannot load the jdwp agent.
11-27 20:42:38.252  8005  8085 E de.tachiyomi.sy: No package ID 77 found for resource ID 0x770b000f.
11-27 20:42:38.252  8005  8085 E de.tachiyomi.sy: No package ID 77 found for resource ID 0x770b000f.
11-27 20:42:38.361  8005  8115 E chromium: [1127/204238.361747:ERROR:variations_seed_loader.cc(39)] Seed missing signature.
11-27 20:42:45.536  8005  8205 E SQLiteLog: (284) automatic index on C(manga_id)
11-27 20:42:45.536  8005  8205 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-27 20:42:45.566  8005  8205 E SQLiteLog: (284) automatic index on C(manga_id)
11-27 20:42:45.566  8005  8205 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-27 20:42:45.566  8005  8205 E SQLiteLog: (284) automatic index on merged(manga_id)
11-27 20:42:45.566  8005  8205 E SQLiteLog: (284) automatic index on ME(merge_id)
11-27 20:42:45.566  8005  8205 E SQLiteLog: (284) automatic index on C(merge_id)
11-27 20:42:45.566  8005  8205 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-27 20:50:55.070  8005  8005 E MangaScreenModel: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@94b4147
11-27 20:50:55.376  8005  8005 E MangaScreenModel: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@94b4147
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: java.lang.IllegalArgumentException: Key eu.kanade.tachiyomi.ui.library.LibraryTab:currentTab was used multiple times 
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at androidx.glance.session.SessionWorkerKt$runSession$6.invoke(SourceFile:177)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(SourceFile:5)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at com.google.firebase.crashlytics.internal.common.AppData.dispatchRememberObservers(SourceFile:121)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(SourceFile:63)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at androidx.compose.runtime.CompositionImpl.applyChanges(SourceFile:6)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at androidx.compose.material3.DatePickerKt$HorizontalMonthsList$1$2$1.invoke(SourceFile:228)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(SourceFile:34)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(SourceFile:48)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at android.view.Choreographer.doFrame(Choreographer.java:1069)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at android.os.Handler.handleCallback(Handler.java:958)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at android.os.Looper.loopOnce(Looper.java:230)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at android.os.Looper.loop(Looper.java:319)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:8919)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
11-27 20:52:16.032  8005  8005 E GlobalExceptionHandler: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@2a20b63, androidx.compose.ui.platform.MotionDurationScaleImpl@93360, StandaloneCoroutine{Cancelling}@dd25019, AndroidUiDispatcher@349e8de]
11-27 20:52:16.144  8005  8005 E AndroidRuntime: FATAL EXCEPTION: main
11-27 20:52:16.144  8005  8005 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 8005
11-27 20:52:16.144  8005  8005 E AndroidRuntime: java.lang.IllegalArgumentException: Key eu.kanade.tachiyomi.ui.library.LibraryTab:currentTab was used multiple times 
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at androidx.glance.session.SessionWorkerKt$runSession$6.invoke(SourceFile:177)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(SourceFile:5)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at com.google.firebase.crashlytics.internal.common.AppData.dispatchRememberObservers(SourceFile:121)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(SourceFile:63)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.applyChanges(SourceFile:6)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at androidx.compose.material3.DatePickerKt$HorizontalMonthsList$1$2$1.invoke(SourceFile:228)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(SourceFile:34)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(SourceFile:48)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:1069)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8919)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
11-27 20:52:16.144  8005  8005 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@2a20b63, androidx.compose.ui.platform.MotionDurationScaleImpl@93360, StandaloneCoroutine{Cancelling}@dd25019, AndroidUiDispatcher@349e8de]
11-27 20:52:16.237 15346 15346 E y:error_handler: Not starting debugger since process cannot load the jdwp agent.
11-27 20:52:16.366 15346 15387 E SQLiteLog: (283) recovered 9 frames from WAL file /data/data/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-wal
11-27 20:52:16.403 15346 15419 E y:error_handler: No package ID 77 found for resource ID 0x770b000f.
11-27 20:52:16.403 15346 15419 E y:error_handler: No package ID 77 found for resource ID 0x770b000f.
11-27 20:52:16.807 15527 15527 E de.tachiyomi.sy: Not starting debugger since process cannot load the jdwp agent.
11-27 20:52:16.972 15527 15598 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
11-27 20:52:16.991 15527 15616 E de.tachiyomi.sy: No package ID 77 found for resource ID 0x770b000f.
11-27 20:52:16.992 15527 15616 E de.tachiyomi.sy: No package ID 77 found for resource ID 0x770b000f.
11-27 20:52:16.996 15527 15623 E chromium: [ERROR:variations_seed_loader.cc(39)] Seed missing signature.

### TachiyomiSY version

1.11.0

### Android version

Android 14

### Device

Samsung Galaxy S22 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Mihon issue thats been fixed in the preview
