### ISSUE TITLE
The exhentai URL is outdated and request multiple times

### ISSUE THREAD

**Issue by huajideshutiao** [jobobby04/TachiyomiSY#1336]
### Steps to reproduce

1. Enter the comic details page
2. Pull down refresh

### Expected behavior

Can quickly refresh content

### Actual behavior

![Screenshot_2024-12-04-04-02-19-586_com guoshi httpcanary](https://github.com/user-attachments/assets/b1010243-7849-4e59-88ea-550e5dd68075)

From the network requests I have captured, when I click on a manga that I have never visited before, the application will initiate three requests pointing to a unified resource, two of which were redirected by 302.
When I click the start reading button, the app starts searching for all the links to the comic. Similarly, it's another 302 redirect.
In summary, it took me nearly eight seconds from entering the comic detail page to obtaining all the image page links for the application. In an ideal state, The time required to access the detailed URL and obtain links to all image pages should be within 1500 milliseconds.

### TachiyomiSY version

Preview r574 (26cfb4811, 2024/11/8 11:25)

### Android version

Android 15

### Device

redmi k70 pro

### Other details

I have some ideas about obtaining links to image pages. Since accessing the comic detail page itself contains a certain number of image page links (the default setting should be 40 images), the first 40 images can be parsed when entering the detail page for the first time. After clicking on start reading, the application can load the first 40 images, and subsequent image page retrieval can be processed asynchronously. There is no need to wait for all url/?p=x to obtain responses before parsing the image page, and processing can be done every 40 images obtained.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This doesn't really have anything to do with outdated/bad links. This is how the Exh chapter system work, old galleries are chapters and the latest gallery is the latest chapter.
And we need to get all page links at once, this is a restriction of the Tachi/Mihon source api.
So while this isn't optimal, its the best solution available with the restrictions we have.

**Comment by huajideshutiao** [comment]
> I'm not positive but at the top of my head, `nw=always` may be the gallery warning bypass link. I believe that I haven't make it concurrent since Exh has always had a huge rage-limit thats easy to trigger, and its easy to avoid when doing sequential requests.

You can take a look at the series of pictures below. Indeed, the same two requests occurred, with only a few tens of milliseconds difference.
![Screenshot_2024-12-04-23-23-47-961_com guoshi httpcanary](https://github.com/user-attachments/assets/f8df7352-8cad-4d2a-a723-43bcf1fb861d)
![Screenshot_2024-12-04-23-23-59-701_com guoshi httpcanary](https://github.com/user-attachments/assets/2d91f634-c174-4402-a412-62c8b43d9bcf)
![Screenshot_2024-12-04-23-24-08-458_com guoshi httpcanary](https://github.com/user-attachments/assets/9e9d4dc7-05fc-4e97-a9fc-69e7a58010da)
Pay attention to "开始时间" in the last two images, one is 2024-12-04 23:23:32.341 and the other is 2024-12-04 23:23:32.404

**Comment by huajideshutiao** [comment]
> I'm not positive but at the top of my head, `nw=always` may be the gallery warning bypass link. I believe that I haven't make it concurrent since Exh has always had a huge rage-limit thats easy to trigger, and its easy to avoid when doing sequential requests.

I don't seem to have seen any gallery warnings, maybe I don't use the web version very much, or maybe I need to consult other users.

**Comment by jobobby04** [comment]
The 2 requests is another restriction of the Tachi/Mihon source Api, there are separate requests for the chapter list and manga info. So most sources have to do the same request twice.

**Comment by jobobby04** [comment]
> I don't seem to have seen any gallery warnings, maybe I don't use the web version very much, or maybe I need to consult other users.

Its most common with galleries with Guro/Snuff. I'm not sure if ExHentai has it but E-Hentai does.

**Comment by huajideshutiao** [comment]
> > I don't seem to have seen any gallery warnings, maybe I don't use the web version very much, or maybe I need to consult other users.
> 
> Its most common with galleries with Guro/Snuff. I'm not sure if ExHentai has it but E-Hentai does.

Now the problem is clear. For the same gallery, e-hentai will be masked by default due to r18g, while exhentai will not. (Perhaps they think exhentai users have a higher tolerance)

**Comment by huajideshutiao** [comment]
> The 2 requests is another restriction of the Tachi/Mihon source Api, there are separate requests for the chapter list and manga info. So most sources have to do the same request twice.

It seems that even though the Tachi project has disbanded, it still makes us understand in some form that it is still accompanying us. 🤣
