### ISSUE TITLE
Order of chapters wrong when received through sync

### ISSUE THREAD

**Issue by Lolle2000la** [jobobby04/TachiyomiSY#1339]
### Steps to reproduce

Precondition: Device A: Has new chapters not on Device B

1. Device A synchronizes
2. Device B synchronizes
3. View entry with new chapters received through sync (not standard update)

### Expected behavior

Chapters are in correct order.

### Actual behavior

They get mixed in with the latest chapter usually ending up at the next one.

### TachiyomiSY version

r574

### Android version

Android 15 (OxygenOS 15.0)

### Device

OnePlus Pad 2

### Other details

**Edit: I'm using SyncYomi self-hosted** (forgot to also note this down, but I also had this issue on Google Drive before migrating)

Paste from the settings: 

App version: 1.11.0 (standard, 26cfb4811, 71, 2024-11-08T03:25:38Z)
Preview build: 574
Android version: 15 (SDK 35; build OPD2403_15.0.0.202(EX01))
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OP5DAAL1 (OPD2403EEA)
Device model: OPD2403
WebView: Android System WebView 131.0.6778.39

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Lolle2000la** [comment]
I see [7f37989](https://github.com/cuong-tran/TachiyomiSY/commit/7f37989c4e503752ab8f417f4760371654929afa) will fix this, but that commit seems to only affect the Google Drive-Version(?), I'm currently using the SyncYomi-provider (should have mentioned this in the issue honestly; will make an edit). Will this also fix the issue there?

For more context: I originally had sync running with Google Drive (bug also occured here) but switched to SyncYomi for better performance.

**Comment by cuong-tran** [comment]
> I see [7f37989](https://github.com/cuong-tran/TachiyomiSY/commit/7f37989c4e503752ab8f417f4760371654929afa) will fix this, but that commit seems to only affect the Google Drive-Version(?), I'm currently using the SyncYomi-provider (should have mentioned this in the issue honestly; will make an edit). Will this also fix the issue there?
> 
> For more context: I originally had sync running with Google Drive (bug also occured here) but switched to SyncYomi for better performance.

No that commit has nothing to do with this. It just so happen that the original commit message link to an issue on Mihon then got cherry pick on TachiyomiSY, and accidently has same issue number with this.

**Comment by Lolle2000la** [comment]
Ah ok, sorry then! That confused me. I read the message saying that is solves and closes this issue and got confused.
