### ISSUE TITLE
[Feature Request] previous / next option in the reader 

### ISSUE THREAD

**Issue by Mapsred** [jobobby04/TachiyomiSY#134]
## Why/User Benefit/User Problem
(explain why this feature should be added)

Similarly to the standard Tachiyomi I think having the previous / next buttons could be interesting. 
Those button are easier to use than the menu when we want to move one chapter before or after

## What/Requirements
(explain how this feature would behave)

As we already have a chapter list button it would be great to have an option to switch between chapter list and previous / next

**Comment by joseph619** [comment]
Should the chapter buttons be brought back, they should be split from the bottom toolbar like the seekbar like in the mockup below
![Screenshot_20200920-222940](https://user-images.githubusercontent.com/34897862/96128964-fcf10e80-0ec3-11eb-99c5-079b23e93b82.jpg)
.

**Comment by joseph619** [comment]
This has been added in latest preview
