### ISSUE TITLE
Cannot download Mangas with same title

### ISSUE THREAD

**Issue by Linguiniotta** [jobobby04/TachiyomiSY#1343]
### Steps to reproduce

1. Find 2 Mangas with similar/equal name.
2. Download and Add `Manga 1` to library.
3. Download and Add `Manga 2` to library.

### Expected behavior

`Manga 1` and `Manga 2` should have different download button regardless of equality in Manga Title.

### Actual behavior

Since they have the same name, the download button for `Manga 2` is already shown as downloaded even if they are different mangas from different authors/sources.

(Not sure if the same behavior happen in other sources, but this happens on MyReadingManga)

### TachiyomiSY version

Stable 1.11.0 (Oct 28, 2024 11:12 AM)

### Android version

Android 12

### Device

vivo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Sources that have duplicate manga are not supported. If they are different versions that should be specified by the title or scanlator field on the chapters.
