### ISSUE TITLE
[Feature Request] Auto Update/Update notification when new release is available OR an F-Droid repo

### ISSUE THREAD

**Issue by JediRhymeTrix** [jobobby04/TachiyomiSY#135]
Why/User Benefit/User Problem

(explain why this feature should be added)

This would make it a lot easier to keep the app up to date.

What/Requirements

(explain how this feature would behave)

While auto update would be ideal, even a notification when a new build is available would be great. Another option could be adding an F-Droid repo similar to the main app.

**Comment by jobobby04** [comment]
It does have a update notif lol. I am not planning on doing anything fdroid, but the app should support it
