### ISSUE TITLE
[Bug] new backup crashes app.

### ISSUE THREAD

**Issue by ardittristan** [jobobby04/TachiyomiSY#137]
When i try to make a backup with the new version the app crashes a few seconds later. I wasn't able to find any anomalies in the logs: https://gist.github.com/e25ee307e9eb49b0d1586c075447d83f

I do have almost 700 manga in my library

![](https://i.imgur.com/fTYzhlk.png)

**Comment by ardittristan** [comment]
(sorry for bad format, issue templates don't work on my phone)

**Comment by jobobby04** [comment]
Can you try the latest build

**Comment by ardittristan** [comment]
Still crashes the same way (added new log to gist)

**Comment by ardittristan** [comment]
I did find this in my logcat
![](https://i.imgur.com/fPToG8Y.png)

**Comment by jobobby04** [comment]
Can you try on the latest build

**Comment by ardittristan** [comment]
It works now
