### ISSUE TITLE
[Bug] Crash when updating any MangaPlus title on Android 6

### ISSUE THREAD

**Issue by tjgordon** [jobobby04/TachiyomiSY#138]
## Device information
* Tachiyomi version: Preview r271
* Android version: 6
* Device: Boyue Likebook Mars

## Steps to reproduce
1. Open any title in the library from MangaPlus.
2. Refresh the title by pulling from the top.

### Expected behavior
The title's details and chapter list should refresh.

### Actual behavior
Tachiyomi crashes.

## Other details
All MangaPlus titles in the library are missing the art.  

The crash also happens when a full library update gets to any MangaPlus title, and when clicking MangaPlus in Browse.  

This time I have unsuccessfully tried uninstalling and reinstalling the MangaPlus extension, clearing the extension's data, and extracting and installing the extension APK from my other device (r271 on Android 10, same library, no crashes).   

I'm currently using r271 to test because it is the latest and I'm trying to use the new CBZ download feature, but this crash has been happening for a few weeks, though I'm not sure which version was the last one that worked or what the MangaPlus extension version was at the time. I did try uninstalling the preview and using the latest stable at one point a few weeks ago, and the crash still happened. I also have vanilla Tachiyomi installed, and it doesn't crash.

**Comment by tjgordon** [comment]
Here's a log of trying to refresh 'One Piece Re-edition':  
[logcat_10-13-2020_01-28-10.txt](https://github.com/jobobby04/TachiyomiSY/files/5370007/logcat_10-13-2020_01-28-10.txt)

**Comment by jobobby04** [comment]
Can you try on the latest build

**Comment by tjgordon** [comment]
No change on r279.

**Comment by jobobby04** [comment]
Try uninstalling manga plus, and then installing it again

**Comment by tjgordon** [comment]
Updated to r280, uninstalled MP extension, reinstalled extension, no change in behavior.

**Comment by jobobby04** [comment]
Seems the Manga plus extension was updated, it likely fixes your issue
