### ISSUE TITLE
[Feature Request] Custom directory location for your local manga and option to edit local manga "status"

### ISSUE THREAD

**Issue by IAMNOTRANA** [jobobby04/TachiyomiSY#139]
Custom directory.
It would be great if we could set a custom location for our local manga, default one is fine but it become pain in the ass to have a neat and clean folders to keep things tidy, its probably not the most requested feature but having such basic option would be great for local manga users.

Local manga "Status" editing
We have option to edit local manga cover, author, artist and even synopsis but why no option to edit manga status? I've so many manga that I honestly lost track of things, its absolute pain to edit json manually to add "status" for each manga in your collection.

**Comment by joseph619** [comment]
I don't know if custom directories of any kind will be allowed from now onwards due to scoped storage change in Android 11.

**Comment by joseph619** [comment]
This was added with commit https://github.com/jobobby04/TachiyomiSY/commit/5a67d8169d5491b0be625647b0df0793c652aaf0

@jobobby04
