### ISSUE TITLE
[Feature Request] Library Update Frequency - Exclusion Period.

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#140]
## Why/User Benefit/User Problem
Well, it won't update the library especially when we don't use tachi. let's say frequency is set for `every 3 hours`, and from `0900 to 1500` I would like the app to disregard `auto-updates frequency set` and do not update the library.
`setting it to the manual is a bit of hassle and need to revert later to set auto-update library`

## What/Requirements
I would say something like biometric lock time.

### Option 
It would also be feasible to halt the auto-update process when biometric lock time is set.

**Comment by joseph619** [comment]
This is basically the same as custom time range for library update I think

**Comment by Mano5JP** [comment]
well, it is the same as the custom range, and  I would be satisfied with if the job is done^^.

I would want to minimize unnecessary update check while my phone is idle, especially at work and at night.
So advance flexibility on update frequency with custom time range would be niche.

what Syer thinks? is this meriting? 

Thx
Cheers Joseph
