### ISSUE TITLE
[Bug] Can't Track Manga

### ISSUE THREAD

**Issue by Clover-Zero** [jobobby04/TachiyomiSY#141]
## Device information
* Tachiyomi version: Stable 1.3.1
* Android version: 9
* Device: ASUS Zenfone Max Pro M1

## Steps to reproduce
1. Click a manga.
2. Click tracking.

### Expected behavior
"Add tracking" box appears and I can click on it to begin tracking.

### Actual behavior
No box appears and the app freezes. I have to force close it. See screenshot.

## Other details
I thought this only happens to mangas I've tracked in AniList but haven't in Tachiyomi, but turns out there's some mangas and manhwas that I haven't tracked in either that resulted in the same error.

![Screenshot_20201018-111023~2](https://user-images.githubusercontent.com/35261572/96358701-552e4780-1134-11eb-9eec-9589447b895e.png)

**Comment by jobobby04** [comment]
Login to mangadex in the app settings, this is because of the way that I checked the login in the stable version of SY, I have fixed this in the previews

**Comment by Clover-Zero** [comment]
Oh! I forgot to login to Mangadex...
Thank you for the quick response, all is well now.
