### ISSUE TITLE
[Bug] Nhentai setting for displaying title as short title doesn't works as it should be

### ISSUE THREAD

**Issue by sethazazel** [jobobby04/TachiyomiSY#142]
## Device information
* Tachiyomi version: Preview r280
* Android version: 9
* Device: Huawei ANE-LX2

## Steps to reproduce
1. Open Nhentai settings
2. Change Display manga titles as: to short title
3. Open Nhentai, select a random manga
4. Title refresh itself to full title

### Expected behavior
Title should remain as short

### Actual behavior
Title changes to full

## Other details
I tried same thing in Tachiyomi, it was working well.

(Sorry for my bad English.)

**Comment by jobobby04** [comment]
Added in https://github.com/jobobby04/TachiyomiSY/commit/99457526674d309431abdec17eb5fcb07b29768d

**Comment by sethazazel** [comment]
thank you
