### ISSUE TITLE
[Feature Request] Watch specific contents

### ISSUE THREAD

**Issue by sethazazel** [jobobby04/TachiyomiSY#143]
## Why/User Benefit/User Problem
With this way new relases of specific tags and search keywords will be found more easily.

## What/Requirements
We have "watch" feature already. If we could watch tags or search keywords of a source i think it would be better.

example:
watch nhentai for latest vanilla releases.
watch mangadex for latest horror mangas.
don't show latest ntr contents.

**Comment by joseph619** [comment]
You can already save search queries for individual sources. Use that feature next time.

**Comment by jobobby04** [comment]
Watching is only for latest, I don't feel like making it to advanced would be very helpful or intuitive
