### ISSUE TITLE
[Bug] lewd filter doesn't filter out some sources

### ISSUE THREAD

**Issue by sethazazel** [jobobby04/TachiyomiSY#150]
## Device information
* Tachiyomi version: Preview r296
* Android version: 9.1.0
* Device: Huawei ANE-LX2

## Steps to reproduce
Filter out lewd mangas

### Expected behavior
lewd mangas should be filtered

### Actual behavior
Some lewd mangas from specific sources were not filtered

## Other details
hitomi.la and 8muses mangas should also be filtered

**Comment by joseph619** [comment]
This is not really a bug

**Comment by jobobby04** [comment]
Added the sources in https://github.com/jobobby04/TachiyomiSY/commit/98bfe34e1880352dcf781685d7fb9c3917b38de0

**Comment by sethazazel** [comment]
thank you
