### ISSUE TITLE
[Bug] MD Similar Manga frequency not working

### ISSUE THREAD

**Issue by Goku003** [jobobby04/TachiyomiSY#151]
## Device information
* Tachiyomi version: r296
* Android version: A10
* Device: OP6

## Steps to reproduce
1. Setting similar manga frequency to manual

### Expected behavior
Until I manually click 'Pull latest database', it shouldn't pull the records

### Actual behavior
It still pulls the record every 2days.

**Comment by jobobby04** [comment]
Fixed in https://github.com/jobobby04/TachiyomiSY/commit/8f1f6d5a973a6bc2dd99677b5edaaf45fb76aec3
