### ISSUE TITLE
[Feature Request] Selective update

### ISSUE THREAD

**Issue by sethazazel** [jobobby04/TachiyomiSY#152]
## Why/User Benefit/User Problem
I think it would be good if we could update only some of mangas that we select. Especially if we have too much mangas in library and only want to check some of them.

## What/Requirements
1- Select some mangas
2- open 3 dot menu
3- touch to update

**Comment by joseph619** [comment]
Create categories and restrict update to certain category. 

 https://tachiyomi.org/help/guides/categories/

**Comment by jobobby04** [comment]
Ya, you can put manga in multiple categories, make a update manga category, and add them to both your normal category and that category
