### ISSUE TITLE
[Feature Request] <Similar to TachiJ2K remove downloads option>

### ISSUE THREAD

**Issue by jadoff630** [jobobby04/TachiyomiSY#153]
## Why/User Benefit/User Problem
In TachiJ2K, there is a setting in library pages for each manga called "remove downloads" It then asks you if you would like to remove all downloads or all read chapters. In SY there is the clean up downloaded chapters option in advanced settings, but that is global, this would be able to be implemented on an individual manga basis. 

## What/Requirements
Screenshots from TachiJ2K:
![Screenshot_20201103-113914_TachiyomiJ2K](https://user-images.githubusercontent.com/25085973/98021701-3ed9ea00-1dca-11eb-9ad6-4639c6518b0b.jpg)
![Screenshot_20201103-113927_TachiyomiJ2K](https://user-images.githubusercontent.com/25085973/98021706-40a3ad80-1dca-11eb-8ecf-d1f3b658c8d9.jpg)

**Comment by joseph619** [comment]
This already exists. Long press a manga in Library, click on Delete, uncheck 'Manga from Library' then click on 'Downloaded only'.

**Comment by jadoff630** [comment]
That is strange. When I click on delete after long-pressing in library it doesn't have that option. I am on the latest version of SY too... 

![image](https://user-images.githubusercontent.com/25085973/98042202-d2221800-1de8-11eb-8197-2dbd5a1ca5e9.png)

**Comment by joseph619** [comment]
Update your app to Preview build

https://github.com/jobobby04/TachiyomiSYPreview/releases

Close this ticket after you update

**Comment by jadoff630** [comment]
Thanks!
