### ISSUE TITLE
[Feature Request] Full Backup add source thing

### ISSUE THREAD

**Issue by Riztard** [jobobby04/TachiyomiSY#156]
## Why/User Benefit/User Problem
for people who use many ext/source dont need to be in pain again to choose what to enable or disable 
![image](https://user-images.githubusercontent.com/16263232/98445263-54903c00-2149-11eb-9f15-ac81dc087693.png)

## What/Requirements
include source categories, enabled/disabled source, ext setting too if possible

**Comment by joseph619** [comment]
Could probably mention it here instead of new ticket, it also requested saving read history of non library manga

https://github.com/jobobby04/TachiyomiSY/issues/76

**Comment by joseph619** [comment]
@jobobby04 Since multi source extensions no longer exist, this can be closed
