### ISSUE TITLE
[Bug] Some sources not updating and have to do individually

### ISSUE THREAD

**Issue by vipzzx** [jobobby04/TachiyomiSY#158]
## Device information
* Tachiyomi version: r305 (67aafab46)
* Android version: 10
* Device: Note 9

## Steps to reproduce
1. Group by source.
2. Update source individually. In this case MyReadingManga and NHentai are not showing.

### Expected behavior
Should update and show on notification bar.

### Actual behavior
"Updating category" will pop up on the bottom of the screen but it will not show on the notification bar. 

I don't think it is being checked.

## Other details

[Screen_Recording_20201108-175511_TachiyomiSY.zip](https://github.com/jobobby04/TachiyomiSY/files/5507320/Screen_Recording_20201108-175511_TachiyomiSY.zip)

**Comment by jobobby04** [comment]
NHentai doesn't update galleries, so SY has the updater skipping them

**Comment by vipzzx** [comment]
> NHentai doesn't update galleries, so SY has the updater skipping them, idk about MyReadingManga

Ok thanks. I didnt know that about NHentai.

**Comment by joseph619** [comment]
MyRradingManga extension is half broken, I'm pretty sure this is an extension issue. Try it on Stable and report back.

**Comment by vipzzx** [comment]
So stable doesn't group by source. But I have tested on J2K which I can group by source and it does update and show on the notification bar.

**Comment by joseph619** [comment]
Does it work on SY of you don't use group by source?

**Comment by vipzzx** [comment]
Is does work when it is not grouped by source

**Comment by yooman1213** [comment]
I got the same issue with tsumino source not updating
Must update individually 

Does tsumino problem the same with Nhentai?

**Comment by jobobby04** [comment]
I believe that Tsumino is also on the exclude from update check list, like NHentai. But it seems it's possible for the extension to do chapters unlike NHentai, I will remove it from the exclude list. It was there because the integrated version in TachiEH didnt do chapters.

**Comment by joseph619** [comment]
Does this issue still exist Vipzzx?

**Comment by vipzzx** [comment]
It is still happening on SY. 
I do not think it is a source issue because I tested it in J2K which allows grouping by source and it does work there.

**Comment by jobobby04** [comment]
Got around to looking at this, was a relatively easy fix. Next build will have the fix

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/18a119e9cfd4cd20cff8bc2576dbb769cd2f1882
