### ISSUE TITLE
[Bug] Panels not scaling properly

### ISSUE THREAD

**Issue by Myraddin** [jobobby04/TachiyomiSY#162]
This doesn't happen with all manga's (using this as a blanket term for all the graphic novel's in my library), however with a decent majority of them the panels don't always scale or line up properly. I am up to date with everything and I have the scaling setting as smart fit, however I have tried every setting and nothing fixes or changes anything. Picture is attached to show the issue that is occuring.

I can provide additional pictures if needed.
---

## Device information
* Tachiyomi version: Stable 1.3.1
* Android version: 9
* Device: Samsung Galaxy S8

## Steps to reproduce
1. Open up a manga,
2. Scroll through and see if the panels are lined up or scaled properly.

### Expected behavior
Panels should be lined up and scaled properly

### Actual behavior
Panels are not always scaled or lined up properly.

## Other details
![Screenshot_20201105-215350_TachiyomiSY](https://user-images.githubusercontent.com/74342188/98901206-5e83a900-2481-11eb-9474-f57dceb60e1e.jpg)

**Comment by joseph619** [comment]
Disable **crop border** for Webtoon in More > Settings > Reader
