### ISSUE TITLE
[Feature Request] Add delete all downloaded chapters option in multi-select

### ISSUE THREAD

**Issue by vongdong** [jobobby04/TachiyomiSY#163]
It would be great to have this option in the multiple select bar. Beats going into individual titles to delete them.

**Comment by joseph619** [comment]
This already exists. Long press a manga in Library, click on Delete, uncheck 'Manga from Library' then click on 'Downloaded only'.

Update app to latest Preview build

**Comment by vongdong** [comment]
Oh, my bad. Didn't realise it was an option in delete.
