### ISSUE TITLE
Flashing names

### ISSUE THREAD

**Issue by Ramzh** [jobobby04/TachiyomiSY#165]
Device information

    Tachiyomi version: 1.3.1
    Android version: 10
    Device: OnePlus 7 Pro - 12GB

Steps to reproduce

    Group by Source

Expected behavior

No flashing group names
Actual behavior

Flashing names. The group names move quickly left and right to then reposition to the centre
Other details

https://streamable.com/1ewbhr

The issue seems to be not visible when recording via recorder app

**Comment by joseph619** [comment]
Does this still happen on 1.4.1?

**Comment by Ramzh** [comment]
> 
> 
> Does this still happen on 1.4.1?

Nope working fine!
