### ISSUE TITLE
[Feature Request] Show and hide scanlators for MangaDex like Neko

### ISSUE THREAD

**Issue by JasperNg** [jobobby04/TachiyomiSY#167]
## Why/User Benefit/User Problem
(explain why this feature should be added)
Going into webview to block scanlators is clunky on mobile

## What/Requirements
(explain how this feature would behave)
Go into the filter menu and check the boxes of preferred scanlators
Please port the feature from Neko

**Comment by jobobby04** [comment]
This is in the preview build
