### ISSUE TITLE
[Bug] Can't search source screen

### ISSUE THREAD

**Issue by JasperNg** [jobobby04/TachiyomiSY#168]
## Device information
* Tachiyomi version: 1.3.1
* Android version: 10
* Device: Essential PH-1

## Steps to reproduce
1. First step - Turn on Replace latest button in browse settings
2. Second step - Go into Manganelo and you should see browse bar and latest bar
3. Third step - search for random manga
There should be no effect whatsoever

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

## Other details
Additional details and attachments.

**Comment by jobobby04** [comment]
This is fixed in the preview builds
