### ISSUE TITLE
[Feature Request] <Discharge system similar to TachiyomiJ2K>

### ISSUE THREAD

**Issue by KasukeLp23** [jobobby04/TachiyomiSY#170]
## Why/User Benefit
It would be good to have this feature in the application, since the user can download the chapters to choose and it is done more quickly

## What/Requirements
A download button on the right side of each chapter, which when pressed begins to download automatically

Thanks

**Comment by joseph619** [comment]
This is already planned for main Tachiyomi app, Sy will get it when main app Preview gets it

**Comment by KasukeLp23** [comment]
Ok, thank you very much, and excellent
