### ISSUE TITLE
[Feature Request] Option to change colors of theme

### ISSUE THREAD

**Issue by crusaside** [jobobby04/TachiyomiSY#171]
## Device information
* Tachiyomi version: preview r309
* Android version: 10, realme UI 1.0
* Device: realme 3 Pro

## Steps to reproduce
1. First step Go to General tab in settings.
2. Second step In the theme section adjust a 2d slider or tap on colors to make the theme different, suited to the user's liking

## Issue/Request
Have the ability to change the theme to any color we want, or atleast have 'some' no. of color palettes to choose from.

## Other details

like this calculator menu right here, screenshot taken from its google play page
![Screenshot_2020-11-29-10-55-49-72](https://user-images.githubusercontent.com/67280365/100534081-6ab58780-3231-11eb-840d-3b37a2088ed6.jpg)

**Comment by joseph619** [comment]
This will be available in 1.x, wait for that.

**Comment by crusaside** [comment]
cool. hyped up

**Comment by crusaside** [comment]
> This will be available in 1.x, wait for that.

cool. all hyped up now.
