### ISSUE TITLE
[Feature Request] Recognize 509.gif on ExHentai as a error

### ISSUE THREAD

**Issue by uap4** [jobobby04/TachiyomiSY#173]
## Why/User Benefit/User Problem
Exh/Eh serves a gif acting like a normal chapter page, this should be considered a error as its not a real chapter

## What/Requirements
Each download from ExHentai should stop with an error.

## Other details
Debug log:
```
<img id="img" src="https://exhentai.org/img/509.gif"
```
and
```
1606040157153|D|||EH-NETWORK|<-- 200 OK https://exhentai.org/img/509.gif (555ms)
```
```
1606040157156|D|||EH-NETWORK|Content-Type: image/gif
1606040157157|D|||EH-NETWORK|Content-Length: 28658
1606040157158|D|||EH-NETWORK|Last-Modified: Sun, 19 Oct 2008 20:16:57 GMT
```

**Comment by jobobby04** [comment]
Added in https://github.com/jobobby04/TachiyomiSY/commit/f1a6218a4b21d02114177b664abe052525236124
