### ISSUE TITLE
[Bug] Mangadex strange autofill

### ISSUE THREAD

**Issue by scb261** [jobobby04/TachiyomiSY#174]
## Device information
* Tachiyomi version: TachiyomySY r313
* Android version: 5.1
* Device: Huawei TIT-U02

## Steps to reproduce
1. Go to MangaDex settings
1. Login using *MangaDex Login* option
1. Go to *Advanced* settings
1. Clear cookies
1. Go to MangaDex settings
1. Tap *MangaDex Login* option

### Expected behavior
Usual dialog for login

### Actual behavior
Login and password fields are autofilled with something like
`com.google.android.material.textfield.TextInputEditText{... app:id/password}`
(I replaced a part with `...` in case there is authentication token or something)

**Comment by curche** [comment]
most recent screenshot showing the issue
https://media.discordapp.net/attachments/566585518171881493/783461759125159996/Screenshot_20201201-223642.jpg?width=213&height=462

**Comment by jobobby04** [comment]
Fixed with https://github.com/jobobby04/TachiyomiSY/commit/bbc70801dba0564791bfed0bef3aa5c2f0ea4692

**Comment by scb261** [comment]
r326 still happening

**Comment by jobobby04** [comment]
It will happen until the stored username/password get overwritten with a new one, so just login again and when you logout it will use the right autofill
