### ISSUE TITLE
[Feature Request] A chapter date format from J2K

### ISSUE THREAD

**Issue by Xeiniac** [jobobby04/TachiyomiSY#175]
## Why/User Benefit/User Problem
Well, It's more or a QOL feature, isn't really needed but makes it look better Imo and it's easier to tell when a chapter came out rather than having to look at the full date.

## What/Requirements
When a chapter comes out, instead of the date it'll show how long ago it came out eg: 10 minutes ago, 5 hours ago etc
(Images from J2K)

![IMG_20201211_090103](https://user-images.githubusercontent.com/25398298/101859947-adad1e80-3b92-11eb-8524-3b800bebb81c.jpg)

![IMG_20201211_085610 (1)](https://user-images.githubusercontent.com/25398298/101859603-0b8d3680-3b92-11eb-851d-4c86f0c4e2c8.jpg)

After 24 hours, it'll show x days ago and after 7 days It'll show the date like Dec 11, 2020 etc

## How it currently shows in SY:
![IMG_20201211_085028](https://user-images.githubusercontent.com/25398298/101859696-3b3c3e80-3b92-11eb-839a-67a3a5ab1840.jpg)

## How it'll look after (img from J2K):
![IMG_20201211_084953](https://user-images.githubusercontent.com/25398298/101859706-3f685c00-3b92-11eb-800a-7a069a970078.jpg)

**Comment by as280093** [comment]
Much needed as it gives a memory click that the chapter is new and doesn't makes us focus on to see what date it is today.

**Comment by Sad-Jamie** [comment]
Ageee

**Comment by CaptainHalflife** [comment]
Yeah i just migrate to SY from J2K and i miss this feature

**Comment by jobobby04** [comment]
This was added in main Tachi so SY got it
