### ISSUE TITLE
[Bug] Animated Gif Lag

### ISSUE THREAD

**Issue by Xeiniac** [jobobby04/TachiyomiSY#176]
## Device information
* Tachiyomi version: Tachiyomi SY Preview r131 (f1a6218a4)
* Android version: 8.1
* Device: Mi Pad

## Steps to reproduce
1. Open Series 
2. Open chapter with gif

### Expected behavior
Gif loads then plays smoothly

### Actual behavior
Gif loads and plays around 1 frame per second

## Other details
I have the same issue on Tachiyomi AZ.
It works perfectly without any lag on J2K.
Haven't tried the normal version or neko so can't say anything about those.
Maybe you can check what he does to fix it and port it over 👀

**Comment by jobobby04** [comment]
This is a Tachi stable issue, I probably wont fix this myself, if a fix is added to Tachi stable, I will pull it
