### ISSUE TITLE
[Bug] MAL login shows error

### ISSUE THREAD

**Issue by crusaside** [jobobby04/TachiyomiSY#177]
## Device information
* Tachiyomi version: preview r313
* Android version: 10, realme UI 1.0
* Device: realme 3 Pro

## Steps to reproduce
1. Go to tracking menu and select MyAnimeList.
2. Try to log in. Despite correct credentials, some error prevents you from logging in.

### Expected behavior
Should log in like normal so that chapters could be tracked.

### Actual behavior
Despite correct credentials, some error prevents you from logging in.

**Comment by jobobby04** [comment]
Fixed in the latest release
