### ISSUE TITLE
[Bug] Mangadex deeplink

### ISSUE THREAD

**Issue by curche** [jobobby04/TachiyomiSY#178]
## Device information
* Tachiyomi Sy version: Preview build 314
* Android version: 10 (lineage os custom ROM)
* Device: Xiaomi Redmi 7

## Steps to reproduce
1. Open any mangadex link in a browser (refer Other details section below)
2. Since Sy has mangadex deeplink, try to open above links using the app

## Expected behavior
App should open manga titles and also chapter links in reader. Other links shouldnt work

## Actual behavior
A mix of stuff seem to happen

## Other details
- [x] Main page - https://mangadex.org/ - works as intended (link doesn't open in app)
- [x] Search page - https://mangadex.org/search?title=Evans - works as intended (link doesn't open in app)
- [x] Manga title page - https://mangadex.org/title/21685/lies-of-the-sheriff-evans-dead-or-love - works as intended (link can be opened in app)
- [ ] Manga title comments page - https://mangadex.org/title/21685/lies-of-the-sheriff-evans-dead-or-love/comments/ 
        works as intended? - tries to open in app and instead of comments opens the title page (similar to the previous one)

- [x] Manga Chapter page - https://mangadex.org/chapter/214338/1
        doesn't work
        tries to open but gives Error - `Could not open manga: Unknown manga type for manga: https://mangadex.org/chapter/214338/1)`
- [ ] Manga Chapter comments page - https://mangadex.org/chapter/214338/comments
        tries to open and fails with Error - `Could not open manga: Unknown manga type for manga: https://mangadex.org/chapter/214338/comments)`

- [x] Group profile page - https://mangadex.org/group/35/cyan-steam 
        tries to open in app and fails with Error - `Could not open manga: Unknown manga type for manga: https://mangadex.org/chapter/214338/comments)`
        
- [x] User profile page - https://mangadex.org/user/4969/wabewalker
        tries to open in app and fails with Error - `Could not open manga: Unknown manga type for manga: https://mangadex.org/chapter/214338/comments)`

**Comment by jobobby04** [comment]
Fixed with https://github.com/jobobby04/TachiyomiSY/commit/1dcf161131e3a54720132a06967a365b4439934e
