### ISSUE TITLE
[Feature Request] Backup all manga in reading history (including manga not in library)

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#179]
Requesting to make backup of entire reading history (including manga not in library).

Some relevant comments that may help (taken from az4521 on Discord):

> SELECT * FROM mangas WHERE id IN(select UNIQUE (manga_id) FROM chapters WHERE read=1)

> All just add a where favorited=0 so that it doesnt conflict with the library manga query

**Comment by joseph619** [comment]
This has been added, should be marked complete for next release

**Comment by jobobby04** [comment]
Added in https://github.com/jobobby04/TachiyomiSY/commit/e633da5567e6cc33beff1757d50c55b7e729a644
