### ISSUE TITLE
[Bug] hentai.cafe open URL not working

### ISSUE THREAD

**Issue by Ramzh** [jobobby04/TachiyomiSY#180]
## Device information
* Tachiyomi version: 1.4..0
* Android version: 10
* Device: OnePlus 7 Pro

## Steps to reproduce
1. Get a hentai.cafe link via browser 
2. "Open in App"

### Expected behavior
Open the respective page in app

### Actual behavior
Error 404 issue

## Other details
Using "Read Online":
`https://hentai.cafe/manga/read/piyopiyo-tachibana-san-is-so-kind/en/0/1/page/1`
![image](https://user-images.githubusercontent.com/20802073/102200856-45757a00-3ebd-11eb-8015-dbb743ee0082.png)

Using entry page: 
`https://hentai.cafe/hc.fyi/7160`
![image](https://user-images.githubusercontent.com/20802073/102200868-49090100-3ebd-11eb-8bce-d94dca766835.png)

Potential fix?:
- Read Online: regex the manga title in the URL and search it in hentai.cafe like Hentai2Read
- Entry: regex the ID and search it using hentai.cafe

**Comment by jobobby04** [comment]
Fixed with https://github.com/jobobby04/TachiyomiSY/commit/1dcf161131e3a54720132a06967a365b4439934e
