### ISSUE TITLE
[Feature Request] Ignore articles (a, an, the) when sorting (from J2K)

### ISSUE THREAD

**Issue by jadoff630** [jobobby04/TachiyomiSY#184]
## Why/User Benefit/User Problem
J2k has an ability to skip a, an, the when using alpha-order (that way all the titles with "the" (and there are A LOT of them).

## What/Requirements
In library settings, J2K has a toggle switch to ignore these articles. It then ignores the first word of titles if they start with an article.

**Comment by dephunk** [comment]
+1 updoot

**Comment by jobobby04** [comment]
See https://github.com/tachiyomiorg/tachiyomi/issues/6032 for the reason I am closing this, I agree with main Tachi in regards to this.
