### ISSUE TITLE
[Feature Request] Add Scroll Up/ Down to S Pen Air Gestures as Next/ Previous Page does not work in Landscape

### ISSUE THREAD

**Issue by kalinskym** [jobobby04/TachiyomiSY#187]
This is a feature request to add "Scroll Up/ Down" to S Pen Air Gestures. I've seen you have "Next Page" and "Previous Page" which while it's great to have when in portrait orientation.  

It does not work correctly in landscape orientation. As when you use "Next Page" or "Previous Page", it goes to beginning of the page. However, as a normal scroll does on landscape when whole page is unable to fit. It cuts off the bottom section of the page, when it moves to the next page. As it does not realise the page is cut off due to not fitting on the screen. Only fix is scrolling up manually which defeats the purpose of using the function on S Pen. 

An easy solution seems to be adding a Scroll function to S Pen Air Gestures.

I hope you do consider this. The same function occurs when you use volume keys as well, if you need to test this out. It moves to next page however does not scroll so it misses out the bottom page of previous page which could not fit on the screen

This be a large help to those who want to not touch their devices. Thank you for reading this.

**Comment by jobobby04** [comment]
I probably wont work on this, so ill close this, but your welcome to open a issue in the Tachiyomi repo and SY will get it if its implemented there
https://github.com/tachiyomiorg/tachiyomi

**Comment by kalinskym** [comment]
SY or normal app does not have Air Gestures function. Only yours does.

**Comment by jobobby04** [comment]
?? this is SY

**Comment by jobobby04** [comment]
Also I dont implement anything for S Pen thats exclusive to SY, everything thats S Pen is from the main Tachiyomi

**Comment by kalinskym** [comment]
![Uploading Screenshot_20210103-002802_Air command.jpg…]()

**Comment by kalinskym** [comment]
![Uploading Screenshot_20210103-002758_Air command.jpg…]()

**Comment by kalinskym** [comment]
Had J2K installed. Which does not have it.  Normal Tachiyoma does.  Thanks for messaging.  Added to tachiyoma feature thread

**Comment by jobobby04** [comment]
Np
