### ISSUE TITLE
[Feature Request] Show snackbar in reader to indicate switch to Webtoon mode

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#19]
### Why/User Benefit/User Problem
It would let the users know that the Auto switch to Webtoon mode has been made, or that the feature is functional.

### What/Requirements
Add a snackbar to let users know about the switch.

![screenshot_20200520-035235_tac](https://user-images.githubusercontent.com/34897862/82420579-e72f0880-9a4d-11ea-8a73-0ba3653a48a8.jpg)

**Comment by jobobby04** [comment]
Added in https://github.com/jobobby04/TachiyomiSY/commit/290e912cf06932b1fab31f4f9157e992fe7c622a
