### ISSUE TITLE
[Bug] <In nhentai eng sort by recent features not working it's only shows same sort by all time popular>

### ISSUE THREAD

**Issue by Hybridcre** [jobobby04/TachiyomiSY#190]
---

## Device information
App version: 1.4.1 (standard, 7b4311c7d, 12)
Preview build: 325
Android version: 10 (SDK 29) 
Android build ID: RMX1851_11_C.10
Device brand: Realme

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
It should be showing recent magazines instead it is showing top popular magazines

### Actual behavior
This happened instead.

## Other details
Its only happen in sy not in orginal version.
So i think this is sy problem not an extension problem
And also its happening with nhentai all extension is not working its show open in webview

**Comment by jobobby04** [comment]
This is a extension issue, if you open NHentai from the Other language in other Tachiyomis, you will see the same behavior

**Comment by jobobby04** [comment]
And it's not really a extension issue either. It's how the site is formatted
