### ISSUE TITLE
[Bug] App Crashes while tracking latest Chapter on both MAL And Anilist

### ISSUE THREAD

**Issue by rickninja765** [jobobby04/TachiyomiSY#191]
Device information
* Tachiyomi version: 1.4.1(r325)
* Android version: 10
* Device: RMX1851

## Steps to reproduce
1. Open tracking Function
2. Refresh the tracking page

### Expected behavior
It supposed to do tracking with latest chapter that we read.

### Actual behavior
But while doing tracking the app eventually crashed.

## Other details
Error Name : Cancelled due to java.lang.NullPointerException

**Comment by Smithienious** [comment]
Try relogin MAL

**Comment by jobobby04** [comment]
Sounds like the Mal issue, you just need to relog
