### ISSUE TITLE
[Feature Request] <Remove Tracking when Manga's are  unfollowed>

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#192]
## Why/User Benefit/User Problem
(If we are to unfollow any manga, we are needed remove tracker and manual step are fine. But if we are to do bulk unfollow manga from library then it take more time than just unfollowing.)

It doesn't matter if tracker isn't removed but also why have it if manga isn't followed.

## What/Requirements
(A toggle button/same as` Clean up downloaded chapters/Refresh tracking` )

It would be time efficient though it wouldn't be used oftentimes.

**Comment by scb261** [comment]
More > Settings > Advanced > Clear database
This will remove data about all manga that aren't in your library, including tracking

**Comment by Mano5JP** [comment]
Didn't knew lmao.... 

thx
