### ISSUE TITLE
[Bug] Logging out of MangaDex crashes app when not connected to WiFi/Data

### ISSUE THREAD

**Issue by curche** [jobobby04/TachiyomiSY#196]
## Device information
* Tachiyomi version: Preview r326
* Android version: android 10 (lineage os)
* Device: onclite (Redmi 5)

## Steps to reproduce
1. Switch off WiFi/Data 
2. Open Sy, More.>Settings>Mangadex
3. Log Out of mangadex

## Issue
App crashes instead of logging out of mangadex

## Other details
Logcat attached

[logcat_01-21-2021_21-22-20.txt](https://github.com/jobobby04/TachiyomiSY/files/5850692/logcat_01-21-2021_21-22-20.txt)

**Comment by jobobby04** [comment]
Addressed in https://github.com/jobobby04/TachiyomiSY/commit/003e916ab026d7aaf8e672f4c3dc5d7a294e543e
