### ISSUE TITLE
[Bug] Download Status ckeck mark displaying wrong

### ISSUE THREAD

**Issue by jopejoe1** [jobobby04/TachiyomiSY#197]
## Device information
App version: 1.4.1 (standard, 9ec67db8c, 12)
Preview build: 329
Android version: 10 (SDK 29) 
Android build ID: QP1A.190711.020.G975FXXS9DTI8
Device brand: samsung
Device manufacturer: samsung
Device name: beyond2
Device model: SM-G975F
Device product name: beyond2ltexx

## Steps to reproduce
1. Open manga that is downloaded 
2. See the downloaded status check mark next to chapter

### Expected behavior
When the chapter is downloaded it should show that it is downloaded

### Actual behavior
It shows as if it is not downloaded

## Other details
Opening the chapter works fine
Trying to downloaded the chapter again changes nothing
Only happens to a minority of manga

**Comment by jobobby04** [comment]
This is probably not a SY specific bug, as the download checkmarks are 100% preview's.
