### ISSUE TITLE
[Feature Request] E-Hentai add missing filter options from extension

### ISSUE THREAD

**Issue by jopejoe1** [jobobby04/TachiyomiSY#198]
## Why/User Benefit/User Problem
This are feuters that are in the normal e-hentai extension

## What/Requirements

- [ ] Misc Tags
- [ ] Female Tags
- [ ] Male Tags
- [ ] Enforce language
- [ ] Different sub extensions for each language (like in normal extension or mangadex)

## Other
Not sure if this can also be applied for ExHentai

**Comment by jobobby04** [comment]
This is all handled by the autocomplete filter, which is arguably more powerful

**Comment by jobobby04** [comment]
Also Sub extensions for languages are not planned, the single all language works perfectly

**Comment by jopejoe1** [comment]
Didn't realize that was an autocomplete filter, though that was just a warning message.
