### ISSUE TITLE
[Feature Request] Multi thread different sources during Library update (from J2K)

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#199]
## Why/User Benefit/User Problem
Would make Library update much faster if user have several sources 

## What/Requirements
Yoink the feature from J2K

**Comment by Nexr0n** [comment]
Not a contributer but looking at the code that could cause some issues even if those issues are worked out it could affect compatibility with future tachiyomi main updates.

**Comment by jobobby04** [comment]
Ya the J2k code is unusable for this, I was able to make my own version today, which will work with minor changes for future Tachiyomi main updates, it might go into the next build

**Comment by joseph619** [comment]
This has been added, should marked complete for next release

**Comment by jobobby04** [comment]
Added in https://github.com/jobobby04/TachiyomiSY/commit/e26ab22e41d6a99973a8b7ca2608223bfee03819
