### ISSUE TITLE
[Bug] Library selection, bottom bar doesn't go away.

### ISSUE THREAD

**Issue by ric0369** [jobobby04/TachiyomiSY#200]
## Device information
* Tachiyomi version:  SY preview r329
* Android version: 10
* Device: s9

## Steps to reproduce
1. In the library, select a manga.
2. With the manga selected click on the start reading button on the cover.

also
1. In the library, select a manga.
2. Using the 3 dot menu on the library bar, click migrate.
3. Exit out of the Migration screen.

### Expected behavior
The bar should go away.

### Actual behavior
The bar doesn't go away

## Other details
Video:
https://cdn.discordapp.com/attachments/729509785887703080/803412341336440842/Screen_Recording_20210125-185051_TachiyomiSY.mp4

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/96a932264b53cfd6c60d20845d956ce145d81370
