### ISSUE TITLE
[Feature Request] Browse Source List Compact

### ISSUE THREAD

**Issue by thu2468** [jobobby04/TachiyomiSY#202]
## Why/User Benefit/User Problem
So that source are not spaced out as much

## What/Requirements
So you can maybe make it so that Description for the source language on the right side of the source name instead of the bottom. or option to remove the language description

**Comment by jobobby04** [comment]
I probably wont do this, if it gets into https://github.com/tachiyomiorg/tachiyomi I will pull the change, but I wont do it for SY
