### ISSUE TITLE
[Feature Request] Allow users to search which manga/manhwa they want to merge

### ISSUE THREAD

**Issue by juleast** [jobobby04/TachiyomiSY#207]
## Why/User Benefit/User Problem
When I try to merge manhwas from another source, it gives me the wrong results so I cannot merge them. 

## What/Requirements
When user taps merge, give them an option to manually search for the desired title if given the wrong results.

**Comment by jobobby04** [comment]
Closing in favour of https://github.com/jobobby04/TachiyomiSY/issues/204
