### ISSUE TITLE
[Bug] Webnovel.com manga not showing in TachiyomiSY works fine in Tachiyomi

### ISSUE THREAD

**Issue by jopejoe1** [jobobby04/TachiyomiSY#208]
## Device information
* Tachiyomi version: r337
* Android version: 10
* Device: Galaxy s10

## Steps to reproduce
1. Open webnovel.com extension 

### Expected behavior
Manga should appear 

### Actual behavior
No manga appear 

## Other details
Works fine in normal Tachiyomi
Webview uses mobile website in TachiyomiSY and desktop version in Tachiyomi
Reported before to tachiyomi-extensions tachiyomiorg/tachiyomi-extensions#5768

**Comment by jobobby04** [comment]
Force close SY and reopen, it was a issue with the extension repo
