### ISSUE TITLE
[Feature Request] Smart background for reader

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#21]
### Why/User Benefit/User Problem
For LTR/RTL viewer, the background will change depending on the page content or system theme. Basically same as it's on J2K.

### What/Requirements
Yoink the feature from J2k, obviously.

**Comment by jobobby04** [comment]
Added with https://github.com/jobobby04/TachiyomiSY/commit/2f98dd2046bf7788e972a59f8db965211c2984fc
