### ISSUE TITLE
[Bug] App crashes when reading Manga only on Tachiyomi

### ISSUE THREAD

**Issue by Beylers** [jobobby04/TachiyomiSY#212]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v1.5.0)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

## Device information
* Tachiyomi version: 1.5.0 and 
* Android version:11
* Device: Samsung S10 Plus

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

## Other details
Additional details and attachments.

**Comment by Beylers** [comment]
changed the description

**Comment by jobobby04** [comment]
Relog into your trackers

**Comment by Beylers** [comment]
Thanks that worked
