### ISSUE TITLE
[Bug] <MDex tracker for non mangadex>

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#213]
## Device information
* Tachiyomi version: r339
* Android version: A11
* Device: Note 10 + 

## Steps to reproduce
1. open non-mangadex manga
2. add tracker

### Expected behavior
when you read the chapter its should update on the tracker.

### Actual behavior
it does not update as it is tracked as unfollow by default.
    1. when you set the tracker to reading, it updates as expected but,
       1.1. it immediately reverts back to unfollow with 0/

## Other details

Additional details and attachments.

https://imgur.com/a/8B94bXq

MDex is temporarily working and so, tried this new feature, hoping it's just to be a cache issue and nothing else.

cheers

**Comment by jobobby04** [comment]
This is because of the cache issue mangadex is having, SY cant do anything about it

**Comment by Mano5JP** [comment]
Yeah that's what i had thought too,

Cheers
