### ISSUE TITLE
[Bug] <Visual MDex tracker for mangadex>

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#214]
## Device information
* Tachiyomi version: r399
* Android version: A11
* Device: Note 10+

## Steps to reproduce

These are for mangadex tracking only.

1. Open any Manga any source (not tracked)
    1.1 Click on Tracking 
2. Open any Manga from mangadex (not tracked)
    2.1 Click on Tracking

### Expected behavior
There should be no trackers (MangDex).

### Actual behavior
For any other sources, everything seems alright except for the mangadex source,
 Although manga's arent tracked (by users), the tracker is set to as unfollowed, literally all manga on mangadex sources, this is even after troubleshooting steps from the app and phone settings

## Other details
Additional details and attachments.

https://imgur.com/a/dT2vW1K

these manga's aren't added to the library or followed/unfollowed on mangadex.

![Screenshot_20210215-133418_TachiyomiSY.jpg](https://user-images.githubusercontent.com/64928088/107935580-9fb0bb00-6f92-11eb-9c0c-f95ec1e635a9.jpg)

![Screenshot_20210215-133436_TachiyomiSY.jpg](https://user-images.githubusercontent.com/64928088/107935591-a3dcd880-6f92-11eb-982a-8bf7b99eb4f3.jpg)

**Comment by jobobby04** [comment]
This is intentional, it allows for easy tracking of mangadex manga

**Comment by Mano5JP** [comment]
Alright, gonna get used to it coz its a easy access kaboom....

Thanks
