### ISSUE TITLE
[Bug] Pages stop loading when chapter cache reaches ~78.51 MB

### ISSUE THREAD

**Issue by Hunter-The-Furry** [jobobby04/TachiyomiSY#217]
## Device information
* Tachiyomi version: 1.5.0
* Android version: 10
* Device: Moto g7 play

## Steps to reproduce
1. Read from any sources until chapter cache reaches ~78.51 MB
2. Try to load a new page

### Expected behavior
Page loads

### Actual behavior
Page doesn't load and asks to "Retry" infinitely

## Other details
It always happens at exactly (or at least seems to always happen at exactly) 78.51 MB. Happens on all sources. Immediately is fixed when I go to advanced settings and clear the chapter cache. Not exactly app breaking but still an inconvenience when I have to exit out of what I'm reading and then go to the settings to clear the cache.

**Comment by jobobby04** [comment]
Is your drive low on space? I cant see this happening normally

**Comment by Hunter-The-Furry** [comment]
I still have 9.2 GB of free space on my device

**Comment by sukhijapiyush** [comment]
It is present in me as well for me as well as this place I still have around 100 GB of free space.

**Comment by Hunter-The-Furry** [comment]
Still having this issue on a whole new device and app version:

App version: 1.7.0 (standard, 7e3e21f1a, 22, 2021-11-14T23:52Z)
Preview build: 414
Android version: 11 (SDK 30)
Android build ID: RRT31.Q1-84-24-2
Device brand: motorola
Device manufacturer: motorola
Device name: nio
Device model: moto g(100)
Device product name: nio_retail

I have almost 50gb of free space on my device so I know that's still not the problem. My device is rooted, giving me the ability to see the cached files. The cache folder "chapter_disk_cache" seems to always sit around 75mb in size, overwriting older cached files to create new ones. I'm beginning to believe that the app won't rewrite over files if they're for the currently being read chapter, this would also mean that the problem would only occur on long chapters with many pages that fill the cache. I'll have to further test this idea but it seems that this might be the issue. I'll also see if I can recreate this on the original tachiyomi app or not.
