### ISSUE TITLE
[Feature Request] Collapse Button for Chapters

### ISSUE THREAD

**Issue by shashank-p** [jobobby04/TachiyomiSY#22]
Something similar to Show/Hide Manga Info button for all chapters list for newer UI you can display 5 chapters when clicked display all chapters

**Comment by joseph619** [comment]
Is collapsing really necessary? What would be the benefit to hide the chapters? There's still a toggle to enable the old tabs UI.

**Comment by jobobby04** [comment]
Maybe it can be a chapter filter, I dont think implementing a seperate button to expand it would work that well
