### ISSUE TITLE
[Feature Request] <download all from library>

### ISSUE THREAD

**Issue by nagaisa-zz** [jobobby04/TachiyomiSY#220]
---

## Why/User Benefit/User Problem
(some peple want to download all and not just unread with out haveing to go to each manga)

## What/Requirements
(adds an option wean selectiong muti manga from library to download all)

**Comment by joseph619** [comment]
This already exists. Ungroup categories in Library > Filter > Group, select all, then click download.

**Comment by jobobby04** [comment]
That will only download unread chapters
