### ISSUE TITLE
[Bug] MD List add status

### ISSUE THREAD

**Issue by Riztard** [jobobby04/TachiyomiSY#222]
## Device information
* Tachiyomi version: r339
* Android version: 10
* Device: redmi 8

## Steps to reproduce
1. open manga not from mangadex
2. add to dex tracker

### Expected behavior
tracker status as reading

### Actual behavior
tracker status as unfollowed

**Comment by jobobby04** [comment]
Addressed with https://github.com/jobobby04/TachiyomiSY/commit/5dace4fd7448da1d8e9c837ea4e8fc25278f8518
