### ISSUE TITLE
[Feature Request] Option to hide/hide the "Incognito mode" toast on top when in incognito mode

### ISSUE THREAD

**Issue by KraXen72** [jobobby04/TachiyomiSY#224]
## Why/User Benefit/User Problem
basically ruins incognito because it isn't incognito anymore. i get that history is paused that is cool and all but please hide / add option to hide the annoying incongito mode toast

**Comment by joseph619** [comment]
This is a terrible idea and the toast exists for a reason, no reason to add bloat by adding extra setting to remove it. Also you requested this on TF repo, so this is redundant.
