### ISSUE TITLE
[Bug] Cannot save cover when manga not in library

### ISSUE THREAD

**Issue by CaptainHalflife** [jobobby04/TachiyomiSY#229]
## Device information
* Tachiyomi version: r340
* Android version: 8.1.0
* Device: Samsung J7 Prime

## Steps to reproduce
1. Select a manga on mangadex or mangapark (i know for sure it don't work on these sources maybe there is more).
2. Save the cover.

### Expected behavior
The cover is saved and can be open.

### Actual behavior
The cover is not saved and an error is given
![Screenshot_20210226-065736_TachiyomiSY](https://user-images.githubusercontent.com/65003109/109305208-d5895580-7856-11eb-9917-2f873da2ee9d.jpg)

## Other details
It is not an extension bug as it work fine on J2K.
Not all sources are affected (i tested with mangahub, webtoon and mangasee)

**Comment by scb261** [comment]
Looks like it happens to manga that aren't in library or were just added to library. In the second case you can reopen source or open manga from library for it to work.

**Comment by CaptainHalflife** [comment]
Yeah seem so. Hope it fix soon thx

**Comment by jobobby04** [comment]
Save/Share actions are now handled by main Tachi, if this still happens its a main Tachi issue
