### ISSUE TITLE
[Bug] crash when opening chapter from manual search migration

### ISSUE THREAD

**Issue by INSANEMODE** [jobobby04/TachiyomiSY#236]
consistent crash.

- Migrate any manga

- Tap manual search

- Long press any manga

- Open a chapter

- Crash happens after a page loads.

App version: 1.5.0 (standard, f35abccfd, 13)
Preview build: 342
Android version: 9 (SDK 28) 
Android build ID: PKQ1.190414.001
Device brand: lge
Device manufacturer: LGE
Device name: joan
Device model: LG-US998
Device product name: joan_nao_us

### Expected behavior
Opened chapter should load and be readable without crashing.

### Actual behavior
As soon as a page loads, the app crashes to home screen.

## Other details

https://youtu.be/uAZF3Zj-mIc

[Log_2021-03-08_09-51-45.txt](https://github.com/jobobby04/TachiyomiSY/files/6102784/Log_2021-03-08_09-51-45.txt)

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/6102785/tachiyomi_crash_logs.txt)

**Comment by PLAYERUNKNOWNHatsune01** [comment]
I have this problem and it's so annoying! Every time I finished a chapter the app crashed! 

Version: 1.5.0 

I shouldn't update me app

**Comment by scb261** [comment]
@PLAYERUNKNOWNHatsune01 your issue is different, relogin to trackers

**Comment by jobobby04** [comment]
Addressed with https://github.com/jobobby04/TachiyomiSY/commit/7c4e89cbc5a6954847bc8cf4f4e8601bd3b912ff
