### ISSUE TITLE
[Ecchi filter] <can you add an option in settings to allow hiding ecchi manga>

### ISSUE THREAD

**Issue by dmswd** [jobobby04/TachiyomiSY#237]
## Why/User Benefit/User Problem
(explain why this feature should be added)
This is a feature for people who want to hide manga with ecchi tag
Notice adult tag doesn't work with them
## What/Requirements
(explain how this feature would behave)
Another filter to filter ecchi manga

**Comment by joseph619** [comment]
Just add adult tag to all your ecchi manga. If you feel the need to hide ecchi, enable biometric lock and secure screen so that other people can't see your library. No need to add more filter for this niche request.
