### ISSUE TITLE
[Bug] Login error in Mangadex settings but not in webview

### ISSUE THREAD

**Issue by Nick1296** [jobobby04/TachiyomiSY#242]
## Device information
* Tachiyomi version: 1.5.0 r344
* Android version: 11
* Device: OnePLus5T / dumpling

## Steps to reproduce
Login with 2FA to mangadex in settings -> MangaDex -> MangaDex login

### Expected behavior
Login should reported as ok and MD features should be enabled through the app (MDlist tracking etc)

### Actual behavior
I get an "Unknown Error", MD features are not enabled since the login is reported as failed, but I am logged in MangaDex webview.

## Other details
In the attached log I managed to capture an EOFException
[2021-03-18-release.log](https://github.com/jobobby04/TachiyomiSY/files/6163027/2021-03-18-release.log)

**Comment by krakerz** [comment]
i have this issue as well. (without 2FA tho)
