### ISSUE TITLE
[Feature Request] Move chapter list button to chapter name at top when it's disabled in bottom toolbar

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#244]
Similar to Manga Rock, move chapter list button to chapter name at top toolbar when it's disabled in bottom toolbar.
![Screenshot_20210318-164858_Manga Rock](https://user-images.githubusercontent.com/34897862/111696344-970a0980-880a-11eb-9f8b-809d5b4587e8.jpg)

This way it will still be accessible when disabled from toolbar

![PicsArt_03-30-07 47 36](https://user-images.githubusercontent.com/34897862/113070837-8013d180-9191-11eb-8d9a-4cd0224fe360.jpg)

**Comment by jobobby04** [comment]
@CrepeTF we have a job for you

**Comment by CrepeTF** [comment]
I see

**Comment by CrepeTF** [comment]
Sure why not

**Comment by joseph619** [comment]
Syer when you gonna yoink chapter comments for Dex from Neko?  :whip:

**Comment by CrepeTF** [comment]
Wait fuck shit, I just remembered that the chapter name and series title aren't like super separate in XML at least

**Comment by jobobby04** [comment]
🤷‍♂️

**Comment by CrepeTF** [comment]
Eh whatever

**Comment by joseph619** [comment]
Could maybe put the orientation lock button on top right corner of toolbar, like Manga Rock. 

Bookmark is already covered by chapter list

**Comment by joseph619** [comment]
The WebView button can now be moved to far left corner, as Custom filter have been moved inside reader settings sheet. So now main app buttons can now be accomodated. Thanks Arkon 😄

**Comment by CrepeTF** [comment]
OwO

**Comment by CrepeTF** [comment]
Also ainz join SY Comics discord when?

**Comment by joseph619** [comment]
As soon as I return to Discord 😁

**Comment by joseph619** [comment]
J2K already added the double page in reader, we need more space for the button :3

![Screenshot_20210330-162110](https://user-images.githubusercontent.com/34897862/113051544-146f3b80-9174-11eb-8e01-16ec53c09e78.jpg)


:whip:

**Comment by CrepeTF** [comment]
@joseph619 is that in the latest version?

**Comment by CrepeTF** [comment]
It isn't right

**Comment by joseph619** [comment]
I manually built in in Android Studio, it's already complete and fully functional. There isn't much time left bruh

https://github.com/Jays2Kings/tachiyomiJ2K/tree/doublePages

**Comment by CrepeTF** [comment]
Could you send a debug APK?

**Comment by CrepeTF** [comment]
I want to test it out too

**Comment by joseph619** [comment]
here https://drive.google.com/file/d/1Xy-94wQZQs8S2_hpKIiXm0cvIcEpnD2s/view?usp=sharing

**Comment by jobobby04** [comment]
👀

**Comment by joseph619** [comment]
> 👍

Bruh move the chapter list button asap to chapter name, we are running out of space for new buttons. hurry :whip:

**Comment by CrepeTF** [comment]
Mlao

**Comment by joseph619** [comment]
I guess the rotation button could be replaced with dual page one, was trying to accomodate as many buttons from upstream as possible

**Comment by joseph619** [comment]
> Wait can't we just remove the useless rotation button tho then

As Syer updated the preview build with the new crop border button, I updated the mockup above accordingly (Settings, double page, crop border and webview). No more **Rotation** and **Reading mode** for now

**Comment by CrepeTF** [comment]
Sounds good to me

**Comment by CrepeTF** [comment]
Good luck syer

**Comment by joseph619** [comment]
> Good luck syer

wdym good luck, you will do it :whiptf:

**Comment by jobobby04** [comment]
With the new reader button customization, we could make it so that when the chapter list button is disabled, its added to the top of the reader
