### ISSUE TITLE
[Feature Request] <a way to clear the chapters in the updates tab>

### ISSUE THREAD

**Issue by dmswd** [jobobby04/TachiyomiSY#245]
## Why/User Benefit/User Problem
(explain why this feature should be added)
After the latest update the tab takes about 2 minutes to fully load the chapters
So I was thinking that there could be a button or something to allow removing the whole entry and start it anew
## What/Requirements
(explain how this feature would behave)
Just a simple button in the updates tab or in advanced settings

**Comment by joseph619** [comment]
This has been declined numerous times before, should make the updates collapsible rather than clearing.

#81
