### ISSUE TITLE
[Bug] Configuration error for exhentai

### ISSUE THREAD

**Issue by mrskizzex** [jobobby04/TachiyomiSY#246]
## Device information
* Tachiyomi version: 1.5 stable
* Android version: 11
* Device: Samsung Galaxy S20+

## Steps to reproduce
1. Enable Exhentai
2. Login
3. Error

### Expected behavior
Proper exhentai functionality.

### Actual behavior
Error immediately after logging in and then when opening any doujin from Exhentai source it shows chapter and metadata but no pages can be loaded.

## Other details
![image](https://user-images.githubusercontent.com/11503128/111776075-df303700-88b1-11eb-8eb2-d6721303ce8b.png)
![Screenshot_20210319-125247_TachiyomiSY](https://user-images.githubusercontent.com/11503128/111776352-32a28500-88b2-11eb-97f3-44bddaeee8b2.jpg)

**Comment by mrskizzex** [comment]
Already tried cleaning cookies and cache, using different account.

**Comment by mrskizzex** [comment]
This fixed the issue, I won't close this issue in case you want to track it, otherwise feel free o close.
![image](https://user-images.githubusercontent.com/11503128/111781860-a34ca000-88b8-11eb-9324-6420e27471bb.png)

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/9a55b70d9180dd600e3f1107cf98743fdd5791d5
