### ISSUE TITLE
[Bug] Random crashing

### ISSUE THREAD

**Issue by Ahsan40** [jobobby04/TachiyomiSY#249]
## Device information
* Tachiyomi version: 1.5 (r347)
* Android version: 9
* Device: Redmi Note 5

## Steps to reproduce
1. Open Updates. Try to update the library
2. Now try to go to settings.

### Expected behavior
Should have open settings

### Actual behavior
App crashes

## Other details
Additional details and attachments.

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/6186570/tachiyomi_crash_logs.txt)

**Comment by jobobby04** [comment]
See https://twitter.com/tachiyomiorg/status/1374128475586621442?s=19

---

🚨 A possible fix has been found for users encountering #Tachiyomi, #TachiyomiJ2K, #TachiyomiSY, and other apps crashing.

Uninstall all Chrome or WebView updates in your device settings, alternatively uninstall and reinstall them.

Read more here: https://t.co/SONRqFRY9D
