### ISSUE TITLE
[Bug] downloaded manga/doujin from tsumino persist mark as not downloaded due to long name on the title

### ISSUE THREAD

**Issue by yooman1213** [jobobby04/TachiyomiSY#250]
---

## Device information
* Tachiyomi version: App version: 1.5.0 (standard, 3a148c73a, 13)
* Preview build: 347
* Android version: 9 (SDK 28) 
* Android build ID: PPR1.180610.011.G955USQS8DTJ3
* Device brand: samsung S8+
* Device manufacturer: samsung
* Device name: dream2qltesq
* Device model: SM-G955U
* Device product name: dream2qltesq

## Steps to reproduce
1. Download any manga with super long title (on other sources than NHentai)
2. Restart the app (swiping up from the task manager until the app re-searching any manga/doujhin on the library)
3. The expected downloaded manga missing its downloaded badge.
4. Thus making reading the said manga on offline is impossible

### Expected behavior
The badge not missing even after restarting the app
So the manga/doujin can still be read without connection

### Actual behavior
The download badge is missing after restarting the app, but the downloaded file exist in the correct directory, 

### Suggestions based on my point of view
From what i guess is due to long title name and cannot be cleaned like in the Nhentai source, but both name from app and the directory have so long name making the app inappropriate locating the downloaded file

Can "clean title" feature work with some or all sources? (But please makes tsumino a priority if can)

Can the "clean title" feature also work for both the title from the app and downloaded directory? So the folder name on that said directory would be also cleaned?

With all due respect can anyone help to fix it?

So sorry if any or anything that I've said before being offended or sounded rude and using poorly grammar.

Sincerely from user yooman1213

**Comment by jobobby04** [comment]
The only thing I can suggest is moving your download directory to a spot higher in the file system, like instead of longpath/downloads, toplevel/downloads. I cant really do anything else to help you
