### ISSUE TITLE
[Feature Request] Skip System webview to "Chrome Tabs"

### ISSUE THREAD

**Issue by iShyboy** [jobobby04/TachiyomiSY#251]
## Why/User Benefit/User Problem.

I think an option to skip the webview to the Chrome tab/Firefox tab directly will be helpful to save data and to low end devices.

After tapping webview button the site open in the webview (with ads and no logins/scripts) the we tap open in browser only then we tap Open in (Default Browser).

The first step takes much data and is the longest depending on your device and source. Sources with ads can lag your device while loading it in system webview before you can tap the "Open in Browser" that takes you to your browser of preference.
Opening a mangabat page in system webview takes 4 times longer than in Firefox Tabs. Depending on the ads that load in system webview.
## What/Requirements
Skip the first step and the slowest.

Loading directly the Chrome tab/Firefox tab where we can load with our browser cookies/add-ons/scripts.

Should have a toggle since I don't know if you could solve captcha/cloud flare issues by loading a Browsertab.

**Comment by jobobby04** [comment]
I probably wont add this myself, only if Main Tachi does, and I think this request has been denied before in the main Tachi repo
