### ISSUE TITLE
[Bug] Mass Migration stuck

### ISSUE THREAD

**Issue by Riztard** [jobobby04/TachiyomiSY#252]
## Device information
* Tachiyomi version: r347
* Android version: 10
* Device: redmi 8

## Steps to reproduce
1. migrate multiple manga
2. while some manga still searching open some manga
3. back to migration 

### Expected behavior
continue searching manga

### Actual behavior
stuck at searching

## Other details
maybe because recent change to migration thing? 
it work just fine on j2k
havent tried in stable sy

**Comment by jobobby04** [comment]
Addressed with https://github.com/jobobby04/TachiyomiSY/commit/6951314744a4108819d61e747e6763ce1978de0d
