### ISSUE TITLE
[Feature Request] Backup custom manga info (from J2K)

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#254]
Relevant commit to cherry pick from - https://github.com/Jays2Kings/tachiyomiJ2K/commit/c21b91bc026213993a67089ef4bc76c68ade4445

Have tested on J2K and can confirm that it works

![screenshot_20210328-155952_tac](https://user-images.githubusercontent.com/34897862/112766249-ddb3ec80-8fde-11eb-8816-95f3fec3ea6f.jpg)

**Comment by jobobby04** [comment]
Added with https://github.com/jobobby04/TachiyomiSY/commit/dc760c05961a09dae599d5b9a99548ed81cc544d
