### ISSUE TITLE
[Bug] <Browsing doesn't work unless on the front page>

### ISSUE THREAD

**Issue by tknwgen** [jobobby04/TachiyomiSY#258]
## Device information
* Tachiyomi version: Preview r349
* Android version: 7.1.2
* Device: Redmi 5 Plus

### Expected behavior
Browse should work as usual

### Actual behavior
Browse throws you out to the front page of the source.

**Comment by jobobby04** [comment]
What exactly is happening

**Comment by joseph619** [comment]
user has not responded, nor specified the type or cause of issue. should be closed?

**Comment by jobobby04** [comment]
Sure
