### ISSUE TITLE
[Bug] Merge search and filter bug 

### ISSUE THREAD

**Issue by jadoff630** [jobobby04/TachiyomiSY#259]
## Device information
* Tachiyomi version: r349
* Android version: 10
* Device: Samsung Galaxy Note9

## Steps to reproduce
1. Merge a title
2. Attempt to do a global search or filter

### Expected behavior
either globally search for title or filter extensions 

### Actual behavior
Global search doesn't work, search won't start
filter crashes app 

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.
[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/6255254/tachiyomi_crash_logs.txt)

**Comment by jobobby04** [comment]
Addressed in https://github.com/jobobby04/TachiyomiSY/commit/acb9bafa0a2ae9740a39c7d598611170e437fa15
