### ISSUE TITLE
[Bug] <search & filter options is hidden>

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#261]
## Device information
* Tachiyomi version: r351
* Android version: A11
* Device: samsung note 10+

## Steps to reproduce
1. Open any manga from lib.
2. Click on tag/genre. So, it searches for manga with/has same tag/genre.

### Expected behavior
When you exit (from search not app), search and fitler should remain visible.

### Actual behavior.
It's hidden, my guess is 
Only enable search when mode is Catalogue (@Jobobby04) from latest preview.

## Other details
http://imgur.com/a/K1UWPY6

![Screenshot_20210407-061551_TachiyomiSY.jpg](https://user-images.githubusercontent.com/64928088/113805181-b7bde300-9768-11eb-9b65-336285830081.jpg)

**Comment by jobobby04** [comment]
Have you tried this on the latest Tachi main preview

**Comment by Mano5JP** [comment]
Soory for delay, was busy at work.

I hadn't but just tried and works flawlessly.

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/d5fcded898949777d7d6dd305776a5fc65e26648
