### ISSUE TITLE
[Bug] Unable to Save Images From Manga With Reserved Characters in Their Titles

### ISSUE THREAD

**Issue by atrhioan** [jobobby04/TachiyomiSY#264]
## Device information
* Tachiyomi version: Preview r351 (3b070d88)
* Android version: 11
* Device: Google Pixel 3 XL

## Steps to reproduce
1. Press and hold page
2. Press save

### Expected behavior
Page saved to device in a folder under the manga's name

### Actual behavior
App creates a folder under the manga's name but throws an error without saving anything to it

## Other details
The issue seems to be caused by Tachiyomi creating folders for manga with reserved characters in their titles (e.g. the ":" in the title "Kaguya-sama: Love is War"), making them inaccessible to the device and subsequently unable to save images. Tested by removing the reserved character from the title of the manga, which allowed it to save images normally.

**Comment by jobobby04** [comment]
This is a issue with the latest main Tachi preview, not SY specific
