### ISSUE TITLE
[Feature Request] add rotation and reading mode button in reader 

### ISSUE THREAD

**Issue by ghost** [jobobby04/TachiyomiSY#267]
from official preview app, they are very useful. maybe replace with chapter and webview button

**Comment by huth13** [comment]
I would really like for this to be as well. I have been settling in SY for a while, and I found it most comfortable in use. I would not like to move back to Preview just for this. I wish for it to be considered as well. The Rotation and Readin Mode look more needed for the toolbar than the Webreader and the Chapters as well. Thank you @jferdous70.

![20210410_075403](https://user-images.githubusercontent.com/61908653/114258823-f7d3ce80-99d1-11eb-927e-6d4259bfd48b.jpg)

**Comment by joseph619** [comment]
This will be covered by #273 , so it can be closed @jobobby04
