### ISSUE TITLE
[Feature Request] 
Filter by "alternative found" in source migration menu

### ISSUE THREAD

**Issue by JudahGoldstein** [jobobby04/TachiyomiSY#268]
## Why/User Benefit/User Problem
When migrating a source with a large number of manga there are times that all someone cares about manga where an alternative is actually found, being able to show only them instead of scrolling through at times dozens of failures to find the ones that actually worked to make sure they are actually a match would save a lot of hassle. 

## What/Requirements
Continue the design language from the filters in the rest of the app, click the filter button to have the list of available filters come up. Some filter options aside from the aforementioned could be filtering by groups or filtering out manga where the alternative found has an earlier latest chapter than what is already being used just as a couple other ideas.

**Comment by jobobby04** [comment]
I dont think I will implement any filtering for migration, best I will give is a drop failed option before the migration starts
