### ISSUE TITLE
[Feature Request] Auto migration for chapter bookmark, last read etc (from J2K)

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#271]
Was added just recently, relevant commit https://github.com/Jays2Kings/tachiyomiJ2K/commit/ee4f3e6586910c8c4d62859c867c2a40e41eef67

**Comment by jobobby04** [comment]
Added with https://github.com/jobobby04/TachiyomiSY/commit/5c1423be8685ba667c39835d8ca2626ff5f0fe0e
