### ISSUE TITLE
[Bug] migrate merged source crash

### ISSUE THREAD

**Issue by Riztard** [jobobby04/TachiyomiSY#272]
## Device information
* Tachiyomi version: r355
* Android version: 10
* Device: redmi 8

## Steps to reproduce
1. open merged manga
2. migrate to any source

### Expected behavior
manga migrated

### Actual behavior
app crash

## Other details
i think its because of this [commit](https://github.com/jobobby04/TachiyomiSY/commit/5c1423be8685ba667c39835d8ca2626ff5f0fe0e) 

[Crash log](https://cdn.discordapp.com/attachments/566585518171881493/832232657647697970/tachiyomi_crash_logs.txt)

**Comment by ardittristan** [comment]
Also happens with manga that dont have cover pictures for me (eg mangadex manga)

**Comment by jobobby04** [comment]
Addressed with https://github.com/jobobby04/TachiyomiSY/commit/f4c6b2e09cac905289590709d671ea45db275a38 and https://github.com/jobobby04/TachiyomiSY/commit/b8e907cea2533b1b35c75b85db4f25cc093e7f52
