### ISSUE TITLE
[Feature Request] Option to choose what button shows up in bottom reader sheet (from J2K)

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#273]
## Why/User Benefit/User Problem
This will solve all the issues of not having the right buttons I guess

## What/Requirements
(Was added recently in J2k, relevant commit  https://github.com/Jays2Kings/tachiyomiJ2K/commit/f12be4a48041ae06e91bfd787b998619bf55a9ca

**Comment by jferdous70** [comment]
Screenshot of what it looks like

![Screenshot2](https://user-images.githubusercontent.com/81538887/115121102-e7e25e80-9f7e-11eb-8655-a51feda8df30.jpg)

**Comment by joseph619** [comment]
What it looks like

![Screenshot2](https://user-images.githubusercontent.com/34897862/115121169-38f25280-9f7f-11eb-8bfb-db2291776619.jpg)

**Comment by huth13** [comment]
This is such a great request. Praying for its forthcoming.

**Comment by jobobby04** [comment]
Addressed with https://github.com/jobobby04/TachiyomiSY/commit/a4933388aada8a193c9eeb1bcb3194844bfe8a74
