### ISSUE TITLE
[Feature Request] <Tab/Section "Recents" Like J2K>

### ISSUE THREAD

**Issue by e-shl** [jobobby04/TachiyomiSY#276]
## What/Requirements
Reduce the number of tabs of the navbar, combine updates and history as in J2K
<img src="https://user-images.githubusercontent.com/35057681/115143854-15a0d380-a063-11eb-8044-51ac6ce6fc39.PNG" width="400" />

**Comment by joseph619** [comment]
This will most certainly not happen unless main app also adopts this

**Comment by jobobby04** [comment]
Ya I wont do this myself, I leave most UI to the main app
