### ISSUE TITLE
[Feature Request] Change blue loading and badge accent colors in Midnight Dusk theme to something similar to J2K Midnight Dusk?

### ISSUE THREAD

**Issue by ImRyley** [jobobby04/TachiyomiSY#277]
## Why/User Benefit/User Problem
Improves the theme by keeping the color scheme.

## What/Requirements
The blue accent on badges and loading (possibly black background on loading too) would be changed to better fit the Midnight Dusk theme.

**SY Midnight Dusk**
![Screenshot_20210418-185406](https://user-images.githubusercontent.com/25411903/115167241-71c42180-a07c-11eb-8788-af9a71c88194.png)
![Screenshot_20210418-185937](https://user-images.githubusercontent.com/25411903/115167243-738de500-a07c-11eb-9dce-56d4e70f3a1f.png)
**J2K Midnight Dusk**
![Screenshot_20210418-185343](https://user-images.githubusercontent.com/25411903/115167246-75f03f00-a07c-11eb-9d6d-a280d60a64ea.png)
![Screenshot_20210418-190003](https://user-images.githubusercontent.com/25411903/115167248-77ba0280-a07c-11eb-9f16-3098ae7c4783.png)

**Comment by ImRyley** [comment]
## Why/User Benefit/User Problem
Improves the theme by keeping the color scheme.

## What/Requirements
The blue accent would be changed to better fit the Midnight Dusk theme.

**Comment by CaptainHalflife** [comment]
Someone can do that for the other themes too and why the text in black-red are red instead of white ? I think its better to just replace everything that blue to red and change the colour of the download badge to one that look good for each theme

**Comment by jobobby04** [comment]
Already addressed by main tachi
