### ISSUE TITLE
[Bug] <Bookmarks disappear on library update>

### ISSUE THREAD

**Issue by pixelade** [jobobby04/TachiyomiSY#278]
---

## Device information
* Tachiyomi version: 1.6.1
* Android version: 11
* Device: Pixel 2

## Steps to reproduce
1. Bookmark chapters
2. Update series

### Expected behavior
Adds new chapters to series while retaining previously added bookmarks

### Actual behavior
Adds new chapters to series while erasing previously added bookmarks

## Other details
Occasionally series will do this without adding chapters.

**Comment by joseph619** [comment]
What source are you using?

**Comment by pixelade** [comment]
I'm using hiperdex

**Comment by pixelade** [comment]
Issue continues to persist on current version 1.7.0 on a different device (Pixel 4a). It also occurs sporadically, with series sometimes not deleting any bookmarks and some still deleting all bookmarks. This can occur within the same round of updates. Also to clarify, I'm referring to the bookmark status, not downloaded chapters. The chapters become unbookmarked.

**Comment by jobobby04** [comment]
Closing due to main Tachi issue
