### ISSUE TITLE
[Change in Layout] <3 Column layout option>

### ISSUE THREAD

**Issue by rickninja765** [jobobby04/TachiyomiSY#279]
So I was just using TachiyomiJ2K and i really like their layout.
Its so convenient to have 3 column than 2 column so can we have 3 column.
![Screenshot_2021-04-20-17-52-51-96.jpg](https://user-images.githubusercontent.com/61545131/115395672-a7c7e980-a1d3-11eb-82a1-5eea5685b582.jpg)
Like this^

**Comment by joseph619** [comment]
Explore the app, SY has far more options for this than J2K
