### ISSUE TITLE
[Bug] Kitsu tracking is not working right now, due failed to resolve the API url (?)

### ISSUE THREAD

**Issue by krakerz** [jobobby04/TachiyomiSY#282]
## Device information
* Tachiyomi version: Stable 1.6.1
* Android version: 10
* Device: Realme 7 pro

## Steps to reproduce
1. Open any manga
2. Click the Tracking
3. Use Kitsu Tracking

### Expected behavior
Search working normally

### Actual behavior
Get failed to connect to the API url instead

## Other details
Login or Logout kitsu service from the app working fine tho no problem,
already tried to clear cookies as well, the api url somehow still same no matter what i do
attached file :
![Screenshot_2021-04-21-13-52-54-56_a603e4da04bada03cae438f177815547](https://user-images.githubusercontent.com/8030983/115510283-b97bc080-a2a9-11eb-9d94-2436c10f7947.jpg)

**Comment by jobobby04** [comment]
SY does not edit the kitsu tracker from Tachiyomi, test it in tachiyomiorg/tachiyomi, as it's likely not SY specific

**Comment by krakerz** [comment]
ah yes, tried it with the vanilla ones, it seems its their end, thanks for pointing it out, gonna report it there

**Comment by jobobby04** [comment]
👍
