### ISSUE TITLE
[Feature Request] please add support to read .bin files as image

### ISSUE THREAD

**Issue by yooman1213** [jobobby04/TachiyomiSY#283]
---

## Why/User Benefit/User Problem
1. Future proofing 
2. maybe faster loading time for downloaded files because of it's native binary reading

## What/Requirements
Please add support to read .bin file as image or any kind of image processing because there's a prove that there is a web that changes their database manga with .bin file so it would load faster 

When downloaded and compressed into .cbz the content would be in .bin file thus rendering it to be unreadable and mark as " no page found ".

What if many popular source start implementing this kind of strategies? It would make the app cannot read any downloaded manga.

**Comment by jobobby04** [comment]
This isnt in the range of SY specific features, I will only add it if Tachiyomi main gets it.
