### ISSUE TITLE
[Bug] Tapping on the resume button would cause me to read the last/latest chapter. 

### ISSUE THREAD

**Issue by Mugen007** [jobobby04/TachiyomiSY#284]
## Device information
* Tachiyomi version: 1.6.1
* Android version: 9
* Device: Huawei Y6 Pro (2019)

## Steps to reproduce
1. Tap the “resume" button in the manga page

### Expected behavior
It would go to the chapter I'm currently reading

### Actual behavior
It would send me to the last/latest chapter available

## Other details
The bug only occurs when I read/tap on another chapter rather than the chapter I'm currently reading (I hope this isn't confusing to read). The only temporary fix I could muster up is to clear the cache and tapping the "start reading" button in the library menu.

**Comment by joseph619** [comment]
This isn't a SY specific bug

**Comment by jobobby04** [comment]
Its fixed in the main apps preview, I will grab the fix sometime
