### ISSUE TITLE
[Feature Request] <a possible way for multi devices syncing>

### ISSUE THREAD

**Issue by SanOtaku09** [jobobby04/TachiyomiSY#288]
Add a option that
On app start up tachiyomi looks for reading progress in tracking site (if site is attached to manga) (tracking site like myanimelist and etc) 
And if the the reading ch no. on tracking site is greater than in tachiyomi than mark the ch as read in app

Just like how tachiyomi sync ch from app to site
You just need to reverse it on startup of the app

It will be a great feature to have and it's possible to do

## Why/User Benefit/User Problem
Can read manga on Multiple devices without remembering last read

## What/Requirements
Hard Works😅😂

**Comment by jobobby04** [comment]
I probably wont do this, I think something similar has been pr'd to the main app before
