### ISSUE TITLE
[SY Crashes] <SY crashes when I open The Flash (2016) from ReadComicOnline and click on the Settings icon>

### ISSUE THREAD

**Issue by GoldMight948** [jobobby04/TachiyomiSY#289]
## Device information
* Tachiyomi version: 1.6.1
* Android version: 8.10
* Device: Vivo 1820

## Steps to reproduce
1. Open The Flash (2016) through the ReadComicOnline Extension while reading.
2. Click on settings icon

### Expected behavior
Settings should open 

### Actual behavior
The app crashes instead of opening settings .

## Other details
Only happening with this comic and in this source 

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

https://discord.com/channels/349436576037732353/566585518171881493/836608567502962718

**Comment by sillvva** [comment]
This is happening on other manga that I'm reading as well. I want to set it to read left to right, but the default setting doesn't work and the individual manga page settings crashes the app.

**Comment by sillvva** [comment]
Here is a crash log: https://drive.google.com/file/d/1M1kMsmWqsiShZGqwokCERZYmsd4JGbrE/view?usp=sharing

**Comment by jobobby04** [comment]
Go to Settings -> Advanced -> Debug Functions -> Fix reading viewer backup bug, it should fix it

**Comment by jobobby04** [comment]
Going to assume this is fixed
