### ISSUE TITLE
[Feature Request] Keep watched list enabled when entering Ehentai

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#29]
### Why/User Benefit/User Problem
Currently, watched list gets disabled everytime user gets out of Ehentai, even if it was enabled. This wastes a lot of time as user has to enable it manually everytime opening the source.

### What/Requirements
The app should remember what state watched list was in even after going out of the source.

**Comment by jobobby04** [comment]
Added in https://github.com/jobobby04/TachiyomiSY/commit/498f69869a8c415091858deffd5ec41ccb353cd9

I didnt expect to do it this fast
