### ISSUE TITLE
[Bug] MangaPlus is broken 

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#291]
## Device information
* Tachiyomi version: r360
* Android version: 11
* Device: Galaxy S10+

## Steps to reproduce
1. Install Mangaplus ext (current version, 1.2.17)

### Actual behavior
Shows the following error 

```kotlinx.serialization.protobuf.ProtoBuf$Default cannot be cast to kotlinx.serialization.BinaryFormat```

## Additional info
Works fine in Stable 0.10.12

**Comment by jobobby04** [comment]
Addressed with https://github.com/jobobby04/TachiyomiSY/commit/f9b4cb5bc910e8735f9bfcd224d1a99bad934799
