### ISSUE TITLE
[Bug] <Font is smaller/decreases>

### ISSUE THREAD

**Issue by e-shl** [jobobby04/TachiyomiSY#293]
## Device information
* Tachiyomi version: 1.6.2
* Android version: 10/11
* Device: AOSP/LOS

In translation(rus), the font is smaller on the Sort(Сортировать) and Group(Группировка) tabs in the library. Also Extensions(Расширения) and Migrate (Мигрировать) in the browse
<img src="https://user-images.githubusercontent.com/35057681/116560160-8d4fe780-a91a-11eb-8a40-568e0b1f1ec1.png" width="200" /><img src="https://user-images.githubusercontent.com/35057681/116560164-8e811480-a91a-11eb-8a0d-eb1285fee4f7.png" width="200" />

**Comment by jobobby04** [comment]
Thats just the way the tabs menu deals with words going over the boundary, cant really do anything about that
