### ISSUE TITLE
[Feature Request] Manga info (title, Artist, description, tags) edit

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#3]
### Why/User Benefit/User Problem
Allows user to edit the manga info and change title, Artist, description and tags of a manga as they please.

### What/Requirements
Feature can be imported from new TachiJ2k commit.

**Comment by vipzzx** [comment]
Yes please add this!

**Comment by joseph619** [comment]
Feature has been implemented
