### ISSUE TITLE
[Feature Request] Have tracking show on default if logged in 

### ISSUE THREAD

**Issue by vipzzx** [jobobby04/TachiyomiSY#30]
### Why/User Benefit/User Problem
Faster to add tracking after adding to library. 
Currently you are only ale to add tracking after you add a manga to the library, exit browse, return to library then going into manga and adding tracking.

A lot of times I find manga that I have read years ago and didn't track it and want to add it to my tracking not would have to go through the whole process just to add it to my tracking.  

### What/Requirements
Like how in J2K and Neko had the tracking button right next to the "add to library", once you go into a manga. Does not require manga to be in library to start tracking.

**Comment by jobobby04** [comment]
Added in https://github.com/jobobby04/TachiyomiSY/commit/69121d39588e0b3999a52255af61cda87b67c0e5
