### ISSUE TITLE
[Bug] <crash>

### ISSUE THREAD

**Issue by dmswd** [jobobby04/TachiyomiSY#300]
## Device information
App version: 1.6.2 (standard, f9b4cb5bc, 16)
Preview build: 361
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A315FXXU1BUA1
Device brand: samsung
Device manufacturer: samsung
Device name: a31
Device model: SM-A315F
Device product name: a31xx

## Steps to reproduce
1. I was just reading a chapter
Then the app crashed suddenly 

### Expected behavior
The app should not crash

### Actual behavior
The app crashed

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.
Logs
--------- beginning of main 05-04 10:42:45.360 27994 27994 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent. 05-04 10:54:59.957 27994 31547 E SQLiteLog: (284) automatic index on C(manga_id) 05-04 10:54:59.958 27994 31547 E SQLiteLog: (284) automatic index on R(manga_id) 05-04 10:54:59.958 27994 31547 E SQLiteLog: (284) automatic index on C(merge_id) 05-04 10:54:59.958 27994 31547 E SQLiteLog: (284) automatic index on R(merge_id) 05-04 10:54:59.958 27994 31547 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-04 10:55:00.095 27994 31531 E gralloc : Arm Module v1.0 05-04 10:55:00.103 27994 31531 E ion : ioctl c0044901 failed with code -1: Invalid argument 05-04 10:55:16.805 27994 27994 E chromium: [ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported. 05-04 10:55:16.806 27994 27994 E chromium: [ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported. 05-04 10:55:39.375 27994 27994 E DecorView: mWindow.mActivityCurrentConfig is null 05-04 10:55:39.442 27994 27994 E DecorView: mWindow.mActivityCurrentConfig is null 05-04 10:55:39.472 27994 27994 E DecorView: mWindow.mActivityCurrentConfig is null 05-04 10:55:43.349 27994 27994 E DecorView: mWindow.mActivityCurrentConfig is null 05-04 10:55:44.402 27994 27994 E DecorView: mWindow.mActivityCurrentConfig is null 05-04 10:55:46.036 27994 27994 E ViewRootImpl: sendUserActionEvent() mView returned. 05-04 10:56:21.936 28601 28601 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent. 05-04 10:56:25.355 28601 32633 E gralloc : Arm Module v1.0 05-04 10:56:25.358 28601 32633 E ion : ioctl c0044901 failed with code -1: Invalid argument 05-04 10:56:30.587 28601 1107 E SQLiteLog: (284) automatic index on C(manga_id) 05-04 10:56:30.587 28601 1107 E SQLiteLog: (284) automatic index on R(manga_id) 05-04 10:56:30.588 28601 1107 E SQLiteLog: (284) automatic index on C(merge_id) 05-04 10:56:30.588 28601 1107 E SQLiteLog: (284) automatic index on R(merge_id) 05-04 10:56:30.588 28601 1107 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) App version: 1.6.2 (standard, f9b4cb5bc, 16) Preview build: 361 Android version: 10 (SDK 29) Android build ID: QP1A.190711.020.A315FXXU1BUA1 Device brand: samsung Device manufacturer: samsung Device name: a31 Device model: SM-A315F Device product name: a31xx

**Comment by jobobby04** [comment]
If you use MAL, re-login. Otherwise I cant tell based on your log

**Comment by dmswd** [comment]
I did as you said 
And I will close this until the app crashes again
