### ISSUE TITLE
[Bug] App crash upon opening reader settings

### ISSUE THREAD

**Issue by semiya5** [jobobby04/TachiyomiSY#301]
## Device information
* Tachiyomi version: r361
* Android version: 11
* Device: Galaxy S10

## Steps to reproduce
1. Add Nano Machine from Reaper Scans to library
2. Open any chapter
3. press settings button to change reading mode

### Expected behavior
Should open in-reader settings

### Actual behavior
App Crashing

## Other details
--------- beginning of system
--------- beginning of main
05-04 08:17:44.325  7082 12457 E chromium: [ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
05-04 08:17:44.583  7082  7082 E chromium: [ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
05-04 08:17:44.584  7082  7082 E chromium: [ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
05-04 08:41:42.418 12402 12402 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
05-04 08:41:52.428 12402 16974 E SQLiteLog: (284) automatic index on C(manga_id)
05-04 08:41:52.428 12402 16974 E SQLiteLog: (284) automatic index on R(manga_id)
05-04 08:41:52.428 12402 16974 E SQLiteLog: (284) automatic index on C(merge_id)
05-04 08:41:52.429 12402 16974 E SQLiteLog: (284) automatic index on R(merge_id)
05-04 08:41:52.429 12402 16974 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
--------- beginning of crash
05-04 08:42:00.193 12402 12402 E AndroidRuntime: FATAL EXCEPTION: main
05-04 08:42:00.193 12402 12402 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 12402
05-04 08:42:00.193 12402 12402 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.getItem(MenuBuilder.java:752)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at eu.kanade.tachiyomi.widget.MaterialSpinnerView.setSelection(MaterialSpinnerView.kt:29)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.initGeneralPreferences(ReaderReadingModeSettings.kt:55)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.<init>(ReaderReadingModeSettings.kt:33)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.<init>(ReaderReadingModeSettings.kt:23)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderSettingsSheet.<init>(ReaderSettingsSheet.kt:16)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderSettingsSheet.<init>(ReaderSettingsSheet.kt:13)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$initializeMenu$$inlined$with$lambda$2.onClick(ReaderActivity.kt:532)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at android.view.View.performClick(View.java:8160)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:8137)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at android.view.View.access$3700(View.java:888)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30236)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
05-04 08:42:00.193 12402 12402 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
05-04 08:42:01.337 17136 17136 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
05-04 08:42:02.131 17136 17204 E SQLiteLog: (284) automatic index on C(manga_id)
05-04 08:42:02.131 17136 17204 E SQLiteLog: (284) automatic index on R(manga_id)
05-04 08:42:02.131 17136 17204 E SQLiteLog: (284) automatic index on C(merge_id)
05-04 08:42:02.131 17136 17204 E SQLiteLog: (284) automatic index on R(merge_id)
05-04 08:42:02.131 17136 17204 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: FATAL EXCEPTION: main
05-04 08:42:07.750 17136 17136 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 17136
05-04 08:42:07.750 17136 17136 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.getItem(MenuBuilder.java:752)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at eu.kanade.tachiyomi.widget.MaterialSpinnerView.setSelection(MaterialSpinnerView.kt:29)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.initGeneralPreferences(ReaderReadingModeSettings.kt:55)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.<init>(ReaderReadingModeSettings.kt:33)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.<init>(ReaderReadingModeSettings.kt:23)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderSettingsSheet.<init>(ReaderSettingsSheet.kt:16)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderSettingsSheet.<init>(ReaderSettingsSheet.kt:13)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$initializeMenu$$inlined$with$lambda$2.onClick(ReaderActivity.kt:532)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at android.view.View.performClick(View.java:8160)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:8137)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at android.view.View.access$3700(View.java:888)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30236)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
05-04 08:42:07.750 17136 17136 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
05-04 08:42:12.144 16841 16841 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
05-04 08:42:18.304 17386 17386 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
05-04 08:42:19.022 17386 17528 E SQLiteLog: (284) automatic index on C(manga_id)
05-04 08:42:19.022 17386 17528 E SQLiteLog: (284) automatic index on R(manga_id)
05-04 08:42:19.022 17386 17528 E SQLiteLog: (284) automatic index on C(merge_id)
05-04 08:42:19.022 17386 17528 E SQLiteLog: (284) automatic index on R(merge_id)
05-04 08:42:19.022 17386 17528 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: FATAL EXCEPTION: main
05-04 08:42:24.321 17386 17386 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 17386
05-04 08:42:24.321 17386 17386 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.getItem(MenuBuilder.java:752)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at eu.kanade.tachiyomi.widget.MaterialSpinnerView.setSelection(MaterialSpinnerView.kt:29)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.initGeneralPreferences(ReaderReadingModeSettings.kt:55)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.<init>(ReaderReadingModeSettings.kt:33)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.<init>(ReaderReadingModeSettings.kt:23)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderSettingsSheet.<init>(ReaderSettingsSheet.kt:16)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderSettingsSheet.<init>(ReaderSettingsSheet.kt:13)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$initializeMenu$$inlined$with$lambda$2.onClick(ReaderActivity.kt:532)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at android.view.View.performClick(View.java:8160)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:8137)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at android.view.View.access$3700(View.java:888)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30236)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
05-04 08:42:24.321 17386 17386 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
05-04 08:42:28.344 17452 17452 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
05-04 08:42:29.252 17452 17783 E SQLiteLog: (284) automatic index on C(manga_id)
05-04 08:42:29.252 17452 17783 E SQLiteLog: (284) automatic index on R(manga_id)
05-04 08:42:29.252 17452 17783 E SQLiteLog: (284) automatic index on C(merge_id)
05-04 08:42:29.252 17452 17783 E SQLiteLog: (284) automatic index on R(merge_id)
05-04 08:42:29.252 17452 17783 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: FATAL EXCEPTION: main
05-04 08:42:52.501 17452 17452 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 17452
05-04 08:42:52.501 17452 17452 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.getItem(MenuBuilder.java:752)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at eu.kanade.tachiyomi.widget.MaterialSpinnerView.setSelection(MaterialSpinnerView.kt:29)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.initGeneralPreferences(ReaderReadingModeSettings.kt:55)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.<init>(ReaderReadingModeSettings.kt:33)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.<init>(ReaderReadingModeSettings.kt:23)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderSettingsSheet.<init>(ReaderSettingsSheet.kt:16)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderSettingsSheet.<init>(ReaderSettingsSheet.kt:13)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$initializeMenu$$inlined$with$lambda$2.onClick(ReaderActivity.kt:532)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at android.view.View.performClick(View.java:8160)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:8137)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at android.view.View.access$3700(View.java:888)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30236)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
05-04 08:42:52.501 17452 17452 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
05-04 08:42:58.254 17546 17546 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
05-04 08:43:01.889 17546 18090 E SQLiteLog: (284) automatic index on C(manga_id)
05-04 08:43:01.889 17546 18090 E SQLiteLog: (284) automatic index on R(manga_id)
05-04 08:43:01.889 17546 18090 E SQLiteLog: (284) automatic index on C(merge_id)
05-04 08:43:01.889 17546 18090 E SQLiteLog: (284) automatic index on R(merge_id)
05-04 08:43:01.889 17546 18090 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: FATAL EXCEPTION: main
05-04 08:43:58.141 17546 17546 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 17546
05-04 08:43:58.141 17546 17546 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.getItem(MenuBuilder.java:752)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at eu.kanade.tachiyomi.widget.MaterialSpinnerView.setSelection(MaterialSpinnerView.kt:29)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.initGeneralPreferences(ReaderReadingModeSettings.kt:55)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.<init>(ReaderReadingModeSettings.kt:33)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.<init>(ReaderReadingModeSettings.kt:23)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderSettingsSheet.<init>(ReaderSettingsSheet.kt:16)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderSettingsSheet.<init>(ReaderSettingsSheet.kt:13)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$initializeMenu$$inlined$with$lambda$2.onClick(ReaderActivity.kt:532)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at android.view.View.performClick(View.java:8160)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:8137)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at android.view.View.access$3700(View.java:888)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30236)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
05-04 08:43:58.141 17546 17546 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
05-04 08:43:59.256 18567 18567 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
05-04 08:44:03.398 17805 17805 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
05-04 08:44:41.456 17805 18859 E SQLiteLog: (284) automatic index on C(manga_id)
05-04 08:44:41.456 17805 18859 E SQLiteLog: (284) automatic index on R(manga_id)
05-04 08:44:41.456 17805 18859 E SQLiteLog: (284) automatic index on C(merge_id)
05-04 08:44:41.456 17805 18859 E SQLiteLog: (284) automatic index on R(merge_id)
05-04 08:44:41.456 17805 18859 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-04 08:45:00.554 18067 18067 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
05-04 08:46:01.801 18067 19556 E SQLiteLog: (284) automatic index on C(manga_id)
05-04 08:46:01.801 18067 19556 E SQLiteLog: (284) automatic index on R(manga_id)
05-04 08:46:01.801 18067 19556 E SQLiteLog: (284) automatic index on C(merge_id)
05-04 08:46:01.801 18067 19556 E SQLiteLog: (284) automatic index on R(merge_id)
05-04 08:46:01.801 18067 19556 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 1.6.2 (standard, f9b4cb5bc, 16)
Preview build: 361
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.G973USQU5GUCH
Device brand: samsung
Device manufacturer: samsung
Device name: beyond1q
Device model: SM-G973U
Device product name: beyond1qltesq

**Comment by jobobby04** [comment]
Go to Settings -> Advanced -> Debug Functions -> Fix reading viewer backup bug, it should fix it
