### ISSUE TITLE
[Feature Request] To be able to filter by category group

### ISSUE THREAD

**Issue by molitar** [jobobby04/TachiyomiSY#303]
## Why/User Benefit/User Problem
**Why:** I have to keep toggling to show unread when I check my 2 other categories
**User Benefit:** It helps prevent too many scrapes to check for new chapters by scanning for rarely updated manhua's.
1. Default category is None - it has all recent and updated manhuas.
2. Manual category - I put manhuas that I find tend to hang for some reason when checking.  Benefit is that now I scan these one at a time and I don't have to keep restarting the check for new chapters when it hangs up causing way too many scrapes to sites that may cause bans on the sites for Tachiyomi.
3. Unknown Status - if manhua has not been updated in several months I put them in this category and only do a once a week scan to see if they get updated or not.  Again this helps prevent the unneeded scrapes against the sites for manhuas that are not being updated.

## What/Requirements
To be able to assign the filter for categories and not a single global filter. So in say Default Category I can just show unread manhuas while in 2 and 3 I can always have them show specifically.  My default library view is by category and that is how I manage the groups but currently I have to keep going into filter and toggle off the unread checkbox so that I can see them all to manually check them in category 2 and 3.

**Comment by jobobby04** [comment]
I dont see much use for this, I am just going to close it since I wont be working on it
