### ISSUE TITLE
[Bug] <crash>

### ISSUE THREAD

**Issue by dmswd** [jobobby04/TachiyomiSY#304]
## Device information
* App version: 1.6.2 (standard, b9b5ef55a, 17)
Preview build: 362
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A315FXXU1BUA1
Device brand: samsung
Device manufacturer: samsung
Device name: a31
Device model: SM-A315F
Device product name: a31xx

## Steps to reproduce
1. Just update the library 

### Expected behavior
Should update

### Actual behavior
The app crashes

## Other details
I tried in main app preview 

The logs

--------- beginning of main 05-07 11:13:02.010 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:13:03.466 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:13:04.591 10268 11955 E SQLiteLog: (284) automatic index on C(manga_id) 05-07 11:13:04.592 10268 11955 E SQLiteLog: (284) automatic index on R(manga_id) 05-07 11:13:04.592 10268 11955 E SQLiteLog: (284) automatic index on C(merge_id) 05-07 11:13:04.592 10268 11955 E SQLiteLog: (284) automatic index on R(merge_id) 05-07 11:13:04.592 10268 11955 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-07 11:13:05.499 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:13:06.398 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:13:07.340 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:13:09.501 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:13:10.322 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:13:12.228 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:13:13.991 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:13:23.349 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:13:25.830 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:13:43.886 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:13:45.112 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:13:45.548 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:13:46.109 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:13:46.314 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:13:46.937 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:13:59.666 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:14:01.476 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:14:23.679 10268 10268 E ViewRootImpl@2ef6361[MainActivity]: Surface is not valid. 05-07 11:14:27.727 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:14:28.978 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:14:31.777 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:14:33.226 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:14:35.550 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:14:37.787 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:14:38.679 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:14:40.375 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:14:41.396 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:14:43.274 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:14:44.525 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:15:02.878 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:15:04.568 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:15:05.492 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:15:06.871 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:16:05.408 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:16:07.429 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:16:13.982 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:16:14.745 10268 10268 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 11:16:15.155 10268 10268 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 11:16:30.804 10268 12655 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher 05-07 11:16:30.804 10268 12655 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 10268 05-07 11:16:30.804 10268 12655 E AndroidRuntime: java.lang.Error: java.lang.Exception: HTTP error 401 05-07 11:16:30.804 10268 12655 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173) 05-07 11:16:30.804 10268 12655 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:16:30.804 10268 12655 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:16:30.804 10268 12655 E AndroidRuntime: Caused by: java.lang.Exception: HTTP error 401 05-07 11:16:30.804 10268 12655 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:16:30.804 10268 12655 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:16:30.804 10268 12655 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:16:30.804 10268 12655 E AndroidRuntime: 	... 2 more 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: java.io.IOException: canceled due to java.lang.Exception: HTTP error 401 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530) 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	Suppressed: java.lang.Exception: HTTP error 401 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		... 3 more 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: java.io.IOException: canceled due to java.lang.Exception: HTTP error 401 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530) 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	Suppressed: java.lang.Exception: HTTP error 401 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:16:30.805 10268 11768 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		... 3 more 05-07 11:16:34.696 10476 10476 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent. 05-07 11:16:35.844 10476 12748 E SQLiteLog: (284) automatic index on C(manga_id) 05-07 11:16:35.844 10476 12748 E SQLiteLog: (284) automatic index on R(manga_id) 05-07 11:16:35.845 10476 12748 E SQLiteLog: (284) automatic index on C(merge_id) 05-07 11:16:35.845 10476 12748 E SQLiteLog: (284) automatic index on R(merge_id) 05-07 11:16:35.845 10476 12748 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-07 11:16:35.929 10476 12725 E gralloc : Arm Module v1.0 05-07 11:16:35.930 10476 12725 E ion : ioctl c0044901 failed with code -1: Invalid argument 05-07 11:16:41.120 10476 12837 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher 05-07 11:16:41.120 10476 12837 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 10476 05-07 11:16:41.120 10476 12837 E AndroidRuntime: java.lang.Error: java.lang.Exception: HTTP error 401 05-07 11:16:41.120 10476 12837 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173) 05-07 11:16:41.120 10476 12837 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:16:41.120 10476 12837 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:16:41.120 10476 12837 E AndroidRuntime: Caused by: java.lang.Exception: HTTP error 401 05-07 11:16:41.120 10476 12837 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:16:41.120 10476 12837 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:16:41.120 10476 12837 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:16:41.120 10476 12837 E AndroidRuntime: 	... 2 more 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: java.io.IOException: canceled due to java.lang.Exception: HTTP error 401 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530) 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	Suppressed: java.lang.Exception: HTTP error 401 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		... 3 more 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: java.io.IOException: canceled due to java.lang.Exception: HTTP error 401 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530) 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	Suppressed: java.lang.Exception: HTTP error 401 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:16:41.121 10476 12779 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		... 3 more 05-07 11:16:47.725 10865 10865 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent. 05-07 11:16:48.712 10865 12979 E SQLiteLog: (284) automatic index on C(manga_id) 05-07 11:16:48.712 10865 12979 E SQLiteLog: (284) automatic index on R(manga_id) 05-07 11:16:48.712 10865 12979 E SQLiteLog: (284) automatic index on C(merge_id) 05-07 11:16:48.712 10865 12979 E SQLiteLog: (284) automatic index on R(merge_id) 05-07 11:16:48.712 10865 12979 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-07 11:16:48.789 10865 12966 E gralloc : Arm Module v1.0 05-07 11:16:48.790 10865 12966 E ion : ioctl c0044901 failed with code -1: Invalid argument 05-07 11:17:58.615 10865 13415 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher 05-07 11:17:58.615 10865 13415 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 10865 05-07 11:17:58.615 10865 13415 E AndroidRuntime: java.lang.Error: java.lang.Exception: HTTP error 401 05-07 11:17:58.615 10865 13415 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173) 05-07 11:17:58.615 10865 13415 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:17:58.615 10865 13415 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:17:58.615 10865 13415 E AndroidRuntime: Caused by: java.lang.Exception: HTTP error 401 05-07 11:17:58.615 10865 13415 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:17:58.615 10865 13415 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:17:58.615 10865 13415 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:17:58.615 10865 13415 E AndroidRuntime: 	... 2 more 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: java.io.IOException: canceled due to java.lang.Exception: HTTP error 401 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530) 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	Suppressed: java.lang.Exception: HTTP error 401 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		... 3 more 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: java.io.IOException: canceled due to java.lang.Exception: HTTP error 401 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530) 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	Suppressed: java.lang.Exception: HTTP error 401 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:17:58.616 10865 13011 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		... 3 more 05-07 11:18:00.959 13085 13085 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent. 05-07 11:18:01.949 13085 13539 E SQLiteLog: (284) automatic index on C(manga_id) 05-07 11:18:01.949 13085 13539 E SQLiteLog: (284) automatic index on R(manga_id) 05-07 11:18:01.949 13085 13539 E SQLiteLog: (284) automatic index on C(merge_id) 05-07 11:18:01.949 13085 13539 E SQLiteLog: (284) automatic index on R(merge_id) 05-07 11:18:01.949 13085 13539 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-07 11:18:02.026 13085 13526 E gralloc : Arm Module v1.0 05-07 11:18:02.029 13085 13526 E ion : ioctl c0044901 failed with code -1: Invalid argument 05-07 11:18:08.175 13085 13604 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher 05-07 11:18:08.175 13085 13604 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 13085 05-07 11:18:08.175 13085 13604 E AndroidRuntime: java.lang.Error: java.lang.Exception: HTTP error 401 05-07 11:18:08.175 13085 13604 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173) 05-07 11:18:08.175 13085 13604 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:18:08.175 13085 13604 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:18:08.175 13085 13604 E AndroidRuntime: Caused by: java.lang.Exception: HTTP error 401 05-07 11:18:08.175 13085 13604 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:18:08.175 13085 13604 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:18:08.175 13085 13604 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:18:08.175 13085 13604 E AndroidRuntime: 	... 2 more 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: java.io.IOException: canceled due to java.lang.Exception: HTTP error 401 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530) 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	Suppressed: java.lang.Exception: HTTP error 401 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		... 3 more 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: java.io.IOException: canceled due to java.lang.Exception: HTTP error 401 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530) 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	Suppressed: java.lang.Exception: HTTP error 401 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:18:08.176 13085 13581 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		... 3 more 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: java.io.IOException: canceled due to java.lang.Exception: HTTP error 401 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530) 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	Suppressed: java.lang.Exception: HTTP error 401 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		... 3 more 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: java.io.IOException: canceled due to java.lang.Exception: HTTP error 401 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530) 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	at java.lang.Thread.run(Thread.java:919) 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 	Suppressed: java.lang.Exception: HTTP error 401 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 11:18:11.063 13085 13580 E LibraryUpdateService$updateManga$$inlined$CoroutineExceptionHandler: 		... 3 more 05-07 11:18:22.005 13209 13209 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent. 05-07 11:18:23.318 13209 13746 E SQLiteLog: (284) automatic index on C(manga_id) 05-07 11:18:23.319 13209 13746 E SQLiteLog: (284) automatic index on R(manga_id) 05-07 11:18:23.319 13209 13746 E SQLiteLog: (284) automatic index on C(merge_id) 05-07 11:18:23.319 13209 13746 E SQLiteLog: (284) automatic index on R(merge_id) 05-07 11:18:23.319 13209 13746 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-07 11:18:23.465 13209 13732 E gralloc : Arm Module v1.0 05-07 11:18:23.466 13209 13732 E ion : ioctl c0044901 failed with code -1: Invalid argument App version: 1.6.2 (standard, b9b5ef55a, 17) Preview build: 362 Android version: 10 (SDK 29) Android build ID: QP1A.190711.020.A315FXXU1BUA1 Device brand: samsung Device manufacturer: samsung Device name: a31 Device model: SM-A315F Device product name: a31xx

**Comment by jobobby04** [comment]
Addressed with https://github.com/jobobby04/TachiyomiSY/commit/858a5e6eeea4443feaed13bbebfef5623c8d32e3
