### ISSUE TITLE
[Bug] <another crash>

### ISSUE THREAD

**Issue by dmswd** [jobobby04/TachiyomiSY#305]
## Device information
* App version: 1.6.2 (standard, b9b5ef55a, 17)
Preview build: 362
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A315FXXU1BUA1
Device brand: samsung
Device manufacturer: samsung
Device name: a31
Device model: SM-A315F
Device product name: a31xx

## Steps to reproduce
1. Open a manga that's tracked by the five trackers (mangadex,kitsu,anilist,shikimori,myanimelist)
And press the trackers button
### Expected behavior
Should open normally 

### Actual behavior
The app crashes

## Other details
https://user-images.githubusercontent.com/66433732/117446174-fb5c6600-af3b-11eb-9604-5872b10427db.mp4

Logs

--------- beginning of main 05-07 13:40:32.334 6469 6585 E SQLiteLog: (284) automatic index on C(manga_id) 05-07 13:40:32.334 6469 6585 E SQLiteLog: (284) automatic index on R(manga_id) 05-07 13:40:32.334 6469 6585 E SQLiteLog: (284) automatic index on C(merge_id) 05-07 13:40:32.335 6469 6585 E SQLiteLog: (284) automatic index on R(merge_id) 05-07 13:40:32.335 6469 6585 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-07 13:40:32.459 6469 6581 E gralloc : Arm Module v1.0 05-07 13:40:32.461 6469 6581 E ion : ioctl c0044901 failed with code -1: Invalid argument 05-07 13:40:37.655 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:40:38.219 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:40:38.417 6469 6469 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 13:40:40.601 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:40:40.823 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:40:44.310 6469 6469 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 13:40:48.687 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:40:48.884 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:40:49.180 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:40:50.291 6469 6469 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 13:40:52.787 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:40:53.043 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:40:54.384 6469 6469 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 13:40:57.275 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:40:57.440 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:40:59.528 6469 6469 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 13:41:02.518 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:41:02.738 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:41:02.855 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:41:08.367 6469 6469 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 13:41:11.272 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:41:11.478 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:41:11.630 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:41:12.015 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:41:12.112 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:41:15.986 6469 6469 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 13:43:07.126 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:43:07.340 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:43:07.489 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:43:07.803 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:43:08.716 6469 6469 E ViewRootImpl: sendUserActionEvent() mView returned. 05-07 13:43:15.397 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:43:15.837 6469 6469 E DecorView: mWindow.mActivityCurrentConfig is null 05-07 13:43:16.677 6469 9499 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher 05-07 13:43:16.677 6469 9499 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 6469 05-07 13:43:16.677 6469 9499 E AndroidRuntime: java.lang.Error: java.lang.Exception: HTTP error 401 05-07 13:43:16.677 6469 9499 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173) 05-07 13:43:16.677 6469 9499 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 13:43:16.677 6469 9499 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919) 05-07 13:43:16.677 6469 9499 E AndroidRuntime: Caused by: java.lang.Exception: HTTP error 401 05-07 13:43:16.677 6469 9499 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 13:43:16.677 6469 9499 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 13:43:16.677 6469 9499 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 13:43:16.677 6469 9499 E AndroidRuntime: 	... 2 more 05-07 13:43:16.683 6469 6469 E MangaController: java.io.IOException: canceled due to java.lang.Exception: HTTP error 401 05-07 13:43:16.683 6469 6469 E MangaController: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530) 05-07 13:43:16.683 6469 6469 E MangaController: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 13:43:16.683 6469 6469 E MangaController: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 13:43:16.683 6469 6469 E MangaController: 	at java.lang.Thread.run(Thread.java:919) 05-07 13:43:16.683 6469 6469 E MangaController: 	Suppressed: java.lang.Exception: HTTP error 401 05-07 13:43:16.683 6469 6469 E MangaController: 		at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 13:43:16.683 6469 6469 E MangaController: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 13:43:16.683 6469 6469 E MangaController: 		... 3 more 05-07 13:43:16.683 6469 6469 E MangaController: 05-07 13:43:16.683 6469 6469 E MangaController: java.io.IOException: canceled due to java.lang.Exception: HTTP error 401 05-07 13:43:16.683 6469 6469 E MangaController: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530) 05-07 13:43:16.683 6469 6469 E MangaController: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-07 13:43:16.683 6469 6469 E MangaController: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-07 13:43:16.683 6469 6469 E MangaController: 	at java.lang.Thread.run(Thread.java:919) 05-07 13:43:16.683 6469 6469 E MangaController: 	Suppressed: java.lang.Exception: HTTP error 401 05-07 13:43:16.683 6469 6469 E MangaController: 		at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-07 13:43:16.683 6469 6469 E MangaController: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-07 13:43:16.683 6469 6469 E MangaController: 		... 3 more 05-07 13:43:35.017 6424 6424 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent. 05-07 13:43:36.193 6424 9727 E SQLiteLog: (284) automatic index on C(manga_id) 05-07 13:43:36.193 6424 9727 E SQLiteLog: (284) automatic index on R(manga_id) 05-07 13:43:36.193 6424 9727 E SQLiteLog: (284) automatic index on C(merge_id) 05-07 13:43:36.193 6424 9727 E SQLiteLog: (284) automatic index on R(merge_id) 05-07 13:43:36.193 6424 9727 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-07 13:43:36.292 6424 9654 E gralloc : Arm Module v1.0 05-07 13:43:36.294 6424 9654 E ion : ioctl c0044901 failed with code -1: Invalid argument App version: 1.6.2 (standard, b9b5ef55a, 17) Preview build: 362 Android version: 10 (SDK 29) Android build ID: QP1A.190711.020.A315FXXU1BUA1 Device brand: samsung Device manufacturer: samsung Device name: a31 Device model: SM-A315F Device product name: a31xx

**Comment by jobobby04** [comment]
Should be fixed for the next build

**Comment by jobobby04** [comment]
Addressed with https://github.com/jobobby04/TachiyomiSY/commit/858a5e6eeea4443feaed13bbebfef5623c8d32e3
