### ISSUE TITLE
[Bug] "Tachiyomi stop responding" every few minutes

### ISSUE THREAD

**Issue by Ramzh** [jobobby04/TachiyomiSY#314]
## Device information
* Tachiyomi version: Preview r368 (d04cdd9b3)
* Android version: Anroid 11
* Device: OnePlus 7 Pro

## Steps to reproduce
1. Open Tachiyomi
2. Browse the app (library, sources, extensions etc)

### Expected behavior
No crahses should happen and normal navigation should occur

### Actual behavior
Keeps crashing with "Tachiyomi stopped responding".

## Other details
Click wait makes Tachitomi work again but few minutes after the crashed popup dissmissal, it reappears. 

[Logs](https://pastebin.com/Vatdjduy)

**Comment by jobobby04** [comment]
Likely addressed with https://github.com/jobobby04/TachiyomiSY/commit/2ec5581e8c9b0535d055f89d387882258292f090
