### ISSUE TITLE
[Bug] Anilist sometimes misidentifies titles

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#317]
## Device information
* Tachiyomi version: r370
* Android version: 11
* Device: Galaxy S10+

## Steps to reproduce
1. Open Manhwa Club
2. open Queen Bee manhwa

### Expected behavior
It should show Anilist recs

### Actual behavior
It shows MAL recs 

## Other details
This was discussed on Discord, Nvm apparently Anilist search has a hidden hentai variable

**Comment by jobobby04** [comment]
Honestly this is a Tech limitation that cant really be fixed on my end. So I am just going to close it
