### ISSUE TITLE
[Bug] <ManhuaScan update (1.2.6)> App keeps crashing when opening or downloading a chapter and loads slowly

### ISSUE THREAD

**Issue by recmsan** [jobobby04/TachiyomiSY#323]
-Device information
* Tachiyomi version: TachiyomiSY Stable 1.6.2
* Android version: 5.1

-Source information

Name: ManhuaScan
Extension version: 1.2.6

-Steps to reproduce
1. Update to the latest extension version.
2. Open or download a lately updated chapter

-Expected behavior
The Manga, Manhwa, Manhua or Media loads and progress 

-Actual behavior
TachiyomiSY app crashes

**Comment by jobobby04** [comment]
ManhuaScan has been removed
