### ISSUE TITLE
[Bug] Crash at start : biometric hardware unavailable

### ISSUE THREAD

**Issue by arthus-leroy** [jobobby04/TachiyomiSY#325]
## Device information
* Tachiyomi version: 1.6.2
* Android version: 10
* Device: Samsung Galaxy Tab A

## Steps to reproduce
Enable the biometric hardware feature
Kill the app
Try to reopen the app

### Expected behavior
The app starts normally

### Actual behavior
The app crashes at start, no way to enter the app

## Other details
This device has no hardware biometric sensor (fingerprint, etc).

A solution would be to disable this option altogether and warn people that try to allow it if no sensor is detected.

**Comment by jobobby04** [comment]
Try the main Tachiyomi app, if the issue happens there it's not a SY specific issue

**Comment by arthus-leroy** [comment]
Issue moved to the Tachiyomi github as it appears to come from the Tachiyomi app.
