### ISSUE TITLE
[Bug] filtered chapters (by scanlator) show up in reader

### ISSUE THREAD

**Issue by Efreak** [jobobby04/TachiyomiSY#326]
## Device information
```
App version: 1.6.2 (standard, ab0f5d107, 17)
Preview build: 371
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.T860XXU3CUC2
Device brand: samsung
Device manufacturer: samsung
Device name: gts6lwifi
Device model: SM-T860
Device product name: gts6lwifixx
```

## Steps to reproduce
1. Make sure *skip filtered chapters* is enabled in settings
2. Open a manga from MangaDex ([Skeleton Soldier Couldn't Protect the Dungeon](https://www.mangadex.org/manga/d993f789-e7e5-4832-92fd-37614220b427))
3. Read/mark read up until a filtered chapter or the chapter before (25-30)
4. Make sure there's a scanlator group filtered out
5. Read next chapter or tap to open a chapter
6. If you opened a chapter directly, scroll to next chapter
 
### Expected behavior
You should skip the chapter that was filtered out
 
### Actual behavior
You are now reading a chapter that you filtered out
 
## Other details
[Recording](https://gistcdn.githack.com/Efreak/dfda214d44fdec51c26dbf557adc4969/raw/b7d0b8fed856deb03f91bd96cbc73cf522573bbc/index.html)

This is a Neko/SY feature that doesn't exist in tachi stable or dev.

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/8d7aa4b6a28c1c4e70982265035e6d590a2bca20

**Comment by Efreak** [comment]
This has been fixed in preview, but a similar big exists for downloading. When tapping to download unread chapters, it downloads chairs that have been hidden by the scanlator filter. Let me know if I should post this as a new bug; I'm posting here because it seems like it might be related (I'd personally expect that the filtered list should be used everywhere--if you filter the list to only show read chapters, then downloading unread chapters should do nothing)

<details>
<summary>I'm on r421</summary>

App version: 1.7.0 (standard, c93db9909, 22, 2021-12-12T01:55Z)
Preview build: 421
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.T860XXU4CUI4
Device brand: samsung
Device manufacturer: samsung
Device name: gts6lwifi
Device model: SM-T860
Device product name: gts6lwifixx
</details>
