### ISSUE TITLE
[Bug] labels are not displayed correctly in russian locale

### ISSUE THREAD

**Issue by simakover** [jobobby04/TachiyomiSY#328]
## Device information
* Tachiyomi version: 1.6.2
* Android version: 9
* Device: Xiaomi mi mix 2s

## Steps to reproduce
1. First bug: Then on library tab, tap library button again
2. Second bug: open browser tab in nav bar

### Expected behavior
Label titles in one row

### Actual behavior
Two rows
![Screenshot_2021-05-22-15-37-39-864_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/6729515/119223826-02c36800-bb15-11eb-9fb0-b5be88dd7da7.jpg)
![Screenshot_2021-05-22-15-37-57-047_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/6729515/119223827-048d2b80-bb15-11eb-99b2-a06e0b678c80.jpg)

Im can try fix it myself, but how better to do it?

**Comment by jobobby04** [comment]
Nothing I can do about that, thats just how the tab rows handle long names

**Comment by simakover** [comment]
@jobobby04 may be change font size for rus locale?

**Comment by jobobby04** [comment]
Wouldn't be worth the work, and wouldn't be worth the upkeep
