### ISSUE TITLE
[Feature Request] <Hide Latest>

### ISSUE THREAD

**Issue by e-shl** [jobobby04/TachiyomiSY#329]
## What/Requirements

Hide the "Latest" options for:
1. "Watch" "Latest" tab and context menu
<img src="https://user-images.githubusercontent.com/35057681/119236633-f7daf880-bb51-11eb-9e58-c28686c3fe6a.JPG" width="200" /><img src="https://user-images.githubusercontent.com/35057681/119236635-f90c2580-bb51-11eb-8186-51b4c863bd73.JPG" width="200" />
2. Button "Latest" on installed source (this can hide not completely, but put it in the context menu(from screenshot above))
<img src="https://user-images.githubusercontent.com/35057681/119236760-9ff0c180-bb52-11eb-9873-cc6ed954c835.JPG" width="200" /><img src="" width="200" />

**Comment by jobobby04** [comment]
Hiding latest is already already possible, there is a option to combine latest and browse together, I dont really want to add another way

**Comment by e-shl** [comment]
Then what's with the "Latest" tab? (I have described two options)

**Comment by jobobby04** [comment]
Hiding the latest tab has been attempted, but it comes with bugs that would be really difficult to fix
