### ISSUE TITLE
[Bug] Comick.fun not loading chapters

### ISSUE THREAD

**Issue by BriggsWall** [jobobby04/TachiyomiSY#334]
## Device information
* Tachiyomi version: 1.6.2
* Android version: 10
* Device: moto g (8) play

## Steps to reproduce
1. I opened the manga
2. Appeared a message, and the chapters didn't load.

### Expected behavior
I opened the manga and be able to see the chapters and read.

### Actual behavior
A message appeared with the error, and the chapters didn't load.

## Other details
I checked the webview the chapters are working fine, the site is also working, I even logged in the site to see if it would work, but the problem remained the same. I think it's not a problem with the source, but with the the app, name of the source is "Comick.fun" version: 1.2.1
![Screenshot_20210524-103121](https://user-images.githubusercontent.com/83545586/119386317-5bba0a00-bc95-11eb-9aa2-1b5e9d6e7a6f.png)

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by jobobby04** [comment]
Already fixed in the preview builds

**Comment by BriggsWall** [comment]
Okay then. Thanks
