### ISSUE TITLE
[Bug] <crash while downloading>

### ISSUE THREAD

**Issue by dmswd** [jobobby04/TachiyomiSY#335]
## Device information
* App version: 1.6.2 (standard, 481f60005, 18, 2021-05-23T22:26Z)
Preview build: 375
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A315FXXU1BUA1
Device brand: samsung
Device manufacturer: samsung
Device name: a31
Device model: SM-A315F
Device product name: a31xx

## Steps to reproduce
1. Try downloading these
2. 
![Screenshot_20210525-095647_TachiyomiSY](https://user-images.githubusercontent.com/66433732/119461562-1c94c300-bd40-11eb-9394-8fff3f988cb5.jpg)

### Expected behavior
The app shouldn't crash

## Other details

Crash logs

05-25 09:54:00.518 16335 16335 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent. 05-25 09:54:02.477 16335 18474 E gralloc : Arm Module v1.0 05-25 09:54:02.479 16335 18474 E ion : ioctl c0044901 failed with code -1: Invalid argument 05-25 09:54:14.626 16335 16335 E DecorView: mWindow.mActivityCurrentConfig is null 05-25 09:54:14.671 16335 16335 E DecorView: mWindow.mActivityCurrentConfig is null 05-25 09:54:15.762 16335 16335 E ViewRootImpl: sendUserActionEvent() mView returned. 05-25 09:54:20.153 16335 18550 E SQLiteLog: (284) automatic index on C(manga_id) 05-25 09:54:20.153 16335 18550 E SQLiteLog: (284) automatic index on R(manga_id) 05-25 09:54:20.153 16335 18550 E SQLiteLog: (284) automatic index on C(merge_id) 05-25 09:54:20.153 16335 18550 E SQLiteLog: (284) automatic index on R(merge_id) 05-25 09:54:20.153 16335 18550 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-8 05-25 09:54:37.866 16335 18554 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 16335 05-25 09:54:37.866 16335 18554 E AndroidRuntime: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling. 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:7) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: Caused by: rx.exceptions.OnErrorNotImplementedException: java.lang.Exception: Failed to bypass Cloudflare 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:2) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:1) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:1) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:2) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:4) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:4) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:5) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:7) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.Subscriber.setProducer(Subscriber.java:7) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.Subscriber.setProducer(Subscriber.java:6) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:1) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.Subscriber.setProducer(Subscriber.java:6) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:5) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:1) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.Observable.unsafeSubscribe(Observable.java:2) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.Observable.unsafeSubscribe(Observable.java:2) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.Observable.subscribe(Observable.java:25) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.Observable.subscribe(Observable.java:7) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at eu.kanade.tachiyomi.multisrc.madara.Madara.fetchPageList(Madara.kt:616) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:10) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:1) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.Observable.unsafeSubscribe(Observable.java:2) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	... 6 more 05-25 09:54:37.866 16335 18554 E AndroidRuntime: Caused by: java.io.IOException: java.lang.Exception: Failed to bypass Cloudflare 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:16) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:12) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:8) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:12) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:16) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:5) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:2) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	... 29 more 05-25 09:54:37.866 16335 18554 E AndroidRuntime: Caused by: java.lang.Exception: Failed to bypass Cloudflare 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.resolveWithWebView(CloudflareInterceptor.kt:21) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:14) 05-25 09:54:37.866 16335 18554 E AndroidRuntime: 	... 35 more 05-25 09:54:41.113 16488 16488 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent. 05-25 09:54:42.331 16488 18815 E SQLiteLog: (284) automatic index on C(manga_id) 05-25 09:54:42.331 16488 18815 E SQLiteLog: (284) automatic index on R(manga_id) 05-25 09:54:42.331 16488 18815 E SQLiteLog: (284) automatic index on C(merge_id) 05-25 09:54:42.331 16488 18815 E SQLiteLog: (284) automatic index on R(merge_id) 05-25 09:54:42.332 16488 18815 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-25 09:54:42.545 16488 18784 E gralloc : Arm Module v1.0 05-25 09:54:42.547 16488 18784 E ion : ioctl c0044901 failed with code -1: Invalid argument App version: 1.6.2 (standard, 481f60005, 18, 2021-05-23T22:26Z) Preview build: 375 Android version: 10 (SDK 29) Android build ID: QP1A.190711.020.A315FXXU1BUA1 Device brand: samsung Device manufacturer: samsung Device name: a31 Device model: SM-A315F Device product name: a31xx

Note it crashes either on an internet connection or a wi file connection 
Another note
It seems the combination above causes the crash
But if I download separately from each source nothing happens

**Comment by jobobby04** [comment]
Its a source issue, SY cant do anything about that, for some reason the source has code which throws a exception inside an interceptor, which in turn crashes the app
