### ISSUE TITLE
[Feature Request] <Compact manga controller>

### ISSUE THREAD

**Issue by e-shl** [jobobby04/TachiyomiSY#337]
## What/Requirements

Change manga controller to compact and beautiful from j2k
<img src="https://user-images.githubusercontent.com/35057681/119596892-7a391600-bdf9-11eb-9fab-0ef0c7b720af.JPG" width="300" />=><img src="https://user-images.githubusercontent.com/35057681/119596900-7c02d980-bdf9-11eb-9073-c19da1a43af1.JPG" width="300" />

**Comment by jobobby04** [comment]
Im not planning on changing the UI in SY, way too much upkeep, so its not worth it, and that is pretty much the old design of Tachi stable as well, so main Tachi wouldn't go back to it
