### ISSUE TITLE
[Bug] Download say complete, but it  paused with error

### ISSUE THREAD

**Issue by akzn** [jobobby04/TachiyomiSY#338]
## Device information
* Tachiyomi version: preview r375
* Android version: oreo
* Device: redmi note 9

## Steps to reproduce
1. Source :  mangadex
2. title : Fuan no Tane
3. download chapter 4

### Expected behavior
notification complete if download actually complete, or notification error if there are errors happened

### Actual behavior
notification complete, but download is paused and manga page have download error icon on said chapter

### Other detail

![IMG_20210528_133339.jpg](https://user-images.githubusercontent.com/40191741/119941164-6dafeb80-bfba-11eb-9318-068d972ef372.jpg)

![119941181-73a5cc80-bfba-11eb-818d-71fc1f6f726d](https://user-images.githubusercontent.com/40191741/119941816-49a0da00-bfbb-11eb-9aa0-b058da94fe91.jpg)

![Screenshot_2021-05-28-13-32-30-882_eu.kanade.tachiyomi.sy.jpg](https://user-images.githubusercontent.com/40191741/119941191-77395380-bfba-11eb-8245-e62461b9a2f4.jpg)

**Comment by jobobby04** [comment]
Main Tachi issue, SY doesnt edit this
