### ISSUE TITLE
[Bug] Extension settings make SY crash. Text Input commit from upstream needs to be merged?

### ISSUE THREAD

**Issue by crisalis2** [jobobby04/TachiyomiSY#34]
Since this: https://github.com/inorichi/tachiyomi-extensions/commit/14e644d358be7c66057bd7ef5b49bfc87f6e1f09 , the new version of the Madokami extension doesn't work properly in SY only. When you go to Madokami's settings, SY crashes.

Maybe it's because this commit from upstream isn't merged here yet: https://github.com/inorichi/tachiyomi/pull/3261/commits .

I use SY's latest apk from the preview builds.

**Comment by jobobby04** [comment]
Can you try on the latest preview build of SY?

**Comment by crisalis2** [comment]
It still crashes for me. If you install the Madokami extension, go to its settings and try to set a username or password, doesn't the app crash for you (you shouldn't need to actually type anything for the crash to happen)?

**Comment by jobobby04** [comment]
Not really, I have no issues with the extension username and password boxes

**Comment by jobobby04** [comment]
I am going to check a few things, I may find the issue

**Comment by crisalis2** [comment]
I tried a clean (cleanest no root allows (?)) install of everything with no luck.

>I am going to check a few things, I may find the issue

Thanks.

One thing I notice is I see different menus in Tachiyomi and TachiyomiSY inside the extension's details.
Here's Tachiyomi:
![20200609_022859](https://user-images.githubusercontent.com/65630147/84093155-b6614400-a9f9-11ea-9e6c-88a4c7347c90.png)
Here's TachiyomiSY:
![20200609_022919](https://user-images.githubusercontent.com/65630147/84093174-c5e08d00-a9f9-11ea-9600-daff32d53b48.png)
Inside this settings button, I can access the username and password option if I use a previous version of the Madokami extension (1.2.2), but it crashes for newer versions (1.2.3 and the 1.2.4 newer one that was released a while ago unrelated to all of this).

**Comment by crisalis2** [comment]
> Its a release only issue, I think I know how to fix it then

Oh, good to hear, thanks.

**Comment by jobobby04** [comment]
After a lot of fumbling, this is now fixed in https://github.com/jobobby04/TachiyomiSY/commit/fdc2b37addc54cc8556c05e5b0780e80fb539147

**Comment by crisalis2** [comment]
Thanks!
