### ISSUE TITLE
[Bug] Read chapters not registering as read 

### ISSUE THREAD

**Issue by AwkwardOne** [jobobby04/TachiyomiSY#340]
## Device information
* Tachiyomi version: Tachiyomi SY Preview Built 376
* Android version: 11
* Device: Samsung Galaxy S7+

## Steps to reproduce
1. Read a chapter 
2. Go to the next chapter 

### Expected behavior
The chapter gets grayed out  and is seen as read 
![Screenshot_20210529-001506_TachiyomiSY](https://user-images.githubusercontent.com/12501958/120046664-f5c1df80-c012-11eb-8975-95bc4a31fd11.jpg)

### Actual behavior
It didn't do that, instead it shows which page you were on.  
![Screenshot_20210528-235622_TachiyomiSY](https://user-images.githubusercontent.com/12501958/120046586-ca3ef500-c012-11eb-86d3-974d7b390a48.jpg)

## Other details
Additional details and attachments.

I'm using landscape mode dual pages setup which is probably the cause.

**Comment by jobobby04** [comment]
Should be addressed by https://github.com/jobobby04/TachiyomiSY/commit/114ba42af7dfa11d54dc903b0f9dd7538b3c2d48

**Comment by AwkwardOne** [comment]
> Should be addressed by [114ba42](https://github.com/jobobby04/TachiyomiSY/commit/114ba42af7dfa11d54dc903b0f9dd7538b3c2d48)

This one was fixed in the preview builtThat came a few days later, SY was doing Allot of builts for preview Then
