### ISSUE TITLE
[Feature Request] Allow Changing page layout on webtoons

### ISSUE THREAD

**Issue by jopejoe1** [jobobby04/TachiyomiSY#342]
## Why/User Benefit/User Problem
Now that some Madara sites have started splitting images in half this would help in reading those webtoons
Examples:
- https://manhuaus.com/manga/starting-from-today-ill-work-as-a-city-lord/chapter-305/
- https://comickiba.com/manga/cultivator-against-hero-society/chapter-87/

## What/Requirements
Having the page layout button available for webtoons or some other methods of having 2 images next to each other for webtoons

**Comment by jobobby04** [comment]
Well this didn't really last, not worth making this for only a few chapters that released like this 😄
