### ISSUE TITLE
[Bug] <"...Move to More tab" options swapped>

### ISSUE THREAD

**Issue by xicra** [jobobby04/TachiyomiSY#346]
Options "Move Update button to the More tab" and "Move History button to the More tab" are swapped on the preview release.

---

## Device information
* Tachiyomi version: Preview r379
* Android version: 10
* Device: Sharp Aquos R2

## Steps to reproduce
1. Go to settings>General
2. Toggle "Move History button to the More tab"

### Expected behavior
The history button would be located on the more tab.

### Actual behavior
The history button stills on the main bar but the update button is now on the more tab.

## Other details
The same Happens the opposite way.

**Comment by jobobby04** [comment]
Fixed in the latest build 👍
