### ISSUE TITLE
[Bug] Page transition not smooth with background color set to automatic when left/right tapping

### ISSUE THREAD

**Issue by Oblongmoon7808** [jobobby04/TachiyomiSY#349]
## Device information
* Tachiyomi version: 1.7.0 and preview build r380
* Android version: 10
* Device: Huawei mate 10 pro (6Gb of RAM)

## Steps to reproduce
1. Open a chapter
2. Set background color to automatic
3. Left tap or right tap on the screen to transition to the previous/next page

### Expected behavior
Smooth transition

### Actual behavior
Not smooth transition

## Other details
Transition is smooth when swiping. 
Issue is not fixed when downloading the chapter

**Comment by joseph619** [comment]
This doesn't seem like a SY specific issue, can you try this on main app 0.11.1?

**Comment by Oblongmoon7808** [comment]
This problem does indeed also occur in the main app. However, I'm almost sure this didn't happen in the previous version of tachiyomi SY. I cannot confirm this because when I try to install the apk of an older version, it gives me the error: "App not installed". 
TachiyomiJ2K, which also has the automatic background option (it is called "smart(based on page)"), doesn't suffer from this problem.

**Comment by jobobby04** [comment]
So its not a SY specific issue, open a issue inside the main Tachi repo.
