### ISSUE TITLE
[Bug] tachiyomi keep crashing at start 

### ISSUE THREAD

**Issue by CaptainHalflife** [jobobby04/TachiyomiSY#351]
## Device information
* Tachiyomi version: 1.7.0
* Android version: 11
* Device: samsung note 10 lite

## Steps to reproduce
1. use the app normally

### Expected behavior
The app work 
### Actual behavior

Get a random crash and after the app keep crashing non stop
## Other details
I think its because of android 11 as on my other phone with android 8.1 it work fine. I cant get the crash log as the app don't work at all.

my friend got the same problem and he is also on android 11.

**Comment by jobobby04** [comment]
Main tachi issue https://github.com/tachiyomiorg/tachiyomi/issues/5364
