### ISSUE TITLE
[Bug] <mangadex random feature broken>

### ISSUE THREAD

**Issue by Bmswad1** [jobobby04/TachiyomiSY#352]
## Device information
App version: 1.7.0 (standard, d5638c620, 19, 2021-06-10T21:24Z)
Preview build: 383
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.A315FXXU1CUD4
Device brand: samsung
Device manufacturer: samsung
Device name: a31
Device model: SM-A315F
Device product name: a31xx

## Source information
- Name: mangadex
- Extension version: 1.2.119

## Steps to reproduce
1. Open the filter sheet
2. Press the random option

### Expected behavior
A manga should Appear

### Actual behavior
It says no results found

## Other details
Noticed that when using this feature
The ID appears in the search field missing the id:
If I add id: before the manga id it works

**Comment by jobobby04** [comment]
Will be fixed in the next build

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/e3fd17f55012403874cf98c6de5df7f57daae8c6
