### ISSUE TITLE
[Bug] Double Page Reader Hiding Pages

### ISSUE THREAD

**Issue by AwkwardOne** [jobobby04/TachiyomiSY#353]
## Device information
* Tachiyomi version: App version: 1.7.0  Preview build: 383
* Android version: 11
* Device: Samsung Galaxy Tab 7+
* Manga: Hellsing (although this works with any manga with a double spread)
## Steps to reproduce
1. Go to a double spread page (Can't be the last page of the chapter) 
2. Move to the next page 

### Expected behavior
It goes from the one page to the next page by page number, without skipping pages.

### Actual behavior
So what happens is the following: in this screenshot you can see that the doublespread has two page numbers at the bottom. (115-116)
![Screenshot_20210614-014358_TachiyomiSY](https://user-images.githubusercontent.com/12501958/121825683-172df700-ccb4-11eb-9c42-2f236ae3d9f2.jpg)
When I swipe to the next page this is what appears: notice the page number went up. (117-118)
![Screenshot_20210614-014408_TachiyomiSY](https://user-images.githubusercontent.com/12501958/121825682-16956080-ccb4-11eb-8a6c-3728728fb689.jpg)
But here's the problem there was a page skipped with this, the double spread only counts as 1 page  (115) and therefore we skipped a page (116). 
When saving combined pages on page (115-116) we get the following: here we see the page that was skipped (116) allong with the doublespead (115).   
![Hellsing - v06 (2005) (Digital) (Lovag-Empire) - 115-116](https://user-images.githubusercontent.com/12501958/121825678-139a7000-ccb4-11eb-920f-73280afd123e.jpg) 

I pressed this ![SmartSelect_20210614-021555_TachiyomiSY](https://user-images.githubusercontent.com/12501958/121826127-80166e80-ccb6-11eb-8b0d-2a3232f163f0.jpg) icon to make the pages shift so the double spread (115) is on it's own page, the result is what we wanted. 
![Screenshot_20210614-014500_TachiyomiSY](https://user-images.githubusercontent.com/12501958/121825681-15fcca00-ccb4-11eb-9a70-719ecd372d0a.jpg)
![Screenshot_20210614-014521_TachiyomiSY](https://user-images.githubusercontent.com/12501958/121825680-14cb9d00-ccb4-11eb-9e7b-4a1db2c1f8d2.jpg)

**Comment by jobobby04** [comment]
Can you try to reproduce this on the latest build?

**Comment by Therealcrazyone** [comment]
> Can you try to reproduce this on the latest build?

I tried doing it with the same manga, the same pages and it's still the same as it was above. In the meantime I have noticed that manga from the VIZ media extenction doesn't have this issue, but that's maybe how it's uploaded or something?

**Comment by jobobby04** [comment]
I believe this is fixed, let me know if it still happens
