### ISSUE TITLE
[Feature Request] Browse sources: Option to don't show default/latest gallery entries before you make a search

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#355]
## Why/User Benefit/User Problem
When I browse a source, I generally want to search for specific galleries (and not be distracted by anything else). But before I have the chance to type my search, the latest galleries already appear on the source screen, and many times I end up being distracted by these unrelated galleries (check them out, add them to my library, etc.).
I'd like to have the option to change the default behavior of the Browse source screen, as described below. 

## What/Requirements
The app could have a Browse setting to not show (hide) galleries when not searching for something.
When the setting is enabled, if you browse a source, it wouldn't show ANY gallery (latest galleries, the ones that are shown by default whenever you browse a source) before I make a search. It would only show galleries AFTER I make a search (the galleries I want to see).

**Comment by joseph619** [comment]
I don't see how this is useful to anybody else, sounds extremely niche and just adding more unnecessary toggles.

**Comment by jobobby04** [comment]
Thats true, not worth the work and upkeep
