### ISSUE TITLE
[Bug] Screen becomes black if device orientation is changed during EH Favorites sync

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#357]
## Device information
* Tachiyomi version: Preview r384
* Android version: 7.1.1
* Device: Samsung Galaxy J2 Pro (SM-J250M)

## Steps to reproduce
1. Start "Sync EH favorites"
2. During or after the "Calculating remote changes" step of the sync, rotate the mobile device to change orientation (from Portrait to Landscape, or vice-versa).

### Expected behavior
The app screen should be refreshed and rotated to the new device orientation, as usual.

### Actual behavior
The app screen becomes black. Even if I rotate my device back to Portrait, the app screen is still black.

**Comment by jobobby04** [comment]
Misclick

**Comment by lucky777709** [comment]
Still happens in TachiyomiSY Preview r455.
A workaround is to disable the Auto-rotation feature on the smartphone before starting an EH sync (but sometimes the user may forget to do that step...)

**Comment by jobobby04** [comment]
Shouldnt happen anymore in the latest preview builds
