### ISSUE TITLE
[Feature Request] Add a toggle to activate/deactivate tablet ui instead of using smallest width

### ISSUE THREAD

**Issue by MmyGgithubAaccount** [jobobby04/TachiyomiSY#360]
## Why/User Benefit/User Problem
This helps users like me with smallest width below 720dp who want tablet ui, and it also helps users above 720dp smallest width who don't want tablet ui

## What/Requirements
A toggle in settings which overrides the 720dp check for tablet ui. If it's on, switch to tablet ui regardless of smallest width and vice versa

**Comment by jobobby04** [comment]
I wont be messing with the tablet ui, this is all on main tachi

**Comment by MmyGgithubAaccount** [comment]
You don't need to mess with the ui/layout of app for this. Just add a bypass for this check
https://github.com/jobobby04/TachiyomiSY/blob/4f9eb19eada7222a1bebe3d390fba98507479793/app/src/main/java/eu/kanade/tachiyomi/util/system/ContextExtensions.kt#L277

So something like
```
if (bypass condition)
    return true
else
    current line 277
```
