### ISSUE TITLE
[Bug] Updates not showing in update tab under "todays" heading

### ISSUE THREAD

**Issue by buggyde** [jobobby04/TachiyomiSY#362]
## Device information
* Tachiyomi version: 1.7.0
* Android version: 10
* Device: Samsung SM-T835 

## Steps to reproduce
1.  Switch to updates Tab
2.  Click refreash/update

### Expected behavior
List of updated chapters to appear under "todays" tag

### Actual behavior
Manga's updated (you can see the new chapters when you open them), but the update list does not update. This was working morning but all early morning udpates have now disappeared and no  further updates are showing. 

## Other details
This happens to all extentions I have. I have also tried this on bluestacks and it happens there as well, I have also tried this on my mobile device and same issue. 

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by jobobby04** [comment]
Try this on main Tachi, I dont believe this is SY specific

**Comment by jobobby04** [comment]
Closing due to no updates
