### ISSUE TITLE
[Bug] manga title word dissapear 

### ISSUE THREAD

**Issue by Riztard** [jobobby04/TachiyomiSY#369]
## Device information
* Tachiyomi version: 0.11.1 r3472
* Android version: 10
* Device: redmi 8

## Steps to reproduce
open manga with long title
go to potrait mode
go to landscape mode

## Expected behavior
title should be same or removed from the end/last part

## Actual behavior
some title/word in the begining dissapear

## Other details
didnt get fixed in sy
https://github.com/tachiyomiorg/tachiyomi/issues/5309

**Comment by jobobby04** [comment]
Probably addressed by https://github.com/jobobby04/TachiyomiSY/commit/c9438d55e09e4048094596ac548b22828c80abf2
