### ISSUE TITLE
[Feature Request] Add resume button to thumbnails in Library

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#37]
### Why/User Benefit/User Problem
This will allow users to resume reading manga directly from Library without requiring to visit Chapter list or History tab.

### What/Requirements
Yoink the feature from J2K, and also enable it by default as it's an important QoL. Add an option to disable it in case reader doesn't like it.

**Comment by crusaside** [comment]
good one

**Comment by jobobby04** [comment]
Added with https://github.com/jobobby04/TachiyomiSY/commit/2f98dd2046bf7788e972a59f8db965211c2984fc
