### ISSUE TITLE
[Bug] Previous Chapter Button Broken

### ISSUE THREAD

**Issue by 98ne** [jobobby04/TachiyomiSY#370]
## Device information
* Tachiyomi version: r384 + v1.7.0 
* Android version: 8.0
* Device: LG V20 (H918)

## Steps to reproduce
1. Load a chapter.
2. Tap the Previous Chapter button.

### Expected behavior
Loads previous chapter.

### Actual behavior
Doesn't load previous chapter.

## Other details
Button doesn't work when on the first two pages of a chapter.
Using the Chapters button shows similar behavior.

https://streamable.com/3tijyo

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/33c48412beb78be98826c5f86a0e099d012697ca
