### ISSUE TITLE
bar covers part of the description when collapsed

### ISSUE THREAD

**Issue by Mugen007** [jobobby04/TachiyomiSY#371]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/v1.7.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r385

### Android version

Android 9

### Device

Huawei Y6 Pro

### Steps to reproduce

1. open a manga page

### Expected behavior

I'm able to see a full collapsed description

### Actual behavior

A random bar blocks part of the text

### Other details

![Screenshot_20210628_010654](https://user-images.githubusercontent.com/80591855/123553381-74926f80-d7ad-11eb-8822-fdabe83fcee5.jpg)
![Screenshot_20210628_010608](https://user-images.githubusercontent.com/80591855/123553383-778d6000-d7ad-11eb-9641-cd60c0937025.jpg)
(sidenote: there's another bug where the 'More' button merges with the text)

**Comment by jobobby04** [comment]
Addressed with https://github.com/jobobby04/TachiyomiSY/commit/417c3459462353896b1c893ce5b25c517088c7d9
