### ISSUE TITLE
[Bug]The navigation bar cuts off

### ISSUE THREAD

**Issue by Poggies01** [jobobby04/TachiyomiSY#373]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/v1.7.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r387

### Android version

Android 10

### Device

Realme 3 

### Steps to reproduce

Open tachi sy
Look at the bottom navigation bar
Enable it
Upon enabling the phone's navigation bar cuts off tachi's bar

### Expected behavior

The window size should readjust

### Actual behavior

The navigation bar cuts off

### Other details

![IMG_20210630_130604](https://user-images.githubusercontent.com/86711105/123925037-272e2200-d9a8-11eb-83d9-b7c562f32091.jpg)
![IMG_20210630_130615](https://user-images.githubusercontent.com/86711105/123925060-2ac1a900-d9a8-11eb-8329-7a06f744e7fe.jpg)

**Comment by Poggies01** [comment]
I also tested it in r384 and r385, the bug was there.
Main tachi(tachiyomi az) and sy stable version didnt have the bug

**Comment by jobobby04** [comment]
Did you confuse main tachi and TachiyomiAZ?

**Comment by Poggies01** [comment]
> TachiyomiAZ

Yupppp

**Comment by jobobby04** [comment]
Does this happen on the real main tachi? Not AZ fyi

**Comment by Poggies01** [comment]
> You tested the preview version listed on this page? https://tachiyomi.org/download/

Nonono i tested tachi sy preview versions, sy stable and main tachi stable. I didnt check main tachi preview.
Should i check it now?

**Comment by jobobby04** [comment]
Yes, SY preview is based on Tachi preview

**Comment by Poggies01** [comment]
> Yes, SY preview is based on Tachi preview

Just checked. I can't replicate the bug on tachi preview

**Comment by jobobby04** [comment]
Can you try on the latest build?

**Comment by Poggies01** [comment]
> Can you try on the latest build?

Done
Can't replicate the bug anymore.
Yay

**Comment by jobobby04** [comment]
Awesome, ill just close this then
