### ISSUE TITLE
Main build or latest Preview build still crash in Library

### ISSUE THREAD

**Issue by overallbit9** [jobobby04/TachiyomiSY#374]
### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/v1.7.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

1.7.0 and Build 387

### Android version

Android 9

### Device

Galaxy A10

### Steps to reproduce

1. When trying to open TachiyomiSY crash
2. Clicking and holding the app icon and select other options instead Library the app runs normal, at the moment you click in Library it crash.

### Expected behavior

App runs without any problems.

### Actual behavior

The app crash when trying to run it, Clicking and holding the app icon and select other options instead Library the app runs normal, at the moment you click in Library it crash.

**Comment by jobobby04** [comment]
Can you try to get a crash log from Settings -> Advanced -> Dump crash log?

**Comment by VictoorH** [comment]
Hello @jobobby04 do you remember me? I posted the same issue in 2020 and in this update I have the same problem just like @overallbit9 again.
Im still using Galaxy S4 Mini and the same Custom ROM Android 10. Please check my log too.
[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/6749890/tachiyomi_crash_logs.txt)

**Comment by jobobby04** [comment]
Did you update from a really old version? It looks like the migration didnt run for you, use the shortcuts and go to Settings -> Advanced -> Debug Menu -> Force upgrade migration

**Comment by VictoorH** [comment]
Hello, yes updated from an older version XD
This option is suposed to reinstall the app? for some reason it just show a message without information (check the pic) but  the app works after I clicked in this option and restarted my phone.
When I click in Force upgrade I just get this message from the pic.
![Screenshot_20210701-154940_TachiyomiSY](https://user-images.githubusercontent.com/29027747/124192354-891b8400-da9b-11eb-8d5b-eabb27f53688.png)

**Comment by overallbit9** [comment]
Hello Im sorry for the trouble... after I made this post I formatted my phone and it works now... you can close.
Im really sorry XD

**Comment by jobobby04** [comment]
> 
> 
> Hello, yes updated from an older version XD
> This option is suposed to reinstall the app? for some reason it just show a message without information (check the pic) but the app works after I clicked in this option and restarted my phone.
> When I click in Force upgrade I just get this message from the pic.
> ![Screenshot_20210701-154940_TachiyomiSY](https://user-images.githubusercontent.com/29027747/124192354-891b8400-da9b-11eb-8d5b-eabb27f53688.png)

That means it succeed, its not supposed to update the app or anything, it just runs the migrations that are used to migrate old data to new, and that menu means it succeed, now try going to your library.
