### ISSUE TITLE
'set as default' in chapter sorting crashes app

### ISSUE THREAD

**Issue by K3end0** [jobobby04/TachiyomiSY#378]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/1.7.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

1.7.0

### Android version

Android 11

### Device

Samsung A51

### Steps to reproduce

1. Click on a manga
2. Enter submenu and head to 'sort' category
3. Adjust current settings (crash occurs no matter what you chose, By Source, By Upload Date, By Chapter Number all crash)
4. Press menu and set as default, click tick box for 'also apply to all manga'

### Expected behavior

App should apply new chapter sort settings to all manga

### Actual behavior

App freezes and then crashes 

### Crash logs

--------- beginning of system
--------- beginning of main
--------- beginning of crash
07-07 23:37:16.196 31985 31985 E AndroidRuntime: FATAL EXCEPTION: main
07-07 23:37:16.196 31985 31985 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 31985
07-07 23:37:16.196 31985 31985 E AndroidRuntime: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = eu.kanade.tachiyomi.data.database.models.LibraryManga)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeSerializable(Parcel.java:2125)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1895)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1056)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1813)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1056)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1813)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1056)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1813)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeList(Parcel.java:1104)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1844)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1056)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1813)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1056)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1813)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4952)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: Caused by: java.io.NotSerializableException: eu.kanade.tachiyomi.data.library.CustomMangaManager
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	at android.os.Parcel.writeSerializable(Parcel.java:2120)
07-07 23:37:16.196 31985 31985 E AndroidRuntime: 	... 40 more
07-07 23:37:17.967  7615  7615 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
07-07 23:37:25.670  7615  7726 E SQLiteLog: (284) automatic index on C(manga_id)
07-07 23:37:25.670  7615  7726 E SQLiteLog: (284) automatic index on R(manga_id)
07-07 23:37:25.670  7615  7726 E SQLiteLog: (284) automatic index on C(merge_id)
07-07 23:37:25.670  7615  7726 E SQLiteLog: (284) automatic index on R(merge_id)
07-07 23:37:25.670  7615  7726 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-07 23:48:07.632 16151 16151 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
07-07 23:48:08.840 16151 17658 E SQLiteLog: (284) automatic index on C(manga_id)
07-07 23:48:08.840 16151 17658 E SQLiteLog: (284) automatic index on R(manga_id)
07-07 23:48:08.840 16151 17658 E SQLiteLog: (284) automatic index on C(merge_id)
07-07 23:48:08.840 16151 17658 E SQLiteLog: (284) automatic index on R(merge_id)
07-07 23:48:08.840 16151 17658 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-07 23:51:24.011 17394 17394 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
07-07 23:51:24.781 17394 17394 E SQLiteLog: (539) recovered 4739 pages from /data/user/0/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-journal
07-07 23:51:25.473 17394 19969 E SQLiteLog: (284) automatic index on C(manga_id)
07-07 23:51:25.473 17394 19969 E SQLiteLog: (284) automatic index on R(manga_id)
07-07 23:51:25.473 17394 19969 E SQLiteLog: (284) automatic index on C(merge_id)
07-07 23:51:25.474 17394 19969 E SQLiteLog: (284) automatic index on R(merge_id)
07-07 23:51:25.474 17394 19969 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: FATAL EXCEPTION: main
07-07 23:54:37.900 17394 17394 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 17394
07-07 23:54:37.900 17394 17394 E AndroidRuntime: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = eu.kanade.tachiyomi.data.database.models.LibraryManga)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeSerializable(Parcel.java:2125)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1895)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1056)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1813)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1056)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1813)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1056)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1813)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeList(Parcel.java:1104)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1844)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1056)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1813)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1056)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:1813)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4952)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: Caused by: java.io.NotSerializableException: eu.kanade.tachiyomi.data.library.CustomMangaManager
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	at android.os.Parcel.writeSerializable(Parcel.java:2120)
07-07 23:54:37.900 17394 17394 E AndroidRuntime: 	... 40 more
07-07 23:54:39.544 22159 22159 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
07-07 23:54:41.157 22159 22159 E SQLiteLog: (284) automatic index on C(manga_id)
07-07 23:54:41.157 22159 22159 E SQLiteLog: (284) automatic index on R(manga_id)
07-07 23:54:41.157 22159 22159 E SQLiteLog: (284) automatic index on C(merge_id)
07-07 23:54:41.157 22159 22159 E SQLiteLog: (284) automatic index on R(merge_id)
07-07 23:54:41.157 22159 22159 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-07 23:56:01.775 17751 17751 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
07-07 23:56:02.790 17751 17751 E SQLiteLog: (539) recovered 4739 pages from /data/user/0/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-journal
07-07 23:56:02.792 17751 17751 E SQLiteLog: (284) automatic index on C(manga_id)
07-07 23:56:02.792 17751 17751 E SQLiteLog: (284) automatic index on R(manga_id)
07-07 23:56:02.792 17751 17751 E SQLiteLog: (284) automatic index on C(merge_id)
07-07 23:56:02.793 17751 17751 E SQLiteLog: (284) automatic index on R(merge_id)
07-07 23:56:02.793 17751 17751 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 1.7.0 (standard, 51a1092, 19, 2021-06-02T00:51Z)
Preview build: 0
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.A515FXXU4EUD7
Device brand: samsung
Device manufacturer: samsung
Device name: a51
Device model: SM-A515F
Device product name: a51nseea

**Comment by jobobby04** [comment]
Main tachi issue, I'll pull the fix to preview when I get to my computer
