### ISSUE TITLE
Library update is stuck

### ISSUE THREAD

**Issue by dmswd** [jobobby04/TachiyomiSY#381]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/1.7.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r393

### Android version

Android 11

### Device

Samsung galaxy a31

### Steps to reproduce

Just update the library

### Expected behavior

The update should complete

### Actual behavior

The update is stuck

### Other details

![Screenshot_20210713-023323_TachiyomiSY](https://user-images.githubusercontent.com/66433732/125373025-ae09d400-e384-11eb-8d03-9b29586d161a.jpg)
![Screenshot_20210713-024210_TachiyomiSY](https://user-images.githubusercontent.com/66433732/125373030-af3b0100-e384-11eb-8bc5-6fcc5661f8ff.jpg)
This is what happens

**Comment by jobobby04** [comment]
Source?

**Comment by dmswd** [comment]
Mainly mangadex and readm and mangabat
A happy couple >> mangadex
Reincarnator >> readm
Ori of the dragon >> mangadex

**Comment by jobobby04** [comment]
Wouldnt be a SY issue then. Its probably a main Tachi issue

**Comment by dmswd** [comment]
No i think it isn't as I used a backup that I just made
And restored it in main tachi
And it updated normally

**Comment by dmswd** [comment]
After clearing the app data and restoring from a backup I just created 
the problem disappeared
I think the library got corrupted at some point
