### ISSUE TITLE
Add option to remove latest tab

### ISSUE THREAD

**Issue by Safuez** [jobobby04/TachiyomiSY#384]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/1.7.0)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

![Screenshot_20210716-192526137](https://user-images.githubusercontent.com/81817527/125948533-f6118147-8b96-4c12-84c3-4afe8c3d66de.jpg)

**Comment by jobobby04** [comment]
Has been denied before
