### ISSUE TITLE
Resume FAB shows after clicking the cover although all chapters was mark as read

### ISSUE THREAD

**Issue by CVIUS** [jobobby04/TachiyomiSY#387]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/1.7.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

preview r399

### Android version

Android 11

### Device

Redmi Note 7

### Steps to reproduce

Open TachiyomiSY,  open any manga in library, mark all as read, click the cover

### Expected behavior

resume fab should not appear because all chapter was mark as read

### Actual behavior

resume fab appears although all chapter was mark as read

### Other details

I already tried to reproduce this bug on Tachiyomi Vanilla version r3606, but it seems it is only present in TachiyomiSY r399.

**Comment by jobobby04** [comment]
Addressed with https://github.com/jobobby04/TachiyomiSY/commit/1699c2ed67586885f032dcafaa940f23544bf923
