### ISSUE TITLE
Sy preview : Loading animation not shown

### ISSUE THREAD

**Issue by Safuez** [jobobby04/TachiyomiSY#388]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/1.7.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

R399

### Android version

Android 10

### Device

Aosp rom

### Steps to reproduce

Open one chapter in any manga

### Expected behavior

There's should appear loading animation

### Actual behavior

Loading animation not shown

### Other details

https://user-images.githubusercontent.com/81817527/126860788-93122ae3-b2a0-41f1-90df-87480dfd7cab.mp4

**Comment by jobobby04** [comment]
Main tachi is doing weird stuff with the loading animations
