### ISSUE TITLE
[Duplicate manga find Feature]

### ISSUE THREAD

**Issue by mirdolon1** [jobobby04/TachiyomiSY#389]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/1.7.0)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Please add a feature so that i can find duplicate Manga, Manhua files in my library. It gets harder to keep track of duplicate files in your library when you have  400 to 500 manga in your App.

**Comment by jobobby04** [comment]
I'm going to have to say no to this, it has a very small use case and it's not something I am interested in adding.
