### ISSUE TITLE
[Feature Request] Logo

### ISSUE THREAD

**Issue by HaraDesu** [jobobby04/TachiyomiSY#39]
I am somewhat designer, I want to contribute to this project by presenting the logo for free.

![Untitled-s3](https://user-images.githubusercontent.com/32463794/84918580-fa83d100-b0ea-11ea-98f3-64a3cd22598d.png)

please tell me if you are interested!

**Comment by da123rrell** [comment]
PLEASE CHANGE THE ICON I BEG YOU

**Comment by jobobby04** [comment]
Im not too interested in a icon right now, but I may be in the future, thanks for the offer.

If you(or anyone) is interested, my requirements are this
- Must be a SVG or a Android Vector, created in a software like Adobe Illustrator(or you can use a another software that does vector based images)
- Inside a circle outline like regular Tachiyomi, I will be scaling it into the current icon where the SY currently is, but colours are your choice
- Possibly a snake in the middle of the circle, but I am open to ideas

**Comment by crisalis2** [comment]
> Possibly a snake in the middle of the circle, but I am open to ideas
Well, just an idea. Maybe you want the Tachiyomi logo but with the kanji for snake (蛇 hebi) instead of the kanji for tachi (立). You could even name the app Hebiyomi 😂

**Comment by afterdelight** [comment]
hebiyomi with snake logo is better i think. the circle is a bad idea in my opinion, it will makes the snake logo small.

**Comment by jobobby04** [comment]
Addressed with https://github.com/jobobby04/TachiyomiSY/commit/2b12fa154c30987debf55f9c36475609ef3c0eb5

**Comment by crisalis2** [comment]
The new logo is great!

**Comment by afterdelight** [comment]
thanks for the new logo! appreciate it :))

**Comment by jobobby04** [comment]
New logo is out 👍
