### ISSUE TITLE
Wrong Notification

### ISSUE THREAD

**Issue by CoffeeDrinker01** [jobobby04/TachiyomiSY#390]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/1.7.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

SY Preview r400

### Android version

Android 10

### Device

Realme 3 Pro

### Steps to reproduce

Download a chapter 
Pause the download
The notification in the notification says Paused- Download Paused
Now re-enable the download

### Expected behavior

The new notification should say Dowloading chapter along with number of pages i.e 11/20

### Actual behavior

Although the download starts but the notification in the notification bar says Downloading 12/20
and download paused alongside
![IMG_20210729_101413](https://user-images.githubusercontent.com/88128946/127437950-f6b72ad6-525a-46b3-84d8-c3fd1b5b8dd9.jpg)

### Other details

Can reproduce this everytime

**Comment by jobobby04** [comment]
Its a main Tachi bug if its still happening
