### ISSUE TITLE
Wrong page

### ISSUE THREAD

**Issue by e-shl** [jobobby04/TachiyomiSY#392]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/1.7.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview 401

### Android version

11(Custom AOSP)

### Device

MI9

### Steps to reproduce

Open a chapter in webtoon mode

### Expected behavior

Opening the first chapter or memorized

### Actual behavior

Random opening with a transfer:
https://drive.google.com/file/d/1-08CpxxaDcdS2lM4DH2NKKh4GHBlJ72C/view?usp=sharing

### Other details

In the 400 version everything is fine

**Comment by jobobby04** [comment]
This is a main Tachi issue, someone went and pushed a untested commit
