### ISSUE TITLE
Global update starts 1-2 more times after cancelling

### ISSUE THREAD

**Issue by vongdong** [jobobby04/TachiyomiSY#393]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/1.7.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r402

### Android version

Android 11

### Device

Galaxy Tab S7 plus

### Steps to reproduce

Global update starts. Cancel it.

### Expected behavior

Global update cancels and notification disappears

### Actual behavior

Another global update starts, sometimes even another one starts (but doesn't update) after cancelling the second time.

**Comment by jobobby04** [comment]
Its a main Tachi bug if its still happening
