### ISSUE TITLE
Much of the manga in the library is dissociated from the source. 

### ISSUE THREAD

**Issue by uap4** [jobobby04/TachiyomiSY#398]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [ ] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/1.7.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

1.7.0

### Android version

Android 8.1.0 (SDK 27)

### Device

Smartphone

### Steps to reproduce

Manga was added to the library from the [RU] Grouple sources (Readmanga.live, Mintmanga.live). 
After a while, some of the source URIs changed. And recently there are a lot of them. 

### Expected behavior

The update will continue to work. Perhaps, if requested by the URI returns a redirect, then it is necessary to update the URI. 
Then there will be no problems. Only it is worth considering the possible conflicts, so in this case to terminate with an error, then to deal with them manually.

### Actual behavior

Updating manga with outdated URIs works fine. Probably, when accessing the old URI, a response with a redirect is returned, which is silently processed. Obsolete URI is not updated. 
When searching in the source, a manga that already has a new URI looks like it has nothing to do with the one appended with the old URI. If added to the library, then almost identical mangas are obtained there.
Necessary to carry out a slow migration of thousands of manga. Almost blindly. And the URIs keep changing, so it's not a one-off thing. 

### Crash logs

```
2021-08-17 19:28:38.110 D/||EH-NETWORK: --> GET https://readmanga.live/0_0_mhz
2021-08-17 19:28:38.110 D/||EH-NETWORK: --> GET https://readmanga.live/0_0_mhz
2021-08-17 19:28:38.111 D/||EH-NETWORK: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.63
2021-08-17 19:28:38.111 D/||EH-NETWORK: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.63
2021-08-17 19:28:38.111 D/||EH-NETWORK: Cache-Control: max-age=600
2021-08-17 19:28:38.112 D/||EH-NETWORK: --> END GET
2021-08-17 19:28:38.112 D/||EH-NETWORK: Cache-Control: max-age=600
2021-08-17 19:28:38.113 D/||EH-NETWORK: --> END GET
2021-08-17 19:28:39.930 D/||EH-NETWORK: <-- 200 OK https://readmanga.live/0_0_mhz__A5238 (1817ms)
```

### Other details

I don't think it's enough to modify the extension. Or do I still go out and create the issue in tachiyomiorg/tachiyomi-extensions?
Translated with "Google Translate".

**Comment by jobobby04** [comment]
Migrate the manga back to the source to fix manga URLs

**Comment by uap4** [comment]
From this side, I understood. As I mentioned, migration works, but this is more of an edge case.
But at least is it possible to add a switch to the debug menu that will set the followRedirects for OkHttpClient.Builder to false? Then I can sort out the non-updated ones and send them for migration. I don't have a couple dozen, but 15500 in the library, so I can't just start migrating everything. If not, then I have to go through this situation, and disassemble it manually. Someday this wave of URI changes will pass, hopefully. Although, I can think of a few more ways to break redirection at another level.
