### ISSUE TITLE
[Feature Request] Comfortable Grid view for Library and Browse

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#4]
### Why/User Benefit/User Problem
This allows for easier visibility of the thumbnails, and also shows author name under title.

### What/Requirements
Can be added as a toggle under Display on Library filters. Feature is present on J2K 1.0.0 and onwards.

**Comment by jobobby04** [comment]
Added in https://github.com/jobobby04/TachiyomiSY/commit/ccbe2408467c787fe6edd42b49d35409ebddbf9b and the next few commits
