### ISSUE TITLE
[Bug] (kind of) Cosmetic thing in the "Browse" tab, see pic

### ISSUE THREAD

**Issue by crisalis2** [jobobby04/TachiyomiSY#40]
![Screenshot_20200620-225010_TachiyomiSY](https://user-images.githubusercontent.com/65630147/85211336-6ca52180-b348-11ea-9c78-ede09bb2be8d.png)

As can be seen in the image, the "S" in "EXTENSIONS" doesn't align well now that there's also the "LATEST" section. My device's width is 1080 pixels, which should be fairly common. I use the latest APK from the preview builds.

**Comment by jobobby04** [comment]
Found the reason, it will be fixed in the next build 👍

**Comment by jobobby04** [comment]
Fix is now out 👍
