### ISSUE TITLE
No Group doesn't show on anonymous uploads after MangaDex update 1.2.129

### ISSUE THREAD

**Issue by loocool2** [jobobby04/TachiyomiSY#401]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/1.7.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

TachiyomiSY Dev Build 402

### Android version

Android 9

### Device

Amazon Fire HD 10 Plus

### Steps to reproduce

1. Update to MangaDex Extension 1.2.129
2. Go to a manga with anonymously uploaded chapters like https://mangadex.org/title/319d1283-3e91-4b7a-86f3-947a3831212f/where-we-used-to-be or https://mangadex.org/title/fac1870c-2ca1-439c-bd97-020dbbd732f0
3. see if the group name is replaced correctly

### Expected behavior

Any empty string or no group string should be replaced with No Group

### Actual behavior

The group name remains empty or "no group"

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/9ddadae07817ff5477a3bdd46b2d19f1194e5b7f
