### ISSUE TITLE
Uniform themes

### ISSUE THREAD

**Issue by chocoblin** [jobobby04/TachiyomiSY#405]
### Describe your suggested feature

All themes available except 'Blue' have complete white top and bottom bars. Whereas the 'Blue' theme has blue top and bottom bars
 I want to switch the color but ultimately it looks so white, that i have to revert back to the 'blue' theme.
We should have the option to enable(for guys like me, who like the screen sandwiched between a particular color) or disable(for people happy with current theme system) that feature of top and bottom bars color or white.

### Other details

Basically, ability to switch the major blue areas in the 'Blue' theme with any other available colors.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is more in the field of main Tachiyomi, I dont deal with UI

**Comment by chocoblin** [comment]
ah my bad. i thought this theme section was an addition from ur part. maybe this is because i've been using tachiyomisy from days of old now when there's were just light and dark.
