### ISSUE TITLE
TachiyomiSY isn't displaying local source manga covers

### ISSUE THREAD

**Issue by AbdullahMehiz** [jobobby04/TachiyomiSY#408]
### Steps to reproduce

Use local source
add manga to library

### Expected behavior

the manga should have its cover as the firstpage of the first chapter
if not, it can be edited

### Actual behavior

the cover stays black, editing or choosing a cover from outside the app doesn't change the cover in the library

### Tachiyomi version

Preview r403

### Android version

Android 11

### Device

Xiaomi Redmi Note 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a main Tachi issue, I will leave it for them to fix 😄
