### ISSUE TITLE
[Bug] Android locale in Spanish (especifically) changes app name to Tachiyomi, creates /Tachiyomi/logs folder

### ISSUE THREAD

**Issue by crisalis2** [jobobby04/TachiyomiSY#41]
I use TachiyomiSY in English, but my Android's locale is Spanish. The thing is, for a while now, if my Android's locale is Spanish, TachiyomiSY appears as Tachiyomi in the app list, and a /storage/emulated/0/Tachiyomi/ folder appears with the logs folder inside. Local manga still works under /storage/emulated/0/TachiyomiSY/local . If I change Android's locale to English or Japanese, this problem disappears.

I think the problem is related to https://github.com/jobobby04/TachiyomiSY/blob/master/app/src/main/res/values-b%2Bes%2B419/strings.xml , especifically this: \<string name="app_name" translatable="false">Tachiyomi\</string> , which should be changed to "TachiyomiSY".

**Comment by jobobby04** [comment]
Well that is really weird, thanks for the notification, no strings.xml other then the default English should have the app name. I'll fix that and then release a build

**Comment by crisalis2** [comment]
I guess some other locales are affected: https://github.com/inorichi/tachiyomi/search?q=translatable&type=Code

**Comment by jobobby04** [comment]
I made sure to look through all of them, it will be fixed when the build releases in a few mins 👍

**Comment by jobobby04** [comment]
And its out 👍
