### ISSUE TITLE
MangaDex tags do not display correctly

### ISSUE THREAD

**Issue by 98ne** [jobobby04/TachiyomiSY#411]
### Steps to reproduce

1. Open a manga from the MangaDex source.

### Expected behavior

The tags display correctly.

### Actual behavior

The tags do not display correctly.

### Tachiyomi version

r405 Preview

### Android version

Android 9.0

### Device

V35

### Other details

The tags shouldn't include their category (Demographics: / Tags:) in them. Expanding the synopsis will correctly display the tags, but will then include the categories as their own individual tags. Also, the layout for MangaDex tags is not consistent when expanded.

Here's a comparison  between r405 and 1.7.0.

**r405 Preview**

![Screenshot_20210902-171655](https://user-images.githubusercontent.com/81591386/131920688-aeb51cce-baab-4d50-a33c-592d6c5c1bfe.png)

![Screenshot_20210902-171703](https://user-images.githubusercontent.com/81591386/131920693-e6fd016e-d2d0-4a31-b093-32853c2a62bc.png)

**1.7.0 Stable**

![Screenshot_20210902-171419](https://user-images.githubusercontent.com/81591386/131920754-c1d73437-0d36-4cfc-9126-5918c27b6d83.png)

![Screenshot_20210902-171428](https://user-images.githubusercontent.com/81591386/131920759-150b19ba-62a8-46bc-93be-a56e5eec4290.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is intentional, in 1.7.0 Mangadex is not delegated, while in the preview it is. The delegated source categorizes the tags.
