### ISSUE TITLE
Can't pull down expanded sheet in sources

### ISSUE THREAD

**Issue by vengiare** [jobobby04/TachiyomiSY#413]
### Steps to reproduce

Browse Nhentai
Click filters
Swipe up to make sheet full screen
Swipe down to hide/make sheet 50%

### Expected behavior

https://user-images.githubusercontent.com/63973749/132121156-1a11a488-8917-4eb2-ba2d-31b0a1f9cc28.mp4

### Actual behavior

https://user-images.githubusercontent.com/63973749/132121147-dd007cb3-1946-4f33-80d0-e66d4b130fcb.mp4

### Tachiyomi version

r405

### Android version

A10

### Device

Redmi Note 9 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Irellavent now due to the filter sheet rewrite
