### ISSUE TITLE
All tab appears when library is ungrouped

### ISSUE THREAD

**Issue by loocool2** [jobobby04/TachiyomiSY#415]
### Steps to reproduce

1. Set your library to ungrouped, only having the default category may exhibit this issue as well
2. Open the library or exit a manga 
3. The category tab shows for a moment then disappears, or stays there

### Expected behavior

The All category tab should always remain hidden

### Actual behavior

The category tab shows for a moment then disappears, or stays there

### Tachiyomi version

Preview R405

### Android version

Android 9

### Device

Amazon Fire HD Plus 2021

### Other details

This issue seems to not be exhibited in the latest Tachiyomi Preview r3783 with the Default Category

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a main Tachi bug, you can reproduce it like this
1. Have multiple categories
2. Disable `Library -> Filter -> DIsplay -> show category tabs`
3. Issue reproduced
