### ISSUE TITLE
Wifi access point change breaks downloads

### ISSUE THREAD

**Issue by Sir-Crusher** [jobobby04/TachiyomiSY#417]
### Steps to reproduce

1: start downloading manga;
2: connect to a different access point without pausing the downloads;

### Expected behavior

The app should keep downloading without issues.

### Actual behavior

The app suddenly stopped all downloads and notified me the current download folder was invalid. After that, I attempted to change app's download folder and download other manga to it, and the app detected them, then I switched back to the first folder to detect the manga I downloaded before switching access points, as the previous downloaded manga still exist, because I found them with an external image viewer, yet tachiyomi did not detect them.

### Crash logs

There were no crash logs as the app continued running.

### Tachiyomi version

1.7.0

### Android version

Android 9 PPW29.69-40-4

### Device

Motorola X4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is probably a main Tachi bug, since I dont change how downloading works at all

**Comment by Sir-Crusher** [comment]
Is there any way to transfer that issue to their fork?

**Comment by jobobby04** [comment]
Other then opening a new one, no. I can only transfer issues between github repos I own
