### ISSUE TITLE
Small history feature

### ISSUE THREAD

**Issue by Xeiniac** [jobobby04/TachiyomiSY#418]
### Describe your suggested feature

Darken the title of the series in the history if all the chapters of the series are read and maybe also change the next chapter icon to another icon (Maybe a checkmark).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This sounds like a Main Tachiyomi request, I dont mess with history and UI 😄
