### ISSUE TITLE
Date header repeats itself in history

### ISSUE THREAD

**Issue by loocool2** [jobobby04/TachiyomiSY#419]
### Steps to reproduce

1. Go to the history page
2. Enter a entry in history
3. Exit the entry and scroll down 
4. The date header repeats itself

### Expected behavior

There should only be one header

### Actual behavior

There are like 7 for each date header

### Tachiyomi version

Preview R405

### Android version

Android 9

### Device

Amazon Fire HD Plus 2021

### Other details

![Screenshot of issue](https://user-images.githubusercontent.com/36128021/132570984-798e04f8-feb9-41a8-bfe8-02287aa923da.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
No idea how to reproduce this :thinkies:

**Comment by jobobby04** [comment]
Probably fixed with the compose rewrite
