### ISSUE TITLE
E-Hentai/ExHentai will keep retrying from the same Hentai@Home Network endpoint URL even if its broken.

### ISSUE THREAD

**Issue by raisehero** [jobobby04/TachiyomiSY#421]
### Steps to reproduce

1. Open a E-Hentai Gallery
2. Wait image to load, that would fail.
3. Tap on "Retry"

### Expected behavior

Image should load correctly the next time I press "Retry"

### Actual behavior

Sometimes image would load to 99% circle progress indicator and shows "Retry", other times it would start from 0% to around 12.5% circle progress, then stall for a long time, then shows "Retry"

### Crash logs

Logcat captured from 1.7.0, still reproducible in Preview r407
[logcat_08-29-2021_20-39-24.txt](https://github.com/jobobby04/TachiyomiSY/files/7162331/logcat_08-29-2021_20-39-24.txt)

### Tachiyomi version

Preview r407

### Android version

Android 11

### Device

Xiaomi Redmi Note 8

### Other details

Fixing this requires deleting /data/data/eu.kanade.tachiyomi.sy/cache/network_cache and using a VPN to United States, and even this is not bulletproof, and somethings I would encounter two or three broken images. The WebView roughly has the same performance, but at least it has "Click Here if the image fails to load" feature, but TachiyomiSY doesn't make use of this feature. It's evident from looking at the logcat TachiyomiSY would never attempt to request another endpoint URL.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
For E/Ex-H it uses that get new image link on the website, I dont know why its not working for you, it always works perfect for me

**Comment by raisehero** [comment]
I tried again, and sure enough, TachiyomiSY does change URL. Still getting that "Retry" error that doesn't show up in the logcat even with Extreme logging level. It even says "200 OK"

**Comment by jobobby04** [comment]
Its probably not something I can fix since even new urls are not showing for you, its probably something to do with the Hentai@Home hosts you have close to your location, best I can suggest is a VPN.

**Comment by raisehero** [comment]
No, the URL changes.
TachiyomiSY just fails to display them.

**Comment by jobobby04** [comment]
Is it a specific manga that this happens on, it doesnt seem reproducible on my end.

**Comment by raisehero** [comment]
No, most E-Hentai galleries has this issue. Is there any logging level that I need to enable to view these errors?
