### ISSUE TITLE
Change App Language in settings

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#422]
### Describe your suggested feature

Since some time ago, I noticed most of the app's text is localized to my device's language. Nice localization work!
But I prefer to use TachiyomiSY with English texts, and I didn't find a setting to change the app's language.
Can this language selection be added to the settings? Or does this feature already exist and I just didn't find it?

### Other details

I'm using Preview r407.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Taken from the Tachi discord.

Changing the app language has been removed due to it causing small bugs everywhere in Tachiyomi. 

Android does not provide a standard way of selecting a language that's not your device-language so it was a messy implementation.
