### ISSUE TITLE
Invisible sources in "latest" view

### ISSUE THREAD

**Issue by mneko** [jobobby04/TachiyomiSY#425]
### Steps to reproduce

I'm not sure what I did, so this is a guess:
Fill the watch list with 5 sources, then uninstall one without removing it from the watch list. 

### Expected behavior

The uninstalled source gets removed from the watch list

### Actual behavior

The watch list behaves like it's full, despite showing fewer than 5 sources

### Tachiyomi version

1.7.0

### Android version

Android 11

### Device

Samsung Note 10+

### Other details

I personally am stuck only able to watch 3 sources since I apparently did this twice. The removed extensions were obsoleted, so I can't reinstall them to see if the slot reappears.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mneko** [comment]
What version has that option? The stable release version doesn't have it

**Comment by jobobby04** [comment]
The latest [preview builds](https://github.com/jobobby04/tachiyomisypreview/releases) have it, I havent released it as a stable yet
