### ISSUE TITLE
Remember scroll position when going back to History tab or after deleting history items.

### ISSUE THREAD

**Issue by raisehero** [jobobby04/TachiyomiSY#426]
### Describe your suggested feature

Currently, going back from a manga detail page to history page or deleting an item from history resets scroll position to the top. This is annoying if you want to say, read 5 manga from the bottom of history list because every time you back out from the manga detail page, you need to scroll back to the bottom of the list.

### Other details

Going back from manga detail page behaviour:

https://user-images.githubusercontent.com/71166028/135214438-55d6dfa5-f4a7-4d48-bf65-e3081730f2ab.mp4

Delete item from history behavior:

https://user-images.githubusercontent.com/71166028/135214479-7db15c20-899d-441c-8e8f-0ecdbeebd39a.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a main Tachi bug, I dont edit anything in the history menu 😄

**Comment by raisehero** [comment]
@jobobby04 Tachiyomi r3833 (latest preview version) doesn't have this issue, both when deleting a history item, or going back from a manga details page.

**Comment by jobobby04** [comment]
🤷‍♂️ Literally nothing is different about the history menus between SY and main Tachi
