### ISSUE TITLE
Cache network request to use when device is temporarily disconnected from Internet.

### ISSUE THREAD

**Issue by ghost** [jobobby04/TachiyomiSY#428]
### Describe your suggested feature

Currently, for manga that has pages in image_cache, but is not marked as a downloaded manga will fail to load even if all its pages are completely downloaded in image_cache.
Caching the network request to prepare for offline device regardless of manga being downloaded or not, will improve user experience during temporary network disconnection situation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Most likely a main tachi bug in the first place
