### ISSUE TITLE
[Feature Request] <nhentai filters problem>

### ISSUE THREAD

**Issue by Hybridcre** [jobobby04/TachiyomiSY#43]
Can you provide filters in nhentai extension. In other j2k and original there is a ton of filters in nhentai but not in sy and az. 
@she11sh0cked

**Comment by jobobby04** [comment]
Lol, they were just added to the extension, yep I can probably port it over to the in-built version

**Comment by jobobby04** [comment]
Added in https://github.com/jobobby04/TachiyomiSY/commit/1374c773d7e5f5311db70817c7591354110aa9c1
You can use them in the latest preview build 👍
