### ISSUE TITLE
[Feature Request] Differentiate Complete Status on Mangadex 

### ISSUE THREAD

**Issue by vipzzx** [jobobby04/TachiyomiSY#44]
### Why/User Benefit/User Problem
Status on manga where not all the chapters are uploaded will be marked as completed when it is the publication that is completed and not the uploads.

### What/Requirements
Similar to how J2K and Neko behaves. If the manga's publication is complete but not all the chapters are translated it will say "Publication Complete". When all chapters are uploaded it will say "Complete"

**Comment by joseph619** [comment]
Post a screenshot to show how it's different on J2K

**Comment by vipzzx** [comment]
So in Neko it will differentiate between Completed and Publication Complete.
![Screenshot_20200630-175749_Neko](https://user-images.githubusercontent.com/59638889/86181281-b8e82280-bafb-11ea-9434-7a4980d5f4de.jpg)
![Screenshot_20200630-175648_Neko](https://user-images.githubusercontent.com/59638889/86181294-bc7ba980-bafb-11ea-8fdd-96d9fc01c265.jpg)

In J2K it will only mark complete if all the chapters have been uploaded 
![Screenshot_20200630-175834_TachiyomiJ2K](https://user-images.githubusercontent.com/59638889/86181333-d0271000-bafb-11ea-8df6-27734d1b9e75.jpg)
![Screenshot_20200630-175713_TachiyomiJ2K](https://user-images.githubusercontent.com/59638889/86181335-d0bfa680-bafb-11ea-9d88-49f398a50f9e.jpg)

In SY it marks status as unknown 
![Screenshot_20200630-181053_TachiyomiSY](https://user-images.githubusercontent.com/59638889/86182103-509a4080-bafd-11ea-82ea-75ab26b79acf.jpg)
![Screenshot_20200630-181037_TachiyomiSY](https://user-images.githubusercontent.com/59638889/86182104-509a4080-bafd-11ea-8935-c4eae7d6042d.jpg)

**Comment by vipzzx** [comment]
hmm it seems like theres some issue with it in J2K too that I just found. But this is what i meant with how some status will be marked as complete or unknown when its neither.

**Comment by joseph619** [comment]
Well anything on Neko regarding this issue is unlikely to be considered, since Neko is a single source app modified to match Mangadex. So you should only use J2k as example and delete the Neko screenshots.

**Comment by vipzzx** [comment]
Ok. I fixed the images. Since there no official eta on Jay's return from his long deserved break, I want to know if this is possible because it looks like the app is reading the status differently anyway

**Comment by jobobby04** [comment]
Closed in favor of #70, since this will be a delegation feature
