### ISSUE TITLE
"Add to MangaDex follows" in library action bar persist even the delegated sources is disabled

### ISSUE THREAD

**Issue by CVIUS** [jobobby04/TachiyomiSY#444]
### Steps to reproduce

1. Disable delegated sources in Settings > Advanced
2. Hold and select a manga in library. The bottom action bar will show.
3. Click on the overflow menu in action bar.

### Expected behavior

"Add to MangaDex follows" should be hidden since delegated sources is disabled

### Actual behavior

"Add to MangaDex follows" persist in overflow menu of bottom action bar

### Tachiyomi version

r411

### Android version

11

### Device

Redmi Note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Technically addressed by https://github.com/jobobby04/TachiyomiSY/commit/93f8a4274278718e4172774d359c8077ee2d6e60
