### ISSUE TITLE
Closing in manual update

### ISSUE THREAD

**Issue by KasukeLp23** [jobobby04/TachiyomiSY#451]
### Steps to reproduce

1. Open SY
2. Manually update a category

### Expected behavior

The update continues normally without any failure

### Actual behavior

The application closes automatically when updating the category

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/7443775/tachiyomi_crash_logs.txt)

### Tachiyomi version

1.7.0 - Preview 411

### Android version

Android 7

### Device

SAMSUNG

### Other details

![Screenshot_20211029-081109~01~01](https://user-images.githubusercontent.com/70596255/139475250-2a7e4fbe-e99c-4ced-8119-7897107dd3fd.jpg)

![Screenshot_20211029-114428](https://user-images.githubusercontent.com/70596255/139475265-e8351d7d-ab64-48bb-8d73-683aab3fe5c5.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Should be fixed in the last few builds
