### ISSUE TITLE
Library won't auto update on Android 12

### ISSUE THREAD

**Issue by Dragonzroar** [jobobby04/TachiyomiSY#452]
### Steps to reproduce

I have the app set to update the library every 6 hours and it has yet to updated once.

### Expected behavior

Update every 6 hours and show a notification it is doing so.

### Actual behavior

Will not update after 6 hours has passed and no notification shows up.

### Tachiyomi version

1.7.0

### Android version

Android 12

### Device

Google Pixel 6 Pro

### Other details

I have battery optimization set to unrestricted and all the permissions are net like normal.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is likely fixed in preview, and if it isnt its a main Tachi issue
