### ISSUE TITLE
Restore backup allow us to select what to restore just as we do when we save

### ISSUE THREAD

**Issue by molitar** [jobobby04/TachiyomiSY#453]
### Describe your suggested feature

I would like to be able to just restore specific selections during restore. When we backup manually we can select to not save categories but everything else.  I lost all my categories so when I restore the latest backup I still had lost categories so had to go to next latest which caused me to lose days of read libraries or added libraries.

### Other details

Allow selective restore just like we are allowed selective backup.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a thing for main Tachi as I'm not interested in making it. I believe it has a issue open though.
