### ISSUE TITLE
Please add a 'hide available update count' in the navbar

### ISSUE THREAD

**Issue by lewdpatriot** [jobobby04/TachiyomiSY#456]
### Describe your suggested feature

I have too many series added in the library under different categories for the future and only update the currently reading category. So always having the available update count in the navbar is disturbing but don't want to remove the update icon completly. Please add an option to remove the counter. 

### Other details

![IMG_20211107_111954](https://user-images.githubusercontent.com/63286528/140634279-4cae43fc-ce45-4aa0-bd26-9151801cc39a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Already available, check the settings

**Comment by lewdpatriot** [comment]
I checked everything except general, haha. Sorry to bother you.
