### ISSUE TITLE
Mangadex: Manga "Completed" Status broken/not added

### ISSUE THREAD

**Issue by curche** [jobobby04/TachiyomiSY#457]
### Steps to reproduce

Need to view a manga which is both publication complete and scanlation complete:
1. Open one of the mangadex links below
2. Check status of the manga

Links:
 - https://mangadex.org/title/c3ffcb40-f4c0-4046-9d29-f4f82cf32515
- https://mangadex.org/title/881fccb1-e60c-4c82-b64c-28f709545174

### Expected behavior

Above manga should show up as "Completed"

### Actual behavior

Above manga shows up as "Publication Complete"

### Crash logs

N/A

### Tachiyomi version

Preview 412

### Android version

Android 11

### Device

Onclite

### Other details

Neko works fine.
Parts of Dex code in Sy is still commented out.
Relevant part of Sy: https://github.com/jobobby04/TachiyomiSY/blob/892f64829b8e925d8429442629201c77c8aececc/app/src/main/java/exh/md/handlers/ApiMangaParser.kt#L101
Relevant part of Neko: https://github.com/CarlosEsco/Neko/blob/master/app/src/main/java/eu/kanade/tachiyomi/source/online/handlers/ApiMangaParser.kt#L87

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/0df5376545a0d1c116042346e97d8b985de2047b
