### ISSUE TITLE
add ability to exclude extension from using data saver

### ISSUE THREAD

**Issue by FrixBOX** [jobobby04/TachiyomiSY#458]
### Describe your suggested feature

please add the ability to exclude certain extension from using data saver since there's some extension that doesn't work using data saver option.

### Other details

or you could just add a shortcut to turn on and off data saver rather than go deep into the setting just to turn it on or off

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/c5b2aa180eb82b97afc4d723f0406aea0d8b0f63
