### ISSUE TITLE
Buggy top bar [Library]

### ISSUE THREAD

**Issue by CVIUS** [jobobby04/TachiyomiSY#459]
### Steps to reproduce

1. Disable delegated sources and integrated hentai features
2. Open a manga in your Library
3. Click one genre chip
4. Clear the query and press back 

### Expected behavior

Search button, filter button, and update library button should be present at the top bar

### Actual behavior

Search button, filter button, and update library button are not present at top bar. 
Only unclickable overflow button is present.

![Screenshot_1636566239](https://user-images.githubusercontent.com/84634607/141165329-f1d57ee0-091d-40c5-b2d3-44b9a0f769d8.png)

### Tachiyomi version

r412

### Android version

11

### Device

Redmi Note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Duplcate of https://github.com/jobobby04/TachiyomiSY/issues/368
