### ISSUE TITLE
[Bug] Mangadex Delegation Issues

### ISSUE THREAD

**Issue by crisalis2** [jobobby04/TachiyomiSY#46]
After the latest update, with the Mangadex delegation thing, I have noticed two problems.

1. Can't search on Mangadex anymore, even if logged in via webview. Disabling delegated sources doesn't solve it.

This requires some explanation. In the previous version of TachiyomiSY, I was logged in on Mangadex via webview and thus searches worked. Then I updated to the new TachiyomiSY version. At first, searches worked fine in the new version too. Later I noticed if I opened Mangadex on webview I didn't appear as logged in, which was strange, because searches worked. I cleared cookies as a test, and then searches didn't work anymore, as clearing cookies must have logged me out for good. But the thing is, from this point on, no matter if I log in via webview, or disable/enable delegated sources, searches never work anymore.

2. Mangadex extension settings (server, data saver...) aren't accesible anymore, regardless whether delegated sources are enabled or disabled. I don't know if this is intended.

**Comment by jobobby04** [comment]
- [ ] Fix configuration

- [ ] Fix search

**Comment by jobobby04** [comment]
Temporarily disabled MangaDex delegation, will re-enable it when I am able to get it working properly

**Comment by jobobby04** [comment]
Closing in favor of #70
