### ISSUE TITLE
[minor] missing "+" in edit manga dialog

### ISSUE THREAD

**Issue by CVIUS** [jobobby04/TachiyomiSY#460]
### Steps to reproduce

1. Edit manga info

### Expected behavior

![IMG_20211115_101717](https://user-images.githubusercontent.com/84634607/141711995-153c7bef-8faf-445a-82e9-81db33ccb67c.jpg)

### Actual behavior

![IMG_20211115_101738](https://user-images.githubusercontent.com/84634607/141712005-ff64ef75-ff64-489e-9160-69ab8bf5d143.jpg)

### Tachiyomi version

r414

### Android version

11

### Device

Redmi Note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Gotta love material 3 :harold:

**Comment by jobobby04** [comment]
Fixed in latest preview by @D3xron
