### ISSUE TITLE
Multi-device synchronization with webdav

### ISSUE THREAD

**Issue by ckn4** [jobobby04/TachiyomiSY#461]
### Describe your suggested feature

Thanks for your work. But would you please add webdav supports？
I have two devices, one is my mobile phone and the other is an e-ink reader. TachiyomiSY works fine on my e-ink devices, but it's hard to keep in sync with my phone. I can only backup on phone and then move it to e-ink reader to restore. Sometimes, I must backup on e-ink reader and restore it on my phone. Operations like that takes a lot of time.
Could you please add webdav supports? Or it could be added as an option. The funcation may work like this: When you close the app, it will automatically start backup and upload the backup files to your webdav. And when you open the app, it will automatically try to get the backup files from the webdav and restore them. In this way, the reading progress of multiple devices can be synchronized. In fact, many softwares adopt this method in the function of multi-device synchronization.
Sorry for my bad english. Thanks again. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Nope, not even going to get close to that, waaaaay to much work. There is a open issue about cross device sync on the main tachi repo btw
