### ISSUE TITLE
Anti-Aliasing

### ISSUE THREAD

**Issue by JaitinPrakash** [jobobby04/TachiyomiSY#462]
### Describe your suggested feature

An Anti-Aliasing filter to reduce moire, stair-stepping, and overall improve general image quality.

### Other details

https://github.com/tachiyomiorg/tachiyomi/issues/6133#issue-1029644721
This explains the request much better than I can.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I'll leave this to main tachi, I dont feel like trying to implement this myself. If main tachi gets it SY will as well
