### ISSUE TITLE
Low Performance on Tall Images

### ISSUE THREAD

**Issue by JaitinPrakash** [jobobby04/TachiyomiSY#463]
### Steps to reproduce

1. Find series with tall image files
2. Load chapter with those image files

### Expected behavior

The pages should load as usual, and continue scrolling along like normal.

### Actual behavior

The entire app slows down and becomes almost unresponsive, and scrolling becomes extremely choppy, with update speed of less than 1hz

### Tachiyomi version

1.7.0

### Android version

Android 9

### Device

Samsung Galaxy S8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a known bug for main Tachi, I will leave it to them.
