### ISSUE TITLE
Pure Red theme inconssitent

### ISSUE THREAD

**Issue by jopejoe1** [jobobby04/TachiyomiSY#464]
### Steps to reproduce

1. Change to Pure Red Theme
2. Enable Pure black dark mode

### Expected behavior

All text and icons are red.

### Actual behavior

Some are red and some are white.

### Tachiyomi version

r414

### Android version

10

### Device

Samsung Galaxy s10+

### Other details

Example Images

![Screenshot_20211120-140740_TachiyomiSY](https://user-images.githubusercontent.com/34899572/142708971-80b1f764-d7c2-4266-aed1-469c9dea9561.png)
![Screenshot_20211120-140701_TachiyomiSY](https://user-images.githubusercontent.com/34899572/142708976-ef492428-ea0e-4855-83da-19087dfcd375.png)
![Screenshot_20211120-140648_TachiyomiSY](https://user-images.githubusercontent.com/34899572/142708977-3d7a1e12-1e75-4654-a8a1-f78e2d7bba0c.png)
![Screenshot_20211119-123530_TachiyomiSY](https://user-images.githubusercontent.com/34899572/142708981-84fe6943-dc15-47c4-a9a3-988ad044b89a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Pure red theme dead in preview, closing 😄
