### ISSUE TITLE
[Shizuku] can't update extensions with shizuku installer

### ISSUE THREAD

**Issue by hasanpasha** [jobobby04/TachiyomiSY#465]
### Steps to reproduce

1. Select shizuku as the installer
2. update any extension

### Expected behavior

It should update, cause it works when I install new extensions

### Actual behavior

It just shows 'retry' beside the extension I am updating.

### Crash logs

Crash Log: [here](https://justpaste.it/8p9m2) hosted in justpaste.it

### Tachiyomi version

Preview r414

### Android version

Android 7.1.1

### Device

Samsung Galaxy Grand Prime Pro (SM-J250F)

### Other details

Disclaimer: I hadn't updated the existed extensions, because, well, The issue is in the updater.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
https://tachiyomi.org/help/faq/#shizuku
