### ISSUE TITLE
Text field covered while trying to edit "Override BaseUrl"

### ISSUE THREAD

**Issue by joseph15two** [jobobby04/TachiyomiSY#466]
### Steps to reproduce

1. Go to extensions tab.
2. Pick any extension with "Override BaseUrl" option.
3. Tap on that extension.
4. Tap the gear icon to go to extension settings.
5. Tap on "Override BaseUrl".

### Expected behavior

Text field should be visible when the keyboard pops up so that the user can see what they are editting.

### Actual behavior

Text field gets squished when the overlay to edit the url pops up. Overlay view returns to normal when keyboard is taken away.

### Tachiyomi version

1.7.0 (Preview r417)

### Android version

Android 8.0

### Device

LG G5

### Other details

Screenshots:

![Capture+_2021-12-04-02-34-48](https://user-images.githubusercontent.com/42328095/144702108-614790f0-293e-45e8-a155-89a8188b0ad7.png)

![Capture+_2021-12-04-02-34-57](https://user-images.githubusercontent.com/42328095/144702110-60e17e58-15c5-4986-99a5-780a81aec09c.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Main tachi bug
