### ISSUE TITLE
Why no stable release?

### ISSUE THREAD

**Issue by lewdpatriot** [jobobby04/TachiyomiSY#469]
### Describe your suggested feature

Just a curiosity. It has been 6 months from the last stable release. In the meantime the beta version has undoubtedly become the best fork of tachiyomi. So, why no stable release?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
The preview was very unstable for the longest time, now that its sorta stable main Tachi is going through a UI update. I will probably do a stable when main Tachi does one.

Also going to close this 😄
