### ISSUE TITLE
Double page layout only displaying single page

### ISSUE THREAD

**Issue by MrCythos** [jobobby04/TachiyomiSY#470]
### Steps to reproduce

On version 1.7.0 with the Samsung galaxy z fold 3.

When setting the page layout to "double pages", it doesn't display double pages immediately. Instead "dual page split" must be toggled on and off for the viewer to properly display both pages. Double page layout is then retained while reading, into other chapters. However, if exiting the reader or changing any other reader or general setting, it switches back to the single page layout (despite page layout displaying double pages) and the dual page split needs to be toggled on and off again.

### Expected behavior

Selecting "double pages" in "page layout" under reading mode should allow the reader to display double pages.

### Actual behavior

Performing the above selection does not change the page layout and its kept in its single page layout until dual page split is toggled on and off.

### Tachiyomi version

1.7.0

### Android version

Android 11

### Device

Samsung galaxy z fold 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I believe I disabled double pages on stable for 1.7.0, its now complete and working fine in the preview

**Comment by MrCythos** [comment]
You're right, just checked out the preview and it is working. Thanks for letting me know and for the help!
