### ISSUE TITLE
Adding status "On hold" at edit info, and making pop-up menu bigger

### ISSUE THREAD

**Issue by D3xron** [jobobby04/TachiyomiSY#473]
### Describe your suggested feature

There are some website that have status on_hold like TuMangaOnline, there are any posibility to add this status? And can you make status pop-up menu bigger?
![Снимок экрана 2021-12-20 172255](https://user-images.githubusercontent.com/46288465/146807559-712c8bf3-1671-4946-9aed-2cad46846895.png)
![Снимок экрана 2021-12-20 172314](https://user-images.githubusercontent.com/46288465/146807571-56766d8f-bce7-4f2a-b356-5ee0565526cc.png)
 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
There is already a hiatus status lol. Open a new issue for a bigger spinner menu
