### ISSUE TITLE
Migrate button invisible bug

### ISSUE THREAD

**Issue by LoLyeah** [jobobby04/TachiyomiSY#477]
### Steps to reproduce

Migrate a manga

### Expected behavior

![IMG_20211223_121315](https://user-images.githubusercontent.com/11774211/147191507-9632928a-6a16-4d87-9fca-8a390213bccb.jpg)

### Actual behavior

![IMG_20211223_120806](https://user-images.githubusercontent.com/11774211/147191305-9349c7d8-62e3-469b-b400-c962a057e92d.jpg)

### Tachiyomi version

App version: 1.7.0 (standard, 6972edbcb, 23, 2021-12-18T23:18Z) Preview build: 422  

### Android version

Android version: 11 (SDK 30)

### Device

Poco F3

### Other details

The button still works, just invisible.
![IMG_20211223_121506](https://user-images.githubusercontent.com/11774211/147191457-4a2f613b-4cef-4ee7-b7ce-3724589c56ee.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by JudahGoldstein** [comment]
Same issue here on OP8

**Comment by jobobby04** [comment]
Does this still happen in the latest build?

**Comment by JudahGoldstein** [comment]
> Does this still happen in the latest build?

Seems to be fixed in latest experimental version, not sure about main-line releases.

**Comment by jobobby04** [comment]
Mainline doesnt have the bug in the first place, it was introduced in the previews. Ill close this then, it can be re-opened in the future if someone finds it still happens
