### ISSUE TITLE
Library not Updating Properly 

### ISSUE THREAD

**Issue by dondeepak** [jobobby04/TachiyomiSY#479]
### Steps to reproduce

updating  Library not working properly  i have 260+ mangas in Library but its only updating 7 always after update 
app version  TachiyomiSY Dev Build 422 and also same issue in TachiyomiSY Dev Build 423
 

### Expected behavior

launching global update should update all manga in library 

### Actual behavior

launching global update only updating 7  

### Crash logs

--------- beginning of main
12-27 11:26:36.607 17419 17419 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
12-27 11:26:39.636 17419 17512 E SQLiteLog: (284) automatic index on C(manga_id)
12-27 11:26:39.637 17419 17512 E SQLiteLog: (284) automatic index on R(manga_id)
12-27 11:26:39.637 17419 17512 E SQLiteLog: (284) automatic index on C(merge_id)
12-27 11:26:39.637 17419 17512 E SQLiteLog: (284) automatic index on R(merge_id)
12-27 11:26:39.637 17419 17512 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-27 12:13:57.278 22504 22504 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
12-27 12:13:59.790 22504 22577 E SQLiteLog: (284) automatic index on C(manga_id)
12-27 12:13:59.791 22504 22577 E SQLiteLog: (284) automatic index on R(manga_id)
12-27 12:13:59.791 22504 22577 E SQLiteLog: (284) automatic index on C(merge_id)
12-27 12:13:59.791 22504 22577 E SQLiteLog: (284) automatic index on R(merge_id)
12-27 12:13:59.791 22504 22577 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-27 12:22:57.843 24899 24899 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
12-27 12:23:00.473 24899 24998 E SQLiteLog: (284) automatic index on C(manga_id)
12-27 12:23:00.474 24899 24998 E SQLiteLog: (284) automatic index on R(manga_id)
12-27 12:23:00.474 24899 24998 E SQLiteLog: (284) automatic index on C(merge_id)
12-27 12:23:00.474 24899 24998 E SQLiteLog: (284) automatic index on R(merge_id)
12-27 12:23:00.474 24899 24998 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-27 12:29:47.571 28561 28561 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
12-27 12:29:49.977 28561 28677 E SQLiteLog: (284) automatic index on C(manga_id)
12-27 12:29:49.978 28561 28677 E SQLiteLog: (284) automatic index on R(manga_id)
12-27 12:29:49.978 28561 28677 E SQLiteLog: (284) automatic index on C(merge_id)
12-27 12:29:49.978 28561 28677 E SQLiteLog: (284) automatic index on R(merge_id)
12-27 12:29:49.978 28561 28677 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 1.7.0 (standard, 5c9d1afe4, 23, 2021-12-26T21:41Z)
Preview build: 423
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 1951
Device model: vivo 1951
Device product name: 1951

### Tachiyomi version

 1.7.0 (standard, 5c9d1afe4, 23, 2021-12-26T21:41Z)

### Android version

Android 11 (SDK 30)

### Device

vivo z1 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
New library update restrictions were added, review them at Settings -> Library -> Library update restrictions
