### ISSUE TITLE
[Feature Request] Global Library Search

### ISSUE THREAD

**Issue by Fahad1998** [jobobby04/TachiyomiSY#48]
---

### Why/User Benefit/User Problem
Currently i have to search categories one by one

### What/Requirements
Add options to search in all categories at once

**Comment by vipzzx** [comment]
think this might be difficult if its not like J2K or Neko where it is vertical instead of tabs

**Comment by jobobby04** [comment]
I cant see any good way to directly implement this, not in the UI or code

**Comment by Fahad1998** [comment]
Just add a new view for this. Like trackers.

**Comment by Fahad1998** [comment]
> I cant see any good way to directly implement this, not in the UI or code

Just add a new activity for this. Like trackers.

**Comment by jobobby04** [comment]
Added with groups, you can set your library to ungrouped and search it
