### ISSUE TITLE
Favorite sync could not finish

### ISSUE THREAD

**Issue by ZerataX** [jobobby04/TachiyomiSY#480]
### Steps to reproduce

I tried to sync my favorites which are about 2.3k galleries. I set my phone to not sleep, disabled battery optimizations and just let it run in the forground for 4 hours when it failed like this:

![Screenshot_20211227-175209952_1](https://user-images.githubusercontent.com/5024958/147493809-7a927b62-c823-4ebf-ae4a-58014320f858.jpg)

### Expected behavior

All galleries synced up to this gallery should now be added to my library and it should either just try to continue and ignore this one gallery or let me continue at this point. I don't understand why this huge process has to be done in one go. not being able to use my phone for 4 hours and it then being for nothing is a little frustrating ^^

### Actual behavior

The sync stops with this error and throws away all progress

### Tachiyomi version

1.7.0

### Android version

Android 11

### Device

mi 9 pro t

### Other details

I am on preview build 422

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
If you look at the parent gallery of https://e-hentai.org/g/982170/492dc7a1c0 you will notice that it errors out, normal errors are skipped, but this one was deemed important enough to error out. I suggest removing that gallery from your favourites
