### ISSUE TITLE
Filter unread in "Updates" tab

### ISSUE THREAD

**Issue by JudahGoldstein** [jobobby04/TachiyomiSY#481]
### Describe your suggested feature

In the "Updates" tab being able to filter out already read chapters it would be useful for those who want to read the oldest chapters they have yet to read. Also being able to flip the entry order would be useful (oldest to newest). 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Not really interested in this, and it looks like its an already open issue on main Tachi. If it ever is created for main Tachi i will merge it here https://github.com/tachiyomiorg/tachiyomi/issues/3365
