### ISSUE TITLE
[Feature Request] Change tracking similar or same as Neko/J2K

### ISSUE THREAD

**Issue by vipzzx** [jobobby04/TachiyomiSY#49]
### Why/User Benefit/User Problem
Does not have to open a "new page" where the screen is only tracking, and shows on the bottom screen
Be able to delete/remove manga from tracking list in case the wrong one was selected.
Selecting chapters are easier when inputting manually.

### What/Requirements
Look at Neko?

**Comment by jobobby04** [comment]
Unlikely to be implemented, this falls under Tachiyomi Stable's purview then SY's. SY likely wont get any tracking upgrades on its own, unless someone that is not me makes it and posts a PR.

**Comment by vipzzx** [comment]
Oh man. Ok

**Comment by jobobby04** [comment]
My tracking button will be going away soon anyway, Ill will be dropping my manga page and implementing previews when its done, so I will be picking up whatever they do for the tracking tab(mine was just a stop gap)
