### ISSUE TITLE
[Preview version] Bookmarking cause scrolling in chapter list

### ISSUE THREAD

**Issue by Quickdesh** [jobobby04/TachiyomiSY#494]
### Steps to reproduce

1. open up a manga in reader
2. Press the chapter list button (bottom left)
3. Bookmark / Unbookmark a page

### Expected behavior

The chapter simply gets bookmarked/unbookmarked. No scrolling in chapter list taking place

### Actual behavior

The chapter scrolls up by around 1 page when bookmarking or unbookmarking a chapter. 
![gif-20220102-232913](https://user-images.githubusercontent.com/36792807/147879372-655e8d9e-a503-4fc0-a8ae-f29297973c27.gif)

### Crash logs

N.A

### Tachiyomi version

TachiyomiSY preview r425

### Android version

Android 11

### Device

Motorola Edge 20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/cccf956fae5460171aaa8669dac319349a5063d7
