### ISSUE TITLE
[Preview] Read from .cbz sometimes crash

### ISSUE THREAD

**Issue by Baetul** [jobobby04/TachiyomiSY#498]
### Steps to reproduce

App crash sometimes after read from .cbz, especially after download.

For additional information, i use micro-sd as download folder

### Expected behavior

Smoothly read manga

### Actual behavior

In middle page app crash,
And after I open it again, it crashes right away

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/7810154/tachiyomi_crash_logs.txt)

### Tachiyomi version

r425

### Android version

Android 7

### Device

Redmi Note 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Most likely a main Tachi bug since in the latest build CBZ is now implemented in main Tachi.
