### ISSUE TITLE
[Feature Request] Auto-webtoon mode

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#5]
### Why/User Benefit/User Problem
Webtoon mode will be force triggered for all comics tagged as Long Strip, Webtoon(s), Manhua and Manhwa, and user don't have to change their reader mode when switching from Manga to webtoons.

### What/Requirements
Can be added as a toggle under Reader settings. Feature would work same way as on TachiJ2k. J2k also forces webtoons for certain sources like Webtoons which doesn't have webtoon tag, but has only webtoons.

**Comment by jobobby04** [comment]
Added my own implementation in https://github.com/jobobby04/TachiyomiSY/commit/43098aa61b6455c4d3f1b7a51d2ca6bdacf7ce54
