### ISSUE TITLE
[Bug] Exhentai chapter duplicate

### ISSUE THREAD

**Issue by de-odex** [jobobby04/TachiyomiSY#50]
### Device information
App version: 0.9.2.7 (standard, ad82dc1c, 1)
Android version: 9 (SDK 28)
Android build ID: ONEPLUS A5010_43_190731
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus5T
Device model: ONEPLUS A5010
Device product name: OnePlus5T

An exhentai gallery in my library has duplicate chapters, and I can infinitely scroll the last chapter into itself

![Screenshot_20200630-160341](https://user-images.githubusercontent.com/11498305/86094851-078dc080-baec-11ea-859a-3ffb6afa5556.jpg)

Perhaps this is due to restoring the same backup twice, but I do not see this issue in other galleries, so I am unsure on what the actual root cause is

**Comment by de-odex** [comment]
Also, fix your actions

**Comment by jobobby04** [comment]
🤷‍♂️
You will likely have to remove that manga from library and clear the db in advanced settings, it will remove history and chapters from manga not in library

**Comment by jobobby04** [comment]
Technically fixed for the next release, it wont cause you reading errors any more
