### ISSUE TITLE
Does not load default filter options in search

### ISSUE THREAD

**Issue by jopejoe1** [jobobby04/TachiyomiSY#500]
### Steps to reproduce

1. Search something in an extension that hase default filter settings.

### Expected behavior

Uses the default filter settings

### Actual behavior

Does not use the default filter settings

### Tachiyomi version

r426

### Android version

10

### Device

Samsung s10+

### Other details

Loads default filters in global search. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I do not believe that I do anything different from main Tachiyomi in this aspect. Both main Tachi and SY use an empty filterlist when filter has not been pressed.

**Comment by jobobby04** [comment]
It works fine for me, though I did notice a small data race when you search from the combined latest/browse view with the filters that could cause this.
Main Tachi also would contain this bug, just try pressing the expand button from global search.
![TdYrK9H 1](https://user-images.githubusercontent.com/17078382/148712183-d4038b5d-9faf-4ff3-90a0-a20d2bcaa138.png)
