### ISSUE TITLE
[Preview Version] the app closes when you change the compression percentage of Data Saver

### ISSUE THREAD

**Issue by AethersKz** [jobobby04/TachiyomiSY#503]
### Steps to reproduce

https://user-images.githubusercontent.com/96607644/148828647-62bcbc99-5774-4904-bd2b-ae82f1b36159.mp4

### Expected behavior

the app does not close when changing the percentage.

### Actual behavior

the app closes when I change the percentage

### Tachiyomi version

App version: 1.7.0 (standard, 04f284e27, 23, 2022-01-09T20:47Z) Preview build: 426

### Android version

Android version: 7.0 (SDK 24)

### Device

Device model: HUAWEI NXT-L09

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/479950e60e29fe11e8f6d40721c4cd4c7fafba75
