### ISSUE TITLE
[Preview Version] Local Manga source can't be read

### ISSUE THREAD

**Issue by mish20011** [jobobby04/TachiyomiSY#504]
### Steps to reproduce

TachiyomiSY > Local > Manga name > chapter folder 

### Expected behavior

should work for both internal and sd card storage

https://i.imgur.com/FXz5UYN.jpg

https://i.imgur.com/Ts8kEcq.jpg

https://i.imgur.com/SRacW4A.jpg

### Actual behavior

I can only use it when put in internal storage, and this happens when its in the external storage

https://i.imgur.com/K4rKefZ.jpg

https://i.imgur.com/GZXSkaw.jpg

No cover + the manga is unreadable

### Tachiyomi version

App version: 1.7.0 (standard, 04f284e27, 23, 2022-01-09T20:47Z) Preview build: 426

### Android version

Android version: 8.1.0 (SDK 27) 

### Device

Device brand: lge Device manufacturer: LGE Device name: mh Device model: LG-M700 Device product name: mh_global_com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
SY doesnt do anything special with Local source, and I personally dont use it. Feel free to join the Tachiyomi discord for help
