### ISSUE TITLE
PageList cache doesn't work. 

### ISSUE THREAD

**Issue by f1998f1998** [jobobby04/TachiyomiSY#505]
### Steps to reproduce

open any chapter.
close it.
open it again. 

### Expected behavior

it should load page list from cache. 

### Actual behavior

it loads pagelist from internet. 

### Tachiyomi version

App version: 1.7.0 (standard, 04f284e27, 23, 2022-01-09T20:47Z) Preview build: 426

### Android version

9.1

### Device

Huawei y9 2019 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
SY makes no edits to chapter cache, so this is likely a Main Tachi buh

**Comment by f1998f1998** [comment]
I checked the code and pagelist cache function is still there. It just doesn't work for some reason. maybe because it now uses json instead of gson and it broke something. I couldn't find the problem. I only use tachiyomisy so i don't know about main tachi.
