### ISSUE TITLE
[Bug] EH not batch updating, only individually

### ISSUE THREAD

**Issue by Kingdreadz** [jobobby04/TachiyomiSY#507]
### Steps to reproduce

1. Group by source
2. 'Update Gallery' button/Pull down to update
3. Notification bar pops up for update

### Expected behavior

Manga updated in EH/ExH update in library

### Actual behavior

Manga library does not update.
But when viewing a manga, when you 'pull down' the one will update itself

### Tachiyomi version

1.70

### Android version

Android 11

### Device

Galaxy Tab 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
E-Hentai has a separate updater that you can enable in the E-Hentai settings.

**Comment by Kingdreadz** [comment]
Yes the "Gallery Update Checker.' I've been working on this for a week and it doesn't update. I've even set the automatic updater to no avail

**Comment by jobobby04** [comment]
Make sure EHentaiUpdateChecker is included in `Settings -> Advanced -> Debug Menu -> List scheduled jobs` and that the galleries you want updated are not over a year old, since galleries that are over a year old are locked on E-Hentai and not checked.

**Comment by Kingdreadz** [comment]
This is what I get

![Screenshot_20220115-175556_TachiyomiSY](https://user-images.githubusercontent.com/97810449/149640280-767337a2-3f48-4514-8a0e-3b9d24e55a16.jpg)

**Comment by jobobby04** [comment]
You should update to the preview then, the updater has been improved and works more reliably in the preview. 
https://github.com/jobobby04/tachiyomisypreview/releases

**Comment by Kingdreadz** [comment]
Still not updating. Even checked my favorites on the website to make sure. This is what's been going on with the updater

![Screenshot_20220115-174955_TachiyomiSY](https://user-images.githubusercontent.com/97810449/149642389-f8a60f45-69a7-4db8-902a-287ba93febb1.jpg)

**Comment by Kingdreadz** [comment]
and the one is from when I did an individual update. This is from the update to the 426 build and the result is the same

**Comment by jobobby04** [comment]
What does the list scheduled jobs show now

**Comment by Kingdreadz** [comment]
![Screenshot_20220115-192931_TachiyomiSY](https://user-images.githubusercontent.com/97810449/149642531-bfa19ef1-9b0b-436d-a5b2-603a6c55fd90.jpg)

**Comment by jobobby04** [comment]
It looks like the E-Hentai updater was added after the update, wait a few hours and check back to see if it updated any galleries
