### ISSUE TITLE
[Bug] <local manga (stored in phone) don't display covers>

### ISSUE THREAD

**Issue by crusaside** [jobobby04/TachiyomiSY#51]
### Device information
* Tachiyomi version: preview r150 and all below, maybe newer as well
* Android version: 10
* Device: realme 3 Pro

## Steps to reproduce
1. First step - have a downloaded manga in ur phone
2. Second step- add it to ur library

### Expected behavior
This should happen. - just like all other manga, the cover should be visible. and i do have a cover image file in the appropriate location, as in original tachiyomi, it is displayed properly

### Actual behavior
This happened instead. - white. pure, glistening white in the cover space

### Other details
Additional details and attachments. - attached
![Screenshot_2020-07-01-18-07-28-98](https://user-images.githubusercontent.com/67280365/86245014-75a6b600-bbc6-11ea-9fac-27db827b1ddc.jpg)
![Screenshot_2020-07-01-18-07-23-77](https://user-images.githubusercontent.com/67280365/86245018-7a6b6a00-bbc6-11ea-91e1-d3d744fb03e2.jpg)

**Comment by jobobby04** [comment]
That happens sometimes, I found a fix is to remove the manga from your library, and then clear the db in the advanced settings, and then add them again

**Comment by crusaside** [comment]
> That happens sometimes, I found a fix is to remove the manga from your library, and then clear the db in the advanced settings, and then add them again

whoa that's great! it worked, thanks! i was worried for no reason..
