### ISSUE TITLE
Keeping track of previous tab(s) when clicking on tags

### ISSUE THREAD

**Issue by Auyuez** [jobobby04/TachiyomiSY#510]
### Describe your suggested feature

Currently, when you click on the tags, it brings you to the extension's search page of that tag. But if you go back, it doesn't go back to the manga where you clicked the tag on, but to the homepage of the website (refreshed). Is there a way for it to NOT skip all the way back to the homepage, and just go back to the manga page you were on? This would also keep track of the position/page you were browsing in the webpage (browse/latest catalog) if you went back out of the manga page.

### Other details

Reason why I'm posting this here, instead of vanilla Tachiyomi (which, along with all the other forks, have this same problem) is because this is only a feature that I find inconvenient for situations where I HAVE to click on the tag, instead of clicking on the author/artist (where it does a global search and this problem wouldn't occur). Example: On a E-Hentai/Exhentai manga/gallery page, and it's a group work (so there's no artist), so I click on the group name from the tags instead. It'd probably be more convenient for NHentai, too, because clicking on the artist tag is good for saving time (skipping going to global search and picking the source you were on), but it doesn't keep track of the previous tab (the manga page I clicked the tag from). Was using TachiEH up until a few days ago, and only stopped using it because I have a bug where the app always crashes now when I click on the tags (I'm probably wrong, but I think it has something to do with the E-Hentai extension update a few days prior). I might be Mandela effecting myself here, but I don't recall having this problem on TachiEH (it would go back to the manga page, instead of the homepage refreshed). It's inconvenient, because every time I'm browsing hentai and click on a tag, it loses track of not only the manga I was on, but the spot where I was browsing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Just long click the tag
