### ISSUE TITLE
App crashed 

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#516]
### Steps to reproduce

Go to browse bottom navbar tav from another screen

### Expected behavior

App shouldn't crash

### Actual behavior

App crashes

### Crash logs

--------- beginning of main
01-31 19:44:19.213 22314 23523 E SQLiteLog: (284) automatic index on C(manga_id)
01-31 19:44:19.214 22314 23523 E SQLiteLog: (284) automatic index on R(manga_id)
01-31 19:44:19.214 22314 23523 E SQLiteLog: (284) automatic index on C(merge_id)
01-31 19:44:19.214 22314 23523 E SQLiteLog: (284) automatic index on R(merge_id)
01-31 19:44:19.214 22314 23523 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
--------- beginning of crash
01-31 20:07:30.495 22314 22314 E AndroidRuntime: FATAL EXCEPTION: main
01-31 20:07:30.495 22314 22314 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 22314
01-31 20:07:30.495 22314 22314 E AndroidRuntime: java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: LatestHolder{98826ad position=4 id=-484570858, oldPos=-1, pLpos:-1 invalid update tmpDetached undefined adapter position no parent} androidx.recyclerview.widget.RecyclerView{37637c2 VFED..... .......D 0,0-1440,2718 #7f09032d app:id/recycler}, adapter:eu.kanade.tachiyomi.ui.browse.latest.LatestAdapter@7a80f4e, layout:androidx.recyclerview.widget.LinearLayoutManager@b8c786f, context:eu.kanade.tachiyomi.ui.main.MainActivity@9567364
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:25)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:12)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:8)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at androidx.recyclerview.widget.DefaultItemAnimator$6.onAnimationEnd(DefaultItemAnimator.java:3)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1112)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1061)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:775)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1048)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8641)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
01-31 20:07:30.495 22314 22314 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
01-31 20:07:31.647 11136 11136 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
01-31 20:07:31.648 11136 11136 E USNET   : USNET: appName: eu.kanade.tachiyomi.sy
01-31 20:07:32.170 11136 11136 E de.tachiyomi.s: Invalid ID 0x00000000.
01-31 20:07:32.855 11136 11268 E SQLiteLog: (284) automatic index on C(manga_id)
01-31 20:07:32.855 11136 11268 E SQLiteLog: (284) automatic index on R(manga_id)
01-31 20:07:32.855 11136 11268 E SQLiteLog: (284) automatic index on C(merge_id)
01-31 20:07:32.855 11136 11268 E SQLiteLog: (284) automatic index on R(merge_id)
01-31 20:07:32.855 11136 11268 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
01-31 20:07:36.039 11136 11382 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/eu.kanade.tachiyomi.sy/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
01-31 20:07:36.039 11136 11382 E chromium: [ERROR:simple_index_file.cc(575)] Could not reconstruct index from disk
01-31 20:07:36.039 11136 11396 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/eu.kanade.tachiyomi.sy/cache/WebView/Default/HTTP Cache/Code Cache/wasm: No such file or directory (2)
01-31 20:07:36.039 11136 11396 E chromium: [ERROR:simple_index_file.cc(575)] Could not reconstruct index from disk
App version: 1.8.0 (standard, f089991e0, 25, 2022-01-31T23:47Z)
Preview build: 434
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.G975WVLU6HULD
Device brand: samsung
Device manufacturer: samsung
Device name: beyond2q
Device model: SM-G975W
Device product name: beyond2qltecs

### Tachiyomi version

Sy Preview r434

### Android version

Android 12

### Device

Galaxy S10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Im just going to close this since it will just be irrelavent/fixed whenever Feed is re-written into Compose
