### ISSUE TITLE
add to library and set category by how recent i added a series 

### ISSUE THREAD

**Issue by NotPageD** [jobobby04/TachiyomiSY#517]
### Describe your suggested feature

currently if you have a lot of categories and you add a manga, if your categories is really far you have to scroll endlessly so it would be nice and a very convenient thing if the categories position changed to the top according to how recent i added a manga to a particular category...

For example tachiyomisy already has this but it's for sources, it's called last used source and whenever you are done with a source but then wanna go back you dont have to endlessly scroll down as to click the source again...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Personally not something I am interested in adding, feel free to request it to main Tachi and SY would get it if main Tachi adds it
