### ISSUE TITLE
Yoink search bar from Takoyomi

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#519]
### Describe your suggested feature

TF's Android studio is broken, so he can't PR.

Search bar doesn't autohide, need cleanup 

A gift for Sy stable users who waited 8 months for updates!

https://github.com/CrepeTF/Takoyomi/commits/search-bar

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
https://github.com/CrepeTF/Takoyomi/compare/master...search-bar
