### ISSUE TITLE
[Feature Request] Shortcut for catagories

### ISSUE THREAD

**Issue by ghost** [jobobby04/TachiyomiSY#52]
### Why/User Benefit/User Problem
Shortcut for accessing catagories faster. (not android shortcut) inside app shortcut. 

### What/Requirements
Some kind of popup menu that shows the list of categories and goto the spicific catagorie when clicked.

**Comment by joseph619** [comment]
A drop-down like what J2K has might be possible

**Comment by joseph619** [comment]
You can swipe the tabs to quickly reach any category

**Comment by jobobby04** [comment]
I dont really feel a need for this, I will only add it to SY if it gets added to the main Tachiyomi
