### ISSUE TITLE
Reintroduce setting for app-language

### ISSUE THREAD

**Issue by SennaGehenna** [jobobby04/TachiyomiSY#521]
### Describe your suggested feature

My phone is set to german and tachiyomi was specifically set to english. The latest update enforces the app to follow the system language (with an, honestly, shoddy translation. parts are entirely untranslated)

it would be great if that option was reintroduced

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I wont re-introduce it myself, only if main Tachi re-adds it will I pull the change, but I dont think main Tachi wants to as well since it had quite a few bugs.
