### ISSUE TITLE
where did e hentai go?

### ISSUE THREAD

**Issue by NotPageD** [jobobby04/TachiyomiSY#522]
### Steps to reproduce

go to source
search for e hentai

### Expected behavior

it should be on the list of extensions

### Actual behavior

disappeared...

### Tachiyomi version

tachiyomisy r437

### Android version

android 8

### Device

Samsung A7

### Other details

also, i can still read the hentai that ive saved in my library but i can't find the extension for some reason.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by joseph619** [comment]
1. Sy doesn't use Ehentai ext, since Ehentai is built in. Go to Browse > Sources > Filter > tick Ehentai to enable

2. Enable 18+ source in Browse

**Comment by NotPageD** [comment]
i know. i have been using the built in extension for a LONG TIME, i'm not stupid and i know where to search for it and now i even downloaded the e hentai thats on the website and it says that its redundant but the built in e hentai still ISNT THERE.

**Comment by jobobby04** [comment]
Make sure you didn't disable the all language or that you didn't disable hentai in the advanced settings

**Comment by NotPageD** [comment]
ahhh, thank you very much... i think i accidently clicked the disable hentai feature button. it's all good now.
