### ISSUE TITLE
Auto download still doesn't work with merged sources

### ISSUE THREAD

**Issue by CaptainHalflife** [jobobby04/TachiyomiSY#525]
### Steps to reproduce

1. Auto download should be enable
2. Create a merged source in library
3. Update the library 

If there is an update in the merged source the bug will occur.

### Expected behavior

All chapters should be downloading.

### Actual behavior

The download queue pause and when pressing the resume button it pauses instantly.

### Tachiyomi version

Preview r437

### Android version

Android 11

### Device

Oneplus Nord ce

### Other details

I know this is a duplicate of [Issue#396](https://github.com/jobobby04/TachiyomiSY/issues/396) which I posted a while ago. It is now close and says that the bug is addressed but it seems thats not the case. 
 
I don't know if the fix is applied or will be soon sorry if that the case. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Got around to this and found it was just me being an idiot. Fixed for the next build
