### ISSUE TITLE
MyReadingManga extension doesn't work

### ISSUE THREAD

**Issue by Rubberxgum** [jobobby04/TachiyomiSY#526]
### Steps to reproduce

1. Open **browse** tab.
2. Select **MyReadingManga** source.

### Expected behavior

I should be able to browse using **MyReadingManga** extension after bypassing cloudflare.

### Actual behavior

The app freezes after pressing **MyReadingManga**.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/8138151/tachiyomi_crash_logs.txt)

### Tachiyomi version

TachiyomiSy version 1.8.1

### Android version

Android 12 (custom ROM)

### Device

Xiaomi Redmi Note 10

### Other details

**MyReadingManga** is still working with TachiyomiJ2K so I'm assuming is not a problem with the extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Rubberxgum** [comment]
Edit: I added crash logs.

**Comment by jobobby04** [comment]
The logs do not say anything

**Comment by Rubberxgum** [comment]
I have changed already it.
