### ISSUE TITLE
Enhance to Migrate Button

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#531]
### Steps to reproduce

Visit any of the Series
Navigate to Overflow and then click Migrate.
Then select Migrate.

### Expected behavior

Swiping is not required.

### Actual behavior

Swipe up and then select Migrate.

However, if I go back one step and then click Migrate,
It is not necessary to swipe.

### Crash logs

N/A

### Tachiyomi version

r441

### Android version

Android 12

### Device

Samsung Galaxy Note 10+

### Other details

https://user-images.githubusercontent.com/64928088/154063404-804b82a1-2ea0-4d94-baa7-247e410b252c.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is how how bottom sheets work, it starts half expanded, if you want you can use the Skip Pre-Migration menu option for use-cases like this.

**Comment by Mano5JP** [comment]
I have pinned source enabled. So, it wouldn't hurt to skip pre-migration. Although i might need to pin/unpin source, but that won't be auto populate. Hence need to go back that redo again.

Meanwhile, i rarely need to migrate. So, I am ok with how it is right now.
