### ISSUE TITLE
The doublepage feature does not work when using AVIF files.

### ISSUE THREAD

**Issue by sosboy-san** [jobobby04/TachiyomiSY#532]
### Steps to reproduce

Create a file in your local folder that summarizes the AVIF format.
Open that file.
Single page view is fine.
Double-page view does not work.

### Expected behavior

Double-page view is fine

### Actual behavior

File loading icon is not completed.

### Tachiyomi version

1.8.1

### Android version

Android11

### Device

Galaxy Tab S7 FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I probably wont be touching double pages for a while, test it on J2k and report it there if it happens. If J2k fixes it then I will pull the fix

**Comment by jobobby04** [comment]
Will be fixed in the next build
