### ISSUE TITLE
add chapter URL in zip comment

### ISSUE THREAD

**Issue by Efreak** [jobobby04/TachiyomiSY#534]
### Describe your suggested feature

For recognizing the source a chapter came from *outside* of tachiyomi, it would be nice to see the original URL of the chapter.

### Other details

I actually tried implementing this myself, as it should be fairly trivial but I can't trace the *chapter* URL in Downloader.kt. I found references to a page, but this is ambiguous considering many sources have individual pages for each image. I did figure out where to add it; add something like `zipOut.setComment(strComment)` where the compression level is set at line 508.

Full metadata would be even better, but this seems unlikely to happen (tachiyomiorg/tachiyomi#698 closed, tachiyomiorg/tachiyomi#4965 and https://github.com/tachiyomiorg/tachiyomi/issues/918#issuecomment-362785889 ignored, etc).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
SY doesn't handle cbz support now that main Tachi added it, feel free to open a issue in the main Tachi repo though.
