### ISSUE TITLE
Migration fails, When you interrupt the flow and perform manually.

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#535]
### Steps to reproduce

Got to any of the Series
Navigate to Migration from Overflow. Multiple Sources is enabled for the time being.
Click on Migrate.

1st Scenario

1. Wait for couple of second.
2. It will display the outcome to which we can migrate.
3. If the outcome does not meet your expectations, do a manual search.

2nd Scenario

1. Don't wait; Instead Cancel the process and do a manual search.
2. Choose the series from the source to which you want to migrate.

### Expected behavior

It should provide a outcome regardless of whether the process was automated or manual.

Note: Here 2nd scenario fails.

### Actual behavior

The first scenario is working perfectly. 

Whereas the second scenario fails to get an outcome to which I could migrate.
Where it fails.

1. Once i cancel the process and do a manual search.
2. It will search all enabled sources, and I will be able to select the series from which I want to migrate.
3. Now it gets stuck in a loop and does not display the result.

### Tachiyomi version

r441

### Android version

Android 12

### Device

Samsung Galaxy Note 10+

### Other details

This below is from 1st Scenario,

https://user-images.githubusercontent.com/64928088/155089074-2cf530e7-5a41-4ebb-a50f-37774df9e992.mp4

This below is from 2nd Scenario,

https://user-images.githubusercontent.com/64928088/155089099-e62c5551-bec5-4b63-802d-b030fd2869ab.mp4

I'm not sure if the title of this issue is appropriate.
Please feel free to change it, Syer.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Does this still happen in the latest preview?

**Comment by Mano5JP** [comment]
Not sure doesn't select any.

Ref.https://user-images.githubusercontent.com/64928088/190018582-7e8bb161-ae6e-4e15-84d2-31d2ef698585.mp4
