### ISSUE TITLE
Vertical reading mode now defaults to double page

### ISSUE THREAD

**Issue by R-N** [jobobby04/TachiyomiSY#536]
### Steps to reproduce

1. Set reading mode to vertical
2. Read a manga

### Expected behavior

Only one page loads at a time. Just like webtoon, but doesn't continuously scroll. This was the old behavior, prior to 1.8.1.

### Actual behavior

Two pages load at a time, except for cover pages.

### Tachiyomi version

1.8.1

### Android version

Android 11

### Device

Redmi Note 4 Global (Snapdragon)

### Other details

If the new default behavior was intended, please at least make an option to keep the old behavior (single page). 

Also, there is now a "continuous vertical" reading mode; how is it different from webtoon?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
You enabled double pages, go to the reader settings and disable it.

**Comment by R-N** [comment]
I think I did not.

![image](https://user-images.githubusercontent.com/1442761/155384616-78cadda8-0cea-4f03-ba2f-ba23f0a73041.png)

**Comment by R-N** [comment]
> Try looking at the settings in the reader

Yeah I attached the screenshots of my reader settings. The dual split options are off.

**Comment by R-N** [comment]
> There is a settings menu in the reader, not that menu. And duel page split != duel page view

Found it. Thanks. It was on auto. 
Shouldn't this be in the reader settings though? I mean, it's a global settings. 
This option being there is pretty much hidden... or like it was only for the manga currently being read.

![image](https://user-images.githubusercontent.com/1442761/155387027-56a6de08-6962-42c1-9b99-b4db70b0f16c.png)

Also, there's a page layout button here that I had been using to make it single page. It doesn't save, not globally and not for the manga either. Is that intentional too?

![image](https://user-images.githubusercontent.com/1442761/155387538-dbb74755-fee3-41f3-8d90-39d54069346e.png)

**Comment by jobobby04** [comment]
Ya it should be in the reader settings, I just forgot to add it.
The button is meant to be a temporary switch for manga that doesn't work well with dual page view

**Comment by R-N** [comment]
I see. Thank you very much
