### ISSUE TITLE
Automatically sync data across devices

### ISSUE THREAD

**Issue by deez-slimes** [jobobby04/TachiyomiSY#539]
### Describe your suggested feature

I've been using the app for a while and recently got a new device that I'm using alongside my existing one. I noticed that syncing data across multiple devices has been suggested before but I was wondering if you would be open to a PR for something like this if I was to make one.

This would be an incredibly simple sync system. The user would choose the types of data they want to sync (config, library, extension settings, etc), then they would provide credentials for accessing a blob storage service like Backblaze B2, or Amazon S3.

This would end up being a bit more of a power user feature because of the choice of backing storage, but I think having it as an option would still be preferable to nothing.

If you'd be interested at all let me know, I'll probably end up doing something similar on my own but if it's something that others could use I'd rather it be shared.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Because of the scope of the changes required for a feature like this, I would deny it. Unless the changes were small enough that it wouldn't make cherry-picking from main Tachi more difficult, I don't think I would merge a PR with this feature. My best suggestion would be to look into getting it in Main Tachi or look into making a fork of your own.

**Comment by deez-slimes** [comment]
> Because of the scope of the changes required for a feature like this, I would deny it. Unless the changes were small enough that it wouldn't make cherry-picking from main Tachi more difficult, I don't think I would merge a PR with this feature. My best suggestion would be to look into getting it in Main Tachi or look into making a fork of your own.

Fair enough, I'll post an issue on the main repo and get some feedback there as well. Main thing I want to avoid with this is making it a huge project. Realistically this would just end up being one additional option inside settings and a class or two to manage the IO.
