### ISSUE TITLE
Auto chapter download not working

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#540]
### Steps to reproduce

Enable automatic chapter ownload in download settings

### Expected behavior

Chapters should download when there are new chapter updates 

### Actual behavior

Manga doesn't auto download 

### Tachiyomi version

r441

### Android version

Android 12

### Device

Galaxy S20+

### Other details

Behaviour has been there since 1.8.0 update. Have to download each chapter manually. Tried enabling other settings in various combination to see if it made a difference, but to no avail. I have one category excluded from auto download, although not sure if that's relevant 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Probably a main Tachi bug if anything. SY doesnt mess with auto-downloading
