### ISSUE TITLE
[Feature Request] Toggle for local manga folder location

### ISSUE THREAD

**Issue by w4tchdoge** [jobobby04/TachiyomiSY#544]
### Describe your suggested feature

I understand that, according to issue #139 is it not possible to have a user defined location for the app to search for local manga. However, I would like to know the feasibility of instead having there be an option to toggle between the current location the app searches (`/TachiyomiSY/local`) and the location that both the original Tachiyomi app and TachiyomiJ2K searches (`/Tachiyomi/local`).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I dont really care for Local, if someone wants to PR it sure, but I probably wont work on it myself

**Comment by jobobby04** [comment]
Ill just close this since someone can add this to Main Tachi and SY will get it by default
