### ISSUE TITLE
Global update doesn't skip completed series 

### ISSUE THREAD

**Issue by Turhvjbufv** [jobobby04/TachiyomiSY#545]
### Steps to reproduce

Go to settings, in settings choose library tap on skip updating and choose "is completed series"
Then do a global update 

### Expected behavior

Does a global update only on ongoing series 

### Actual behavior

Does global update on all series 

### Tachiyomi version

App version: 1.8.1 (standard, 75a99cbc5, 30, 2022-03-13T23:27Z) Preview build: 442 Android version: 11 (SDK 30) Android build ID: RP1A.200720.012.A705FNXXU5DUI1 Device brand: samsung Device manufacturer: samsung Device name: a70q Device model: SM-A705FN Device product name: a70qxx

### Android version

Android 11

### Device

Galaxy A70

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Probably a main Tachi bug if anything
