### ISSUE TITLE
Feed (superseding Latest)

### ISSUE THREAD

**Issue by CrepeTF** [jobobby04/TachiyomiSY#547]
### Describe your suggested feature

The ability to add saved searches to Latest (now referred to as "Feed").

### Other details

@joseph619 what you think

![Screenshot_20220315-234435_Figma](https://user-images.githubusercontent.com/70870719/158491865-69b41f2b-91c4-4062-ad66-ddc3a57f68f0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by joseph619** [comment]
Interesting. Does the saved search here refer to saved queries? Also, the Browse section might also be cached so it doesn't have to load it every single time (as it rarely changes)

**Comment by CrepeTF** [comment]
Yeah it's from the saved filters when browsing

**Comment by CrepeTF** [comment]
Basically a step towards
https://github.com/jobobby04/TachiyomiSY/issues/79

**Comment by jobobby04** [comment]
Done, it will be in the next build
![6FcHVd3 1](https://user-images.githubusercontent.com/17078382/160307245-dbcdf82d-a0d9-4bde-8efd-6eae909a676d.gif)
![XajS5Gi 1](https://user-images.githubusercontent.com/17078382/160307259-b62adefb-cc27-45b1-92a5-7e6f76f80e49.gif)

**Comment by joseph619** [comment]
As per TF's mockup, the language code needs to be removed in feed (user can put language manually when naming queries)

**Comment by joseph619** [comment]
@CrepeTF what's a good description for Feed in your opinion? Creating a new banner for Sy (for Latest it was _View all the latest manga directly from Browse tab_)
