### ISSUE TITLE
Saved searches chips inconsistently visible

### ISSUE THREAD

**Issue by tanuukii** [jobobby04/TachiyomiSY#549]
### Steps to reproduce

1. Save your search filter.
2. Save another different search filter on the same source.

### Expected behavior

Chips should be visible everytime I save a search filter.

### Actual behavior

Saved searches chips disappear every 2nd, 4th, 6th.... time.

### Tachiyomi version

r443

### Android version

10

### Device

realme c11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Closing in favor of https://github.com/jobobby04/TachiyomiSY/issues/556 since it has a video of it happening
