### ISSUE TITLE
[Feature Request] Nhentai language filter, login and various other setting

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#55]
1. Filter unwanted languages permanently while Browsing, just like the website

2. Add a login option in Settings > Nhentai and shove a few open in webview buttons for various nhentai settings (quoting Discord)

**Comment by sethazazel** [comment]
It would be better if we could use default blacklist or whitelist tags. I don't wanna see 177013 anymore. Makes me sad.

**Comment by joseph619** [comment]
If it's not possible on the website, it won't be possible on the app

**Comment by sethazazel** [comment]
App already have filter feature, it can save filters for later use too. If we could set a saved filter to default it would be good enough. [NClientV2](https://github.com/Dar9586/NClientV2) This app has a good filter system for example. Visually filter tags might be more usefull than typing one by one but it will be more hard to implement.

**Comment by vongdong** [comment]
I'd like feature #1 to be implemented. Having to manually filter languages is a tiny niggle.

**Comment by jobobby04** [comment]
> 
> 
> I'd like feature #1 to be implemented. Having to manually filter languages is a tiny niggle.

You can make a saved search that you can just press for now

**Comment by jobobby04** [comment]
1 is completed by using the extension, there is now a english only version of the source

**Comment by joseph619** [comment]
Now that Nhentai has been delegated and there is no special screen left for Nhentai, this ticket can be closed. Also Nhentai doesn't have many account specifc setting anyway.
