### ISSUE TITLE
Rearranging chapters in downloads crashes app

### ISSUE THREAD

**Issue by jopejoe1** [jobobby04/TachiyomiSY#550]
### Steps to reproduce

1. Go to downloads
2. Start downloads
3. Rearrange some entries

### Expected behavior

Rearranges chapters

### Actual behavior

Rearranges chapters but also crashes sometimes.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/8324232/tachiyomi_crash_logs.txt)

### Tachiyomi version

r443

### Android version

10

### Device

samsung galaxy s10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
You have outdated and probably obsolete extensions, its probably just one of those causing a crash
