### ISSUE TITLE
[Bug] Mangadex sign in unknown error

### ISSUE THREAD

**Issue by Volern** [jobobby04/TachiyomiSY#552]
### Steps to reproduce

Go to settings and attempt to sign in to mangadex login. 

### Expected behavior

Should sign in. 

### Actual behavior

Gives an error message that states 'unknown error' and then refuses to sign in. 

### Tachiyomi version

App version: 1.8.1

### Android version

Android 11

### Device

Oneplus 8 Pro

### Other details

![Screenshot_20220325-043254__01](https://user-images.githubusercontent.com/13373330/160054835-12d474e0-77fd-42c5-b389-63e5c4ab6ee4.jpg)

I have tried numerous things like clearing cache, clearing cookies, reinstalling even though this is the first time I've used this fork of tachiyomi, force close and reopen, device restart, waited a day, tried a different account and changed connected network.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Make sure you entered the correct email and password, also try logging in with webview

**Comment by Volern** [comment]
Have logged in through Web view and it works fine. I know I'm putting the right password in as well

**Comment by jobobby04** [comment]
The new OAuth provider fixes this for the next build
