### ISSUE TITLE
Option to move or hide this section

### ISSUE THREAD

**Issue by Palloxin** [jobobby04/TachiyomiSY#554]
### Describe your suggested feature

![IMG_20220327_104715](https://user-images.githubusercontent.com/75091899/160275351-9412ac71-7cba-42e8-a11c-f41d2e510e02.jpg)
i suggest to add an option to hide or move(somewhere else, but not there) this section (screenshot) since i really don't use it and prefer just  the 3 sections there, sources, extensions and migrate; nothing else.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Im going to deny this since its too much work and it was recently improved so more people can find uses for it

**Comment by Palloxin** [comment]
can you keep it open just i case someone wants to add this feature?
