### ISSUE TITLE
Phantom saved filters disappear

### ISSUE THREAD

**Issue by Palloxin** [jobobby04/TachiyomiSY#556]
### Steps to reproduce

https://user-images.githubusercontent.com/75091899/160276968-17dce1ce-1580-44ec-814f-afd64162c2bf.mp4

1. create 3 saved filters on an extension

### Expected behavior

the app profiles saved should not disappear and appear like in the video

### Actual behavior

profiles saved should be at a fixed spot and not disappear if not deleted.

### Tachiyomi version

1.8.1

### Android version

android 8

### Device

huawei p8 lite 2017

### Other details

i tried with 3 profile with different names and it is the same

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Irellavent now due to the filter sheet rewrite
