### ISSUE TITLE
Support the option to watch sources for more than 5

### ISSUE THREAD

**Issue by hani19998** [jobobby04/TachiyomiSY#558]
### Describe your suggested feature

It must support viewing of more than 5 sources

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Watched has been rewritten in the latest preview, this does not apply anymore.

**Comment by hani19998** [comment]
@jobobby04 How can I activate the data saver option (bandwidth hero proxy)
