### ISSUE TITLE
Remove verified links from app

### ISSUE THREAD

**Issue by w4tchdoge** [jobobby04/TachiyomiSY#564]
### Describe your suggested feature

The app currently has mangadex.org set as a verified link, as such it bypasses any attempt to open a mangadex link using a different tachiyomi app

### Other details

I am on OnePlus's version of Android 12 which unfortunately does not give the end user the option to not let an app not open supported links

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
If neko and the extension remove it I will as well, but I don't see it going anywhere. The link handling on Android 12 is just bad so I personally use https://github.com/ivaniskandar/shouko/ which allows something like how Android previously did it.

**Comment by arkon** [comment]
> which unfortunately does not give the end user the option to not let an app not open supported links

Link handling is done at the extension level, not the app. Android 12 lets users disable link handling for the extension "apps" as before.

**Comment by w4tchdoge** [comment]
> Android 12 lets users disable link handling for the extension "apps" as before.

By "disable link handling" do you mean the `Open supported links` [option](https://www.xda-developers.com/files/2021/12/Screenshot_20211221-192657.jpg) in an apps settings? Because the latest version of OnePlus does not give users that option, either in the [extension "apps" settings page](https://cdn.discordapp.com/attachments/315115284853817345/960096769864245318/Screenshot_2022-04-03-09-40-56-98_fc704e6b13c4fb26bf5e411f75da84f2.jpg?size=4096) or the [actual apps settings page](https://cdn.discordapp.com/attachments/315115284853817345/960096770262695946/Screenshot_2022-04-03-09-41-10-10_fc704e6b13c4fb26bf5e411f75da84f2.jpg?size=4096)

**Comment by arkon** [comment]
Can't you just tap the checkbox?

**Comment by w4tchdoge** [comment]
> Can't you just tap the checkbox?

Nope, that does absolutely nothing.
