### ISSUE TITLE
[Preview Version] The position in the category bar is reset

### ISSUE THREAD

**Issue by AethersKz** [jobobby04/TachiyomiSY#567]
### Steps to reproduce

https://user-images.githubusercontent.com/96607644/161874837-da959a46-d691-44dd-9365-008ed3f9cf0a.mp4

I think it also happens when the library is updating

### Expected behavior

the position in the category bar remains unchanged

### Actual behavior

When entering a manga and then exiting, the position in the category bar changes

### Tachiyomi version

App version: 1.8.1 (standard, 7b7e625f5, 31, 2022-03-28T13:20Z)Preview build: 447

### Android version

Android version: 7.0 (SDK 24)

### Device

HUAWEI NXT-L09

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I believe this is a Main Tachi bug, test on main Tachi preview and open a issue there if it is.

**Comment by KazKaz90** [comment]
Yeah it also happens with the original tachiyomi app
