### ISSUE TITLE
Automatic hide on long list of tags

### ISSUE THREAD

**Issue by Palloxin** [jobobby04/TachiyomiSY#568]
### Describe your suggested feature

![IMG_20220406_094334](https://user-images.githubusercontent.com/75091899/161922731-8aff7954-7420-42be-b8ff-c8b3547b1a11.jpg)
As you can see the list of tags in the bar i ban (standard) using the save-filter feature is too long and I would like to make it easier the eventual addition of  more tags by making space in the tag bar (but also the other bars)
i suggest to make the app hide automatically in a little colored square: 
![ghggfhf](https://user-images.githubusercontent.com/75091899/161926811-af245351-e016-44d4-83c2-b73729fc99b3.png)
in this way one could add all the tags wanted without obstructing the space of the bar.
The automatic part should be triggered by the number of words typed in the bar (also other bars).
Also, clicking on the colored squadre should make the tags appear but i don't have a proper suggestion of how it should happen,  or at least, not a comfortable one.
Add a toggle option to disable this feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I personally done see a need for this, its working as its supposed to in the material spec
