### ISSUE TITLE
E-Hentai File Search integration (reverse image search for EH galleries)

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#569]
### Describe your suggested feature

It would be nice to use EH/ExH File Search (where the user uploads an image to search for galleries that contain it), without leaving TachiyomiSY or having to open WebView for that feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I believe this is out of the scope of a manga reader
