### ISSUE TITLE
Why was the horizontal screen adaptation removed?

### ISSUE THREAD

**Issue by AimerEGOIST** [jobobby04/TachiyomiSY#571]
### Steps to reproduce

1.Turn on auto-rotate
2.Rotate the screen

### Expected behavior

![IMG_20220407_210301](https://user-images.githubusercontent.com/48597571/162206649-29c92700-3609-4a4e-ab4c-3ced3d00bd83.jpg)
![IMG_20220407_210330](https://user-images.githubusercontent.com/48597571/162206670-6373e9b2-0bb9-4a15-924a-ad8146c238a7.jpg)

### Actual behavior

![IMG_20220407_210411](https://user-images.githubusercontent.com/48597571/162206730-a9ad3819-17fd-4c13-9fc2-6c934b9b0faf.jpg)
![IMG_20220407_210442](https://user-images.githubusercontent.com/48597571/162206739-779f79a3-b6e6-451d-968f-d3d352a5e2d5.jpg)

### Tachiyomi version

1.8.1

### Android version

Android 11

### Device

Xiaomi Mi pad 5 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AimerEGOIST** [comment]
Not everyone uses a mobile phone to read manga, but also uses a tablet.

**Comment by jobobby04** [comment]
Closing for the same reason as https://github.com/jobobby04/TachiyomiSY/issues/572
