### ISSUE TITLE
Requires the same horizontal screen adaptation as version 1.7.0

### ISSUE THREAD

**Issue by AimerEGOIST** [jobobby04/TachiyomiSY#572]
### Describe your suggested feature

![IMG_20220407_210301](https://user-images.githubusercontent.com/48597571/162207519-ff5ea4c6-dbd1-4b43-8552-3cedac00553e.jpg)
![IMG_20220407_210330](https://user-images.githubusercontent.com/48597571/162207540-1988bf74-8245-4716-b82e-3975bda49277.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is handled the same way as main Tachi, probably has something to do with your screen dp not being enough with the new requirements

**Comment by AimerEGOIST** [comment]
> 

It means that the horizontal screen adaptation has not been deleted, I just need to adjust the dp?

**Comment by jobobby04** [comment]
Ya

**Comment by jobobby04** [comment]
Or you can look in advanced settings, I think there was a tablet ui setting there
