### ISSUE TITLE
Show downloaded orphaned chapters

### ISSUE THREAD

**Issue by sad-kato** [jobobby04/TachiyomiSY#574]
### Steps to reproduce

Add manga from sunday webry, niconico or mangaplus to library and download the latest chapter. Wait for a new chapter to release and the downloaded chapter will disappear when the manga information is updated as the source tends to remove the chapter.

### Expected behavior

Chapters that are downloaded but removed in source should show in the manga.

### Actual behavior

Chapters disappear whenever the source deletes the chapter even though it's downloaded on device.

### Tachiyomi version

Preview r447

### Android version

Android 12

### Device

Poco F1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Tachiyom i is meant to be a 1:1 view of the website, either use another source or dont update the manga until your done reading your chapters
