### ISSUE TITLE
[Feature Request] Compact Sections on Manga Page so theres no Horizontal Scrolling

### ISSUE THREAD

**Issue by vipzzx** [jobobby04/TachiyomiSY#58]
### Why/User Benefit/User Problem
Once the tracking button is added, the other buttons are shifted over and it requires a horizontal scrolling so the "Find in another source" does not show.

This is the same with the tags of the manga. If there are a lot of tags, it requires horizontal scrolling. It will be much easier if I can see all the tags at once.

### What/Requirements
Compact the section where it is "In library" "Tracking" "Set category" "Share" "Webview" "Migrate" "Find in another source"
Maybe merge "In library" and "set category" to one so long press on "In library" will result in the category pop up like in J2K

Have all the tags show without horizontal scrolling like how it is when it is expanded even when the About section is not expanded

**Comment by vipzzx** [comment]
[Screen_Recording_20200710-030728_TachiyomiSY.zip](https://github.com/jobobby04/TachiyomiSY/files/4901660/Screen_Recording_20200710-030728_TachiyomiSY.zip)

**Comment by joseph619** [comment]
Change the ticket title to something like this

_Make the pills on manga info page compact_

**Comment by vipzzx** [comment]
Stable tachiyomi doesnt have this issue because it is a bit different. it looks like he made the fix on preview

**Comment by joseph619** [comment]
Close this ticket then

**Comment by jobobby04** [comment]
Seems like this has been taken care of
