### ISSUE TITLE
Tapping navigation

### ISSUE THREAD

**Issue by ourslfs** [jobobby04/TachiyomiSY#580]
### Describe your suggested feature

With the new update the features to disable tappings navigation was removed. Could it be brought back?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Instead of a seperate setting its now a Navigation Layout option. Set navigation layout to disabled
