### ISSUE TITLE
Crash while trying to restore backup

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#585]
### Steps to reproduce

1. Try to restore backup
2. Wait for backup to finish 

### Expected behavior

Backup is restored succesully 

### Actual behavior

App crashes before backup is restored 

### Crash logs

[2022-04-23-release.log](https://github.com/jobobby04/TachiyomiSY/files/8546261/2022-04-23-release.log)

### Tachiyomi version

r450

### Android version

Android 12

### Device

Galaxy Tab S7

### Other details

App was fresh install, library was completely empty before restore 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Does this still happen in the latest build?

**Comment by joseph619** [comment]
No idea, i didn't check. Closing
