### ISSUE TITLE
Tap/volume key navigation sometimes doesn't work

### ISSUE THREAD

**Issue by hungrypippo** [jobobby04/TachiyomiSY#587]
### Steps to reproduce

1. Select L shaped navigation or any navigation inputs
2. Try using the tapping method to change pages

### Expected behavior

It should work properly and change pages on a single tap. 

### Actual behavior

It doesnt change pages and it stays where it is. And in rare ocassion it does change pages it stop changing pages after 3-4 times. 

### Tachiyomi version

r451

### Android version

A11

### Device

Samsung Tab S7FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a main Tachi bug, it's reported so I will pull any fix they make into SY.
