### ISSUE TITLE
Autoscroll.Not Working

### ISSUE THREAD

**Issue by hungrypippo** [jobobby04/TachiyomiSY#588]
### Steps to reproduce

1. Select autoscroll input any values
2. Autoscroll doesnt work, and page is stuck. 

### Expected behavior

I expect autoscroll well, automatically scroll.

### Actual behavior

The page stays as it is, and no automatic scroll happens. 

And before anyone asks, i have done evertyhing possible. That includes reinstalling, toggling each reader settings on and off and checking. Its still the same. 

This is a new issje started on r451

### Tachiyomi version

r451

### Android version

A11

### Device

Galaxy Tab S7FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is part of the scrolling bug main Tachi has, it will be fixed when main Tachi fixes the scrolling bug.
