### ISSUE TITLE
Visual glitch in "more" tab

### ISSUE THREAD

**Issue by JudahGoldstein** [jobobby04/TachiyomiSY#593]
### Steps to reproduce

Open the more tab, no other actions needed. 

### Expected behavior

Switch should visually function as a switch 

### Actual behavior

A true/false text is on top of the switch, the switch does not move left/right when clicked. 

https://user-images.githubusercontent.com/39227048/166254307-564a3cca-f123-4518-8470-9d8de669f50a.mp4

### Tachiyomi version

r451

### Android version

Oxogen OS 12 (android 12) 

### Device

Oneplus 8 (global)

### Other details

Not fixed in r452, but the app crashes on my phone before I can properly record the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
See https://github.com/jobobby04/TachiyomiSY/issues/589
