### ISSUE TITLE
r452 crash a few seconds after starting app

### ISSUE THREAD

**Issue by JudahGoldstein** [jobobby04/TachiyomiSY#594]
### Steps to reproduce

Open app, wait 4-5 seconds

### Expected behavior

App should continue to function

### Actual behavior

Crash

### Crash logs

--------- beginning of crash
05-02 10:03:57.668 21401 21401 E AndroidRuntime: FATAL EXCEPTION: main
05-02 10:03:57.668 21401 21401 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 21401
05-02 10:03:57.668 21401 21401 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.kanade.tachiyomi.sy/eu.kanade.tachiyomi.ui.main.MainActivity}: com.pushtorefresh.storio.StorIOException: Error has occurred during Get operation. query = Query{distinct=false, table='categories', columns=[], where='', whereArgs=[], groupBy='', having='', orderBy='sort', limit='', observesTags='[]'}
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3781)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3943)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2348)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:344)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8191)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: Caused by: com.pushtorefresh.storio.StorIOException: Error has occurred during Get operation. query = Query{distinct=false, table='categories', columns=[], where='', whereArgs=[], groupBy='', having='', orderBy='sort', limit='', observesTags='[]'}
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.operations.get.PreparedGetListOfObjects.executeAsBlocking(PreparedGetListOfObjects.java:20)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibrarySettingsSheet$Grouping$InternalGroup.<init>(LibrarySettingsSheet.kt:10)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibrarySettingsSheet$Grouping.<init>(LibrarySettingsSheet.kt:3)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibrarySettingsSheet$Grouping.<init>(LibrarySettingsSheet.kt:4)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibrarySettingsSheet.<init>(LibrarySettingsSheet.kt:15)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibrarySettingsSheet.<init>(LibrarySettingsSheet.kt:4)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibraryController.onViewCreated(LibraryController.kt:18)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseController$1.postCreateView(BaseController.kt:1)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.inflate(Controller.java:12)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:17)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:1)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:22)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.setBackstack(Router.java:71)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.ConductorExtensionsKt.setRoot(ConductorExtensions.kt:4)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.onCreate$lambda-1(MainActivity.kt:7)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.$r8$lambda$RaFpmgnGEPx7TFoW4Vt_84xksbk(Unknown Source:0)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity$$ExternalSyntheticLambda5.onNavigationItemSelected(Unknown Source:4)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.google.android.material.navigation.NavigationBarView$1.onMenuItemSelected(NavigationBarView.java:3)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:1)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:5)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.google.android.material.navigation.NavigationBarView.setSelectedItemId(NavigationBarView.java:2)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.setSelectedNavItem(MainActivity.kt:2)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.onCreate(MainActivity.kt:55)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8129)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8109)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3750)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	... 12 more
05-02 10:03:57.668 21401 21401 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 14 to 13
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at androidx.sqlite.db.SupportSQLiteOpenHelper$Callback.onDowngrade(SupportSQLiteOpenHelper.java:1)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at io.requery.android.database.sqlite.RequerySQLiteOpenHelperFactory$CallbackSQLiteOpenHelper.onDowngrade(RequerySQLiteOpenHelperFactory.java:1)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:28)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:3)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:1)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.impl.DefaultStorIOSQLite$LowLevelImpl.query(DefaultStorIOSQLite.java:25)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.operations.get.DefaultGetResolver.performGet(DefaultGetResolver.java:13)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.operations.get.PreparedGetListOfObjects.executeAsBlocking(PreparedGetListOfObjects.java:6)
05-02 10:03:57.668 21401 21401 E AndroidRuntime: 	... 38 more
05-02 10:04:01.426 21532 21532 E AndroidRuntime: FATAL EXCEPTION: main
05-02 10:04:01.426 21532 21532 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 21532
05-02 10:04:01.426 21532 21532 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.kanade.tachiyomi.sy/eu.kanade.tachiyomi.ui.main.MainActivity}: com.pushtorefresh.storio.StorIOException: Error has occurred during Get operation. query = Query{distinct=false, table='categories', columns=[], where='', whereArgs=[], groupBy='', having='', orderBy='sort', limit='', observesTags='[]'}
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3781)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3943)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2348)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:344)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8191)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: Caused by: com.pushtorefresh.storio.StorIOException: Error has occurred during Get operation. query = Query{distinct=false, table='categories', columns=[], where='', whereArgs=[], groupBy='', having='', orderBy='sort', limit='', observesTags='[]'}
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.operations.get.PreparedGetListOfObjects.executeAsBlocking(PreparedGetListOfObjects.java:20)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibrarySettingsSheet$Grouping$InternalGroup.<init>(LibrarySettingsSheet.kt:10)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibrarySettingsSheet$Grouping.<init>(LibrarySettingsSheet.kt:3)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibrarySettingsSheet$Grouping.<init>(LibrarySettingsSheet.kt:4)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibrarySettingsSheet.<init>(LibrarySettingsSheet.kt:15)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibrarySettingsSheet.<init>(LibrarySettingsSheet.kt:4)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibraryController.onViewCreated(LibraryController.kt:18)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseController$1.postCreateView(BaseController.kt:1)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.inflate(Controller.java:12)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:17)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:1)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:22)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.setBackstack(Router.java:71)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.ConductorExtensionsKt.setRoot(ConductorExtensions.kt:4)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.onCreate$lambda-1(MainActivity.kt:7)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.$r8$lambda$RaFpmgnGEPx7TFoW4Vt_84xksbk(Unknown Source:0)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity$$ExternalSyntheticLambda5.onNavigationItemSelected(Unknown Source:4)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.google.android.material.navigation.NavigationBarView$1.onMenuItemSelected(NavigationBarView.java:3)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:1)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:5)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.google.android.material.navigation.NavigationBarView.setSelectedItemId(NavigationBarView.java:2)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.setSelectedNavItem(MainActivity.kt:2)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.onCreate(MainActivity.kt:55)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8129)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8109)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3750)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	... 12 more
05-02 10:04:01.426 21532 21532 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 14 to 13
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at androidx.sqlite.db.SupportSQLiteOpenHelper$Callback.onDowngrade(SupportSQLiteOpenHelper.java:1)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at io.requery.android.database.sqlite.RequerySQLiteOpenHelperFactory$CallbackSQLiteOpenHelper.onDowngrade(RequerySQLiteOpenHelperFactory.java:1)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:28)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:3)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:1)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.impl.DefaultStorIOSQLite$LowLevelImpl.query(DefaultStorIOSQLite.java:25)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.operations.get.DefaultGetResolver.performGet(DefaultGetResolver.java:13)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.operations.get.PreparedGetListOfObjects.executeAsBlocking(PreparedGetListOfObjects.java:6)
05-02 10:04:01.426 21532 21532 E AndroidRuntime: 	... 38 more
--------- beginning of system
05-02 10:49:00.595 27102 27102 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
--------- beginning of main
05-02 10:49:35.462 27102 27102 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:39.533 27102 27119 E de.tachiyomi.s: num_type_ids or num_method_ids mismatch for dex base.apk, types: expected=13758 v. actual=0, methods: expected=65377 actual=65377
05-02 10:49:58.870 27651 27651 E de.tachiyomi.s: Unknown bits set in runtime_flags: 0x40000000
05-02 10:49:58.872 27651 27651 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
05-02 10:49:58.980 27651 27707 E de.tachiyomi.s: Loaded layer handle (2407329807482143697) for layer /my_product/lib64/libcolorx-loader.so
05-02 10:49:58.980 27651 27707 E de.tachiyomi.s: Looking for entrypoint ColorX_Check
05-02 10:49:58.980 27651 27707 E de.tachiyomi.s: Found ColorX_Check for /my_product/lib64/libcolorx-loader.so
05-02 10:49:58.980 27651 27707 E de.tachiyomi.s: Check failed
05-02 10:49:59.001 27651 27651 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
05-02 10:49:59.098 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.098 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.099 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.100 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.100 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.101 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.102 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.102 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.103 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.103 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.104 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.104 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.105 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.105 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.106 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.106 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.107 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.107 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.108 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.108 27651 27651 E Parcel  : Reading a NULL string not supported here.
05-02 10:49:59.267 27651 27702 E ExtensionsLoader: dlopen failed: library "libhwuiextimpl.so" not found
05-02 10:49:59.267 27651 27651 E ExtensionsLoader: dlopen failed: library "libSchedAssistExtImpl.so" not found
05-02 10:49:59.319 27651 27651 E Parcel  : Reading a NULL string not supported here.
App version: 1.8.3 (standard, 0a908464f, 34, 2022-05-01T21:04Z)
Preview build: 452
Android version: 12 (SDK 31)
Android build ID: IN2015_11_C.16
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus8
Device model: IN2015
Device product name: OnePlus8

### Tachiyomi version

r452

### Android version

OOS12

### Device

Oneplus 8 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
It looks like its trying to downgrade the database, did you try going back to a previous preview?

**Comment by JudahGoldstein** [comment]
> It looks like its trying to downgrade the database, did you try going back to a previous preview?

Going back to the previous preview (r451) fixes the issue.

**Comment by jobobby04** [comment]
Thats weird, I would have thought it would cause the issue

**Comment by JudahGoldstein** [comment]
If there's any other logs that could be helpful just let me know.

**Comment by jobobby04** [comment]
I doubt it, I will investigate though

**Comment by jobobby04** [comment]
Should be fixed in the latest build
