### ISSUE TITLE
E-Hentai not disabling

### ISSUE THREAD

**Issue by noxan-dev** [jobobby04/TachiyomiSY#595]
### Steps to reproduce

1. Turn off e-hentai in settings

### Expected behavior

e-hentai to be disabled and not shown in sources/extensions list

### Actual behavior

e hentai not getting disabled

### Tachiyomi version

r453

### Android version

Android 10

### Device

OnePlus 6t

### Other details

This happened when I updated to the latest preview 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed in the latest build
