### ISSUE TITLE
Read chapter will be marked unread when there is new version on a website.

### ISSUE THREAD

**Issue by KaiserBh** [jobobby04/TachiyomiSY#598]
### Steps to reproduce

So this been happening for awhile and it's annoying me now. To elaborate so when a manga or manhwa in this case has been read up to like 600 chapter ish for me and everything is marked read. This works as intended but the issue is that mangadex updates their old chapter I believe therefore it reset those chapter and marked the unread this lead to old chapter being redownloaded which will fail cause for some reason it just doesn't want to download it. But the thing is, it shouldn't try to download it or marked them unread just because they updated the old chapter. 

1. 
![Screenshot_20220505-022220_GitHub](https://user-images.githubusercontent.com/41852205/166726288-e973f06c-db3c-4117-9df9-c74eaa05d5f9.jpg)

I get those notification almost everyday and I have to manually go back there and mark them read again. 

2. This is the manhwa that's causing the issue and I don't know what's the problem at this point. 
![Screenshot_20220505-022409_TachiyomiSY](https://user-images.githubusercontent.com/41852205/166726638-fc1dc7eb-2fb8-428b-9fc0-ab9a037bba3d.jpg)

### Expected behavior

What should happen is that it ignores any updates of old chapter that has been read and being pushed by mangadex, ignore as in don't mark them unread...cause I already read it, it won't change that fact. 

### Actual behavior

Will mark the updated chapter as unread.

### Tachiyomi version

App version: 1.8.3 (standard, 53a03cb00, 34, 2022-05-02T21:29Z) Preview build: 453 

### Android version

Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.G988BXXUDFVC7

### Device

Device brand: samsung Device manufacturer: samsung Device name: z3s Device model: SM-G988B Device product name: z3sxxx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Bilibili are uploading thier versions of the translations but since they are not released yet they cant be downloaded. Nothing SY can do since mangadex handles this
