### ISSUE TITLE
[Bug] App freezes /crashes while browsing certain sources in one manga page mode

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#6]
### Device information
* Tachiyomi version: TachiyomiSY Dev Build 20
* Android version: 10
* Device: Galaxy S10+

## Steps to reproduce
1. Install and open MangaPark source 
2. Try to scroll up and down

### Expected behavior
App shouldn't freeze.

### Actual behavior
App freezes and often crashes.

**Comment by jobobby04** [comment]
Fixed in https://github.com/jobobby04/TachiyomiSY/commit/51c8430e9c17f0958f8e33f38ff01d75ce04bdc1
