### ISSUE TITLE
App freezes upon tapping browse tab

### ISSUE THREAD

**Issue by joseph15two** [jobobby04/TachiyomiSY#600]
### Steps to reproduce

1. Open the app.
2. Tap the browse tab
3. Try to open any source

### Expected behavior

Sources should open and show a list of mangas

### Actual behavior

As soon as the browse tab is tapped, the whole app freezes and cannot tap anything. App displays, "App is not responding" dialogue. I have to force close it. Reopening gives the same result

### Tachiyomi version

r454

### Android version

Android 8.0

### Device

LG G5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Crash logs?

**Comment by jobobby04** [comment]
This is probably fixed in the preview
