### ISSUE TITLE
Return option to keep navbar on scrren

### ISSUE THREAD

**Issue by DatHypnoboi** [jobobby04/TachiyomiSY#601]
### Describe your suggested feature

Previously, it was possible to keep the navbar on the screen when scrolling down, but at some point this was removed in a preview version. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Bmswad1** [comment]
This was removed in tha main app at some point
And they are migrating to compose
So we should wait till they finish it before suggesting any changes to the ui

**Comment by jobobby04** [comment]
I am not going to re-add it myself, it's on the main app to add it again.
