### ISSUE TITLE
Option to drag and drop multiple series at once

### ISSUE THREAD

**Issue by ciel3110** [jobobby04/TachiyomiSY#603]
### Describe your suggested feature

There's drag and drop feature when sorting library, it would be better if we could choose/select multiple series then drag&drop them as we want at once instead of drag&drop one single manga at time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
Didn't Sy remove this feature recently?

**Comment by jobobby04** [comment]
Yep, in todays build
