### ISSUE TITLE
Saving a combined page on landscape

### ISSUE THREAD

**Issue by cryonicles** [jobobby04/TachiyomiSY#604]
### Steps to reproduce

so trying to save a combined page on landscape mode but as the screenshot shows, I couldn't scroll to the 'Save combined pages' button as it's in the bottom below these other buttons.

### Expected behavior

I expected it to be able to scroll to the desired button

### Actual behavior

it just stopped once it reached the top of my screen

### Crash logs

![Screenshot_2022-05-22-23-53-37-05_a603e4da04bada03cae438f177815547](https://user-images.githubusercontent.com/106028703/169706860-fed8fd7d-6361-45d7-a7e8-65068cf72894.jpg)

### Tachiyomi version

Stable 1.8.3

### Android version

12

### Device

Realme GT Master

### Other details

was suggested to come here from the discord

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed in the new build
