### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by momobobe** [jobobby04/TachiyomiSY#607]
### Describe your suggested feature

Hello,

Would you approve to have the app included to F-Droid? I see there were some understandings and conflicts between the Tachiyomi community and F-Droid, but eventually Tachiyomi still has been continuously listed and updated there till now, so I think there is nothing really blocking its forks getting included there. If you're not absolutely opposite to it, then the process wouldn't take too much time since their team would help you.

### Other details

Thanks for your attention and if you're interested feel free to contact github.com/linsui

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I would have to say no, its not worth the issues it brings:
1. Required a reinstall if someone wants to move to/from F-Droid to the github version because of signing differences.
2. Updates must be handeled by F-Droid, Tachi/SY may or may not properly handle them.
3. In general the way Tachi extensions work is a grey area for F-Droid and copywrite laws.

This is a fork and I personally don't want people to bring me said issues that Tachi already has to deal with, so I am going to have to deny it.

**Comment by momobobe** [comment]
Thanks for your quick response, and of course I understand and respect your idea. However, just to clarify it, I'd like to say a little bit more.

>     1. Required a reinstall if someone wants to move to/from F-Droid to the github version because of signing differences.

Actually not a must if they can reproduce your builds. They only sign it when their build is different from yours, otherwise they can just verify and pick up builds signed by you. 

>     2. Updates must be handeled by F-Droid, Tachi/SY may or may not properly handle them.

Not a hard requirement, and not an issue for the case of reproducible builds.

>     3. In general the way Tachi extensions work is a grey area for F-Droid and copywrite laws.

Kinda, but since Tachiyomi has successfully dealt with it, its forks should be fine now with no more drama.

Anyway, if you got your mind changed, feel free to reopen this and contact github.com/linsui for further assistance. Thanks again for your attention.
