### ISSUE TITLE
Downloaded manga have their folders renamed after some time

### ISSUE THREAD

**Issue by INAGU1** [jobobby04/TachiyomiSY#608]
### Steps to reproduce

1. Manually or auto-download a chapter for a series from any source.
2. Within a day, that chapter and any chapters downloaded before that point for that series will stop being detected as downloaded
3. Verify that the files are still present on my phone, but the folder they are in has been renamed.

### Expected behavior

Chapter downloads should be persistently detected.

### Actual behavior

Since some time around mid-May, Tachiyomi has become blind to downloaded chapters not long after they're downloaded, despite the files still being present.

For some reason, the manga folder the downloaded files are stored in gets renamed to end with (1), e.g. Kono Oto Tomare! (1) . If I try to download the files again, they are initially downloaded into a correctly named folder, but then eventually get moved into a new numbered folder, e.g. Kono Oto Tomare! (2).

### Tachiyomi version

App version: 1.8.3 (standard, c4dfbd476, 35, 2022-05-25T00:05Z) Preview build 456

### Android version

12

### Device

Samsung Galaxy S10 Plus (SM-G975F)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Try cleaning your download folder, if its on a SD card the card may be failing. Otherwise try deleting the whole downloads folder and let Tachi re-create it.
