### ISSUE TITLE
[Feature Request] Grouping library by tag

### ISSUE THREAD

**Issue by sethazazel** [jobobby04/TachiyomiSY#61]
### Why/User Benefit/User Problem
I think this will be very usefull for choosing which manga to read. It is handier than searching for tag.

### What/Requirements
TachiyomiJ2K and Neko already have this feature and it is very usefull. Neko and TachiyomiJ2K have 3 options for grouping. Tag, status and tracking status or Sources. We can use grouping by tag, status and Sources. It could be hard to implement because the other 2 apps use diffrent design.

**Comment by vipzzx** [comment]
pretty much almost impossible imo since SY uses tabs while J2K and Neko doesnt

**Comment by joseph619** [comment]
What Vippz said, this is likely impossible with tab UI which Sy has. J2K can group entirely library because it's all on the same screen. This wouldn't make sense on tabs, since the categories here are meant to be independent and separate views.

**Comment by sethazazel** [comment]
This makes sense. Thank you guys for explaining it.
