### ISSUE TITLE
Add option to categorize history by library categories/manual

### ISSUE THREAD

**Issue by cheesuscrisp** [jobobby04/TachiyomiSY#610]
### Describe your suggested feature

Maybe add categorization by sources (as mentioned in another issue), by library categories, or by manual user input. Also add an uncategorized tab for reading manga not in any categories. 

Side issue: maybe add an option for toggling between the new history in preview 456 of 1.8.3(where clicking on chapter title continues) and old history in non preview versions of 1.8.3 (where clicking on title opened details and had a seperate continue button) and the new proposed history settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I am going to deny this. Doesnt seem like something I would be interested in adding. Maybe open a issue in the main Tachi repo
