### ISSUE TITLE
Add option to view Bandwidth hero data saver stats

### ISSUE THREAD

**Issue by suhan-paradkar** [jobobby04/TachiyomiSY#611]
### Describe your suggested feature

The chrome extension actually gives the stats of data compression... I guess its better to be added inside the app too?
![Screenshot_2022-06-04-11-15-49-91](https://user-images.githubusercontent.com/76830230/171986364-e7f6f253-ee10-4ba6-8ed2-b86430cf4771.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Im personally finished with the bandwith hero proxy. It works and thats all I want it to do, I wont be personally working on new features for it since I dont actually use it.
