### ISSUE TITLE
[BUG][Preview Version] Browse->Extensions plugin page drop-down refresh failed

### ISSUE THREAD

**Issue by Howard20181** [jobobby04/TachiyomiSY#612]
### Steps to reproduce

After pulling down and releasing, nothing happens.

### Expected behavior

The dropdown should refresh the extension plugin page

### Actual behavior

https://user-images.githubusercontent.com/40033067/171992590-ebe07a1e-3524-40ff-9021-1df5d917a1ea.mp4

### Crash logs

N/A

### Tachiyomi version

r456

### Android version

Android 11

### Device

Xiaomi 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Its most likely refreshing really fast. Are you having issues seeing the avalible extensions?

**Comment by Howard20181** [comment]
The available extensions appear to load normally.
But this dropdown refresh is a bit odd, should add logging to see if the refresh is being triggered.

**Comment by jobobby04** [comment]
Thats on main Tachi then. I dont mess with the extension loading so UX like that should be handeled by Main Tachi

**Comment by Howard20181** [comment]
Confirm that this behavior comes from upstream.
Tachiyomi Preview r4430 does not have this behavior, but r4445 has it.
Maybe it is by design. to prevent multiple refreshes in a short period of time?
