### ISSUE TITLE
Chapters not marked as read on updates tab

### ISSUE THREAD

**Issue by DatHypnoboi** [jobobby04/TachiyomiSY#613]
### Steps to reproduce

1. Read chapter from updates tab
2. Don't leave updates tab after finishing chapter
3. Chapter is not marked as read until you navigate to another tab then back

### Expected behavior

Chapter should be marked as read shortly after exiting the reader

### Actual behavior

Chapter is not marked as read until you switch tabs then go back to updates tab

### Tachiyomi version

Preview r457

### Android version

Android 12

### Device

Google Pixel 3a XL

### Other details

When trying to bookmark a chapter that hasn't been marked read, it will be bookmarked as usual, but permanently remain unread even after re-navigating to updates page

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is the effect of gradually migrating to a new database framework. So nothing I can do until main Tachi finishes the migration.
