### ISSUE TITLE
Mass migration limit per source 

### ISSUE THREAD

**Issue by CVIUS** [jobobby04/TachiyomiSY#616]
### Describe your suggested feature

`MANGA_PER_SOURCE_QUEUE_WARNING_THRESHOLD` should be enough

### Other details

Limit DDoS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This goes against what mass migration is even for tho. It's meant for **mass** migration to another source.
