### ISSUE TITLE
[Bug] important feature removed in latest release

### ISSUE THREAD

**Issue by crusaside** [jobobby04/TachiyomiSY#62]
### Device information
* Tachiyomi version: preview r165 tachi sy
* Android version: 10
* Device: realme 3 Pro

## Steps to reproduce
1. go to settings for enabling original tachiyomi view once a manga is selected from library ( the option is now no longer present)

### Expected behavior
3 tabs should be present
1.Overview(with manga's description and the "see recommendations" button,
2. Chapters, and
3. Tracking.

### Actual behavior
Normal TachiSY view is observed with only one tab where all chapters are listed below the manga description and the tracking has a small button just right there.

**Comment by jobobby04** [comment]
It has been removed because the latest Tachiyomi preview has moved to a combined manga page, and I moved my implementation to theirs. 
TachiyomiSY will be moving forward with only the combined manga page, as the only reason I had that option was because I decided to keep the original Tachiyomi implementation as a option.

**Comment by crusaside** [comment]
> It has been removed because the latest Tachiyomi preview has moved to a combined manga page, and I moved my implementation to theirs.
> TachiyomiSY will be moving forward with only the combined manga page, as the only reason I had that option was because I decided to keep the original Tachiyomi implementation as a option.

dang. this is sad. don't get me wrong, i know u're working really hard and can only fork off of original Tachiyomi. i am enjoying tachi SY very much! it's just that the earlier view was a lot less clustered and congested. 
i just have a small query. if i keep installed the preview r155, am i gonna face any problem in the future?

**Comment by jobobby04** [comment]
> > It has been removed because the latest Tachiyomi preview has moved to a combined manga page, and I moved my implementation to theirs.
> > TachiyomiSY will be moving forward with only the combined manga page, as the only reason I had that option was because I decided to keep the original Tachiyomi implementation as a option.
> 
> dang. this is sad. don't get me wrong, i know u're working really hard and can only fork off of original Tachiyomi. i am enjoying tachi SY very much! it's just that the earlier view was a lot less clustered and congested. 
> i just have a small query. if i keep installed the preview r155, am i gonna face any problem in the future?

Likely at some point, but not anytime soon. The only really issue you will face is continuous app update notifications

**Comment by crusaside** [comment]
> > > It has been removed because the latest Tachiyomi preview has moved to a combined manga page, and I moved my implementation to theirs.
> > > TachiyomiSY will be moving forward with only the combined manga page, as the only reason I had that option was because I decided to keep the original Tachiyomi implementation as a option.
> > 
> > 
> > dang. this is sad. don't get me wrong, i know u're working really hard and can only fork off of original Tachiyomi. i am enjoying tachi SY very much! it's just that the earlier view was a lot less clustered and congested.
> > i just have a small query. if i keep installed the preview r155, am i gonna face any problem in the future?
> 
> Likely at some point, but not anytime soon. The only really issue you will face is continuous app update notifications
thank heavens. that's not a big deal. all the best for the future! i'll definitely aid you with funds once i get a job!
