### ISSUE TITLE
"Mark previous as read" marking only some non-previous chapters as read

### ISSUE THREAD

**Issue by bb010g** [jobobby04/TachiyomiSY#621]
### Steps to reproduce

1. Install "Questionable Content" source.
2. Add "Questionable Content" to library.
3. Open "Questionable Content" from the library.
4. Ensure: no filtering, sorting descending by source, and displaying chapter title.
5. Select all chapters, and mark as unread.
6. Select chapter "Comic 4394: Clever Reference".
7. Invoke "Mark previous as unread" from the contextual bar.

### Expected behavior

All visible chapters below the selected chapter should be marked as read.

### Actual behavior

"Comic 1" through "Comic 1159" are marked as read, and "Comic 4465" through "Comic 4815" (the most recent chapter) are marked as read.

### Tachiyomi version

1.8.3 (standard, 3805f3a16, 35, 2022-06-26T00:36Z); Preview build: 462

### Android version

12 (SDK 32)

### Device

Brand: google; Manufacturer: Google; Name: redfin; Model: Pixel 5; Product name: redfin

### Other details

Android build ID: SQ3A.220605.009.A1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I'm currently not accepting bug reports for preview builds since it's going through a massive rewrite on Tachi main's end. If you can reproduce it in Tachi main report it there, otherwise wait until the rewrite is over and report it if it still happens.

**Comment by bb010g** [comment]
Could this be kept open at least with a relevant tag until the issue is resolved? That way I don't have to file again if the issue persists past the rewrite.

**Comment by jobobby04** [comment]
No, 90% sure it's not a SY specific issue in the first place. So even if it was kept open main Tachi should be the one to fix it.

**Comment by bb010g** [comment]
Could that be noted in the issue template, then? The normal open source convention is to report issues to downstream and then let them escalate to upstream (or tell you to escalate, that sort of thing). The issue normally remains open because it's still an extent behavior in downstream, independent of upstream's issue tracker.

I get that you don't want to operate that way here, but I think the deviation from norms would be good to note. E.g. "if you're on unstable, go reproduce on unstable Tachiyomi, and only open an issue here if it's unique to TachiyomiSY unstable". (Except that still has an issue of potentially multiple users having to track downstream's application of upstream patches to know when to retest downstream and open an issue in the first place.)

**Comment by jobobby04** [comment]
Added a small disclaimer in the issue template 👍
