### ISSUE TITLE
Library search: Filter EH/ExH galleries by expunged

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#622]
### Describe your suggested feature

Is there any way to do a local library search returning only 'EH/ExH expunged galleries' in the results?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Adding a (invisible) tag for that in the next build. So whenever a gallery updates it will have the invisible tag. You can then search expunged or visibility:yes and it will show galleries that are visible and such.

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/27733aba02896502835200a327f0481960de101d
Note that nothing will realy happen until all galleries have been re-tagged by the gallery updater. I suggest resetting all galleries aged flag in the debug menu so all galleries will get it added eventially.
