### ISSUE TITLE
EH/ExH search: Option to auto load search parameters/filters from last search, instead of resetting

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#623]
### Describe your suggested feature

Could be a toggle to set the behavior of the search parameters/filters' initialization when I start a brand new search (from the Browse screen).
- Reset filters (current behavior)
- Load filters from the last search (those filters would need to be saved somewhere)

For example, I usually want to make ExH searches with "Show Expunged Galleries" setting always enabled.
But sometimes, I forget that the setting is auto-disabled every time I make a brand new search. And I have to go to the Filter options frequently, just to enable that setting again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I would suggest just using a Feed/Source Feed that has with that search. After clicking that feed it loads those parameters so you can just add and go from there.
