### ISSUE TITLE
Unable to sync EH favorites after upgrading to Preview r462

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#624]
### Steps to reproduce

Start an EH favorites sync.

### Expected behavior

The sync runs normally, on every local/remote gallery with changes.

### Actual behavior

The sync never advances past the first gallery. ("Adding gallery 1 of 141 to local library")

### Tachiyomi version

Preview r462

### Android version

Android 7.1.1

### Device

Samsung Galaxy J2 Pro 2018 (SM-J250M)

### Other details

For some reason, the first sync steps ("downloading favorites from remote server", "calculating remote/local changes") seem to be slower since I upgraded to r462 (I upgraded today).

Then, the sync seems to get stuck on the first gallery ("Adding gallery 1 of 141 to local library"), every time I try to sync.
During my multiple tests, the sync tried to add 2 different galleries as gallery 1. The sync never got past gallery 1, regardless of what gallery it was. 

Were there any recent changes to the EH favorites sync logic?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I'm currently not accepting bug reports for preview builds since it's going through a massive rewrite on Tachi main's end, and so bugs that happen during the rewrite are unlikely to happen after it. You can wait until the rewrite is over and report it if it still happens.

**Comment by lucky777709** [comment]
Ok, understood. I read your post just after sending another bug report, sorry about that.
I'll report those bugs again if they happen after the rewrite.
