### ISSUE TITLE
History screen: Clicking on gallery cover is opening another unrelated gallery (Preview r462)

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#625]
### Steps to reproduce

Go to the History screen. Click on a gallery's cover.

### Expected behavior

The app should open the "main info/chapter select screen" of the gallery.

### Actual behavior

The app is opening the "main info/chapter select screen" of another (unrelated) gallery.

### Tachiyomi version

Preview r462

### Android version

Android 7.1.1

### Device

Samsung Galaxy J2 Pro 2018 (SM-J250M)

### Other details

Clicking the gallery name opens the last read chapter of the correct gallery. (correct behavior)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Its a main Tachi bug. I will open a PR to fix it there since its a easy fix.
