### ISSUE TITLE
Stuck in loading while browsing 

### ISSUE THREAD

**Issue by CaptainHalflife** [jobobby04/TachiyomiSY#631]
### Steps to reproduce

1. Choose a source to browse (can be any source)
2. Tap on either latest or browse
3. Tap on any manga
4. Press back

### Expected behavior

It should send me back to the previous menu

### Actual behavior

The app keep loading 

### Tachiyomi version

Preview r464

### Android version

Android 11

### Device

Oneplus Nord ce

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a known main Tachi bug

**Comment by CaptainHalflife** [comment]
Ok idk why when i've test it on the latest tacho preview i didn't encounter the bug

**Comment by jobobby04** [comment]
Someone asked about the same bug in discord and they said it was known. Might be because the changes are not in the latest preview yet
