### ISSUE TITLE
The ability to select which categories you wanna backup.

### ISSUE THREAD

**Issue by NotPageD** [jobobby04/TachiyomiSY#632]
### Describe your suggested feature

It should work similarly to migration in which you choose which manga you wanna migrate but the difference with this is that, it's categories.

### Other details

Currently we can only backup all of our manga or none at all which is already very good feature but having the ability to choose which categories you wanna backup or not makes it a lot better for people who has thousands of mangas in their library like me. 

It takes you literally hours to restore the backup and when it crashes mid restore you have to redo and wait for it again! So yeah, i think this would be a good feature to have.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Personally not interested in this, so I am going to close it, SY would probably only get it if main Tachi adds it. Also if your backup restore is crashing then there is some underlying issue that needs to be fixed.
