### ISSUE TITLE
Orientation Settings per Reading Mode

### ISSUE THREAD

**Issue by playful1510** [jobobby04/TachiyomiSY#641]
### Describe your suggested feature

It would be really cool if we could have specific orientations assignable to specific reading modes, e.g. Right-to-left is set to be forced landscape while Webtoon is forced portrait. I know that there's the default rotation type, but that's really only good for one or the other. I have to manually set the orientation for every webtoon I read, which is frustrating. I know that there's #232 but that's not exactly what I'm talking about, as that's specific to a single series.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I don't think this is worth implementing, maybe open a issue with main Tachi and if it gets it then SY will get it by default
