### ISSUE TITLE
Configurable number of rows for gallery preview

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#643]
### Describe your suggested feature

Currently there are 4 rows for gallery preview in manga description screen, which is too many. As discussed on discord, request to make the row number configurable (like 1 or 3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
@jobobby04 is it possible to disable the gallery image preview for next stable release, until the row count is configurable?

**Comment by jobobby04** [comment]
Nope

**Comment by LetrixZ** [comment]
Any update on this?
