### ISSUE TITLE
After reading the latest chapter, the unread display on the bookshelf has not been updated

### ISSUE THREAD

**Issue by hanxin1997** [jobobby04/TachiyomiSY#648]
### Steps to reproduce

Return to the bookshelf after reading

### Expected behavior

The unread count on the bookshelf is displayed normally

### Actual behavior

The unread display on the shelf is the state before reading

### Tachiyomi version

TachiyomiSY Dev Build 471

### Android version

 Android 12

### Device

miui13

### Other details

The unread display of the bookshelf has not been updated. You need to switch to another page and then switch back to the bookshelf to display it normally
TachiyomiSY 1.8.4 Stable version is normal 

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Known main Tachi issue
