### ISSUE TITLE
Hope TachiyomiSY supports the migration function of tachiyomiJ2K

### ISSUE THREAD

**Issue by hanxin1997** [jobobby04/TachiyomiSY#649]
### Describe your suggested feature

It is hoped that comics with the same name and different image sources can be directly migrated from the old reading comic data to the new comic data

### Other details

Like tachiyomiJ2K's

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Did you explore the app? It exists.

**Comment by hanxin1997** [comment]
> 你浏览过这个应用程序吗？它存在。
![tachi](https://user-images.githubusercontent.com/58620096/182327029-b70d1786-7521-447f-8f09-8a18787026a2.jpg)
![tachi1](https://user-images.githubusercontent.com/58620096/182327049-56c5c305-8442-4ead-a455-44e900f76680.jpg)
In fact, I hope the migrate function on this image helps with my single manga migration
