### ISSUE TITLE
[Feature Request] Make it possible to configure the start reading button to open the last chapter

### ISSUE THREAD

**Issue by randolph24** [jobobby04/TachiyomiSY#65]
### Why/User Benefit/User Problem
In EH the chapter function is not used for chapters but for the individual revisions of the gallery. For this reason you will want to open the last/newest chapter in almost all cases for these sources. However, the floating start button opens the oldest/first unread chapter which is undesirable for this source. A configuration option to reverse this behaviour would make it possible to start reading the content in EH/EXH without scrolling to the end of the page first.

Translated with www.DeepL.com/Translator (free version)

### What/Requirements
A new option in the settings (maybe EH/EXH exclusive) to reverse the behaviour of the start button to open the newest/last chapter instead.

![20200718_153639](https://user-images.githubusercontent.com/68469969/87854279-1f997880-c911-11ea-95c5-e111fe559911.jpg)

**Comment by jobobby04** [comment]
This will be in the next release
