### ISSUE TITLE
Exhentai not resuming latest gallery version (for multi chapter galleries)

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#651]
### Steps to reproduce

1. Open an Exhentai favourite with multiple gallery versions
2. Click resume

### Expected behavior

The latest gallery version/chapter should open (ie. if there are 38 versions/chapters for the gallery, resume should open the 38th chapter)

### Actual behavior

The first unread gallery version is opened (if I had read until 31st gallery version/chapter, reader now opens the 31st chapter instead of chapter 38)

### Tachiyomi version

471

### Android version

Android 12

### Device

Galaxy S10+

### Other details

Potentially related to #642, this issue started from 457 onwards, after manga info screen was migrated to compose 

I have attached a video for example below 

https://user-images.githubusercontent.com/34897862/183115488-27a8fe7e-7e35-4758-8182-bbb092ea9f84.mp4

Can provide back up file for reproduction if necessary 

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Seems it got lost in the rewrite, fixed for next build 😄
