### ISSUE TITLE
Toongod.com not working

### ISSUE THREAD

**Issue by Israld** [jobobby04/TachiyomiSY#652]
### Steps to reproduce

1. instal the latest version
2. install extension
3. still not working

### Expected behavior

Showed the list of manga

### Actual behavior

manga list not showed

![Screenshot (Aug 12, 2022 03_05_02)](https://user-images.githubusercontent.com/110901776/184235861-52cfec8e-ec10-454d-9de8-0fc94e84f7f6.png)

### Tachiyomi version

1.8.4

### Android version

Android 10

### Device

Xperia xz3

### Other details

the same problem accour in Tachiyomi

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
> the same problem accour in Tachiyomi
This should have been opened here https://github.com/tachiyomiorg/tachiyomi-extensions
