### ISSUE TITLE
Open from browser broken TachiyomiSY

### ISSUE THREAD

**Issue by e-shl** [jobobby04/TachiyomiSY#656]
### Steps to reproduce

Open manga from browser

### Expected behavior

Display opened manga
![Screenshot_20220815-161239059.jpg](https://user-images.githubusercontent.com/35057681/184625449-8a609600-8ca2-4841-82bb-5e3aea96a707.jpg)

### Actual behavior

Display black screen
![Screenshot_20220815-161228041.jpg](https://user-images.githubusercontent.com/35057681/184625471-30615d8d-cf9f-49c4-b026-6ef839949d06.jpg)

### Tachiyomi version

p474

### Android version

11

### Device

Mi9(LOS)

### Other details

Does not work only if SY is not started manually (should be open in recent tasks)

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Is global search pinned sources enabled, without that source being pinned?

**Comment by e-shl** [comment]
@jobobby04 it looks like this has been fixed in the newer preview
