### ISSUE TITLE
Feed page with little padding is cutting off last source

### ISSUE THREAD

**Issue by Blackklegend** [jobobby04/TachiyomiSY#658]
### Steps to reproduce

Go to feed page
add some sources, enough to fill the screen, around 3 or 4
Scroll all the way down
You'll see that the last source is chopped off and not displaying properly 
![Screenshot_20220816-235235](https://user-images.githubusercontent.com/73979580/185024118-c9fea943-e139-4803-a2cc-efbe4c09b5f3.png)

### Expected behavior

The last source should show up properly like the above sources 

### Actual behavior

It gets chopped off and hides titles and bits of covers, sometimes it even chops off the whole source 

### Tachiyomi version

App version: 1.8.5 (standard, 7ef429176, 38, 2022-08-14T22:33Z) Preview build: 474

### Android version

Android version: 11 (SDK 30) Android build ID: RPXS31.Q2-58-17-7-2

### Device

Device brand: motorola 
Device manufacturer: motorola 
Device name: guamp 
Device model: moto g(9) play 
Device product name: guamp_retail

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Ya I've tried to fix it but nothing I did worked. So I'm just going to wait until main Tachi converts global search to the new UI framework and use the code from there to rewrite the Feed UI

**Comment by Blackklegend** [comment]
Oh I see. I thought someone might've already noticed it but didn't see any issue regarding it so decided to make sure the dev team was aware. Thanks for your time :)

**Comment by jobobby04** [comment]
Fixed in the preview 👍

**Comment by Blackklegend** [comment]
fucking legend
