### ISSUE TITLE
Always show chapter transition does not work

### ISSUE THREAD

**Issue by NotPageD** [jobobby04/TachiyomiSY#661]
### Steps to reproduce

Toggle off the always shoe chapter transition
Just go through any series 

### Expected behavior

Do not show chapter transition when the next chaptee has been loaded or downloaded

### Actual behavior

Still shows chapter transition

### Tachiyomi version

TachiyomiSY 1.8.5

### Android version

Android 11

### Device

Vivo Y33T

### Other details

Its uncommon for normal series to encounter this problem but if you find a series that has single page chapters 90% of the time the chapter transition still shows even though the next chapter has been downloaded.

I tried this bug on the original tachiyomi app and it works perfectly fine there and i found this thread on their github https://github.com/tachiyomiorg/tachiyomi/issues/3079 it might be of some help fixing the bug.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Are you using double pages?

**Comment by NotPageD** [comment]
@jobobby04 nope

**Comment by jobobby04** [comment]
It seems it's a main Tachi thing
Arkon said:
> It'll still show it if it can't load the next chapter early enough for whatever reason
