### ISSUE TITLE
Can’t download any extension 

### ISSUE THREAD

**Issue by 7allom** [jobobby04/TachiyomiSY#662]
### Steps to reproduce

![Screenshot_20220819-165715](https://user-images.githubusercontent.com/97411710/185634896-d260001a-c6b9-458c-b919-20ba38670b41.jpg)

### Expected behavior

. 

### Actual behavior

. 

### Tachiyomi version

App version: 1.8.4 

### Android version

Android version: 8.1.0

### Device

Device model: DUB-LX1 Huawei Y7 (2019)

### Other details

I have another issue that i Can’t update tachiyomi to 1.8.5

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This sounds like a device issue, not something to do with SY since you can't update the app as well.

You can ask for help in the support channel of the discord https://discord.gg/tachiyomi

**Comment by 7allom** [comment]
> This sounds like a device issue, not something to do with SY since you can't update the app as well.
> 
> You can ask for help in the support channel of the discord https://discord.gg/tachiyomi

Ok thanks
