### ISSUE TITLE
Append EH "gallery ID" to downloaded gallery's folder name, to avoid accidental overwrites caused by non-unique gallery names

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#667]
### Describe your suggested feature

I frequently download EH galleries to my device. But there are many instances of multiple EH galleries having the exact same name, as galleries' names aren't unique (although their IDs are unique).

So, I usually rename the gallery's folder after the download finishes, manually appending the gallery ID to the folder name, to avoid later accidentally overwriting a previous gallery I downloaded with a newer one.
I copy the gallery ID value from the "ⓘ More info" screen.

Now, I thought about having the option to _automatically_ append the gallery ID number to the downloaded gallery's folder name.
This could be a very useful feature, to avoid overwrite collisions with same-named galleries.

It would be nice if the gallery ID could be appended to the downloaded galleries folders (located on `TachiyomiSY\downloads`) and also to the "saved images" folders (located on `Pictures\TachiyomiSY`).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I added the gallery id as the scanlator and hidden it from the UI, should fit your needs

**Comment by lucky777709** [comment]
> I added the gallery id as the scanlator and hidden it from the UI, should fit your needs

I updated Tachi to Preview r479, but for me, download folders are still the same as before (no gallery ID appended to the folder name), both when downloading entire chapters (`TachiyomiSY\downloads`) and when downloading single images (`Pictures\TachiyomiSY`).

Maybe I'm missing some step? I didn't understand this "gallery id as the scanlator" feature you mentioned.

**Comment by jobobby04** [comment]
You have to refresh the chapter list to set the scanlator field

**Comment by lucky777709** [comment]
Thanks for the tip! 😄

Just doing a "pull to refresh" on the gallery's main screen (chapter list) did the trick for my existing galleries (newer galleries don't need this step 👍).
And it even works for my already downloaded galleries: the refresh auto-renames the downloaded chapter folder's name, prepending the gallery ID to it, without me needing to re-download the galleries. I appreciate this feature!

I like the extra organization that this feature gave to the downloaded galleries' folders:
- The chapter folder names having the gallery ID prepended (instead of appended at the end of the name) avoids issues with very long gallery names. This also makes the IDs easily visible at a glance (important for mobile file explorers).
- Also, the same-named galleries are now neatly organized into a common parent folder, separated by their IDs on the chapter folders.
- And the parent gallery folders still have the same names as before (gallery name only), so I can still search for them in alphabetic order. 👍 

I'd be grateful if this same folder structure could also be enabled on the Reader-downloaded images (`Pictures\TachiyomiSY`).
Perhaps as a sister option to `Reader -> Actions -> Save pages into separate folders`?
But in case that's not possible, no problem. I'm thankful for having this feature on the downloaded chapters, at least. 😄

**Comment by jobobby04** [comment]
👍
I was able to take advantage of the existing scanlator handling for the chapter downloads. It would be another thing entirely to make something for saved images. I don't think it's priority so I'll mark this as completed for now

**Comment by yooman1213** [comment]
@jobobby04 could you please also added this to nhentai

I have 2 library with 2 same name but different content and id
