### ISSUE TITLE
Offer to migrate before uninstalling in uses extension

### ISSUE THREAD

**Issue by binyaminyblatt** [jobobby04/TachiyomiSY#668]
### Describe your suggested feature

Extensions get deprecated and deleted all the time and it's really annoying and hard to keep track of what's in use in my library so I feel it would be really useful that when I go to uninstall a in-use extension it offers to migrate my library before it uninstalls
I have a extremely large Library and I try to spread it all over as many extensions as I can so it doesn't cause any issues I also don't update it very often but that's something else

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Thats what the Migrate menu is for. I don't think adding a dialog for this is very useful since you can just go and migrate those from the migrate menu after.
