### ISSUE TITLE
[Feature Request] Toggle to disable zoom-ing in reader view

### ISSUE THREAD

**Issue by DarkAlphaSete** [jobobby04/TachiyomiSY#67]
### Why/User Benefit/User Problem
QoL feature. When reading fast-paced webtoons, I usually scroll bit by bit, a lot, which means a lot of tap-sliding up. This, sometimes, gets interpreted by the app as a double-tap, which means it will now zoom out instead of scroll.

Very frustrating because getting back exactly to 0 zoom is really difficult without leaving and re-entering the view.

### What/Requirements
*(TachiyomiJ2K already has this, and it's the feature I miss the most).*

Would be a toggle in the settings menu that can be accessed in the reader view by tapping anywhere (something like "Allow to zoom") and, when disabled, the app would not allow zooming at all. More ambitiously, there could be a toggle to set this to apply to all kinds of a certain type of reader (Manga / Webtoon / etc.).

**Comment by jobobby04** [comment]
You can double tap to zoom back in to the normal spot

**Comment by DarkAlphaSete** [comment]
Thanks for that. Makes this slightly less frustrating, but at least it should do for the meantime.

**Comment by joseph619** [comment]
This has been added now :)

**Comment by jobobby04** [comment]
True, added with https://github.com/jobobby04/TachiyomiSY/commit/c340884adb2d31256eec1b8e9cab9eac76068a42
