### ISSUE TITLE
Pinch to zoom out is not working as intended for Webtoon and Continuous Vertical reading mode

### ISSUE THREAD

**Issue by BaccanoMob** [jobobby04/TachiyomiSY#670]
### Steps to reproduce

1. Open a Manga/Manhwa/Manhua for said reading mode.
2. The images are fit to max width (or screen width) by default.
3. Pinch to zoom out works but it does not make the image width less than screen width.

### Expected behavior

The image should zoom out and have background color on the sides (Tachiyomi's reading modes works fine as intended btw).
Temporary workaround is to manually set the side padding. 

### Actual behavior

Image is forcibly fit to max width

### Tachiyomi version

1.8.5

### Android version

12

### Device

Samsung Note10 Lite

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Im guessing you missed this setting
![BiJpwZB 1](https://user-images.githubusercontent.com/17078382/187089187-00c3fbe7-6587-4f05-8cc9-55ddec1599aa.png)
