### ISSUE TITLE
Beta image split and webtoon/continuous mode issue

### ISSUE THREAD

**Issue by MichaelDavidGK** [jobobby04/TachiyomiSY#671]
### Steps to reproduce

1. Turn on splitting images
2. Use continuous vertical or webtoon reading mode
3. Open new chapter (if u change reading mode while in chapter then chapter loads normally) 

### Expected behavior

Long images load normally

### Actual behavior

Images are loading infinitely (sometimes 1st image will load, often not), doesn't happen on preview

### Tachiyomi version

1.8.5 r478

### Android version

Android 11

### Device

S22 Ultra

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a known Main Tachi issue.
