### ISSUE TITLE
Add folders to group together continuous works from nhentai

### ISSUE THREAD

**Issue by MangaPsychopath** [jobobby04/TachiyomiSY#674]
### Describe your suggested feature

Add option to create folders in categories to group together continuous works from nhentai or e-hentai

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Im personally not interested in this. I know its a open feature request for Tachi so you can know that if Tachi gets it, SY will as well.
