### ISSUE TITLE
Tachiyomi preview r478

### ISSUE THREAD

**Issue by Jenmaq13** [jobobby04/TachiyomiSY#675]
### Steps to reproduce

Im just a user of your app. 

### Expected behavior

Im just a user

### Actual behavior

I think there's a problem on the updated version. Most of the downloaded chaps/mangas are gone and it keeps on loading.

### Crash logs

--------- beginning of crash
09-07 23:40:05.303 11278 26461 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-30
09-07 23:40:05.303 11278 26461 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 11278
09-07 23:40:05.303 11278 26461 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:483)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invokeSuspend(ReorderCategory.kt:20)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invoke(ReorderCategory.kt:2)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:9)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at eu.kanade.domain.category.interactor.ReorderCategory.await(ReorderCategory.kt:2)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.category.CategoryPresenter$moveDown$1.invokeSuspend(CategoryPresenter.kt:6)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
09-07 23:40:05.303 11278 26461 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@630a943, Dispatchers.IO]
09-07 23:40:19.265 26647 26765 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-19
09-07 23:40:19.265 26647 26765 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 26647
09-07 23:40:19.265 26647 26765 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:483)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invokeSuspend(ReorderCategory.kt:20)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invoke(ReorderCategory.kt:2)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:9)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at eu.kanade.domain.category.interactor.ReorderCategory.await(ReorderCategory.kt:2)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.category.CategoryPresenter$moveDown$1.invokeSuspend(CategoryPresenter.kt:6)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
09-07 23:40:19.265 26647 26765 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c96b99f, Dispatchers.IO]
09-07 23:41:22.034 26936 27059 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-43
09-07 23:41:22.034 26936 27059 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 26936
09-07 23:41:22.034 26936 27059 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:483)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invokeSuspend(ReorderCategory.kt:20)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invoke(ReorderCategory.kt:2)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:9)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at eu.kanade.domain.category.interactor.ReorderCategory.await(ReorderCategory.kt:2)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.category.CategoryPresenter$moveDown$1.invokeSuspend(CategoryPresenter.kt:6)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
09-07 23:41:22.034 26936 27059 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f1ff4ea, Dispatchers.IO]
09-08 00:10:27.167  2948  4998 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-15
09-08 00:10:27.167  2948  4998 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 2948
09-08 00:10:27.167  2948  4998 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:483)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invokeSuspend(ReorderCategory.kt:20)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invoke(ReorderCategory.kt:2)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:9)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at eu.kanade.domain.category.interactor.ReorderCategory.await(ReorderCategory.kt:2)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.category.CategoryPresenter$moveDown$1.invokeSuspend(CategoryPresenter.kt:6)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
09-08 00:10:27.167  2948  4998 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@be8d07b, Dispatchers.IO]
--------- beginning of main
09-08 01:02:43.045  5540 18669 E DatabaseUtils: Writing exception to parcel
09-08 01:02:43.045  5540 18669 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=23524, uid=1000 requires the provider be exported, or grantUriPermission()
09-08 01:02:43.045  5540 18669 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:740)
09-08 01:02:43.045  5540 18669 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:659)
09-08 01:02:43.045  5540 18669 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
09-08 01:02:43.045  5540 18669 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
09-08 01:02:43.045  5540 18669 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
09-08 01:02:43.045  5540 18669 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1056)
09-08 01:02:43.045  5540 18669 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1029)
09-08 01:02:43.766  5540 18669 E DatabaseUtils: Writing exception to parcel
09-08 01:02:43.766  5540 18669 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=23524, uid=1000 requires the provider be exported, or grantUriPermission()
09-08 01:02:43.766  5540 18669 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:740)
09-08 01:02:43.766  5540 18669 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:659)
09-08 01:02:43.766  5540 18669 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
09-08 01:02:43.766  5540 18669 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
09-08 01:02:43.766  5540 18669 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
09-08 01:02:43.766  5540 18669 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1056)
09-08 01:02:43.766  5540 18669 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1029)
09-08 01:02:48.647  5540 18669 E DatabaseUtils: Writing exception to parcel
09-08 01:02:48.647  5540 18669 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=23524, uid=1000 requires the provider be exported, or grantUriPermission()
09-08 01:02:48.647  5540 18669 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:740)
09-08 01:02:48.647  5540 18669 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:659)
09-08 01:02:48.647  5540 18669 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
09-08 01:02:48.647  5540 18669 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
09-08 01:02:48.647  5540 18669 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
09-08 01:02:48.647  5540 18669 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1056)
09-08 01:02:48.647  5540 18669 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1029)
App version: 1.8.5 (standard, bd1acc3ae, 38, 2022-08-28T01:23Z)
Preview build: 478
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A750GNDXU6CVG1
Device brand: samsung
Device manufacturer: samsung
Device name: a7y18lte
Device model: SM-A750GN
Device product name: a7y18ltedx

### Tachiyomi version

478

### Android version

10

### Device

Samsung A7

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Can you try explaining your issue again? I don't understand what your trying to say
