### ISSUE TITLE
[Security] "Require Unlock" isn't working when opening app

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#681]
### Steps to reproduce

Enable "Require Unlock" setting on Settings -> Security.
Lock when idle = Always
Close the app and open it again.

### Expected behavior

TachiyomiSY should display the "Unlock Tachiyomi" screen (Android's "insert password/unlock device" screen) when opening the app.

### Actual behavior

After upgrading to Preview r479, TachiyomiSY isn't displaying the "Unlock Tachiyomi" screen, and Tachi opens without requiring to insert the password/unlock the device, even with the aforementioned settings.

### Tachiyomi version

Preview r479

### Android version

7.1.1

### Device

Samsung Galaxy J2 Pro (SM-J250M)

### Other details

The "Unlock Tachiyomi" screen appears normally when minimizing and then returning to the app. (same behavior as before)

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a main tachi bug, you should open this issue there if one isnt already open

**Comment by lucky777709** [comment]
No problem, thanks for the info.
