### ISSUE TITLE
trying to view bato.to's latest filter in preview 479 update causes SY to crash 

### ISSUE THREAD

**Issue by jadoff630** [jobobby04/TachiyomiSY#682]
### Steps to reproduce

1. Go to Bato extension
2. select latest from options of latest/browse
3. will try to load
4. SY will crash

### Expected behavior

Should show the list of latest chapters

### Actual behavior

SY Crashes

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/9560763/tachiyomi_crash_logs.txt)

### Tachiyomi version

r479

### Android version

12

### Device

Samsung S21+

### Other details

I have tried to reproduce this behavior in Stable and Preview for main tachi version and the extension works as intended, therefore I submitted this report here and not in the extensions repo. I cleared cache and databases and it still occurs.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Works fine on my end, clear database in advanced settings and try again

**Comment by jadoff630** [comment]
Clearing database is in settings, advanced, clear databases, and then select bato and delete it correct? I have done this multiple times, making sure to also uncheck keep read chapters and it still crashes.

**Comment by jadoff630** [comment]
In case it helps, here is a screen capture showing an empty database and the problem persisting. 
https://user-images.githubusercontent.com/25085973/190036769-359f2428-f531-46fe-b5e3-08a8de178736.mp4

**Comment by jadoff630** [comment]
Changing DNS over HTTPS from disabled to another option, and then back to disabled again fixed the issue
