### ISSUE TITLE
[Browse -> Sources] Can't "pre-type" a search before opening a source anymore; Opening source doesn't "auto-trigger" my search anymore

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#683]
### Steps to reproduce

Open Browse -> Sources tab.
Tap the Global Search icon at the top-right.

### Expected behavior

Before upgrading to Preview r479, I could tap the Global Search icon (or the area at the left of the icon, I don't remember exactly), this would display an 'edit text field' at the top of the screen (without leaving/hiding the Sources list below).

I could type my desired search on this field, then either:
- Tap the Global Search icon to open the global search view, using the search I typed beforehand.

- Tap any source from the list below.
This would open the selected source, and the source would automatically do/display the search I typed beforehand (auto-filtering the results with my search), skipping the "source's default results" (popular, latest).

Most times, I prefer to skip those initial source results while doing my searches, for a more "distraction-free" experience.
But if the user wants to see those "default results" (ignoring the previously-typed search), then the user could simply press Back while on the filtered search view, to go back to the source's default results view.

### Actual behavior

After upgrading to Preview r479, tapping the area at the left of the Global Search icon does nothing (I think this action opened the search field in earlier versions, IIRC).

And tapping the Global Search icon doesn't display the search field either. Instead, it already opens the global search view, while hiding the entire list of installed sources.
The global search view shows nothing at first, then you can click the Search icon to type your global search, as usual. (Global Search works as expected)

My issue is that it's not possible anymore to pre-type my search and then open a specific source while auto-triggering my search (and skipping the source's default results view), as I could do in earlier TachiyomiSY versions.

### Tachiyomi version

Preview r479

### Android version

7.1.1

### Device

Samsung Galaxy J2 Pro (SM-J250M)

### Other details

There's a very similar issue with the Source Feeds, which I'll explain in a separate bug report shortly.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Known main Tachi bug 😄 https://github.com/tachiyomiorg/tachiyomi/issues/7938
