### ISSUE TITLE
[Browse -> Feed] Opening Source Feed doesn't auto-trigger its respective "saved search" anymore

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#684]
### Steps to reproduce

Open Browse -> Feed tab.
Tap the title (or arrow button) of any Source Feed you have previously added to the list.

### Expected behavior

Opening the Source Feed should auto-trigger its saved search, in case it's a Source Feed based on a saved search.

### Actual behavior

After upgrading to Preview r479, opening the Source Feed isn't auto-triggering its saved search.
Instead, it displays the source's default (Latest) results, even if it's a Source Feed based on a saved search.

### Tachiyomi version

Preview r479

### Android version

7.1.1

### Device

Samsung Galaxy J2 Pro (SM-J250M)

### Other details

Similar, possibly-related issue:
https://github.com/jobobby04/TachiyomiSY/issues/683

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Already fixed for the next build 👍
