### ISSUE TITLE
TachSy won't fetch all available chapters (Pr479)

### ISSUE THREAD

**Issue by TsumiHokiro** [jobobby04/TachiyomiSY#685]
### Steps to reproduce

1. Choose a manga to read;
2. Check if manga has more than 1 chapter or not, if so, open one of them;
3. Make sure images are loaded and go to either the end of the chapter (if there is a next one) or beginning and scroll back (if there is a previous one.)

### Expected behavior

Ability to navigate between currently reading chapter and previously and future ones, seemingly or on-pick.

### Actual behavior

No other chapter is added to the reading list, requiring manual intervention, going back to chapter list and opening next one and continuing.

### Tachiyomi version

Preview r479

### Android version

Android 9

### Device

GM-9600

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TsumiHokiro** [comment]
Downgrading to r478 fix issue.

**Comment by jobobby04** [comment]
Can you upgrade again and see if `Settings -> Advanced -> Debug menu -> Reset filtered scanlators for all manga` fixes it

**Comment by TsumiHokiro** [comment]
To downgrade I had to uninstall the app and install r478. r479 is now working as expected. Could the uninstall have reset that option?

**Comment by jobobby04** [comment]
The backup restore automatically performs that option on restored manga, so ya that was probably the issue.

**Comment by TsumiHokiro** [comment]
As a side note, the issue wasn't immediately visible upon upgrade, took a while to take place. Tested for a while right now and saw no errors hence why I just answered.
