### ISSUE TITLE
MMScans not recognizing other chapters in reader

### ISSUE THREAD

**Issue by DatHypnoboi** [jobobby04/TachiyomiSY#686]
### Steps to reproduce

1. Open MMScans series
2. Open any chapter
3. Open chapters list or try to scroll to other chapter

### Expected behavior

All available chapters should appear in the list and be available to read

### Actual behavior

Only the current chapter appears

### Tachiyomi version

1.8.5 Preview r479

### Android version

Android 12

### Device

Google Pixel 3a XL

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
See https://github.com/jobobby04/TachiyomiSY/issues/685 for temp fixes
It will be fixed in the next build
