### ISSUE TITLE
TachiyomiSY sometimes crashes on loading images

### ISSUE THREAD

**Issue by MangaPsychopath** [jobobby04/TachiyomiSY#688]
### Steps to reproduce

1. Open random manga
2. Open any chapter
3. Loading circle gets stuck and apps crashes

### Expected behavior

Shoulf load the image

### Actual behavior

App crash

### Crash logs

--------- beginning of main
09-20 10:20:59.582  6634  6634 E GraphicExt: Can't load libboost_ext_fwk
09-20 10:20:59.582  6634  6634 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-20 10:20:59.693  6634  6771 E ion     : ioctl c0044901 failed with code -1: Invalid argument
09-20 10:20:59.730  6634  7199 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:20:59.730  6634  7201 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:34.251  6634  7594 E SQLiteLog: (284) automatic index on C(manga_id)
09-20 10:22:34.251  6634  7594 E SQLiteLog: (284) automatic index on R(manga_id)
09-20 10:22:34.252  6634  7594 E SQLiteLog: (284) automatic index on C(merge_id)
09-20 10:22:34.252  6634  7594 E SQLiteLog: (284) automatic index on R(merge_id)
09-20 10:22:34.253  6634  7594 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
09-20 10:22:36.106  6634  7607 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.106  6634  7201 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.107  6634  7605 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.107  6634  7610 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.151  6634  7610 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.151  6634  7622 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.153  6634  7605 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.154  6634  7607 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.160  6634  7201 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.163  6634  7622 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.163  6634  7610 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.165  6634  7605 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.168  6634  7607 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.171  6634  7610 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.171  6634  7201 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.178  6634  7622 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.182  6634  7201 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.182  6634  7199 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.183  6634  7607 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.189  6634  7605 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.193  6634  7622 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.193  6634  7607 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.197  6634  7616 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.200  6634  7610 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.200  6634  7199 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.206  6634  7605 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.209  6634  7622 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.210  6634  7616 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.212  6634  7199 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.217  6634  7610 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.220  6634  7605 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.221  6634  7622 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.222  6634  7201 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.225  6634  7616 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.228  6634  7199 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.232  6634  7201 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.232  6634  7610 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.233  6634  7616 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.240  6634  7622 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.241  6634  7605 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.244  6634  7616 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.248  6634  7201 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.253  6634  7610 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.254  6634  7622 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.255  6634  7199 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.259  6634  7605 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.262  6634  7622 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.265  6634  7616 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.273  6634  7201 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.278  6634  7610 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.279  6634  7605 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.283  6634  7622 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.286  6634  7616 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.293  6634  7201 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.294  6634  7605 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.299  6634  7622 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.299  6634  7610 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.307  6634  7610 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.307  6634  7616 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.313  6634  7613 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.316  6634  7622 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.322  6634  7201 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.324  6634  7610 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:22:36.325  6634  7616 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-20 10:24:39.545  6634  6634 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
App version: 1.8.5 (standard, b7779ba, 36, 2022-08-14T19:51Z)
Preview build: 0
Android version: 10 (SDK 29)
Android build ID: TB-X606F_S300660_220613_BMP
Device brand: Lenovo
Device manufacturer: LENOVO
Device name: X606F
Device model: Lenovo TB-X606F
Device product name: LenovoTB-X606F_EEA

### Tachiyomi version

1.8.5

### Android version

Android 10

### Device

Lenovo TB-X606F

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Main Tachi issue that might already be fixed
