### ISSUE TITLE
DOWNLOAD ERROR FOR TACHIYOMISY UPDATE

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#69]
#Device information
* Tachiyomi version: stable 1.1.0
* Android version: 10
* Device: Note 10+

## Steps to reproduce
1. First step
Go to more-about-check for update

2. Second step
Download Available Update

### Expected behavior
It should download update either on background or foreground.

### Actual behavior
It will only succeed downloading if stays on TACHIYOMISY, else there is download error

### Other details
Battery optimization is already disabled. 

Attached link for video reference.
_http://sendanywhe.re/IZON8HYF_
Link expires on 48 hrs.

**Comment by Mano5JP** [comment]
I have already updated to latest version, so i can't say if bug still persist or not.

**Comment by jobobby04** [comment]
You can notify me if it works, this will be closed for now
