### ISSUE TITLE
Add random sort option

### ISSUE THREAD

**Issue by hdk5** [jobobby04/TachiyomiSY#692]
### Describe your suggested feature

I want a new option under "Filters - Sort" that would shuffle my eromanga library so I could quickly pick something up to fap to at random.

Similar issue exists at the upstream repo (tachiyomiorg/tachiyomi#1248), but it seems to be stalled.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Nah
