### ISSUE TITLE
Save to SD card option has disappeared

### ISSUE THREAD

**Issue by nfalKuro** [jobobby04/TachiyomiSY#693]
### Steps to reproduce

1. Select 'More' on navigation
2. Settings → Downloads → Download Location →
3. 
![Screenshot_2022-09-25-02-56-08-636_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/52811621/192133485-3e9d8cb4-9aca-430c-8fe0-a3b8a0a0a00f.png)

### Expected behavior

There should be an option to save to SD card.

For example: 
![Screenshot_2022-09-25-13-22-01-549_eu kanade tachiyomi](https://user-images.githubusercontent.com/52811621/192133662-65db58df-371c-42cb-b43d-2778d1024136.png)

> (This is screenshot of Tachiyomi 0.12.3)

### Actual behavior

There is no option to save to SD card

### Tachiyomi version

1.8.5

### Android version

Android 7.1

### Device

Xiaomi Redmi 4A

### Other details

This issue occurred after an error notification 'invalid location' when I was about to download a chapter. When I checked the storage they were full. I only realized this issue after cleaning storage and going to settings.

**Note:** I have tried to install several versions of TachiyomiSY and Tachiyomi, and this issue only occurs on TachiyomiSY (and TachiyomiSY preview).

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Sounds like device specific issue, and its main Tachi code so I can't do anything about that
