### ISSUE TITLE
Option to skip automatically downloading series

### ISSUE THREAD

**Issue by DatHypnoboi** [jobobby04/TachiyomiSY#696]
### Describe your suggested feature

Downloading new chapters should have an option to filter out series with certain conditions similar to the "Skip updating titles" option.
EX. With unread chapter(s), without downloaded chapter(s), etc. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Add those series to a auto-download excluded category
