### ISSUE TITLE
Add Discussion Feature to this Fork

### ISSUE THREAD

**Issue by ar664** [jobobby04/TachiyomiSY#697]
### Describe your suggested feature

The discord linked is for the official Tachiyomi. I have some questions, but I don't want to put issues for them. I think this would be a good solution.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
There is a SY channel in the Tachiyomi discord, feel free to ask there.
