### ISSUE TITLE
Mangadex filter by Latest infinite loading and crashes.

### ISSUE THREAD

**Issue by cyborgA0** [jobobby04/TachiyomiSY#698]
### Steps to reproduce

1. Open mangadex extension
2. Tap Latest

### Expected behavior

Latest manga should appear not infinite loading, and tappping latest should not cause crash
This does not happen in the original tachiyomi so I think this is not a manga extension issue.

### Actual behavior

Latest mangadex manga should appear, no crashes upon tapping "Latest"
![Screenshot_2022-10-03-06-48-06-659_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/46979593/193481450-d440166c-0c7c-43db-a9d6-c86cfbad2213.jpg)

### Crash logs

--------- beginning of system
10-02 12:02:01.910 22421 22421 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is selene
10-02 15:41:38.641 26579 26579 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is selene
10-02 20:10:05.086 17104 17104 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is selene
10-02 21:51:28.143 24588 24588 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is selene
10-03 06:06:45.412 12452 12452 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is selene
10-03 06:47:49.304 16669 16669 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is selene
--------- beginning of crash
10-03 06:48:12.992 16669 16669 E AndroidRuntime: FATAL EXCEPTION: main
10-03 06:48:12.992 16669 16669 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 16669
10-03 06:48:12.992 16669 16669 E AndroidRuntime: java.lang.IllegalStateException: ResultSet returned more than 1 row for mangas.sq:getMangaByUrlAndSource
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at com.squareup.sqldelight.Query.executeAsOneOrNull(Query.kt:46)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at eu.kanade.data.AndroidDatabaseHandler$awaitOneOrNull$2.invokeSuspend(AndroidDatabaseHandler.kt:42)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at eu.kanade.data.AndroidDatabaseHandler$awaitOneOrNull$2.invoke(AndroidDatabaseHandler.kt:13)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at eu.kanade.data.AndroidDatabaseHandler$dispatch$3.invokeSuspend(AndroidDatabaseHandler.kt:33)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at eu.kanade.data.AndroidDatabaseHandler$dispatch$3.invoke(AndroidDatabaseHandler.kt:13)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at eu.kanade.data.AndroidDatabaseHandler.dispatch(AndroidDatabaseHandler.kt:160)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at eu.kanade.data.AndroidDatabaseHandler.awaitOneOrNull(AndroidDatabaseHandler.kt:7)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at eu.kanade.data.manga.MangaRepositoryImpl.getMangaByUrlAndSourceId(MangaRepositoryImpl.kt:10)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at eu.kanade.domain.manga.interactor.GetManga.await$1(GetManga.kt:3)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter.access$networkToLocalManga(BrowseSourcePresenter.kt:103)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$getMangaList$1$2$1$1.invokeSuspend(BrowseSourcePresenter.kt:37)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
10-03 06:48:12.992 16669 16669 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [LazyStandaloneCoroutine{Cancelling}@bbb6307, Dispatchers.Main]
--------- beginning of main
10-03 06:48:25.876 17212 17212 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
10-03 06:48:26.183 17212 17256 E SQLiteLog: (283) recovered 2 frames from WAL file /data/user/0/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-wal
10-03 06:48:26.185 17212 17261 E QT      : [QT]file does not exist
10-03 06:48:26.341 17212 17212 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is selene
10-03 06:48:27.020 17212 17321 E SQLiteLog: (284) automatic index on UR(manga_id)
10-03 06:48:27.020 17212 17321 E SQLiteLog: (284) automatic index on R(manga_id)
10-03 06:48:27.020 17212 17321 E SQLiteLog: (284) automatic index on UR(merge_id)
10-03 06:48:27.020 17212 17321 E SQLiteLog: (284) automatic index on R(merge_id)
10-03 06:48:27.020 17212 17321 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-03 06:48:27.099 17212 17259 E OpenGLRenderer: Device claims wide gamut support, cannot find matching config, error = EGL_SUCCESS
10-03 06:48:27.123 17212 17408 E ion     : ioctl c0044901 failed with code -1: Invalid argument
10-03 06:48:27.385 17212 17328 E ion     : ioctl c0044901 failed with code -1: Invalid argument
10-03 06:48:27.455 17212 17432 E OpenGLRenderer: Device claims wide gamut support, cannot find matching config, error = EGL_SUCCESS
10-03 06:48:27.624 17212 17259 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
10-03 06:48:27.624 17212 17259 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
10-03 06:48:27.795 17212 17227 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#0](f:0,a:2) isEGL=1, mPendingRelease.size()=1, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=2
10-03 06:48:27.862 17212 17476 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#0](f:0,a:3) isEGL=1, mPendingRelease.size()=2, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=2
10-03 06:48:49.141 17212 17227 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#1](f:0,a:3) isEGL=1, mPendingRelease.size()=1, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=2
10-03 06:48:49.157 17212 17227 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#1](f:0,a:4) isEGL=1, mPendingRelease.size()=2, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=2
10-03 06:49:00.570 17212 17476 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#2](f:0,a:2) isEGL=1, mPendingRelease.size()=1, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=2
10-03 06:49:00.602 17212 17476 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#2](f:0,a:4) isEGL=1, mPendingRelease.size()=2, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=2
App version: 1.8.5 (standard, 8d91c54c1, 42, 2022-09-26T02:11Z)
Preview build: 481
Android version: 12 (SDK 31)
Android build ID: AL5186-selene-build-20220906012418
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: selene
Device model: 21061119AG
Device product name: selene_global

### Tachiyomi version

preview r481

### Android version

Android 12

### Device

Xiaomi Redmi 10

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Go to Advanced Settings and use Clear Database on mangadex
