### ISSUE TITLE
[Deeplink][Delegation] - Opening Group links using Tachiyomi MangaDex extension is broken in Sy

### ISSUE THREAD

**Issue by curche** [jobobby04/TachiyomiSY#699]
### Steps to reproduce

1. Find a group on mangadex. Eg: Aumakua scanlating Flying Witch https://mangadex.org/group/332c5876-fc6f-4ddf-8972-7c58472f3eb0
2. Open the link in Tachiyomi: MangaDex and then choose SY as an option
3. Now, try opening the link in Tachiyomi: MangaDex but use Main tachiyomi

### Expected behavior

Both behave similarly

### Actual behavior

There's a difference
Main Tachiyomi uses a special search filter to global search in _only_ MangaDex
Sy doesn't seem to have that and just global searches (pinned) extensions 

### Crash logs

NA

### Tachiyomi version

Preview r481

### Android version

Android 12

### Device

SM-N770F

### Other details

Note that Sy works like Main Tachiyomi when its a deep link which is from another source (Eg: MangaPlus links)
Issue also prevails for any deeplinks other than manga or chapter (i.e. problem can be seen with [grp](https://mangadex.org/group/4f1de6a2-f0c5-4ac5-bce5-02c7dbb67deb/mangaplus):, [usr](https://mangadex.org/user/d2ae45e0-b5e2-4e7f-a688-17925c2d7d6b/mangadex):, [list](https://mangadex.org/list/4be9338a-3402-4f98-b467-43fb56663927/seasonal-fall-2022):)

Issue can also be reproduced in other delegated sources: like NHentai deeplinks in Tachiyomi: NHentai extension

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed for the next build 👍
