### ISSUE TITLE
Migration makes chapter unread

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#700]
### Steps to reproduce

1. Add manga 'Home Alone Romp with my Childhood Friend' from Nhentai to Library (Nhentai code 350536)
2. Mark chapter as read
3. Migrate manga to Nana (English) source

Alternatively
1. Add comic 'A Sunday Schooling [NLT Media]' from 8Muses to Library
2. Mark chapter as read
3. Migrate comic to AllPornComic source

### Expected behavior

Migrated chapter should be marked as read (same as original)

### Actual behavior

Chapter is unread

### Tachiyomi version

483

### Android version

Android 12

### Device

Galaxy A72

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I believe its intentional since it cannot find a chapter number to compare the read status to, so it cant do anything to move it over
