### ISSUE TITLE
Kitsu broken on sy stable, requesting stable update with fix if possible

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#703]
### Steps to reproduce

1. login to kitsu
2. open manga 
3. try to track

### Expected behavior

should track

### Actual behavior

Toast error appears saying 'Could not find manga'

### Tachiyomi version

1.8.5

### Android version

12

### Device

galaxy a72

### Other details

tried logging in and out on fresh install, still same

kitsu works as expected on Stable 0.13.6 

sy preview still unstable, so requesting stable update with fix

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Next stable will probably be based on the latest preview anyway. Closing since this issue is uneeded.
