### ISSUE TITLE
Group by failed.

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#706]
### Describe your suggested feature

Right now, if there are any failed series while library updates, we can view it from notification and check the log.
but with this group by, we can get all failed series dynamically in one category, and we can use that to either migrate, manually refresh and so on.

idk if this should be on main tachi, but main doesn't have group options.

### Other details

I am ok with all failed one's to be be in one category, but if we can have dynamic category according to error, that's much better as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I don't really understand what your trying to say 😕 ? Is this a bug or a feature request? If its a bug what needs to be fixed? If its a feature request what needs to be added?

**Comment by Mano5JP** [comment]
So, let's say we have some failed library updates.
![Failed updates.png](https://user-images.githubusercontent.com/64928088/196521005-05962c13-0c13-4ab7-a8a5-3ad47cff86e4.png)

So, we could use something like this to get it all in one place.
![Group options.png](https://user-images.githubusercontent.com/64928088/196520961-f7639581-a5f3-4623-969b-9b0fc2dbe03a.png)


Hence we could migrate, do manual updates and so on.

**Comment by Mano5JP** [comment]
A group category to get all failed upon updates.

As same as Group - Source: it shows all errors in categories tabs in the library like this.
![Sources.png](https://user-images.githubusercontent.com/64928088/196522217-0ebec7a3-026e-49c3-8b4b-8659a6058b7f.png)

**Comment by Mano5JP** [comment]
> I don't really understand what your trying to say 😕 ? Is this a bug or a feature request? If its a bug what needs to be fixed? If its a feature request what needs to be added?

Feature request. I am on phone so it's hard to explain properly. Let me know if the above comments didn't make sense I will try to explain tomorrow.

**Comment by jobobby04** [comment]
I understand now, I'll consider it 👍

**Comment by jobobby04** [comment]
I think I am going to deny this. Failed manga updates are not stored anywhere and this seems like its such a niche thing that its not worth the work to implement
