### ISSUE TITLE
[Bug] Manually updating skips a lot of titles

### ISSUE THREAD

**Issue by vongdong** [jobobby04/TachiyomiSY#71]
## Steps to reproduce
1. Pull page down to update category
2. Watch update progess

### Expected behavior
Entire library category should be update/checked

### Actual behavior
Updates a few titles then skips a whole bunch

### Other details
I was trying to get my category sorted by latest update first and saw it wasn't correct so manually updated, went and did some browsing and saw the progress bar was gone. Thought no way it was that fast. Tried again and watched the progress bar and saw it skipping a massive amount of titles. I've got it set to update all status's.

**Comment by jobobby04** [comment]
It will skip the internal and some delegated sources, as most hentai sources do not update galleries, and E-Hentai has a built in updater that it requires to be able to properly update galleries

**Comment by vongdong** [comment]
I'm using nhentai and hentai2read. So it's a bug right?

**Comment by jobobby04** [comment]
hentai2read may check for updates since its not internal or delegated, but nHetnai is skipped intentionally, as it doesnt have a gallery update system

**Comment by vongdong** [comment]
Hmm, is this something you may be looking at changing?

**Comment by jobobby04** [comment]
nHentai cant update galleries on its website in the first place, once a gallery is posted it cant be edited. So nope, this is intentional and how it should be 😄

**Comment by vongdong** [comment]
Ah okay. Well there's another bug I've noticed. So I've got my library to show latest update first but anything from nhentai is showing oldest first by the looks of it.

**Comment by jobobby04** [comment]
Technically that is not a bug, since nHentai doesnt store the when the chapter was posted, maybe I can whip up something at some point though

**Comment by AriaMoradi** [comment]
@jobobby04 please re-open this
https://discord.com/channels/349436576037732353/566585518171881493/790535909735923722

**Comment by AriaMoradi** [comment]
> and it's all of them not some
"hentai2read may check for updates since its not internal or delegated, but nHentai is skipped intentionally, as it doesn't have a gallery update system on the website"
"Technically that is not a bug, since nHentai doesnt store the when the chapter was posted, maybe I can whip up something at some point though"
ok its intentional
but it should load when you mass add mangas
so maybe add a check if (manga.initialized == false) then update?
it should fix my problem

**Comment by vongdong** [comment]
> > and it's all of them not some
> > "hentai2read may check for updates since its not internal or delegated, but nHentai is skipped intentionally, as it doesn't have a gallery update system on the website"
> > "Technically that is not a bug, since nHentai doesnt store the when the chapter was posted, maybe I can whip up something at some point though"
> > ok its intentional
> > but it should load when you mass add mangas
> > so maybe add a check if (manga.initialized == false) then update?
> > it should fix my problem

Why? Nhentai works fine now?
