### ISSUE TITLE
Tall Images Parts Loading Problem.

### ISSUE THREAD

**Issue by TsumiHokiro** [jobobby04/TachiyomiSY#711]
### Steps to reproduce

1 - Long strip comic with a sufficient number of pages (10+);
2 - Scroll down the chapter as pages load;
3 - Notice the discontinuity of the comic.

### Expected behavior

No page skipping or transparent notification/display of page not downloaded.

### Actual behavior

Pages which might have been downloaded or are yet to be are skipped/not displayed as such.

### Tachiyomi version

Preview r485

### Android version

Android 10

### Device

SM-G9600

### Other details

I have noticed this happening at least since r478. A few things I've noticed are that:
1 - Pages behave like this usually in the middle of the chapter (most noticeable around pages 3-4.)
2 - In some cases the images were downloaded (I managed to see a part of the image before the app 'hid' it) but soon are hidden in favour of the next one [pages skip from 2 to 3] without due notification on the page progression display.
3 - A few ways to try to make the app display the images: Scroll Down and then all the way up again (Works best with chapters with more pages); restart reading the chapter; close the app and try it all again.
4 - The app may or not later re-display images that were skipped without user intervention.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is most likely a main Tachi bug with Split Tall Images, open a issue in the main Tachi repo if there is not already one.
