### ISSUE TITLE
"See recommendations" button showing no results every time

### ISSUE THREAD

**Issue by smazek** [jobobby04/TachiyomiSY#712]
### Steps to reproduce

For example "solo leveling" 
Click on the manga
And click recommendations 
Starts loading for a few secs
And nothing shows up
This happens on every manga i tried 

### Expected behavior

Recommendations should have poped up

### Actual behavior

Says "nothing was found" after clicking the rcmd button

### Tachiyomi version

1.8.5

### Android version

Android 11

### Device

Samsung galaxy A70

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Duplcate of #689
