### ISSUE TITLE
Duplicate manga shown in mangadex extension Latest view

### ISSUE THREAD

**Issue by tonizombie** [jobobby04/TachiyomiSY#716]
### Steps to reproduce

1. Open Browse
2. Open Mangadex extension
3. Choose Latest and not Browse

### Expected behavior

No duplicate manga shown

### Actual behavior

Duplicate manga is shown, shows manga like normally for 5-10 manga and then repeats the same manga, very slowly showing new manga but also repeating them

### Tachiyomi version

1.8.5

### Android version

Android 12

### Device

One Plus 10 Pro

### Other details

Picture 1 shows it in [Dev Build 485](https://github.com/jobobby04/TachiyomiSYPreview/releases/tag/485)
Picture 2 shows it in latest stable (1.8.5 as of this moment)
Picture 3 shows it keeps going and isnt just first few manga

![1](https://user-images.githubusercontent.com/30530331/199071640-5f415326-8f2a-4d50-bd46-5434a4c10765.jpg)
![2](https://user-images.githubusercontent.com/30530331/199071660-dacd6354-3725-4676-be21-c43d59b8d8b3.jpg)
![3](https://user-images.githubusercontent.com/30530331/199071675-f3ab8f76-e9fd-48bb-a788-5956adcfcc66.jpg)

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by tonizombie** [comment]
Updated mangadex extension today to 1.3.174, bug still there

**Comment by jobobby04** [comment]
Mangadex browse only shows things from the extension, so if its showing dupes its because thats what the extension is returning. Open a issue in the extensions repo for this if there is not one already open
