### ISSUE TITLE
Library sort no longer works when grouping by source

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#718]
### Steps to reproduce

1. Open library filter
2. Group by source
3. Sort entries

### Expected behavior

Sorting should work (last read etc)

### Actual behavior

Nothing happens when clicking any sort option

### Tachiyomi version

488

### Android version

Android 12

### Device

Galaxy S21 Ultra

### Other details

![Screenshot ](https://user-images.githubusercontent.com/83420659/199592525-3fbb8ba4-8c00-4697-a3fe-b81e09936c46.png)

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed in the latest build
