### ISSUE TITLE
Front page category for Exhentai don't work 

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#719]
### Steps to reproduce

1. Open Ehentai setting
2. Toggle front page categories
3. Open Exhentai in browse screen

### Expected behavior

Browse should only show the ehentai categories toggled in setting

### Actual behavior

It shows every front page category, no filter is applied

### Tachiyomi version

488

### Android version

Android 12

### Device

Galaxy S21 Ultra

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Hmm this seems to work fine for me, try changing it and then changing it back
