### ISSUE TITLE
Refresh the bookshelf

### ISSUE THREAD

**Issue by huajideshutiao** [jobobby04/TachiyomiSY#721]
### Steps to reproduce

1.Delete or change the classification of comics on the shelf page.
2.Operation does not take effect.

### Expected behavior

Same as the original

### Actual behavior

Same as description, you must switch pages (for example, switch to the settings page) to refresh.

### Tachiyomi version

1.8.5

### Android version

Android 12

### Device

redmi k50 miui13

### Other details

I think this problem is a variation of [#648](https://github.com/jobobby04/TachiyomiSY/issues/648) , or it may be a bug introduced when fixing it.
I didn't encounter the same problem in Tachiyomi 0.14.2-5188

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by huajideshutiao** [comment]
![Screenshot_2022-11-05-00-55-02-115_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/38980554/200032220-3fc5c18e-3d64-4d3b-b8d8-c7ea58e3cc2b.jpg)
like this.The information in the dialog box is correct.

**Comment by jobobby04** [comment]
Closing in favor of https://github.com/jobobby04/TachiyomiSY/issues/734
