### ISSUE TITLE
Exhentai/ehentai not loading beyond first page

### ISSUE THREAD

**Issue by patros36** [jobobby04/TachiyomiSY#722]
### Steps to reproduce

Open Browse or latest tab on either one.
Scroll down.
No new manga entries will get loaded, seems like the next page isn't loading.
Doesn't happen for other sources.

### Expected behavior

After scrolling down, more entries should appear.

### Actual behavior

No new entries appear.

### Tachiyomi version

1.8.5

### Android version

Android 10

### Device

Xiaomi mi mix 2s

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
E-H/Exh redesigned the search engine, E-H is planned to get the changes soon.

Its fixed for Exh in the preview(sorta, more fixes on the way).

I'm planning on doing a release when the changes for E-H go live and I can test everything properly
