### ISSUE TITLE
Clear chapter cache on app close doesn't work

### ISSUE THREAD

**Issue by Volern** [jobobby04/TachiyomiSY#725]
### Steps to reproduce

The clear chapter cache on app close doesn't work for me. I have tried reinstalling and updating, force close app and just normally close app and clear app list to remove it from memory.

I can clear my manually just fine, and I've tried turning the option off and on a few times but it doesn't seem to actually be doing anything at the moment.

Not sure of this is an SY issue or a base tachiyomi issue.

### Expected behavior

Chapter cache should clear on app close.

### Actual behavior

Nothing happens and cache is retained.

### Tachiyomi version

1.8.5

### Android version

Android 11

### Device

Oneplus 8 Pro

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a main Tachi feature that SY does not edit, maybe it works better in the preview, but its not a SY issue if it does not work properly.
