### ISSUE TITLE
[Feature Request] Make Drag & Drop work alongside current sorting

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#73]
### Why/User Benefit/User Problem
Drag & drop would work alongside other sorting

### What/Requirements
Remove individual drag and drop sorting and make it work with all other sorting, like on J2K

GIF
![ezgif-6-2d7931001ebf](https://user-images.githubusercontent.com/34897862/89622115-84852600-d860-11ea-9fc3-40882fbb9dbb.gif)
 attached below for example

**Comment by jobobby04** [comment]
Added with https://github.com/jobobby04/TachiyomiSY/commit/5714f183a8685a6b5c6f01129aff8c8f79750136
