### ISSUE TITLE
Option to minimize page previews

### ISSUE THREAD

**Issue by Th3N3rdyGam3r** [jobobby04/TachiyomiSY#730]
### Describe your suggested feature

I'd like to see a setting that would hide the page previews by default. Something like an initial button with "Show previews" that would then show the screen as it currently is. I don't really use the previews and would rather be able to easily see my read status on the chapters, but with the option to view the previews.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
SY is always going to show at least some previews, there is a issue to make them configurable though https://github.com/jobobby04/TachiyomiSY/issues/643
