### ISSUE TITLE
Avif images not loading

### ISSUE THREAD

**Issue by JaitinPrakash** [jobobby04/TachiyomiSY#731]
### Steps to reproduce

1. Have a comic in local folder with .avif images encoded with librav1e 0.5.1 at speed 10 with pix_fmt yuv444p12le
2. Attempt to load chapter

### Expected behavior

pages should load and display normally

### Actual behavior

reader gets stuck loading and never displays pages

### Tachiyomi version

1.8.5

### Android version

Android 12 one UI 4.1

### Device

Note 20 Ultra 5G SM-N986U

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
All the image decoder stuff is a main Tachi thing, also check to see if it works in the preview
