### ISSUE TITLE
"Migrate all nhentai to other lang" fails

### ISSUE THREAD

**Issue by JaitinPrakash** [jobobby04/TachiyomiSY#732]
### Steps to reproduce

1. Go to Settings>Advanced>Open debug menu
2. click "Migrate all nhentai to other lang"

### Expected behavior

Unknown, I haven't been able to get it work.

### Actual behavior

popup opens with text:

Function returned result:

kotlin. Unit

### Tachiyomi version

1.8.5

### Android version

Android 12 One UI 4.1

### Device

Samsung Galaxy Note 20 Ultra 5G

### Other details

![Screenshot_20221119-193205_TachiyomiSY](https://user-images.githubusercontent.com/35095372/202881568-689af6df-31a5-41e8-875a-75514653b917.jpg)

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
The code looks fine, maybe your misunderstanding it though, renamed for clarification
