### ISSUE TITLE
beta crop long images issue

### ISSUE THREAD

**Issue by capitanjal** [jobobby04/TachiyomiSY#733]
### Steps to reproduce

This is just an inconvenience that happens when you activate the feature and don't have a proper steps to reproduce.
When you have slow internet or the site have low bandwidth or your device have low processing power and the pages don't load on time the reader will not catch with the request and try to jump pages but then the cut pages feature caught with the pages and advance
-load a webtoon with long pages (usually I read the ones that have 3 pages long)
-the page don't load on time and the page is skipped
-the page then load and instead of start still or go back one page it goes forward the same amount of pages cut in this case it goes forward 3 pages

### Expected behavior

The reader jumps pages when there is no loaded pages

### Actual behavior

The cut pages feature should be disable when the current page don't load and activate itself again when the user prompt 1 or 2 actions one or two taps, because it means you notice the no loading or continue 

### Tachiyomi version

App version: 1.8.5 (standard, 792746dce, 42, 2022-11-03T01:47Z) Preview build: 489 

### Android version

 12 (SDK 31) Android build ID: SP1A.210812.016.X200XXU1BVI6

### Device

Device manufacturer: samsung Device name: gta8wifi Device model: SM-X200 Device product name: gta8wifixx

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Long page crop is a main Tachi thing, if you have issues with it please direct them to the main Tachi repo
