### ISSUE TITLE
Changing category for manga doesn't work 

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#734]
### Steps to reproduce

1. Open Library 
2. Long press a manga and change it's category

### Expected behavior

Manga should move out of its current category to new category 

### Actual behavior

Manga stays in original category

### Tachiyomi version

491

### Android version

Android 12

### Device

Galaxy S21 Ultra 

### Other details

Manga appears to change category when switching from Library tab to other tabs (like update/history), or close the app

It might be a visual glitch. Doesn't happen on main preview 

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed for the next build 👍
