### ISSUE TITLE
Filter by scanlator not working

### ISSUE THREAD

**Issue by edmxn** [jobobby04/TachiyomiSY#735]
### Steps to reproduce

open manga from TuMangaOnline source
choose scanlators by filter

### Expected behavior

the chapters of the unelected scanlators should not come out

### Actual behavior

they come out

### Tachiyomi version

1.8.5

### Android version

Android 12

### Device

Samsung s10+

### Other details

![Screenshot_20221120_051438_TachiyomiSY](https://user-images.githubusercontent.com/101371218/202899168-0cf231fe-8501-45d4-a79c-d56760458f96.jpg)
![IMG_20221120_051458](https://user-images.githubusercontent.com/101371218/202899169-459ff9b4-d273-4801-8e8c-0e3935f02cb6.jpg)

• this happens to me with all the mangas
• I only tried TuMangaOnline because I don't know if other extensions have the option to filter by scan
- This happens in all the mangas of the TuMangaOnline extension.
• I restarted the app after applying the filters, I did everything that occurred to me and that remained the same

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed for the nex t preview

**Comment by edmxn** [comment]
> Fixed for the nex t preview

By the way, the downloads are cancelled, I don't know why, it just happens, I assumed it's because I closed the app but not because I tried and the download didn't stop, I would appreciate it if you would take it into account

**Comment by jobobby04** [comment]
Unrelated, ash for help in the discord to get android to stop killing the app

**Comment by edmxn** [comment]
> Unrelated, ask for help in the discord to get android to stop killing the app

But this only appears in TachiyomiSY (do they have discord?) In fact I had to transfer everything to another version of Tachi just for downloads
And of course, I have the battery optimization disabled for SY, the same in the background
