### ISSUE TITLE
Mangadex chapters don't load

### ISSUE THREAD

**Issue by dingleberry53** [jobobby04/TachiyomiSY#739]
### Steps to reproduce

At first it wasn't loading specific chapters from Innocent Rogue (16,33,81 if that would help), I logged out from the mnag6adex setting6 and relogged in and it only loaded a couple of pages then stopped

### Expected behavior

load pages inside a chapter

### Actual behavior

![Screenshot_20221123_171140](https://user-images.githubusercontent.com/100795982/203647145-c2ae008d-c8b7-4965-8ab2-4e5f87ae4772.png)

doesn't load the pages for whatever reason

### Crash logs

--------- beginning of system
11-22 05:07:13.813 26788 26788 E ActivityThread: Failed to find provider info for com.zte.intellitext.IntelliTextProvider
11-22 11:36:22.598  5249  5249 E ActivityThread: Failed to find provider info for com.zte.intellitext.IntelliTextProvider
11-23 07:34:14.696 19606 19606 E ActivityThread: Failed to find provider info for com.zte.intellitext.IntelliTextProvider
11-23 16:20:13.001  6404  6404 E ActivityThread: Failed to find provider info for com.zte.intellitext.IntelliTextProvider
11-23 17:01:16.816 14159 14159 E ActivityThread: Failed to find provider info for com.zte.intellitext.IntelliTextProvider
--------- beginning of main
11-23 17:33:29.913 18126 18126 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
11-23 17:33:30.125 18126 18126 E SQLiteLog: (283) recovered 19 frames from WAL file /data/user/0/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-wal
11-23 17:33:30.165 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_comicextra.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.174 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_mangakakalots.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.181 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_manganeloscom.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.188 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_zh_manhuadui.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.197 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_zh_manhuagui.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.203 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_zh_manhuaren.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.209 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_ja_senmanga.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.232 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_readcomicsonline.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.239 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_ja_shonenjumpplus.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.246 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_mangakakalot.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.253 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_mangabat.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.260 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_mangasee.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.269 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_mmscans.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.277 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_ja_mangaraworg.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.373 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_all_mangadex.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.379 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_zh_tohomh123.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.387 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_zh_pufei.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.393 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_deathtollscans.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.400 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_ja_rawkuma.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.408 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_all_mangaplus.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.417 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_manhwanelo.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.423 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_kireicake.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.430 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_zh_manhuadb.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.435 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_ja_mangaraw.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.442 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_zh_dmzj.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.447 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_merakiscans.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.454 18126 18126 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/resource-cache/cache/icon-cache/icon/icon/eu_kanade_tachiyomi_extension_en_mangalife.png: open failed: ENOENT (No such file or directory)
11-23 17:33:30.470 18126 18229 E SQLiteLog: (284) automatic index on C(manga_id)
11-23 17:33:30.470 18126 18229 E SQLiteLog: (284) automatic index on R(manga_id)
11-23 17:33:30.470 18126 18229 E SQLiteLog: (284) automatic index on C(merge_id)
11-23 17:33:30.470 18126 18229 E SQLiteLog: (284) automatic index on R(merge_id)
11-23 17:33:30.470 18126 18229 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-23 17:33:31.880 18126 18126 E ActivityThread: Failed to find provider info for com.zte.intellitext.IntelliTextProvider
App version: 1.8.5 (standard, b7779ba, 36, 2022-08-14T19:51Z)
Preview build: 0
Android version: 10 (SDK 29)
Android build ID: S_SA_A2021G_V1.7
Device brand: ZTE
Device manufacturer: ZTE
Device name: P725A11
Device model: ZTE A2021G
Device product name: P725A11

### Tachiyomi version

1.8.5

### Android version

Android 10

### Device

ZTE 11 Axon

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Clear cache in advanced settings

**Comment by dingleberry53** [comment]
> Clear cache in advanced settings

I've already done that multiple times

**Comment by jobobby04** [comment]
It sounds like a cache issue. It works fine on my end and someone on discord confirmed it worked for them. No reason why it wouldn't work for you.

**Comment by dingleberry53** [comment]
> 

is there anything else I can try? it seems to be happening with other titles too
