### ISSUE TITLE
[Bug] TachiyomiSY crash in Android 10

### ISSUE THREAD

**Issue by VictoorH** [jobobby04/TachiyomiSY#74]
### Device information
* Tachiyomi version: v1.1.1
* Android version: Android 10 LineageOS (Custom ROM)
* Device: Galaxy s4 mini GT-I9192 (serranodsdd)

### Other details
"normal" Tachiyomi works fine but TachiyomiSY do not launch and say"TachiyomiSY keeps stopping"

**Comment by joseph619** [comment]
Post crash log, since I have Android 10 too and this doesn't happen

**Comment by VictoorH** [comment]
> Post crash log, since I have Android 10 too and this doesn't happen

the app does not open, how can I get the log?

**Comment by joseph619** [comment]
Use something like Logcat Reader from Play store

**Comment by VictoorH** [comment]
Here the log: https://puu.sh/GgioR.txt

**Comment by jobobby04** [comment]
Can you try this build? https://github.com/jobobby04/TachiyomiSYPreview/releases/tag/203

**Comment by VictoorH** [comment]
I installed it as an update (I didn't uninstall what I had before to install the dev build 203 version) and it worked perfectly.
Thank you.

**Comment by jobobby04** [comment]
I will close it when the next update releases, this is a problem some people were having, and I am confident it fixes the issue from what you have said 👍

**Comment by VictoorH** [comment]
Thank you.
