### ISSUE TITLE
[Very little issue] Extension word is not fully showed in italian

### ISSUE THREAD

**Issue by Palloxin** [jobobby04/TachiyomiSY#740]
### Steps to reproduce

![IMG_20221124_205447](https://user-images.githubusercontent.com/75091899/203856780-5e05a7a2-cd4d-4107-918b-1941340aef3d.jpg)

### Expected behavior

Maybe making a little bit of space so that the word is fully showed

### Actual behavior

Space too tight so the word "extension" in italian is not fully shown

### Tachiyomi version

1.8.5 r490

### Android version

Android 8

### Device

Huawei p8 lite 2017 miui 8

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
the full word is "Estensione". Just 3 letters missing "O n e"

**Comment by jobobby04** [comment]
Can't do much about this, it uses the material UI composable and i would have to try to write my own to even attempt a fix, which is just not worth the work.
