### ISSUE TITLE
[f-r] Include these settings in the backup

### ISSUE THREAD

**Issue by Palloxin** [jobobby04/TachiyomiSY#742]
### Describe your suggested feature

Include these settings in the backup:
1. Page preload amount
2. Integreted hentai features
3. delegated sources
4. Replace latest button
5. force horizontal seekbar
6. Fullscreen
7. Show page number
8. tap zones
9. default category
Edit:
10. merge button in overflow
11. raccomandations in overflow

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Settings backup if it ever comes, will be a main Tachi thing
