### ISSUE TITLE
[f-r] Add tachiyomisy icon to options in the settings that belong to this fork

### ISSUE THREAD

**Issue by Palloxin** [jobobby04/TachiyomiSY#743]
### Describe your suggested feature

![sdsdds](https://user-images.githubusercontent.com/75091899/203974749-f8c99203-a430-41dc-bf30-724ea8958bfa.png)
Like this.
My only way to know what are the features of tachisy.. is the missing translation of my language of certain options and sections. Imagine users that are native english (only that) how could they notice the difference? i suggest to add something like in the image to distinguish tachi sy features from the main branch. In the beginning i used english as language and i couldn't notice the difference between the feature of tachisy so i almost reported in the main github a problem with an option that belongs to this fork. This help users that don't know where to post reports when they have a problem with a fork option

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
I don't know if this is a good idea but what about proposing in the main branch about changing a bit the code to accomodate icons next to the name of options exclusive to forks? This would reduce wrong reports on github about problems with certains features that don't belong to the main branch

**Comment by jobobby04** [comment]
This would likely be too much work for little gain, there's not much point to do this

**Comment by Palloxin** [comment]
taking aside the modification of the main branch for it. What about a simple unicode at the end of the name of the option ? like this ✪ 
__
off topic for another issue i can't comment on anymore (i forgot), and i don't know how to contact you so.. #740 

https://user-images.githubusercontent.com/75091899/204768337-b064c57a-01ae-4802-986b-1f45c7d86e16.mp4
what about this? this comes from another fork of tachiyomi so it is ready to use, i guess.

**Comment by jobobby04** [comment]
1. I just don't see much of a point to something like this, they are SY specifc settings ya, but it doesn't usually matter since usually they will come ask in the SY channel or github first.
2. I don't think making the tabs scrollable is a good option.
3. E-H released the update, but I got caught up in main Tachi rewrites so I might have to wait for the next release before the next SY stable is released
