### ISSUE TITLE
Negative tags not working for Exhentai autofill

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#746]
### Steps to reproduce

1. Open Exhentai filter sheet
2. Use autofill tag search

### Expected behavior

Can add negative prompts like -female:big breasts 

### Actual behavior

It becomes female:big breasts instead

### Tachiyomi version

491

### Android version

Android 13

### Device

S21 ultra

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed for the next build 👍
