### ISSUE TITLE
Cannot save edited info of entries 

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#747]
### Steps to reproduce

1. Open a library manga
2. Open edit info box
3. Add a tag
4. Tap save

### Expected behavior

Tag should be added after tapping Save

### Actual behavior

Nothing happens, edit info box remains open

### Tachiyomi version

491

### Android version

Android 13

### Device

galaxy s21 ultra

### Other details

unsure if visual glitch

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Based on my testing, it just doesn't close the dialog, the changes do get saved though, you just have to re-open the manga. Anyway its fixed for the next build
