### ISSUE TITLE
Search bar not using full width, hard to see text

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#749]
### Steps to reproduce

1. Open browse
2. Open source like Mangadex

### Expected behavior

When search for manga (Boku No Hero Academia) in search bar, other icons should disappear, and full search bar should be visible

### Actual behavior

Icons persist on search bar, clipping text and making it hard to see full title length

![Screenshot_20221130_100012_TachiyomiSY](https://user-images.githubusercontent.com/83420659/204832379-9fbfa589-f3bf-4254-96a0-ed95b47e6757.jpg)

### Tachiyomi version

491

### Android version

android 13

### Device

galaxy s21 ultra 

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed for the next build
