### ISSUE TITLE
It takes too long to load the library

### ISSUE THREAD

**Issue by AethersKz** [jobobby04/TachiyomiSY#753]
### Steps to reproduce

TachiyomiSY:

https://user-images.githubusercontent.com/96607644/206187674-233736fa-eb49-44f7-a50d-59171b82af17.mp4

Tachiyomi stable (I have restored a backup of sy):

https://user-images.githubusercontent.com/96607644/206188137-be525e99-2499-48fa-83ca-536f42363107.mp4

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

TachiyomiSY 1.8.5 / Tachiyomi 0.14.2

### Android version

Android 11

### Device

Redmi 9A

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
your tachiyomisy build is very old and outdated. i would recommend installing preview version of sy

**Comment by AethersKz** [comment]
> your tachiyomisy build is very old and outdated. i would recommend installing preview version of sy

The latest stable version is considered outdated? 😁

I have already used the preview version and it is even worse, a lot of bugs and bad optimization, they add bugs instead of functions, that's why I went to the stable version

**Comment by jferdous70** [comment]
> > your tachiyomisy build is very old and outdated. i would recommend installing preview version of sy
> 
> The latest stable version is considered outdated? 😁
> 
> I have already used the preview version and it is even worse, a lot of bugs and bad optimization, they add bugs instead of functions, that's why I went to the stable version

Yes stable sy is based on 0.13.6, and preview is based on 0.14.x. The codebase is completely different. 

The bad optimization is Android issue, it will stay on next stable build too. Preview become faster the longer you use.

**Comment by SSL-ACTX** [comment]
@AethersKz I experienced it back then, when I installed TachiyomiSY on a phone with an outdated "**Android System Webview**." I fixed it by updating it. I have already tested it on most of my android devices.  Just update it if you haven't, but if it doesn't work, maybe its a bug or something(?).

**Comment by AethersKz** [comment]
@SSL-ACTX 
It didn't work, I'll try to use the preview version again
