### ISSUE TITLE
[Preview Version] Lag when going from tab/category

### ISSUE THREAD

**Issue by AethersKz** [jobobby04/TachiyomiSY#757]
### Steps to reproduce

https://user-images.githubusercontent.com/96607644/206759524-d61769e1-3b62-49c4-a7f6-4c37b65f4bf3.mp4

In the SY Stable version it goes much better 🐧

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

Preview r494

### Android version

Android 11

### Device

Redmi 9A

### Acknowledgements

- [x] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Known main Tachi thing
