### ISSUE TITLE
[Feature Request] Custom backup system 

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#76]
### Why/User Benefit/User Problem
The backup would save all info of a manga so that it works for dummy restore (such as chapters for a dummy entry)

### What/Requirements
The backup would perhaps be parallel to current system, so that it doesn't break compatibility with other forks/versions.

**Comment by jobobby04** [comment]
"Personally, I would just shove absolutely everything into my own version of the backup json.
And make outlets for taking care of unknown data"

**Comment by joseph619** [comment]
In addition to what has been added, also requesting to make backup of entire reading history (including manga not in library).

Some relevant comments that may help:

> SELECT * FROM mangas WHERE id IN(select UNIQUE (manga_id) FROM chapters WHERE read=1)
> 
> All just add a where favorited=0 so that it doesnt conflict with the library manga query
