### ISSUE TITLE
(Feature request) Encryption of the cache

### ISSUE THREAD

**Issue by Garantos** [jobobby04/TachiyomiSY#760]
### Describe your suggested feature

Encrypt the cache to keep safe users that enjoy OR stumble upon ill3gal material against their will. I am not sure if these data are called something else and also somewhere else; maybe other parts have to be encrypted too

### Other details

Given the nature of this fork (hentai), some results of hentai sources and of certain types are not exactly legal in some countries. When the app loads images these are technically downloaded somewhere in my phone. So keeping them in the cache is not exactly safe for the user; even if one doesn't like this type of stuff, when searching i already stumbled upon some sh0ta/l0l1/b3st1al1ty content with explicit covers (if i can see them they have been downloaded somewhere in my device) without looking specifically for them. Also my device main storage position is my sd card (on my android device i can choose internal or external storage, idk others) so it would be easy to get these images from my sd, even if deleted by the app.
It is common knowledge that files, when deleted, are just tagged as "rewritable" so the data stays there until it gets overwritten so if lucky (or unlucky, depends on the context) they can be recovered (with the root i guess)
In my country i read someone has been jailed just for one shota sticker from whatsapp that wasn't even his (someone sent it in a group chat) and then it has been discovered by the authorities in a way i don't remember.

I have been teached that when i have to sell my phone, before doing the hard reset i have to encrypt my files. then hard reset and so on..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Garantos** [comment]
I noticed this fork is mainly updated by jobobby. Should i ask this feature suggestion on the main fork too since in some countries just possessing material protected by copyright (aka manga material) is illegal (if not bought)? I'm telling this because i thought that maybe for just one person it is too work. Let me know please

**Comment by jobobby04** [comment]
I would suggest open this kind of issue in the main Tachi repo instead, I probably won't try to implement this. Though I don't expect this to gain much traction either way.
