### ISSUE TITLE
Updater gets stuck and hangs

### ISSUE THREAD

**Issue by JaitinPrakash** [jobobby04/TachiyomiSY#762]
### Steps to reproduce

1. Load TachiyomiSY
2. start an update

### Expected behavior

updater refreshes metadata and chapter count for all manga.

### Actual behavior

updater gets stuck at number 216.
not an issue with the manga itself, as I have removed several manga since the first occurrence of this bug and it only gets stuck at 216.

![Screenshot_20221214_074528_TachiyomiSY](https://user-images.githubusercontent.com/35095372/208000496-da7c4e19-7b41-4a22-9d75-83efea68af6f.jpg)

### Tachiyomi version

1.8.5

### Android version

Android 13 One UI 5.0

### Device

Note 20 Ultra 5G

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Force stop the app, logout of mangadex, wait for it to go through, force stop again, and then login and it should be fixed
