### ISSUE TITLE
(Feature Request) An option for hiding "read" manga under Browse > Filters. 

### ISSUE THREAD

**Issue by Devilmonk7402** [jobobby04/TachiyomiSY#763]
### Describe your suggested feature

When filtering using the browse/search, a new option to hide either:
* Read / Opened manga 
* completed manga 

So that they would be filtered and won't appear in the search. 

I listed both "read" and "completed" because 99% of the time, I stop reading before the manga ends, since it's just author notes, or draft panels. 

### Other details

Especially with particular sources or authors who publish each manga chapter individually, it becomes quite annoying having to figure out which ones I haven't read. 

**For example:**
1. You filter/search for a specific Artist or Group
2. They have published 40 individual manga chapters
  _(some being a series or continuation, but still separated; whereas others being their own one-chapter-story)_
4. You've already read or completed 35 of said chapters, but can't remember which ones you've read until you open the manga, and find out you've already started or finished it. 
5. Proceed to click each manga individually, 40 times, until you figure out which ones you haven't read. 

At the moment, the only roundabout solution I've made for this is creating a new Favorites catagory specifically called "Completed", and favoriting ALL the manga I've read; then, when searching the Artist or Group, ignoring anything that has the "♥" symbol. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Not interested in this personally, Tachi already has these issues open: https://github.com/tachiyomiorg/tachiyomi/issues/2371 and https://github.com/tachiyomiorg/tachiyomi/issues/2941
