### ISSUE TITLE
Enabling center margin causes pages to load infinitely 

### ISSUE THREAD

**Issue by loocool2** [jobobby04/TachiyomiSY#764]
### Steps to reproduce

1. Open a manga
2. Enable dual page mode
3. Go to a page with two pages
4. Enable center margin

### Expected behavior

The pages should load with a margin in between

### Actual behavior

The reader loads infinitely at the almost complete circle icon.

### Tachiyomi version

r495

### Android version

Android 9

### Device

Amazon Fire HD 10+

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Weird, it works fine in my emulator

**Comment by jobobby04** [comment]
Nvm I see it happening now

**Comment by jobobby04** [comment]
Found the issue, will be fixed in the next build
