### ISSUE TITLE
[Bug] Keyboard appears when exiting an entry given from the results of a click of a saved search

### ISSUE THREAD

**Issue by Palloxin** [jobobby04/TachiyomiSY#765]
### Steps to reproduce

https://user-images.githubusercontent.com/75091899/208305666-e46e9838-73bb-42a6-8085-e72ea1a8f356.mp4

1. open an extension that contains a saved search or just pick an extension and create one
2. start the search clicking of the saved search
3. click on a random entry
4. click back button to.come.back

### Expected behavior

Keyboard doesn't appear

### Actual behavior

Keyboard appears without me clicking on the search bar

### Tachiyomi version

r495

### Android version

Android 8 miui 8

### Device

Huawei p8 lite 2017

### Other details

This bug is also present on the main fork, BUT it can be triggered with the saved search. the thing that the two forks have in common is that it can be triggered with a keyword search. I also reported this here because the bug it involves also the saved searches of tachisy. Take in mind that the bug is not triggered by filtered searches (tachi and tachisy) but only by keyword searches on main tachi and only by keyword searches AND saved searches on tachisy
https://github.com/tachiyomiorg/tachiyomi/issues/8771

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a bug caused by a similar main Tachi bug related to global search, will re-open if still reproducable once that one is fixed
