### ISSUE TITLE
Change log not showing

### ISSUE THREAD

**Issue by semiya5** [jobobby04/TachiyomiSY#766]
### Steps to reproduce

Check for app update when one is available

### Expected behavior

Should show change log in the pop-up window

### Actual behavior

Is a blank screen

### Tachiyomi version

495

### Android version

Android 12

### Device

RedMagic 7

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Should be fixed now 👍
