### ISSUE TITLE
Search overload.

### ISSUE THREAD

**Issue by KasukeLp23** [jobobby04/TachiyomiSY#768]
### Steps to reproduce

1. Open extension (Any)

### Expected behavior

1. Open extension (Any)
2. are displayed normally

### Actual behavior

1. Open extension (Any)
2. It opens but it takes time to show the titles

### Tachiyomi version

1.8.5 (Latest Update Preview)

### Android version

Android 10

### Device

Redmi Note 11S

### Other details

**Video of Tachiyomi Preview (Latest Update)**

https://user-images.githubusercontent.com/70596255/208322639-419e11bc-b4db-4908-bb01-7cc286d14a94.mp4

**Video of TachiyomiSY Preview (Latest Update)**

https://user-images.githubusercontent.com/70596255/208322648-4f7c447f-a3fc-4f03-966d-6d4f9ed34604.mp4

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by KasukeLp23** [comment]
Note: In WebView it opens the page normally and perfectly. There is no problem with that.

**Comment by jobobby04** [comment]
Its probably Cloudflare throwing a fit or something(Its weirdly picky sometimes). Everything works fine on my end
