### ISSUE TITLE
[Feature Request] Hiding titles when using compact grid layout

### ISSUE THREAD

**Issue by RealKC** [jobobby04/TachiyomiSY#77]
### Why/User Benefit/User Problem
Titles are pretty redundant given covers are a thing imo. Also it'd allow moving the start reading button to the bottom right corner (like in comfortable grid) when the option is turned on.

### What/Requirements
A checkbox under the Display section of the "filter" area that only appears when you are using compact grid wouldn't be bad.

**Comment by jobobby04** [comment]
Added with https://github.com/jobobby04/TachiyomiSY/commit/a5c10dbf2810f4879e1f4b943717e42962b010f3
