### ISSUE TITLE
Latest version broke landscape (2 page) view

### ISSUE THREAD

**Issue by CritLoren** [jobobby04/TachiyomiSY#771]
### Steps to reproduce

1. Open manga
2. Have reader set to RTL
3. Rotate device

### Expected behavior

Page navigator to always reflect what's on the page and for the reader to not go to the end of a chapter.

### Actual behavior

The reader will now think you've just somehow finished the chapter and will be on the "no further chapters" screen at the end of the chapter while the page navigator will still show the correct page.

### Tachiyomi version

r495

### Android version

Android 10 and 13

### Device

SM-T719 and Grus

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed for the next build
