### ISSUE TITLE
Comico (JA), MangaRaw(JA) Not Working

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [jobobby04/TachiyomiSY#773]
Comico entries appear sarch results, but clicking on any chapter from them just shows a "not found" error popup.

MangaRaw is the the same, except the error is "bad-base64..."

**Comment by jobobby04** [comment]
Extension issues go in the extension repo https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose

**Comment by neurodiverseEsoteric** [comment]
How do you know it's not an issue with your renderer, or decoder/encoder, etc?

**Comment by jobobby04** [comment]
Because those are not decoder errors, they are extension errors.

**Comment by neurodiverseEsoteric** [comment]
base64 sounds like an encoding/decoding term to me...

**Comment by Syer10** [comment]
base64 isnt a image format. If the extension is using base64 for something, its got nothing to do with the apps image decoder.

**Comment by jobobby04** [comment]
base64 isnt a image format. If the extension is using base64 for something, its got nothing to do with the apps image decoder.
