### ISSUE TITLE
Opening via preview image is not working on read chapters

### ISSUE THREAD

**Issue by DemiMort** [jobobby04/TachiyomiSY#774]
### Steps to reproduce

1. Read/mark as read the chapter (on exh it should be the latest release).
2. Click on any image on the image preview.

### Expected behavior

The clicked page should open.

### Actual behavior

Nothing happens.

### Tachiyomi version

r498

### Android version

Android 12

### Device

One plus nord ce

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
Same issue. Jump to page from thumbnail previews don't work if chapter is read.
