### ISSUE TITLE
Open Random Manga (upstream)

### ISSUE THREAD

**Issue by Unknow0059** [jobobby04/TachiyomiSY#776]
### Describe your suggested feature

This was implemented upstream in [October](https://github.com/tachiyomiorg/tachiyomi/pull/8232).

I know version 1.8.5 doesn't support this.

This is different from https://github.com/jobobby04/TachiyomiSY/issues/692.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
SY already has it in the preview, stable will get it when the next release happens
