### ISSUE TITLE
[Bug] Minimum/maximum pages filter half broken (Exhentai)

### ISSUE THREAD

**Issue by Palloxin** [jobobby04/TachiyomiSY#779]
### Steps to reproduce

1. go to exhentai
2. open filter section
3. include the tag "milf"
4. set the minimum pages to 9
5. start the search
6. go back to the filter section, to the maximum pages box, you will see that it is auto filled cloning the value of "minimum pages"

https://user-images.githubusercontent.com/75091899/212743626-a3a0b139-88cf-481a-bfde-e9659167ced3.mp4

### Expected behavior

Maximum pages value does not auto fill 

### Actual behavior

Maximum pages value auto fills itself when I start the filtered search

### Tachiyomi version

r498

### Android version

Android 8 miui 8

### Device

Huawei p8 lite 2017

### Other details

If i DON'T include a tag, so setting only the minimum pages to 9, the maximum pages value will not auto fill itself

https://user-images.githubusercontent.com/75091899/212744191-01b81c5d-a34d-44ab-9fe0-b3bd2a6dc795.mp4

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I cannot reproduce this issue on my device/emulator, everything is working as it should

**Comment by Palloxin** [comment]
> I cannot reproduce this issue on my device/emulator, everything is working as it should

Try disabling the extension exHentai 
![IMG_20230205_060842](https://user-images.githubusercontent.com/75091899/216802858-664e09c8-2f1b-43dd-b9fc-b9abc5dbf306.jpg)
then when you re-enable it the app should ask you to login again from exhentai website. iirc the bug appeared rifht after i did that.

**Comment by jobobby04** [comment]
None of that would have any effect on the source filters, so I cannot see how that would help reproduce this bug. Does it still happen on your end?

**Comment by Palloxin** [comment]
OH strangely it doesn't happen anymore so ???. If it happens again i will report it again kr just reinstall the app.
