### ISSUE TITLE
[Feature Request] More options related to history/updates

### ISSUE THREAD

**Issue by crisalis2** [jobobby04/TachiyomiSY#78]
## ~~Why/User Benefit/User Problem~~
~~I never use these tabs. I find the updates tab unuseful, and the history tab is for me just a nuisance that I have to take care of with the "clear database" option. I would also suggest the option to not save history unless the manga is already in the library, but that would be for another issue.~~

## ~~What/Requirements~~
~~Those tabs just don't appear.~~

##

Since, as I was told, hiding those tabs won't happen, I change this issue to suggest options related to history/updates.

- Ability to use the already existing "clear database" option (which deletes history -read chapters, last page, read date...- for manga that are not saved in your library) directly from the history tab.
- In the history tab too, ability to remove all read dates at once, including those of manga that are in your library (only read dates, so that read chapters and last page aren't reset, but history tab is cleared). Right now it's possible to remove read dates for manga in the history tab, but you have to do this on a one by one basis.
- Ability to clear the updates tab completely, and directly from the updates tab (maybe ability to remove individual entries only too).
- Ability to not save at all any history (read chapters / last page / read date), for manga not in the library. So basically unless you add the manga to the library, the app doesn't remember anything about it.
- (Ability to never save read date for a manga, even if it's in the library.)

**Comment by joseph619** [comment]
This will likely never happen, you should use TachiyomiAZ if you don't like the current bottom navbar

**Comment by crisalis2** [comment]
Well, I don't have a problem with the bottom navbar, in fact I prefer it and find it easier to change between library, browse and settings with it, my thing is related to just those tabs I don't have a use for. But okay. I can just close this if this won't happen.

Regarding the way history works, as I hinted, I have the following wishes. Are these oe some of these more likely to be possible, so I can open another issue for them? Maybe this should be asked in base Tachiyomi, I'm not sure.
- Ability to use the already existing "clear database" option (which deletes history -read chapters, last page, read date...- for manga that are not saved in your library) directly from the history tab.
- Ability to not save at all read chapters / last page / read date for manga not in the library. So basically unless you add the manga to the library, the app doesn't remember anything about it.
- Ability to never save read date for a manga, even if it's in the library.
- Ability to clear the updates tab, completely or by individual entries.

**Comment by joseph619** [comment]
You can request to Clear all history and updates in 1 click, but hiding History and Updates tab will never happen.

I suggest you edit the post title and OP.

**Comment by joseph619** [comment]
This issue will be closed by the following PRs, which will add ability to both disable reading history and delete it as well
https://github.com/inorichi/tachiyomi/pull/3855
https://github.com/inorichi/tachiyomi/pull/3871

**Comment by crisalis2** [comment]
I tried the new changes. They don't address most points in the list I wrote. I understand those were too many and too specific requests, though. 

So I can make do with the new incognito mode, that solves the essential problem I have with the history tab... But there's a problem with the new incognito mode... it introduces an annoying banner that says "Incognito mode" all across the app... When you enable it you already know you are in "incognito mode", **so can that banner be removed?** Otherwise, for me, I don't think the benefit of not having the history tab filled with entries defeats the new problem of having to see an annoying banner always. 

Also, the updates tab part of the request is not addressed. It isn't possible to clear the tab, it still shows a history of updates. So the updates tab won't be addressed?

In any case, thanks.

**Comment by joseph619** [comment]
The banner is necessary to let the user know that Incognito mode is active. No other change is likely to happen. Also updates tab isn't meant to be cleared. You can close this ticket now, or it will be auto closed after next stable update.
