### ISSUE TITLE
[Browse > Feed] Follow Library > Items per row display setting

### ISSUE THREAD

**Issue by mqwec43as** [jobobby04/TachiyomiSY#780]
### Describe your suggested feature

I'd like to request a feature where the Feed tab item per rows display setting matches to Library item per rows display setting.

For the time being, both of them look different and it makes it somewhat visually unpleasant to look at when user browses the filter from the Feed tab

Since we don't have the setting dedicated for the feed tab (as far as I'm aware) It would be nice to have them to follow the library display setting.

### Other details

Here is a comparison. 

Library
![Library](https://i.imgur.com/pWRQSyw.jpeg) 

Feed
![Feed](https://i.imgur.com/Sl6iREk.jpeg)

Browse Filter from Feed
![Filter](https://i.imgur.com/ZAx9TVn.jpeg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Feed uses the Global Search UI, and since it's not a grid it wouldn't work with that setting.

**Comment by mqwec43as** [comment]
Aw, I see. What about adjusting the size and having their own setting then? I'm not sure if this is a fool proof method tough.

I only have one device so I'm not sure if this could be made consistent through multiple platform. 

Beside the looks, having a smaller size makes it quite hard to swipe horizontally, especially for those whose thumb are like elephant. I have quite a few accidental swipe where I swipe on the feed title and it switches to the next tab.

Here's an example from mangadex, it has two covers visible and it has bigger space to swipe.

![Mangadex](https://i.imgur.com/9YEbgbJ.png)

**Comment by jobobby04** [comment]
There wouldn't be much benefit to that in my opinion. Maybe suggest something like that for main Tachi global search, since Feed just uses that UI.

**Comment by mqwec43as** [comment]
The benefit would be the same as organising effect as those in the library and It looks nicer to have everything in uniform. 

Anyway, Isn't Feed exclusively avaiable in TachiyomiSY only? I naturally thought that the size is defined by the fork.

What about using something similar like in Migration? Is this not a part of the global search UI?

It looks bigger and less cramped as well
![migration](https://i.imgur.com/RuT5Pv8.jpeg)

Maybe I should photoshop things a bit to create a mock up, what do you think?
