### ISSUE TITLE
Filtering lewd series requires restart after editing tags

### ISSUE THREAD

**Issue by ItsLogic** [jobobby04/TachiyomiSY#782]
### Steps to reproduce

1. Add "Lewd" tag to series
2. Change lewd library filter
3. Filter doesnt impact this series

### Expected behavior

1. Add "Lewd" tag to series
2. Change lewd library filter
3. Series should be filtered properly

### Actual behavior

1. Add "Lewd" tag to series
2. Change lewd library filter
3. Filter isnt applied until app restart

### Tachiyomi version

r498

### Android version

13

### Device

Xiaomi Mix Fold 2

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a Main Tachi bug, I think there is an open issue for it in the main Tachi repo
