### ISSUE TITLE
Can't scroll in the black part of the screen when pinch to unzoom a webtoon

### ISSUE THREAD

**Issue by starscream00** [jobobby04/TachiyomiSY#784]
### Steps to reproduce

1. Open any webtoon in webtoon mode
2. Pinch to unzoom
3. Scroll the black(or the background ) part of the screen

### Expected behavior

Webtoon should scroll

### Actual behavior

Nothing happens 

### Tachiyomi version

1.9.0

### Android version

Android 10

### Device

Lenovo x606f

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Main Tachi bug that will be fixed in the next release
