### ISSUE TITLE
Disable E-Hentai gallery page previews

### ISSUE THREAD

**Issue by w4tchdoge** [jobobby04/TachiyomiSY#786]
### Describe your suggested feature

Update 1.9.0 added the ability to preview galleries added from E-Hentai/ExHentai and NHentai. While I understand that this is a very useful feature to most people, with the way I use the app it is unnecessary and I would like to be able to turn it off.
If it is possible to have an option to turn previews off I would also like to know whether this is something you are likely to spend time implementing, as I understand this is quite a trivial issue and there are probably more important things about the app that need fixing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
SY is always going to show at least some previews, there is a issue to make them configurable though https://github.com/jobobby04/TachiyomiSY/issues/643
