### ISSUE TITLE
Another option for searching 

### ISSUE THREAD

**Issue by Turhvjbufv** [jobobby04/TachiyomiSY#789]
### Describe your suggested feature

So when you search you would have an option to show anything other than what you search for for example, if I search "romance" and then press on this option it would show any tag I have in my library except for manga/manhua/manhwa with the romance tag/"romance" (word) in their description 
Sorry if unclear

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BaccanoMob** [comment]
There is though. You give '-' before the word you want to omit. For example, '-romance' so that it shows all entries without romance tag.

**Comment by Turhvjbufv** [comment]
Tnx, didn't know about it
