### ISSUE TITLE
[Feature Request] Alternate view for Browse screen 

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#79]
## Why/User Benefit/User Problem
Users will be able to see all relevant content (such as Trending, Latest, New, recommendations) from a source at the same time.

## What/Requirements
The view can be enabled to be default browse view in More > Settings > Browse. A display mode button can be put on top right to switch back and forth between the modes easily. More info on Discord server

Example

<img width="364" alt="Screenshot_2020-09-10_at_16 50 52" src="https://user-images.githubusercontent.com/34897862/92773160-5f596b00-f36a-11ea-88d9-ccf664ead13a.png">

<img width="434" alt="Screenshot_2020-09-10_at_15 30 27" src="https://user-images.githubusercontent.com/34897862/92773296-7b5d0c80-f36a-11ea-80eb-081aa05d6b95.png">

<img width="251" alt="Screenshot_2020-09-08_at_23 14 37" src="https://user-images.githubusercontent.com/34897862/92773440-9b8ccb80-f36a-11ea-87bf-9f666ba3d957.png">

**Comment by joseph619** [comment]
Requesting to modify this feature to show something like this. It would show this screen directly on Browse instead of Source/Extension, and users would switch to new sources using dropdown.

![Enhanced_Browse_Tachiyomi](https://user-images.githubusercontent.com/34897862/92492508-6729db80-f1c1-11ea-94ce-1c34e9ade99f.jpg)

![Enhanced_Browse_Tachiyomi_with_dropdown](https://user-images.githubusercontent.com/34897862/92492666-9ccec480-f1c1-11ea-9c86-b9ae04eb62d7.jpg)

**Comment by joseph619** [comment]
Only doable for Mangadex which is half broken every other day, make too many network calls and not viable for other sources. Closing

**Comment by joseph619** [comment]
@jobobby04 Reopned this after seeing Paperback's tabs for Sources in Browse, and it looks incredible imo. Pls add this 🙏 
![#feedback mp4_snapshot_00 00_ 2021 04 01_14 28 02](https://user-images.githubusercontent.com/34897862/113338196-c6367580-92f6-11eb-9c12-b3b86356bd6e.jpg)

Here's a video of it 

https://discord.com/channels/673606787290759230/676014470316949504/826595944836890664

**Comment by jobobby04** [comment]
Hmmm, looks a bit impossible for most sources lol

**Comment by joseph619** [comment]
Could probably only be applied to the sources which Paperback uses, maybe?
