### ISSUE TITLE
Crash when selecting any manga from any source

### ISSUE THREAD

**Issue by erebfaer** [jobobby04/TachiyomiSY#790]
### Steps to reproduce

Browse any source, and select any manga/gallery

### Expected behavior

Manga is opened

### Actual behavior

Crash

### Crash logs

![Screenshot_20230209-005538_TachiyomiSY](https://user-images.githubusercontent.com/11277129/217551642-f3d046a3-58cb-4ca5-ae02-dc6dcf89afb8.jpg)
[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/10686252/tachiyomi_crash_logs.txt)

### Tachiyomi version

1.9.0

### Android version

8.1

### Device

Samsung Galaxy Tab A10 / SM-T580

### Other details

Problem did not exist prior to latest update.
Does not occur in latest base Tachiyomi.
Tested a dev version as well.

In addition to crash, app in general is general is slow to load anything, particularly browsing sources.
This problem also does not occur in base Tachiyomi.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Use `Settings -> Advanced -> Debug -> Force upgrade migrations`
