### ISSUE TITLE
Batch Add Crashes App

### ISSUE THREAD

**Issue by annonmerchy** [jobobby04/TachiyomiSY#791]
### Steps to reproduce

1. Open Batch Add
2. Enter URLs and Press the Add Galleries Button
3. Press Finish (unsure if this only happens on success)

### Expected behavior

The Finish button should take you back to the Batch Add screen to add more urls.

### Actual behavior

The App Crashes

### Crash logs

[tachiyomi_crash_logs.txt](https://gist.github.com/b0f3073331b4c1e5cffab16aa6a09fbf)

### Tachiyomi version

1.9.0

### Android version

Android 12

### Device

Samsung Galaxy Note 10+

### Other details

The batch add feature is one of the main features that TachiyomiSY has that other forks don't, so it's a bit disappointing to see it break like this.
I've experienced a lot of other crashes and unusual behavior since the latest update which seem to be UI related.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Should be fixed in the next build
