### ISSUE TITLE
See Recommendations Bug

### ISSUE THREAD

**Issue by OmfgItsJesus** [jobobby04/TachiyomiSY#792]
### Steps to reproduce

Make sure See Recommendations button is enabled in settings after that select any manga or doujin select any of the Recommendations after that you have to select a source after you do that and it finds no results.

### Expected behavior

Once your here you can't go back/back out you have to close the app and reopen it to get back to your library or anything else in app.

### Actual behavior

Once your here you can't go back/back out you have to close the app and reopen it to get back to your library or anything else in app.

### Tachiyomi version

Preview r499

### Android version

Android 13

### Device

Samsung Tab 8 Ultra & Flip 4

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Should be fixed for the next build
