### ISSUE TITLE
See Recommendations & Display Tag Option

### ISSUE THREAD

**Issue by OmfgItsJesus** [jobobby04/TachiyomiSY#793]
### Describe your suggested feature

See Recommendations option needs to be updated after you select one of the Recommendations it should allow you to select the sources you would like to look it up on just like when you do Migrate. Because as of now it only allows you to select one and it's currently bugged once you look up one and get no results you can't press back have to end up close app to go back to library.

Also in Library on the Display Option would be nice if Badges had a option called "Total Chapters" to show how many chapters in total that manga you have has in total. Yes sounds dumb but sometimes I send my backup to friends and they can't see chapters on manga cause I have started reading some and looks like it's 5 in total but it's like 349 cause I almost have finished it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [x] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I think you already opened a issue about the see recs issue, and I am not interested in a total chapters badge, see if main Tachi would add it.
