### ISSUE TITLE
Enhanced MangaDex shows API result when opening Webview

### ISSUE THREAD

**Issue by noaione** [jobobby04/TachiyomiSY#795]
### Steps to reproduce

1. Open any manga from MangaDex
2. Click the WebView button

### Expected behavior

Open the actual manga page

### Actual behavior

Shows the API result

### Tachiyomi version

Dev r499

### Android version

Android 9

### Device

Amazon FireHD 8 (2020)

### Other details

It looks like API v1.4 are pushed to the extensions repo on main Tachiyomi and it broke the enhanced source in SY since iirc the extension use some kind of workaround to show the actual pages.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed for the next build
