### ISSUE TITLE
Tag Sorting Tags not working

### ISSUE THREAD

**Issue by TierzaChase** [jobobby04/TachiyomiSY#797]
### Steps to reproduce

1. Go to Settings
2. Go to Library
3. Go to Tag Sorting Tags
4. Add / edit tags

### Expected behavior

Library should be sorted according to the tags. 

### Actual behavior

Library is instead sorted alphabetically. 

I just updated to App version: 1.9.0. It was working just fine on App version: 1.8.5, but after I updated it, my library changed. 

### Tachiyomi version

1.9.0

### Android version

Android 12

### Device

Samsung S22 Ultra

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Should be fixed for the next build
