### ISSUE TITLE
Save Searchs not Work

### ISSUE THREAD

**Issue by derinakcay8** [jobobby04/TachiyomiSY#798]
### Steps to reproduce

1.go to source
2.Select filter
3.save filter
4.click saved search

### Expected behavior

manga in source should show based on selected filters

### Actual behavior

nothing happen when click saved search and where the source name is, there is a text called a eu.kanada.domain.source.interactor.POPULAR
![e793e804-df9f-42f7-a9e6-118e7f0dc0fe](https://user-images.githubusercontent.com/121522858/218847395-2b428861-c2ab-43a6-b83b-76ab9ffd2ee2.jpg)

### Tachiyomi version

1.9.0

### Android version

Android 11

### Device

Samsung A30s 

### Other details

I tried saved search on Mangabuddy,Mangadex,Manganato,Asura scans  source but nothing changed

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
You probably forgot to press filter before saving your search
