### ISSUE TITLE
[Feature Request] Auto choose API based on tags

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#8]
Instead of current method, titles will show recs for either MAL or Anilist based on its genre tags 

For Manhua/Manhwa/Webtoon/Long Strip, it will always be Anilist and show names in English

Otherwise, it will use MyAnimeList

**Comment by jobobby04** [comment]
Added in #10 and https://github.com/jobobby04/TachiyomiSY/commit/24067e1e97e7421a83f9c72dae629018cf54b1a4
