### ISSUE TITLE
Migration bug

### ISSUE THREAD

**Issue by lcd047** [jobobby04/TachiyomiSY#801]
### Steps to reproduce

1. Migrate a manga to a different source (no issue so far, this succeeds)
2. Try to migrate a second manga to some different source
3. Pre-migration stage for the first migration is offered again.

### Expected behavior

The operation should proceed with pre-migration for the second manga.

### Actual behavior

Pre-migration for the first migration is brought up again.  If you cancel it and retry the second migration, the second migration succeeds.

### Crash logs

No crash is involved.

### Tachiyomi version

Preview r499

### Android version

Android 13

### Device

Samsung S23 Ultra

### Other details

This seems to be a leftover from a previous fix related to source migration.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
I have the same issue too. 

If I migrate manga from source to source B first, then again try migrating from C to D, the app shows migration screen for  A to B

**Comment by Blackklegend** [comment]
Seems fixed in the last dev build (502)
