### ISSUE TITLE
Exclude tags on Exhentai not working

### ISSUE THREAD

**Issue by Palloxin** [jobobby04/TachiyomiSY#802]
### Steps to reproduce

NSFW warning due to the nature of the extension
https://user-images.githubusercontent.com/75091899/220932980-d38e1def-d424-403d-948c-8915271f789f.mp4
NSFW warning due to the nature of the extension

as you can see in the video i exclude the tag "western imageset" and yet an entry with that tag appear anyway after i excluded it

### Expected behavior

entries with the tag "western imageset" shoyld not appear

### Actual behavior

entries with the tag "western imageset" appear

### Tachiyomi version

r499

### Android version

Android 8 miui 8

### Device

huawei p8 lite 2018

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
On the gallery you showed it was a low power tag, exhentai does not take low power tags into account unless you use the `weak:` prefix. Like `weak:western imageset`

**Comment by Palloxin** [comment]
I tried the format u suggested and that tag is still not excluded 
https://user-images.githubusercontent.com/75091899/220938241-c90c3e7d-b6ca-492c-b11c-86570f775b53.mp4

**Comment by jobobby04** [comment]
¯\\_(ツ)_/¯. Take that up with the website, its not a app specific thing
