### ISSUE TITLE
Unable to read a Manga. 

### ISSUE THREAD

**Issue by Beech0408** [jobobby04/TachiyomiSY#804]
### Steps to reproduce

I went to browse, then sources, then Mangabuddy, the searched for the Manga I'm looking for. 

### Expected behavior

I expected to see the Manga with its chapters. 

### Actual behavior

Zero chapters found. A long error message always pops up and I found out that the number chapters of the Manga is zero. I checked the Manga while using Webview of the same extension (Mangabuddy) and it is normal (the chapters were intact). I attached a screenshot of the pop-up message. 
![Screenshot_20230225-163351](https://user-images.githubusercontent.com/118119005/221366526-afe9d7ad-0ff1-4131-8e35-a015f1f5d8c2.png)

### Crash logs

--------- beginning of crash
02-25 13:50:34.509 32610  7673 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
02-25 13:50:34.509 32610  7673 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 32610
--------- beginning of main
02-25 17:04:53.731 19143 19225 E libPowerStretch: LucidStats currentFPS = 5.23 [2384984432]
02-25 17:05:02.014 19143 19225 E libPowerStretch: LucidStats currentFPS = 14.49 [2384984432]
02-25 17:05:04.949 19143 19225 E libPowerStretch: LucidStats currentFPS = 40.89 [2384984432]
02-25 17:05:09.750 19143 19225 E libPowerStretch: LucidStats currentFPS = 24.99 [2384984432]
02-25 17:05:11.815 19143 19225 E libPowerStretch: LucidStats currentFPS = 58.11 [2384984432]
02-25 17:05:13.920 19143 19225 E libPowerStretch: LucidStats currentFPS = 57.00 [2384984432]
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: JSON input: <html>
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: <head><title>502 Bad Gateway</title></head>
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: <body>
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: <center><h1>502 Bad Gateway</h1></center>
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: <hr><center>nginx/1.18.0 (Ubuntu)</center>
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: </body>
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: </html>
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:1)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:2)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:70)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:15)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:124)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:47)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:9)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:23)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:26)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:7)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.json.JsonObjectSerializer.deserialize(JsonElementSerializers.kt:3)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.json.JsonObjectSerializer.deserialize(JsonElementSerializers.kt:1)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:74)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:32)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.multisrc.madtheme.MadTheme.chapterListParse(MadTheme.kt:362)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.multisrc.madtheme.MadTheme$fetchChapterList$1.invoke(MadTheme.kt:166)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.multisrc.madtheme.MadTheme$fetchChapterList$1.invoke(MadTheme.kt:165)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.multisrc.madtheme.MadTheme.fetchChapterList$lambda$11(MadTheme.kt:165)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.multisrc.madtheme.MadTheme.$r8$lambda$igbV8ECpBSFx3qTW4JKlFwjUSS4(Unknown Source:0)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.multisrc.madtheme.MadTheme$$ExternalSyntheticLambda0.call(Unknown Source:2)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:3)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:32)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at rx.Subscriber.setProducer(Subscriber.java:39)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:3)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda1.call(R8$$SyntheticClass:24)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at rx.Observable.unsafeSubscribe(Observable.java:10)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at rx.Observable.subscribe(Observable.java:24)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:29)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.source.Source$DefaultImpls.getChapterList(Source.kt:5)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.source.online.HttpSource.getChapterList(HttpSource.kt:1)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.ui.manga.MangaInfoScreenModel$fetchChaptersFromSource$2.invokeSuspend(MangaScreenModel.kt:55)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.ui.manga.MangaInfoScreenModel$fetchChaptersFromSource$2.invoke(MangaScreenModel.kt:13)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.util.lang.CoroutinesExtensionsKt.withIOContext(CoroutinesExtensions.kt:3)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.ui.manga.MangaInfoScreenModel.fetchChaptersFromSource(MangaScreenModel.kt:80)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at eu.kanade.tachiyomi.ui.manga.MangaInfoScreenModel$2$fetchFromSourceTasks$2.invokeSuspend(MangaScreenModel.kt:34)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:20)
02-25 17:05:18.885 19143 19447 E MangaInfoScreenModel: 	... 27 more
02-25 17:05:19.671 19143 19225 E libPowerStretch: LucidStats currentFPS = 20.87 [2384984432]
02-25 17:05:22.731 19143 19225 E libPowerStretch: TimeStamps from Cache: lucid = 20081231170000, customer = 20081231170000
02-25 17:05:22.731 19143 19225 E libPowerStretch: Cache valid RC: lucid = 2, customer = 2
02-25 17:05:22.733 19143 19225 E libPowerStretch: Priority black list: 0
02-25 17:05:22.733 19143 19225 E libPowerStretch: Mode = WVS
02-25 17:05:22.734 19143 19225 E libPowerStretch: Ice is working with black list method
02-25 17:05:22.735 19143 19225 E libPowerStretch: LUCID changing m_iceStateConfig from 0 to 2 
02-25 17:05:22.737 19143 19225 E libPowerStretch: EglCreateWindowSurfaceImp pid 19143 != tid 19225  mResized = 1 [456 192] 1.000000 mIsIceDelayed_wl 1  mIsIceMainThread 0 m_HardCodedBlackListed 1 _X_
02-25 17:05:23.271 19143 19225 E libPowerStretch: LucidStats currentFPS = 33.33 [2384984432]
02-25 17:05:25.447 19143 19225 E libPowerStretch: LucidStats currentFPS = 55.14 [2384984432]
02-25 17:05:27.797 19143 19225 E libPowerStretch: LucidStats currentFPS = 51.08 [2384984432]
02-25 17:05:29.949 19143 19225 E libPowerStretch: LucidStats currentFPS = 55.76 [2384984432]
02-25 17:05:31.951 19143 19225 E libPowerStretch: LucidStats currentFPS = 59.94 [2384984432]
02-25 17:05:35.858 19143 19225 E libPowerStretch: LUCID Battery Level = 80% Battery Temp = -100 Cpu Temp = -100
02-25 17:05:47.200 19143 19225 E libPowerStretch: LucidStats currentFPS = 7.87 [2384984432]
02-25 17:05:47.403 19143 19143 E MangaInfoScreenModel: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@e314ecc
App version: 1.9.0 (standard, d24a8d2, 46, 2023-02-04T23:26Z)
Preview build: 0
Android version: 8.1.0 (SDK 27)
Android build ID: LA7-H393A-O-181211V188
Device brand: TECNO
Device manufacturer: TECNO MOBILE LIMITED
Device name: TECNO-LA7
Device model: TECNO LA7
Device product name: H393

### Tachiyomi version

1.9.0 (stable) 

### Android version

8.1.0

### Device

Tecno LA7 

### Other details

I await your assistance. Thank you in anticipation. 

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Website issue, not anything to do with SY
