### ISSUE TITLE
Broken file names

### ISSUE THREAD

**Issue by JaitinPrakash** [jobobby04/TachiyomiSY#806]
### Steps to reproduce

1. Download manga chapter
2. confirm that downloads are properly completing
3. go do something else for a while
4. come back, see that the number of downloaded chapters in the corner of the cover matches the number you downloaded
5. open the manga info page
6. notice that half of more of the chapters are "not downloaded"

### Expected behavior

files should not have the "(1)" in their names and should be readable in the app

### Actual behavior

![Screenshot_20230302_061736_File Manager +](https://user-images.githubusercontent.com/35095372/222454712-b3c46d0b-5d6b-41d5-acfa-728fb2e94b4d.png)
![Screenshot_20230302_061713_TachiyomiSY](https://user-images.githubusercontent.com/35095372/222454719-e132df0c-19c6-498c-8ab2-f233de095157.png)

### Tachiyomi version

1.90

### Android version

Android 13 ONE UI 5.0

### Device

Note20 Ultra

### Other details

This is has happened to over 2000 files, most of them in mangadex

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Main tachi bug, you have to delete the folder and download everything again to fix it
