### ISSUE TITLE
"Gallery does not exist" error when using Batch add

### ISSUE THREAD

**Issue by w4tchdoge** [jobobby04/TachiyomiSY#807]
### Steps to reproduce

1. Paste gallery link into "Batch add" input box
2. Press "Add Galleries"

### Expected behavior

Gallery is added to library

### Actual behavior

Gallery fails to be added to library
![Screenshot_2023_03_03_14_12_12_80_a603e4da04bada03cae438f177815547](https://user-images.githubusercontent.com/28806101/222742946-fbbf2eb4-7b97-4311-93de-107bb4652ec4.jpg)

### Tachiyomi version

1.9.0

### Android version

Android 13

### Device

OnePlus 9R

### Other details

- I've tested adding other gallery links using Batch add but they all work fine.
- I can also go to my favourites via WebView and find this gallery that the app is saying does not exist.
- I've also verified its visibility on two different browser's that I'm signed into E-H on. However, **the gallery is shown to be unavailable when I am not signed in**.
- I've also done a re-login to E-H via the in-app settings for the E-H login.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
That gallery is not avalible on E-Hentai, you have to use the ExHentai link to view it

**Comment by w4tchdoge** [comment]
> That gallery is not available on E-Hentai, you have to use the ExHentai link to view it

The same error occurs when using the ExHentai link ([image of the error](https://i.imgur.com/6MH9SlE.jpeg)), I cannot add it using batch add nor does it show up when I search for it using the source ([image link](https://i.imgur.com/UPfrvlH.jpeg)), but I can access it in-app using the WebView from the ExHentai source ([image link](https://i.imgur.com/GKmt78C.jpeg)) (I have used the same search terms for both the in-source search and the WebView search).
