### ISSUE TITLE
Categories broken in other grouping methods

### ISSUE THREAD

**Issue by semiya5** [jobobby04/TachiyomiSY#808]
### Steps to reproduce

Group library by any method other than Categories
Select a series
Press category button
Receive wrong list of categories

### Expected behavior

Should show categories made by user

### Actual behavior

Shows categories based on grouping method

### Tachiyomi version

499

### Android version

Android 12

### Device

RedMagic 7

### Other details

![IMG_20230305_140228](https://user-images.githubusercontent.com/1321906/222980605-027490ca-6082-451d-94b9-777a11b3f62e.jpg)
Attached image in case of bad explanation. It's showing tracking categories instead of my made categories

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Should be fixed for the next build
