### ISSUE TITLE
[Feature Request] ExpandableListView for Update

### ISSUE THREAD

**Issue by shashank-p** [jobobby04/TachiyomiSY#81]
ExpandableListView for Update as it will be helpful in grouping chapters of manga with title and it'll be organized for user convenience

Something similar like this :
[image](https://i2.wp.com/tutorialwing.com/wp-content/uploads/2018/09/tutorialwing-android-expandablelistview-output.gif)

**Comment by joseph619** [comment]
Should also open this ticket on the main app repo, this doesn't need to be Sy specific
