### ISSUE TITLE
New 1.9.0 update made  the app extremely laggy and sources load super slow

### ISSUE THREAD

**Issue by shehabcy** [jobobby04/TachiyomiSY#816]
### Steps to reproduce

The recent Library update takes way too long compared to previous update.
And runs extremely laggy and slow

### Expected behavior

It would be really helpful if the new update gixes the aforementioned issues. Than the app may run very smoothly 

### Actual behavior

Runs extremely laggy. Library recent updates are taking hours where is used to take 10-15 minutes. And sources load slow even with vpn

### Tachiyomi version

1.9.0

### Android version

Android 12 , android 6

### Device

Samsung m11

### Other details

  
None

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
The library updator is majorly from main Tachi. And the app wouldnt really have an effect on the speed since it mostly depends on your internets connection to your sources.
