### ISSUE TITLE
Can't Edit Covers

### ISSUE THREAD

**Issue by Zero-G-Sys** [jobobby04/TachiyomiSY#817]
### Steps to reproduce

1. Open any manga
2. Go to "Edit info"
3. Touch cover image

### Expected behavior

It should let you select a local image to replace default cover

### Actual behavior

Upon touching the cover nothing happens

### Tachiyomi version

1.9.0

### Android version

Android 13 (One UI 5.1)

### Device

Samsung Galaxy S21 Ultra

### Other details

- Started happening since last big stable update. 
- I also would like to request (I will make a proper issue after this is fixed) if you can select a page from the manga for the cover instead of searching a local file, and even better if you can crop it.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Click on the cover in the manga page and use the edit function there, I removed the function in the edit info dialog for now

**Comment by Zero-G-Sys** [comment]
Ah, there it is, quite difficult to spot when using the pure black dark mode theme.
