### ISSUE TITLE
Crop an image when editing a cover

### ISSUE THREAD

**Issue by Zero-G-Sys** [jobobby04/TachiyomiSY#819]
### Describe your suggested feature

Let the user crop a selected image when editing a cover.

The purpose of this it mainly to extend the functionality of #818. Sometimes the cover by default is a doble page spread and it will be shown centered and with low resolution. Letting the user select the first page of the current manga, and crop it to a proper cover format will save the user of doing it all of it externally.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
You can already save an image to gallery from reader, then crop it with gallery app. Why should sy add photo editing options?
