### ISSUE TITLE
[bug] something appears in the search bar on 1st kiss only when i trigger a saved search

### ISSUE THREAD

**Issue by Palloxin** [jobobby04/TachiyomiSY#823]
### Steps to reproduce

I noticed it in the version r502

https://user-images.githubusercontent.com/75091899/225801945-69711ebc-ea08-4c54-aeb9-7ec5b9cfa974.mp4

### Expected behavior

clean search bar

### Actual behavior

This appear after the trigger of a saved search:
 ```eu.kanade.domain.source.interactor.POPULAR```

### Tachiyomi version

r503

### Android version

Android 8 miui 8

### Device

huawei p8 lite 2017

### Other details

Doesn't happen if i do a normal filtered search in 1stKiss so i guess it is TachiSY problem

https://user-images.githubusercontent.com/75091899/225802267-fbab4f96-f354-436f-9d78-c99ac2a634a7.mp4

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Delete the saved search and create it again, I fixed this in 503
