### ISSUE TITLE
[Bug] Specifics of a filtered search don't appear when triggering a saved search

### ISSUE THREAD

**Issue by Palloxin** [jobobby04/TachiyomiSY#827]
### Steps to reproduce

1. Go to Nhentai
2. open filter section
3. trigger a saved search 

### Expected behavior

Info are showed in their related value boxes like tags number of pages etc..

### Actual behavior

NSFW warning
https://user-images.githubusercontent.com/75091899/225926839-db903c10-7fcd-4b72-90f1-97c640a4eb05.mp4
NSFW warning

### Tachiyomi version

r503

### Android version

android 8 miui 8

### Device

huawei p8 lite 2017

### Other details

examole on nhentai. If you write "milf" in the tag box, start the filtered search (so not a saved one) and then trigger right away a saved search, the tag "milf" will still remain so when a saved search gets triggered the value boxes are not overwritten.

NSFW warning
https://user-images.githubusercontent.com/75091899/225928080-efc37cc6-8c93-48c9-9f7f-6d1d93ecbe9c.mp4
NSFW warning

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
I tried to create new saved searches in the r503 but the problem still persists

**Comment by jferdous70** [comment]
Can reproduce, tags dont appear for saved search queries

**Comment by Palloxin** [comment]
Fixed in the version r504
