### ISSUE TITLE
all extensions take a very long time to load.

### ISSUE THREAD

**Issue by Volern** [jobobby04/TachiyomiSY#828]
### Steps to reproduce

Browsing any extension takes a very long time to load, this includes just opening the extension, opening latest for the extension, any filters applied and just scrolling down the list until it shows new series, at which point takes a while to start loading.

### Expected behavior

It should load relatively quickly.

### Actual behavior

Takes a considerable amount of time to load. It appears at first glance to correlate time taken to load with amount of series the extension has. For example LH Translation has very few series and takes about 5 to 10 seconds to load, but something like mangadex has thousands of series and took upwards of a minute to load.

### Tachiyomi version

1.9.0

### Android version

Android 11

### Device

OnePlus 8 pro

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
I dont think this is a sy issue. You can check troubleshooting guide

https://tachiyomi.org/help/guides/troubleshooting/#what-are-some-common-issues

**Comment by Volern** [comment]
> I dont think this is a sy issue. You can check troubleshooting guide
> 
> https://tachiyomi.org/help/guides/troubleshooting/

I compared it to regular tachiyomi and it loads everything just fine, but SY does not load properly.

**Comment by jferdous70** [comment]
Sy doesn't do anything special in regards to loading source, to my knowledge. You can follow the steps in the troubleshooting guide, it usually fixes all issues

**Comment by Volern** [comment]
> Sy doesn't do anything special in regards to loading source, to my knowledge. You can follow the steps in the troubleshooting guide, it usually fixes all issues

You have to go through the troubleshooting steps to post an issue, so I've already done everything there. I even uninstalled the app and reinstalled it along with every extension and the behaviour is the same. It was completely fine before updating to 1.9. I was on a version that ran on I believe tachiyomi 1.13.5 or something, not sure the SY version number, and it loaded just fine. The only reason I updated was because my extensions would not longer update on the version I was on so I updated the app to fix it.

**Comment by jobobby04** [comment]
Probably fixed for the next build
