### ISSUE TITLE
App closing while reading

### ISSUE THREAD

**Issue by ZeroOVi** [jobobby04/TachiyomiSY#829]
### Steps to reproduce

1. Open the app
2. Reading a downloaded manga chapter (.cbz)
3. When reading chapter the app closes and open again

### Expected behavior

Read the chapter whitout closing (crashing)

### Actual behavior

While i am reading the downloaded manga chapter (.cbz) the app closes (crashing) and open again

### Crash logs

--------- beginning of crash
03-19 17:46:22.958 32425   439 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 439 (AsyncTask #5)
03-19 18:02:44.448   540  4438 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 4438 (AsyncTask #35)
03-19 18:03:36.581  5090  5326 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 5326 (AsyncTask #2)
03-19 18:43:50.274  5454 14819 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 14819 (AsyncTask #43)
03-19 18:45:33.351 15582 15889 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 15889 (AsyncTask #3)
03-19 20:27:35.637  7584  8131 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 8131 (AsyncTask #4)
03-19 21:09:18.533  8873 14927 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 14927 (AsyncTask #7)
03-19 21:11:27.721 15452 16000 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 16000 (AsyncTask #3)
03-19 21:13:47.996 17365 17550 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 17550 (AsyncTask #3)
03-19 22:55:02.767 30770 30984 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 30984 (AsyncTask #2)
03-19 22:55:13.046 31271 31415 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 31415 (AsyncTask #2)
03-19 22:55:29.610 31448 31628 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 31628 (AsyncTask #2)
03-19 23:03:12.593 32139   525 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 525 (AsyncTask #7)
03-19 23:09:47.245  1158  2025 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 2025 (AsyncTask #2)
App version: 1.9.0 (standard, d24a8d2, 46, 2023-02-04T23:26Z)
Preview build: 0
Android version: 7.0 (SDK 24)
Android build ID: AGS-L03C331B286
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWAGS-Q
Device model: AGS-L03
Device product name: AGS

### Tachiyomi version

1.9.0

### Android version

Android 7

### Device

Huawei mediapad t310

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I think this is a device issue, the crash logs are also not showing anything useful
