### ISSUE TITLE
Global update no longer reports errors and no longer combines notifications

### ISSUE THREAD

**Issue by DatHypnoboi** [jobobby04/TachiyomiSY#832]
### Steps to reproduce

Run a global update

### Expected behavior

Previously, a notification would appear after a global update with a list of series which were unable to update properly, and the new chapter notifications would automatically collapse into a single notification which could be easily viewed and dismissed.

### Actual behavior

The error notification no longer appears in the newest preview build, and the new chapter notifications seem to no longer be able to combine, forcing you to dismiss them one at a time

### Tachiyomi version

1.9.0 Preview r504

### Android version

Android 12

### Device

Google Pixel 3a XL

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by semiya5** [comment]
Is also happening for "Dump Crash Logs"

**Comment by jobobby04** [comment]
Was a main Tachi bug
