### ISSUE TITLE
Tappytoon WebView Broken

### ISSUE THREAD

**Issue by Kuro6804** [jobobby04/TachiyomiSY#835]
### Steps to reproduce

1. Open any Tappytoon comic in WebView.

### Expected behavior

Loads web page.

### Actual behavior

Space where the webpage should be is just completely blank.

### Tachiyomi version

r504

### Android version

Android 10

### Device

Galaxy Note9

### Other details

Tried it on mainline 0.14.5 and it worked just fine there, which is why I assume this is an SY not an extension issue.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Maybe fixed in the next dev build since it works fine in my tests
