### ISSUE TITLE
Feed reloads after opening series

### ISSUE THREAD

**Issue by DatHypnoboi** [jobobby04/TachiyomiSY#836]
### Steps to reproduce

1. Open a series from the feed tab
2. Go back to the feed tab

### Expected behavior

The feed tab should still show the series from the sources in the feed, just like when browsing from within a source.

### Actual behavior

The feed immediately reloads after going back. This makes doing anything with the feed absolutely insufferable, making you wait for every source in the feed to load every single time you open any of the series listed

### Tachiyomi version

1.9.0 r504

### Android version

Android 12

### Device

Google Pixel 3a XL

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed for the next build 👍
