### ISSUE TITLE
Password protected Downloads 

### ISSUE THREAD

**Issue by Shamicen** [jobobby04/TachiyomiSY#840]
### Describe your suggested feature

Hello,
I just wanted to ask if there would be any interest in adding support for Encrypted CBZ archives to this fork? I already made a proof off concept half a year ago here: https://github.com/tachiyomiorg/tachiyomi/pull/8065
But was told It does not fit main Tachiyomi.  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Sure, just make sure that any code that is SY specific is sorrounded by `// SY -->`  `// SY <--`
