### ISSUE TITLE
MangaDex series don't open

### ISSUE THREAD

**Issue by semiya5** [jobobby04/TachiyomiSY#841]
### Steps to reproduce

Set TachiSY as default opening for Dex links
Try to open a Dex link

### Expected behavior

Should display series

### Actual behavior

![IMG_20230404_114906](https://user-images.githubusercontent.com/1321906/229847558-3d680334-46d7-45a0-b911-9c18984639d1.jpg)

### Tachiyomi version

Preview 504

### Android version

Android 12

### Device

RedMagic 7

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Works fine on my end, make sure you have mangadex enabled and have not disabled 18+ in the app settings.

**Comment by semiya5** [comment]
I have figured it out. Having delegated sources off and choosing SY causes this error
