### ISSUE TITLE
Auto backup not working since r504

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#842]
### Steps to reproduce

1. Turn on auto backup (12 hour interval)

### Expected behavior

should work as intended. Last worked over 15 days ago (I assume the day app got updated)

### Actual behavior

doesn't work

### Tachiyomi version

r504

### Android version

Android 13

### Device

S21 ultra

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Main tachi bug thats fixed in the next build
