### ISSUE TITLE
Sorting by "Last Read" not working as it should

### ISSUE THREAD

**Issue by ShiroeHikari** [jobobby04/TachiyomiSY#843]
### Steps to reproduce

1. Read one chapter of a series
2. close and reopen the app

_not consistent but its the only thing I found to replicate it intentionally_ 

### Expected behavior

The read series should be on top of the list

### Actual behavior

The read series mostly goes to the bottom of the list when where it shouldnt be normally

### Tachiyomi version

Stable 1.9.0

### Android version

Android 11

### Device

Redmi K20 Pro

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Last read works for me
