### ISSUE TITLE
Bring back starting screen

### ISSUE THREAD

**Issue by HyperFate** [jobobby04/TachiyomiSY#845]
### Steps to reproduce

Starting screen option that was removed in the version 1.9.0

### Expected behavior

bring back starting screen option in "General tab"

### Actual behavior

Starting screen was removed in v1.9.0

### Tachiyomi version

1.9.0

### Android version

Android 13

### Device

Realme Android

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
This was removed by main tachiyomi app, Sy cant bring it back until they do
