### ISSUE TITLE
Migration feature is not working correctly

### ISSUE THREAD

**Issue by Pheonix-Flames** [jobobby04/TachiyomiSY#847]
### Steps to reproduce

1. Select Manga to migrate
2. Selected source
3. After it is done searching the Manga confirm migration

### Expected behavior

It should immediately migrate the selected Manga

### Actual behavior

Instead of immediately migrating the selected Manga it takes 10 to 20 seconds to migrate the Manga and if I select multiple mangas it will take more time

### Tachiyomi version

1.9.0

### Android version

Android 11

### Device

Realme 3 pro

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Should be improved for the next build
