### ISSUE TITLE
E-he*tai extension suddenly missing in just TachiyomiSY

### ISSUE THREAD

**Issue by therealsbeve** [jobobby04/TachiyomiSY#848]
### Steps to reproduce

Opened the app yesterday, and the extension was still there. Upon opening it today, it has disappeared, and does not appear in the extensions list at all. Downloaded TachiJ2K and the extension was available to download in that.

### Expected behavior

The extension should show up.

### Actual behavior

The extension is missing. Also, any saved posts from the extension can still be opened in the library but the extension itself is missing.

### Tachiyomi version

1.9.0

### Android version

Android 11

### Device

Samsung Galaxy S20 FE

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
Ehentwi is preinstalled so the extension doesn't show up. Enable it from filters in browse

**Comment by jobobby04** [comment]
Try force closing SY and re-opening
