### ISSUE TITLE
Error message even when image successfully loads

### ISSUE THREAD

**Issue by DatHypnoboi** [jobobby04/TachiyomiSY#850]
### Steps to reproduce

1. Open chapter in webtoon reading mode

### Expected behavior

Chapter should load image normally or give error message

### Actual behavior

Image will sometimes load correctly but still have error message overlaid

### Tachiyomi version

1.9.0 Preview r505

### Android version

Android 12

### Device

Google Pixel 3a XL

### Other details

Thought it was gone but it happened again :/
Encountered a few days ago on latest preview release
![Screenshot_20230410-215249](https://user-images.githubusercontent.com/25212257/231902906-63ca9259-30b8-424d-bd53-416cab8e9acc.png)

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DatHypnoboi** [comment]
It seems to mostly happen when returning to the reader from another app and rotating the screen orientation

**Comment by jobobby04** [comment]
This is a main Tachi issue, I think its some kind of data race
