### ISSUE TITLE
Exhentai tag filter not working

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#852]
### Steps to reproduce

1. open exhentai 
2. filter tags like milf, English

### Expected behavior

filtering works

### Actual behavior

Whatever appears doesn't match the tags from input the 

### Tachiyomi version

r505

### Android version

Android 13

### Device

galaxy s21 

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Works fine for me

**Comment by jferdous70** [comment]
Here's a recording. I put Milf and english. As you can see, nothing happened with the filter.

https://user-images.githubusercontent.com/83420659/232351253-15aeeb4f-03d1-4cae-9bb8-00bfbe8ea326.mp4

**Comment by jobobby04** [comment]
You didn't submit the tags before searching, you have to press send for each tag at the bottom right of the keyboard

**Comment by jferdous70** [comment]
I see, thanks for the clarification

**Comment by jferdous70** [comment]
It says no results found after I pressed send 

![Screenshot_20230416_210748_TachiyomiSY](https://user-images.githubusercontent.com/83420659/232355572-368ac9c4-e282-4132-a73a-ae3971fd34df.jpg)

**Comment by jobobby04** [comment]
Make sure to send the tags separately

**Comment by jferdous70** [comment]
Perfect, it works now. I suppose the lack of autofill confused me
