### ISSUE TITLE
Add Drag and Drop back in the library

### ISSUE THREAD

**Issue by Rings4** [jobobby04/TachiyomiSY#854]
### Describe your suggested feature

I use drag and drop to sort my comics in the order I want them in. I am currently on 1.8.4 on my phone but noticed that the current version it's asking me to update to has removed that feature. 

That is preventing me from updating. I want to install this on other devices as well. My tablets have 1.9.0 and the feature is removed. 

Why was the feature removed? Can it be added back? None of the sorting methods satisfy my preferences.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
The feature was removed because it is not compatible with the rewrite of the app that happened in 1.9.0. It cannot be added back for now and probably won't be re-added in the future since it wasnt used by most users.

**Comment by Rings4** [comment]
> The feature was removed because it is not compatible with the rewrite of the app that happened in 1.9.0. It cannot be added back for now and probably won't be re-added in the future since it wasnt used by most users.

That's unfortunate. It seems like I can never update this app again, then.

Can you tell me which version was the last version to have drag and drop? I'd like to be on the latest version I can.

**Comment by jobobby04** [comment]
Any versions before 1.9.0 when the rewrite happened does not have support for the latest extensions. Even if you use an old version, you won't be able to install or update your sources, which means any sources that break will not be fixed.

**Comment by Rings4** [comment]
> Any versions before 1.9.0 when the rewrite happened does not have support for the latest extensions. Even if you use an old version, you won't be able to install or update your sources, which means any sources that break will not be fixed.

I see. In that case, I implore you to please add this to the list of features to add back, as I frankly find it difficult to believe not many people use drag and drop. I only have 3 series in my library and I struggled to order them the way I want without drag and drop. I'm sure when I add more series it will be absolutely impossible to sort them the way I want, and I'm sure other people have a lot more series than I do. 

What was the reason for the rewrite? 

The app is uncomfortable for someone like me who wants their comics sorted in a certain way that does not conform with any of the criteria offered to us. I sort my comics in the order that I read them years ago. When I add such a series to my library, I need to be able to drag it where it should go. This is a very important feature that while I understand had to be removed for the rewrite, I don't understand why it will not come back. Even if it's not at the top of the priority list, it's still an important feature that needs to come back at least this year. I feel this issue should remain open so hopefully one day relatively soon the feature will be brought back.
