### ISSUE TITLE
ExHentai cover images not loading

### ISSUE THREAD

**Issue by audi4444player** [jobobby04/TachiyomiSY#855]
### Steps to reproduce

Open exhentai source
Select latest/browse or search anything

### Expected behavior

Shows cover images in results page. 

### Actual behavior

Shows missing image type icon. 

### Tachiyomi version

Preview r505

### Android version

Android 7.1

### Device

Xperia Z4 tablet

### Other details

https://photos.app.goo.gl/sAFmBkWTScmcTh4J9
Screenshots showing covers loading correctly when in the main source page but not in the results list

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Try re-logging and changing a setting like show japanese title on and off in E-Hentai settings

**Comment by audi4444player** [comment]
turning everything off and on again in the settings and relogging has fixed the issue,, thank  you.
