### ISSUE TITLE
Local source doesn't load 

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#857]
### Steps to reproduce

1. open browse screen
2. Tap local source 

### Expected behavior

my local manga should appear instantly 

### Actual behavior

it's stuck in a loading screen, as if it's trying to load a regular source 

https://user-images.githubusercontent.com/83420659/232356279-02720cb5-6c4d-4b5e-84d0-8e1e939e2fbc.mp4

### Tachiyomi version

r506

### Android version

android 13

### Device

galaxy s21 ultra 

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
SY doesn't really do anything to Local source, are you sure it's a SY specific issue?

**Comment by jferdous70** [comment]
Yep it's only on Sy. I put local folder in main preview and it worked normally. Sy local also used to work not too long ago.

**Comment by jobobby04** [comment]
Can you dump crash logs or get the logs from the logs folder and upload them?

**Comment by jferdous70** [comment]
Sure 

 --------- beginning of main 
04-16 22:11:54.977 25495 26589 E DatabaseUtils: Writing exception to parcel 
04-16 22:11:54.977 25495 26589 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=25576, uid=1000 requires the provider be exported, or grantUriPermission() 
04-16 22:11:54.977 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:918) 
04-16 22:11:54.977 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:836) 
04-16 22:11:54.977 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:712) 04-16 22:11:54.977 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:251) 
04-16 22:11:54.977 25495 26589 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107) 
04-16 22:11:54.977 25495 26589 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1316) 
04-16 22:11:54.977 25495 26589 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1280) 
04-16 22:11:54.978 25495 26589 E DatabaseUtils: Writing exception to parcel 
04-16 22:11:54.978 25495 26589 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=25576, uid=1000 requires the provider be exported, or grantUriPermission() 
04-16 22:11:54.978 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:918) 
04-16 22:11:54.978 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:836) 
04-16 22:11:54.978 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:712) 04-16 22:11:54.978 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:251) 
04-16 22:11:54.978 25495 26589 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107) 
04-16 22:11:54.978 25495 26589 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1316) 
04-16 22:11:54.978 25495 26589 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1280) 
04-16 22:19:07.339 25495 25881 E DatabaseUtils: Writing exception to parcel 
04-16 22:19:07.339 25495 25881 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=25576, uid=1000 requires the provider be exported, or grantUriPermission() 
04-16 22:19:07.339 25495 25881 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:918) 
04-16 22:19:07.339 25495 25881 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:836) 
04-16 22:19:07.339 25495 25881 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:712) 04-16 22:19:07.339 25495 25881 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:251) 
04-16 22:19:07.339 25495 25881 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107) 
04-16 22:19:07.339 25495 25881 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1316) 
04-16 22:19:07.339 25495 25881 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1280) 04-16 22:19:07.339 25495 26589 E DatabaseUtils: Writing exception to parcel 
04-16 22:19:07.339 25495 26589 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=25576, uid=1000 requires the provider be exported, or grantUriPermission() 
04-16 22:19:07.339 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:918) 
04-16 22:19:07.339 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:836) 
04-16 22:19:07.339 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:712) 04-16 22:19:07.339 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:251) 
04-16 22:19:07.339 25495 26589 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107) 
04-16 22:19:07.339 25495 26589 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1316) 
04-16 22:19:07.339 25495 26589 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1280) 
04-16 22:19:57.538 25495 26589 E DatabaseUtils: Writing exception to parcel 
04-16 22:19:57.538 25495 26589 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=25576, uid=1000 requires the provider be exported, or grantUriPermission() 
04-16 22:19:57.538 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:918) 
04-16 22:19:57.538 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:836) 
04-16 22:19:57.538 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:712) 04-16 22:19:57.538 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:251) 
04-16 22:19:57.538 25495 26589 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107) 
04-16 22:19:57.538 25495 26589 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1316) 
04-16 22:19:57.538 25495 26589 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1280) 04-16 22:19:57.539 25495 25510 E DatabaseUtils: Writing exception to parcel 
04-16 22:19:57.539 25495 25510 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=25576, uid=1000 requires the provider be exported, or grantUriPermission() 
04-16 22:19:57.539 25495 25510 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:918) 
04-16 22:19:57.539 25495 25510 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:836) 
04-16 22:19:57.539 25495 25510 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:712) 04-16 22:19:57.539 25495 25510 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:251) 04-16 22:19:57.539 25495 25510 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107) 
04-16 22:19:57.539 25495 25510 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1316) 
04-16 22:19:57.539 25495 25510 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1280) 04-16 22:20:49.503 25495 25881 E DatabaseUtils: Writing exception to parcel 
04-16 22:20:49.503 25495 25881 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=25576, uid=1000 requires the provider be exported, or grantUriPermission() 
04-16 22:20:49.503 25495 25881 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:918) 
04-16 22:20:49.503 25495 25881 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:836) 
04-16 22:20:49.503 25495 25881 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:712) 04-16 22:20:49.503 25495 25881 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:251) 
04-16 22:20:49.503 25495 25881 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107) 
04-16 22:20:49.503 25495 25881 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1316) 
04-16 22:20:49.503 25495 25881 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1280) 
04-16 22:20:49.504 25495 26589 E DatabaseUtils: Writing exception to parcel 
04-16 22:20:49.504 25495 26589 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=25576, uid=1000 requires the provider be exported, or grantUriPermission() 
04-16 22:20:49.504 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:918) 
04-16 22:20:49.504 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:836) 
04-16 22:20:49.504 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:712) 04-16 22:20:49.504 25495 26589 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:251) 
04-16 22:20:49.504 25495 26589 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107) 
04-16 22:20:49.504 25495 26589 E DatabaseUtils:      at android.os.Binder.execTransactInternal(Binder.java:1316) 
04-16 22:20:49.504 25495 26589 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1280) 
App version: 1.9.1 (standard, 64cdf0d15, 50, 2023-04-16T21:46Z) 
Preview build: 506 
Android version: 13 (SDK 33)  
Device brand: samsung 
Device manufacturer: samsung 
Device name: p3q 
Device model: SM-G998
Device product name: p3qcsx

**Comment by jferdous70** [comment]
New log from today for local manga, not sure if it has anything new

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/11299954/tachiyomi_crash_logs.txt)

**Comment by jobobby04** [comment]
It works fine for me, try clearing the database.
