### ISSUE TITLE
Trying to edit manga info crashes app

### ISSUE THREAD

**Issue by lewdpatriot** [jobobby04/TachiyomiSY#858]
### Steps to reproduce

NA

### Expected behavior

NA

### Actual behavior

NA

### Crash logs

--------- beginning of system
--------- beginning of main
04-17 22:01:47.349 16922 16922 E Parcel  : Reading a NULL string not supported here.
04-17 22:01:47.367 16922 16922 E Parcel  : Reading a NULL string not supported here.
04-17 22:01:48.280 16922 16972 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:01:48.285 16922 16972 E EGL-gift: Cannot load register apis
04-17 22:01:48.290 16922 16972 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:01:48.295 16922 16972 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:01:48.418 16922 16972 E ion     : ioctl c0044901 failed with code -1: Invalid argument
04-17 22:01:52.415 16922 16922 E Parcel  : Reading a NULL string not supported here.
04-17 22:01:52.488 17170 17170 E de.tachiyomi.s: Unknown bits set in runtime_flags: 0x40000000
04-17 22:01:52.492 17170 17170 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
04-17 22:01:52.497 17170 17170 E RefClass: java.lang.reflect.InvocationTargetException
04-17 22:01:52.558 17170 17193 E Parcel  : Reading a NULL string not supported here.
04-17 22:01:52.574 17170 17193 E Parcel  : Reading a NULL string not supported here.
04-17 22:01:52.607 17170 17202 E Parcel  : Reading a NULL string not supported here.
04-17 22:01:52.936 17170 17219 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:01:52.936 17170 17215 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
04-17 22:01:53.067 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:01:53.068 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:01:53.122 17170 17170 E Parcel  : Reading a NULL string not supported here.
04-17 22:01:53.139 17170 17170 E Parcel  : Reading a NULL string not supported here.
04-17 22:01:53.616 17170 17217 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:01:53.621 17170 17217 E EGL-gift: Cannot load register apis
04-17 22:01:53.628 17170 17217 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:01:53.633 17170 17217 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:01:53.929 17170 17353 E SQLiteLog: (284) automatic index on C(manga_id)
04-17 22:01:53.929 17170 17353 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-17 22:01:54.094 17170 17363 E Parcel  : Reading a NULL string not supported here.
04-17 22:01:54.115 17170 17170 E Parcel  : Reading a NULL string not supported here.
04-17 22:01:54.450 17170 17353 E SQLiteLog: (284) automatic index on C(manga_id)
04-17 22:01:54.450 17170 17353 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-17 22:01:54.450 17170 17353 E SQLiteLog: (284) automatic index on merged(manga_id)
04-17 22:01:54.450 17170 17353 E SQLiteLog: (284) automatic index on ME(merge_id)
04-17 22:01:54.450 17170 17353 E SQLiteLog: (284) automatic index on C(merge_id)
04-17 22:01:54.450 17170 17353 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-17 22:01:55.314 17170 17346 E ion     : ioctl c0044901 failed with code -1: Invalid argument
04-17 22:01:55.339 17170 17346 E libc    : Access denied finding property "vendor.debug.drm.logv"
04-17 22:01:55.339 17170 17346 E libc    : Access denied finding property "vendor.debug.drm.logv"
04-17 22:01:55.340 17170 17346 E libc    : Access denied finding property "vendor.debug.drm.logd"
04-17 22:01:55.340 17170 17346 E libc    : Access denied finding property "vendor.debug.drm.logv"
04-17 22:01:55.385 17170 17342 E ion     : ioctl c0044901 failed with code -1: Invalid argument
04-17 22:01:55.386 17170 17374 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:00.924 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:00.925 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:01.800 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:01.800 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:01.801 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:01.801 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:01.849 17170 17170 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
04-17 22:02:04.671 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:04.672 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:04.726 17170 17170 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-17 22:02:04.726 17170 17170 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-17 22:02:04.762 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:04.763 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:05.805 17170 17170 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-17 22:02:05.805 17170 17170 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-17 22:02:07.243 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:07.244 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:07.271 17170 17170 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-17 22:02:07.271 17170 17170 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-17 22:02:07.456 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:07.457 17170 17170 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:09.289 17170 17170 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-17 22:02:09.289 17170 17170 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-17 22:02:09.297 17170 17170 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-17 22:02:09.297 17170 17170 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-17 22:02:09.954 17170 17170 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-17 22:02:09.964 17170 17170 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: kotlinx.serialization.SerializationException: Serializer for class 'MangaList' is not found.
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: Mark the class as @Serializable or provide the serializer explicitly.
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:31)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(Platform.kt:6)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:3)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at kotlinx.serialization.SerializersKt.serializer(Unknown Source:7)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at tachiyomi.data.manga.CustomMangaRepositoryImpl.set(CustomMangaRepositoryImpl.kt:142)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.manga.MangaScreen$Content$65.invoke(MangaScreen.kt:392)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.manga.EditMangaDialogKt$EditMangaDialog$1$1$1.invoke(EditMangaDialog.kt:144)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(Clickable.kt:17)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:153)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:82)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:96)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:35)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:37)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:8)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:67)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:21)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(BackwardsCompatNode.kt:26)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:91)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:77)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:77)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:49)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:164)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:78)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:227)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:88)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:575)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1889)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.app.Dialog.dispatchTouchEvent(Dialog.java:880)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:525)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.View.dispatchPointerEvent(View.java:14786)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6760)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6526)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5951)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6015)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5974)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6160)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5982)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6217)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5955)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6015)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5974)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5982)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5955)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8958)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8909)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8860)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9101)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.os.MessageQueue.next(MessageQueue.java:339)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.os.Looper.loop(Looper.java:199)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:8212)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
04-17 22:02:12.303 17170 17170 E GlobalExceptionHandler: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@2bd09e1, androidx.compose.runtime.BroadcastFrameClock@885f306, StandaloneCoroutine{Cancelling}@db87dc7, AndroidUiDispatcher@cca5ff4]
04-17 22:02:12.312 17170 17170 E Parcel  : Reading a NULL string not supported here.
04-17 22:02:12.419 16922 17420 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:12.456 16922 16922 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 22:02:12.457 16922 16922 E libEGL  : Invalid file path for libcolorx-loader.so
App version: 1.9.1 (standard, caee974, 48, 2023-04-16T21:39Z)
Preview build: 0
Android version: 11 (SDK 30)
Android build ID: RMX2002_11_C.19
Device brand: realme
Device manufacturer: realme
Device name: RMX2002L1
Device model: RMX2002
Device product name: RMX2002

### Tachiyomi version

1.9.1

### Android version

Android 11

### Device

RMX2002

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
There will be a hotfix update later today

**Comment by jobobby04** [comment]
Fixed in the latest release 👍
