### ISSUE TITLE
[Feature Request] Search in database cache first

### ISSUE THREAD

**Issue by ghost** [jobobby04/TachiyomiSY#86]
## Why/User Benefit/User Problem
Sometimes searching some sources is super slow or unreliable. For example Hitomi.la search is super slow and sometimes unreliable and show false results. 
## What/Requirements
TachiyomiSy will first search for manga in database cache then search in online.
And also add a option to bulk load the mangas of a source in database in background. this will be used for sources that have slow search.
or create a list of manga with only manga names and urls and use it to speed up search.
it can be added only for Hitomi.la if adding for all sources is not possible. because Hitomi. la search is very buggy. 
i need to manually change all capital letters into small letters and remove all special characters if i want to search in Hitomi.la or else the result shows null. but even then sometimes searching in Hitomi.la force closes tachiyomiSy. same goes for migrations. 
sorry for bad english.

**Comment by joseph619** [comment]
You can use better sources like Exhentai instead, Hitomi has s always been very buggy

**Comment by joseph619** [comment]
Can possibly be cherry picked from this Neko commit I suppose?

https://github.com/CarlosEsco/Neko/commit/c2ac095a6a32cf248d6748ff0b1b347b31294b3b

**Comment by jobobby04** [comment]
Thought about it, but its not worth the word to find out if the source has changed the search results
