### ISSUE TITLE
Crash when trying to add tag

### ISSUE THREAD

**Issue by srcamarda** [jobobby04/TachiyomiSY#860]
### Steps to reproduce

1. Open manga
2. Select Edit Info
3. Select Add Tag
4. Write tag name and select OK
5. Select Save (Crash happens here)

### Expected behavior

The tag should be addeded.

### Actual behavior

The app crashes ("Whoops!" screen).

### Crash logs

[2023-04-18-release.log](https://github.com/jobobby04/TachiyomiSY/files/11264433/2023-04-18-release.log)

### Tachiyomi version

1.9.2

### Android version

Android 13

### Device

Samsung Galaxy S20 FE

### Other details

Worked on 1.9.1

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This was fixed in 1.9.2, update your 1.9.1 version of SY
