### ISSUE TITLE
Having a merged entries and a normal entries will show updates for both but will point to the same source.

### ISSUE THREAD

**Issue by Raizanad** [jobobby04/TachiyomiSY#863]
### Steps to reproduce

Make a merged entry (mangadex + mangasee in my case).
Don't remove the mangadex entry from your library for the manga after doing it.
Wait until manga chapters are updated (let's say the manga is jajuja).
Jajuja chapter 5 will be duplicated in the update tab, both will be clickable and deleting or downloading one will delete the other.

### Expected behavior

Show only the entry you have in the "library" auto update and/or auto download only in the update tab. In my case the mangadex entry is in category that is not included in the updates/downloads.

### Actual behavior

Jajuja chapter 5 will be duplicated in the update tab, both will be clickable and deleting or downloading one will delete the other wasting screen space and making weird interactions with selections.

### Tachiyomi version

1.9.2

### Android version

Android 10

### Device

Xiaomi Mi 8

### Other details

Haven't tested on 1.9.3 but this isn't in the changelog for this version.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Updates shows everything that has recent chapters, no matter the auto-update state of the category. This is expected behavior

**Comment by Raizanad** [comment]
> Updates shows everything that has recent chapters, no matter the auto-update state of the category. This is expected behavior

Even if the library source (mangadex in a non "included" category) wasn't updated by the user or the system, but the merged entry instead? If it is, I have no problem about it... Just reporting it! Thank you for your answer.
