### ISSUE TITLE
Bring back the possibility of double/triple clicking to manually write the score or chapter in the trackers.

### ISSUE THREAD

**Issue by Raizanad** [jobobby04/TachiyomiSY#864]
### Describe your suggested feature

Some versions ago you could double/triple/long tab to force the numeric keyboard to show up and type the chapter you are reading or score instead of using the wheel. For some trackers like mangaupdates which have a really long scoring system and is fairly new without import options, it would make it easier to rate manga or update the chapter you are reading when the publication for the manga is slow.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Raizanad** [comment]
By the way, it was added back to Tachiyomi main I believe but not to this fork.
https://github.com/tachiyomiorg/tachiyomi/pull/9338

**Comment by jobobby04** [comment]
Your likely on stable, it's avaliable in the preview
