### ISSUE TITLE
Luscious and Kemono crash on Tachiyomi SY 

### ISSUE THREAD

**Issue by Gerardalbert21** [jobobby04/TachiyomiSY#869]
### Steps to reproduce

1. Choose one entry on the extension Luscious
2. Disable the transitions between chapter
3. Choose a chapter and read multiple chapter
4. Tachiyomi SY crash

### Expected behavior

I can view all chapter without tachiyomi sy crashing

### Actual behavior

Tachiyomi SY crash after a few chapter 

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/11287585/tachiyomi_crash_logs.txt)

### Tachiyomi version

1.9.3 Preview 508

### Android version

Android 13

### Device

Poco X3 pro

### Other details

Only on SY

https://user-images.githubusercontent.com/88115070/233408987-2ac43113-bf7d-4c52-b429-a5655eccc893.mp4

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Gerardalbert21** [comment]
Also on kemono party

**Comment by jobobby04** [comment]
Should be fixed in the next build
