### ISSUE TITLE
Unique Passcode

### ISSUE THREAD

**Issue by Useless-Panda** [jobobby04/TachiyomiSY#870]
### Describe your suggested feature

The `Require Unlock` option currently uses the lock screen password; it would be great to be able to use a custom pin for TachiyomiSY. TachiyomiAZ already has this feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I specifically removed the AZ passcode feature since its outdated and I don't want 2 different implemnentations of unlocking. SY uses the main Tachi implementation now since its based on the latest Tachi, instead of an old version like AZ.

**Comment by Useless-Panda** [comment]
:(
