### ISSUE TITLE
[Bugs] sort: not working when have ≥12 saved searches

### ISSUE THREAD

**Issue by l2eused** [jobobby04/TachiyomiSY#871]
### Steps to reproduce

1. when have 11 saved searches all work fine
2. add new saved searches
3. for now, it has 12 saved
4. search normal (doesn't use saved searches) and select sort by time (i.e today)

### Expected behavior

search results has show items in sort:_you select this_ (i.e today) and **Sort By:** button should show as **Popular:Today**)

### Actual behavior

search results has show items in sort:all time (**Sort By:** button will reset to **Popular:All Time**)

### Tachiyomi version

1.9.3

### Android version

Android 10

### Device

Xiaomi Mi9 (MIUI 12.0)

### Other details

I tested by clear all data and import my backup (no touch other settings)

tested with only Nhentai extension.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Can you show a video of this happening, I can't see any reason why this would happen normally
