### ISSUE TITLE
Restoring Backup Misplaces Custom Tags

### ISSUE THREAD

**Issue by nopeha** [jobobby04/TachiyomiSY#872]
### Steps to reproduce

1. Create and Restore Backup from one Library (first device) in a second Library (empty Library/second device)
2. Check the tags of some entries in the second Library.
3. In the second Library, custom tags on some entries they shouldn't be on, appearing to be mixed up with others. They do not mirror the tags on the entry in the original device/library.

Example:
Phone (original library/device one)
![Screenshot_20230424-195823_TachiyomiSY](https://user-images.githubusercontent.com/101480834/234173160-69512424-4c00-4de8-86d3-637aa1e2bb15.jpg)

Tablet (library populated by backup)
![image0](https://user-images.githubusercontent.com/101480834/234173251-5c9be8cf-3e0b-410e-a494-72177e6f72aa.jpg)

### Expected behavior

The tags should match between the original library and the new library.

### Actual behavior

The tags do not always match. I had this issue appear on more than one backup, and the entries having the issue changed each time.

### Tachiyomi version

1.9.3 (both devices)

### Android version

Android 12 (both devices)

### Device

Samsung Galaxy S10 & Samsung Galaxy Tab 6

### Other details

I believe this to be an issue with the backup file itself. I don't know enough about the coding of the backup, however through testing that seems to be the main constant in the situation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Can you show a screenshot with the edit info dialog open, as well as can you try to reproduce it with the next build?

**Comment by LittleFreak** [comment]
In other forks, they don't get restored from backups at all.
I would've reported it earlier in the respective repo, but I've figured it's best to solve the problem here in this upstream instead.
