### ISSUE TITLE
Continue button

### ISSUE THREAD

**Issue by daniel95000** [jobobby04/TachiyomiSY#873]
### Steps to reproduce

1. Getting into the manga
2. Add to library
3.  There is no add button because there is already a manga with the same name

![Screenshot_20230425_075627_TachiyomiSY](https://user-images.githubusercontent.com/29511904/234271301-ece4a1b6-2c5a-4781-938f-f33b655229c3.jpg)

### Expected behavior

I think there should be a button to add the manga even though it has the same name as another manga. 

### Actual behavior

Well, I remember ever using the button to add them even though they had the same name

### Tachiyomi version

1.9.3

### Android version

Android 13

### Device

Samsung A71

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a main Tacvhi issue, if its still happening in the next build, open a issue in the main Tachi repo
