### ISSUE TITLE
[Feature Request] Chapter image preview 

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#88]
Show image preview of all pages in a chapter once they're loaded. Tap on a button on reader sheet to access it.

Similar to what Manga Rock  did. Screenshot below

![PicsArt_09-16-04 07 26](https://user-images.githubusercontent.com/34897862/93393012-bc0fc680-f83f-11ea-8191-873756bbf5dc.jpg)

**Comment by joseph619** [comment]
@jobobby04 Are you potentially interested in doing this in future? If not i can close it

**Comment by jobobby04** [comment]
I want it, but its not priority

**Comment by joseph619** [comment]
This might be relevant to yoink from

https://github.com/nv95/Kotatsu/tree/devel/app/src/main/java/org/koitharu/kotatsu/reader/ui/thumbnails
