### ISSUE TITLE
Mangadex chapter loading crash

### ISSUE THREAD

**Issue by JaitinPrakash** [jobobby04/TachiyomiSY#884]
### Steps to reproduce

1. open latest preview build 517
2. open mangadex manga
3. move from the end of one chapter to the next.

### Expected behavior

app loads next chapter and continues reading

### Actual behavior

app crashes

### Crash logs

[tachiyomi_crash_logs.txt.gz](https://github.com/jobobby04/TachiyomiSY/files/11469305/tachiyomi_crash_logs.txt.gz)

### Tachiyomi version

App version: 1.9.3 preview build 517

### Android version

Android 13

### Device

Samsung Note 20 Ultra 5G

### Other details

App version: 1.9.3 (standard, 912d2ecd6, 54, 2023-05-13T04:09Z)
Preview build: 517
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.N986USQU4HWD1
Device brand: samsung
Device manufacturer: samsung
Device name: c2q
Device model: SM-N986U
Device product name: c2qsqw

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
One of the images is likely corrupted, can't do anything about that.
