### ISSUE TITLE
[Feature Request] Pls consider also keepin prev/next buttons

### ISSUE THREAD

**Issue by cavemanversace** [jobobby04/TachiyomiSY#89]
## Why/User Benefit/User Problem
the new botton sheet takes more clicks to get to the next chapter. please consider keeping both the prev/next buttons and the bottom sheet. thanks

## What/Requirements
(explain how this feature would behave)

**Comment by joseph619** [comment]
Not possible to keep those buttons since there's no room for them

**Comment by jobobby04** [comment]
I feel having the chapter list is more useful, never really used the prev/next buttons
