### ISSUE TITLE
Feature to copy & share specific chapter URL.

### ISSUE THREAD

**Issue by heartlog** [jobobby04/TachiyomiSY#894]
### Describe your suggested feature

As we know, sometimes we want to share a specific chapter URL with a friend, but even if you select the chapter, the "copy URL" button is not present.

There's a way to copy the URL, but you have to follow these steps: open the chapter, wait for the page to load, and then the web icon shows up. After that, you open that chapter in web view and click the three dots to access the options menu, where you can share the URL. This process requires a lot of extra data just to copy the URL.
If this feature is added it'll a lot easier !

Edit: 
Thers someone already pointed this issue out, but it got restricted on tachiyomi ?
https://github.com/tachiyomiorg/tachiyomi/issues/9510#issue-1709592911
Please, consider adding this feature ..

### Other details

Something like this ?
![like this](https://user-images.githubusercontent.com/133636085/238289647-c2f205a0-d499-41c4-9609-20bfb91b5094.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
You will be able to do that in the reader for the next build

**Comment by heartlog** [comment]
Thanks, 👍
Waiting for next update !!
