### ISSUE TITLE
Can't quit Searching for Extension by back or scroll action

### ISSUE THREAD

**Issue by curche** [jobobby04/TachiyomiSY#895]
### Steps to reproduce

1. Head over to Browse > Extensions
2. Search for an extension (for the recording, I just did xkcd)
3. Try to swipe left/back to switch to Source/Feed/Migrate
4. Try to use back gesture to quit search

### Expected behavior

scroll between the tabs like how Main Preview allows
Exit search by using back swipe gesture

### Actual behavior

Neither work
Video attached

https://cdn.discordapp.com/attachments/566585518171881493/1114357928007311473/Screen_Recording_20230602_195449_TachiyomiSY.mp4

### Crash logs

N/A

### Tachiyomi version

r522

### Android version

12

### Device

Samsung Note10 Lite

### Other details

Cant reproduce it well on main preview so here I am instead

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Just checked main preview and it does the same thing that SY does, open a bug report there lol
