### ISSUE TITLE
About the number of unread chapters on the shelf

### ISSUE THREAD

**Issue by li-hao-dong** [jobobby04/TachiyomiSY#896]
### Describe your suggested feature

Before, I read comics on other platforms. Now, after adding the comics to the shelf of App, the chapter I read before still shows unread and cannot be set as read. Whether this state can add batch set operation that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Remove all you're chapter filters and mark the chapters as read
