### ISSUE TITLE
Changing results display for Exhentai/E-Hentai doesn't actually do anything (on tablet)

### ISSUE THREAD

**Issue by Erebea** [jobobby04/TachiyomiSY#898]
### Steps to reproduce

1. Access TachiyomiSY on a tablet (I have a Samsung A7 10 inch)
2. Go to any results page for Exhentai or E-Hentai
3. Try to change the display between list, compact grid, or comfortable grid

### Expected behavior

This should change the display of results accordingly

### Actual behavior

It does literally nothing

### Tachiyomi version

1.9.3

### Android version

10

### Device

Samsung Galaxy Tab A7 SM-T500

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
The extended view is a separate option in the E-hentai settings
