### ISSUE TITLE
[Feature Request] Use same thumbnails as Library on Global search instead of the cropped square ones

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#9]
Current thumbnails one Global search are square cropped and look awful, not to mention inconsistent with the ones in Library and Browse.

Thus requesting to change Global search thumbnails to that of Library.

**Comment by jobobby04** [comment]
Closed in https://github.com/jobobby04/TachiyomiSY/commit/75bddd5105cd9f9d1d214e97f486215c58f6a138

Its not the exact same, but it should be enough as its similar and respects your settings
