### ISSUE TITLE
[Feature Request] Time-based biometric locking

### ISSUE THREAD

**Issue by RealKC** [jobobby04/TachiyomiSY#90]
(Writing titles is hard, if you feel like you've got a better one, you're free to change it)

## Why/User Benefit/User Problem
Adding this feature would allow having the app locked in environments you don't control(i.e. school), and unlocked in ones you do control(i.e. your home)

## What/Requirements
When "Lock with biometrics" is toggled on, a new setting could be shown that allows the user to specify an hour interval when the biometric lock is enabled. Maybe also allow specifying days when it is enabled?

**Comment by jobobby04** [comment]
Partially added in https://github.com/jobobby04/TachiyomiSY/commit/035fb9e75523cefa981b2503001fd5220f46d9e2
Days are not implemented

**Comment by jobobby04** [comment]
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/8387492a9bfd27426de79bdb8f1e3bcbf9682bf9
