### ISSUE TITLE
Incognito Mode enhanced privacy

### ISSUE THREAD

**Issue by JaitinPrakash** [jobobby04/TachiyomiSY#900]
### Describe your suggested feature

when incognito mode is enabled, it should make keyboards be in incognito mode, and disable screenshots and screensharing.

### Other details

currently incognito mode only stops the history, which is fairly lacking. by enabling other features of the app and application framework, incognito mode can be a truly private setting. these additions could also be toggled in the security and privacy menu.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Incognito mode is a main Tachi feature, I am currently not interested in expanding it, I suggest opening a issue with main Tachi
