### ISSUE TITLE
MangaDex alternative titles in description not working

### ISSUE THREAD

**Issue by Mythos** [jobobby04/TachiyomiSY#903]
### Steps to reproduce

https://github.com/tachiyomiorg/tachiyomi-extensions/pull/16607 has added appending alternative titles to the description of the manga.

### Expected behavior

When the setting is enabled, it should append the alternative titles upon updating the entry.

### Actual behavior

With TachiyomiSY it does not append the alternative titles.
In Tachiyomi it does append the alt titles.

### Tachiyomi version

Preview r552

### Android version

Android 11

### Device

Lenovo Tab P11

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Turhvjbufv** [comment]
It was merged five days ago, and there hasn't been an update for preview for almost a month of course it won't work

**Comment by jobobby04** [comment]
TachiyomiSY contains extra features for mangadex, and one of the things I have to do for that is overwrite the extensions manga info fetcher with a custom one. I need to add support for that setting in SY manually for it to work.
