### ISSUE TITLE
Better handling/Editing/creation of categories

### ISSUE THREAD

**Issue by trgswe** [jobobby04/TachiyomiSY#906]
### Describe your suggested feature

It should be like this...
1) when you type the name of the category it should go to the alphabetical place in your current category list
2) maybe make it tree based where they can look like this

A
A 》AP Comics
A 》Anime
B
B 》Benny Breakiron

Hentai 》Anime-based
Hentai 》Manga-based

### Other details

The current way of handling category is worse than the previous version of category creating editing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
All category things are handled by main Tachi code, I am not going to do any additions in SY unless I feel its a good feature.
