### ISSUE TITLE
All network requests fail

### ISSUE THREAD

**Issue by ItsElectra** [jobobby04/TachiyomiSY#907]
### Steps to reproduce

Open extensions list or try to read a manga

### Expected behavior

Available downloads for extensions appear / manga opens

### Actual behavior

A toast error that says "failed to get extensions list" or "java.net.unknownhostexception"

### Tachiyomi version

1.9.3

### Android version

Android 13

### Device

Samsung Galaxy A53 5G

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Some countries block githubusercontent, join the discord and ask for support to find solutions.
https://discord.gg/tachiyomi
