### ISSUE TITLE
Crash when reading 

### ISSUE THREAD

**Issue by dondeepak** [jobobby04/TachiyomiSY#908]
### Steps to reproduce

When reading manga app is crashing randomly. 
But when i download the chapters before reading there is no crashing

### Expected behavior

Reading without any random crash

### Actual behavior

Crashing randomly when reading

### Crash logs

--------- beginning of main
06-29 08:00:42.820  3942  4141 E DeferredCoroutine: eu.kanade.tachiyomi.network.HttpException: HTTP error 401
06-29 08:00:42.820  3942  4141 E DeferredCoroutine: 	at exh.md.service.MangaDexAuthService.readingStatusForManga(SourceFile:87)
06-29 08:00:42.820  3942  4141 E DeferredCoroutine: 	at exh.md.handlers.FollowsHandler$fetchTrackingInfo$2$followStatusDef$1.invokeSuspend(SourceFile:39)
06-29 08:00:42.820  3942  4141 E DeferredCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
06-29 08:00:42.820  3942  4141 E DeferredCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:113)
06-29 08:00:42.820  3942  4141 E DeferredCoroutine: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
06-29 08:00:42.820  3942  4141 E DeferredCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
06-29 08:00:42.820  3942  4141 E DeferredCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
06-29 08:00:42.820  3942  4141 E DeferredCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
06-29 08:02:14.772  3942  4144 E DeferredCoroutine: eu.kanade.tachiyomi.network.HttpException: HTTP error 401
06-29 08:02:14.772  3942  4144 E DeferredCoroutine: 	at exh.md.service.MangaDexAuthService.readingStatusForManga(SourceFile:87)
06-29 08:02:14.772  3942  4144 E DeferredCoroutine: 	at exh.md.handlers.FollowsHandler$fetchTrackingInfo$2$followStatusDef$1.invokeSuspend(SourceFile:39)
06-29 08:02:14.772  3942  4144 E DeferredCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
06-29 08:02:14.772  3942  4144 E DeferredCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:113)
06-29 08:02:14.772  3942  4144 E DeferredCoroutine: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
06-29 08:02:14.772  3942  4144 E DeferredCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
06-29 08:02:14.772  3942  4144 E DeferredCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
06-29 08:02:14.772  3942  4144 E DeferredCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: java.io.FileNotFoundException: /data/user/0/eu.kanade.tachiyomi.sy/cache/chapter_disk_cache/12005487d9533fe9b073cdb0afd45f51.0: open failed: ENOENT (No such file or directory)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at libcore.io.IoBridge.open(IoBridge.java:574)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.reader.loader.HttpPageLoader$_loadPage$2.invoke(SourceFile:42)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonPageHolder$setImage$2.invokeSuspend(SourceFile:6)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:113)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@51fb7b4, Dispatchers.Main]
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at libcore.io.Linux.open(Native Method)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8176)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	at libcore.io.IoBridge.open(IoBridge.java:560)
06-29 08:02:47.030  3942  3942 E GlobalExceptionHandler: 	... 9 more
06-29 08:02:47.385 10017 10036 E SQLiteLog: (283) recovered 469 frames from WAL file /data/user/0/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-wal
App version: 1.9.3 (standard, b74d5143e, 54, 2023-06-24T22:57Z)
Preview build: 523
Android version: 12 (SDK 31)
Android build ID: SKQ1.211006.001 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: peux
Device model: 2201116SI
Device product name: peux_in

### Tachiyomi version

App version: 1.9.3 (standard, b74d5143e, 54, 2023-06-24T22:57Z) Preview build: 523

### Android version

Android 12

### Device

Redmi note 11 pro plus 5g (india) 

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Should be fixed in the latest builds

**Comment by dondeepak** [comment]
Thank you
