### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by huajideshutiao** [jobobby04/TachiyomiSY#911]
### Steps to reproduce

a:Click on a comic link in another app.
b:Trigger automatic backup. 

### Expected behavior

a:Jump directly to the comic page.
b:The corresponding file can be found.

### Actual behavior

a:The first click prompts that the corresponding page cannot be found (the application is not in the background at this time)
b:Cannot be found in either the custom or default (/storage/emulated/0/TachiyomiSY/) directory, but the log is normal.

### Tachiyomi version

1.9.3

### Android version

Android 13

### Device

k50

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Known main Tachi issue
