### ISSUE TITLE
Browsing an extension takes too long and often times out (not extension issue)

### ISSUE THREAD

**Issue by lewdpatriot** [jobobby04/TachiyomiSY#912]
### Steps to reproduce

Click an extension to browse the titles in it.

### Expected behavior

Initial loading should not take too long (the main tachi or any other fork works properly, so not an issue of the extensions).

### Actual behavior

The loading takes too long (1 minutes+) and often times out.

### Crash logs

It's been happening for quite a long time and I was hoping an update will fix it or someone else would point it out. But it seems I'm the only one having this issue. 🤷

### Tachiyomi version

Preview r524

### Android version

Android 11

### Device

Realme 6 (RMX2002)

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Maybe try clearing the database in advanced settings. I know another user had a similar issue, and re-installing SY and restoring thier backup fixed the issue

**Comment by lewdpatriot** [comment]
Did not work. I'll try another device to see if it persists. And also see which previous built works properly.

**Comment by jobobby04** [comment]
Due to it unlikely to be a SY specific issue I am closing this, if its identified to be an issue in the SY code I will consider this again.
