### ISSUE TITLE
Individual padding value for each series

### ISSUE THREAD

**Issue by Lhn94** [jobobby04/TachiyomiSY#914]
### Describe your suggested feature

Could you add the ability to customize padding for each series? Not that I want to fiddle with the exact padding, like getting 17% instead of 20% that the app provides, but in the sense that Manga A can have 15% padding, Manga B can have 20%. 

I'd to read manga in landscape mode, but each manga is different. Some with more text, and thus requires less padding, so I can read the texts better. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Personally not interested in this, I believe an issue is already open in Main Tachi
