### ISSUE TITLE
Searching locked into pinned sources, especially when clicking manga title

### ISSUE THREAD

**Issue by CrashCat** [jobobby04/TachiyomiSY#915]
### Steps to reproduce

Go to any manga in your library
Open the info view (with chapter list and other info)
Click title of manga

### Expected behavior

In Tachiyomi Preview, the search automatically begins with that title for Pinned sources, but clicking All will interrupt that search and search all sources. You can also switch between Pinned and All sources in any other global search results and the results will update.

### Actual behavior

Search immediately begins with only pinned sources selected. Clicking All does not initiate a new search with All sources. Searching all sources is not possible in this way. In fact in the normal Browse global source search if you accidentally hit search on the keyboard before switching you are locked into whichever choice is set at the top, and switching will also not work. Basically the switch between Pinned and All doesn't work if a search has initiated, and some situations initiate search immediately.

### Tachiyomi version

1.9.3

### Android version

13

### Device

Samsung Galaxy Tab S8

### Other details

Appears it was fixed in Tachiyomi Preview under https://github.com/tachiyomiorg/tachiyomi/issues/9724 

App version: 1.9.3 (standard, 70bbede29, 55, 2023-07-20T02:04Z)
Preview build: 525
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.X700XXU4BWD8
Device brand: samsung
Device manufacturer: samsung
Device name: gts8wifi
Device model: SM-X700
Device product name: gts8wifixx

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Known main Tachi issue
