### ISSUE TITLE
clean up downloaded chapters deletes bookmarked chapters

### ISSUE THREAD

**Issue by Turhvjbufv** [jobobby04/TachiyomiSY#923]
### Steps to reproduce

Download and read a chapter, bookmark that chapter and then go to settings - advanced - scroll to downloader and press on "clean up downloaded chapters" (and select " clean read")

### Expected behavior

Should delete all read downloaded chapters, but not read downloaded *bookmarked* chapters (btw I have "allow deleting bookmarked chapters" disabled)

### Actual behavior

Deletes all read chapters , even bookmarked ones

### Tachiyomi version

r526

### Android version

Android 12 

### Device

s10

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
It is currently broken, so I am closing this for now. I have hidden the setting
