### ISSUE TITLE
Hidden cover buttons

### ISSUE THREAD

**Issue by fellinir** [jobobby04/TachiyomiSY#924]
### Steps to reproduce

1. Open a manga info
2. Tap on the cover
3. See the buttons down below to edit/share the cover

### Expected behavior

Those buttons should be fully visible.

### The buttons are partially hidden. Still clickable, but not very comfortable. (full screen screenshot below)
![Edit_cover_buttons](https://github.com/jobobby04/TachiyomiSY/assets/92597054/0a6ee031-935e-4c37-b6d4-ca45add5361c)

### Tachiyomi version

1.9.3

### Android version

Android 13 LineageOS

### Device

OnePlus 5T

### Other details

I suspect this is due to my lower DPI and bigger font/UI size because it's easier for me to see the phone like this. It's an accessibility option and so this bug should not exists if someone choose to increase UI.
![Display_Size_Settings](https://github.com/jobobby04/TachiyomiSY/assets/92597054/da61a0f3-ef9d-4be7-aa70-5ed1c78a0dcd)

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
The cover dialog features are a Main Tachi thing, check to see if it happens there and open a bug report in the main Tachi repo.
