### ISSUE TITLE
Can't add tags to library manga 

### ISSUE THREAD

**Issue by jferdous70** [jobobby04/TachiyomiSY#926]
### Steps to reproduce

1. Open a library entry
2. Tap edit info and try to add a tag

### Expected behavior

Tag should be visible

### Actual behavior

Tag doesn't show up on manga info. Even after force closing app

### Tachiyomi version

Preview 526

### Android version

Android 13

### Device

Galaxy S21

### Other details

Tag is visible on edit info dialog box, but no on manga screen

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Just tested it and it works fine, you are likely trying to add a tag to a delegated source manga, which is unsupported
