### ISSUE TITLE
crash when scrolling through exh 

### ISSUE THREAD

**Issue by Turhvjbufv** [jobobby04/TachiyomiSY#927]
### Steps to reproduce

Go into exhentai and scroll down a bit fast

### Expected behavior

Should show new manga

### Actual behavior

Crashes

### Crash logs

[tachiyomi_crash_logs (1).txt](https://github.com/jobobby04/TachiyomiSY/files/12330243/tachiyomi_crash_logs.1.txt)

### Tachiyomi version

r527

### Android version

Android 12

### Device

s10

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Should be fixed in the latest build 👍
