### ISSUE TITLE
Enhance Cloudflare Bypass Speed with FlareSolver Integration

### ISSUE THREAD

**Issue by ShivamB25** [jobobby04/TachiyomiSY#929]
### Describe your suggested feature

Tachiyomi has been an exceptional tool for accessing and managing manga content. However, websites protected by Cloudflare often introduce delays due to the anti-bot measures in place. I request an implementation of their
integration of FlareSolver's  into Tachiyomi to significantly fasten the Cloudflare bypass process

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ShivamB25** [comment]
https://github.com/FlareSolverr/FlareSolverr

**Comment by jobobby04** [comment]
Personally not interested in this, I find the current solution good enough

**Comment by ShivamB25** [comment]
@jobobby04 is this possible to use with extensions ? or atleast adding support for them ?
