### ISSUE TITLE
[Feature Request] Allow showing hidden folders in the Local Source

### ISSUE THREAD

**Issue by RealKC** [jobobby04/TachiyomiSY#93]
## Why/User Benefit/User Problem
I'd like for local to include hidden folders (i.e. those whose name starts with a `.`).

## What/Requirements
A toggle under Browse that says "Include hidden folders", by default this would be off to keep existing behaviour.

**Comment by jobobby04** [comment]
Added in #d83f938e0737d52b306fdb746790bf612aad8f82
