### ISSUE TITLE
Keeping the app in background causes it show Source Not Installed and no download buttons

### ISSUE THREAD

**Issue by curche** [jobobby04/TachiyomiSY#931]
### Steps to reproduce

These steps are kinda rough I know but I can't really describe it very well so sorry about that
1. Open a manga
2. keep the app in recents and switch to other apps for atleast an hour or few hours
3. Switch back to the app to land on the same manga page that you left it at

### Expected behavior

the manga page is the same as you left it and you can see the source name and downloaded chapters

### Actual behavior

Source shows up as unrecognized and downloaded chapters arent displayed
![Screenshot_20230816_111419_TachiyomiSY](https://github.com/jobobby04/TachiyomiSY/assets/72807749/7e6d89a8-d0bf-4f7e-9c27-f4896ea3181f)

### Crash logs

N/A

### Tachiyomi version

528

### Android version

13

### Device

Galaxy Note 10 Lite

### Other details

happens more often on sy imo but maybe thats just placebo 🤷 

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DatHypnoboi** [comment]
Likely related, leaving the app on a source and switching back after a while gives a "Source not installed" error message. It seems like sources aren't loaded properly when SY loads into a screen other than the default

**Comment by DatHypnoboi** [comment]
Likely related, leaving the app on a source and switching back after a while gives a "Source not installed" error message. It seems like sources aren't loaded properly when SY loads into a screen other than the default

**Comment by jobobby04** [comment]
Known Main Tachi issue, I would not be surprised if it was more prevalent in SY since it does a few extra things in source init, but they are needed. But the root cause is still main Tachi
