### ISSUE TITLE
MangaPlus chapters inside MangaDex delegation show incorrect dates

### ISSUE THREAD

**Issue by curche** [jobobby04/TachiyomiSY#936]
### Steps to reproduce

1. Open a mangaplus licensed manga in mangadex
2. Observe the dates for the latest chapter released under mangaplus group

### Expected behavior

The dates correspond to dates seen on mangadex website

### Actual behavior

The date is set to end of unix time

![](https://cdn.discordapp.com/attachments/566585518171881493/1141971765803888700/Screenshot_2023-08-18-09-45-52-83_a603e4da04bada03cae438f177815547.jpg)

### Tachiyomi version

528

### Android version

13

### Device

Samsung Galaxy Note 10 Lite

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Ah I should have been more clearer
mangadex.org uses the `readableAt` date value instead of `publishAt` (Ref: [Timestamps in MangaDex](https://api.mangadex.org/docs/01-concepts/timestamps/))
Neko and Tachiyomi Extension use the same but Sy's MangaPlus dates were never changed

**Comment by jobobby04** [comment]
I checked Tachiyomi extensions, and it uses the same as SY, publishAt

**Comment by jobobby04** [comment]
Neko does use readableAt though

**Comment by curche** [comment]
Ah my bad, its not really required when you're filtering out external urls. Without external urls, there's no difference between readableAt and publishAt but I shall confirm

**Comment by jobobby04** [comment]
Will be fixed in the new build.
