### ISSUE TITLE
Invalid Igneous Cookie - ExHentai 

### ISSUE THREAD

**Issue by PhantomNimbi** [jobobby04/TachiyomiSY#938]
### Steps to reproduce

Attempt to search for something from ExHentai

### Expected behavior

Should display some results

### Actual behavior

Displays the following error:

Invalid igneous cookie, try re-logging or finding a correct one to input in the login menu.

### Tachiyomi version

1.9.3

### Android version

Android 13

### Device

Samsung Galaxy S20+ 5G

### Other details

This issue happens in both the stable and beta releases. I've also attempted to set my tags, but it simply displays a blank screen.

Here is a screenshot of the error screen:
![Screenshot_20230819_183021_TachiyomiSY](https://github.com/jobobby04/TachiyomiSY/assets/17615050/7c1d56d6-8305-4071-9719-584add71f171)

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Turhvjbufv** [comment]
Happens when igneous cookie value is "mystery", when do you create your eh account?

**Comment by PhantomNimbi** [comment]
> Happens when igneous cookie value is "mystery", when do you create your eh account? 

Not sure tbh. I've had it for a while now.

**Comment by Turhvjbufv** [comment]
Try to login to eh from PC every day, and use a cookie manager extensions and try to see what value does the igneous cookie have, if you get something else from "mystery" (like a string of numbers and characters) then copy the cookies to eh login in the app(there is an option on the bottom when you login to put your cookies)

**Comment by PhantomNimbi** [comment]
> Try to login to eh from PC every day, and use a cookie manager extensions and try to see what value does the igneous cookie have, if you get something else from "mystery" (like a string of numbers and characters) then copy the cookies to eh login in the app(there is an option on the bottom when you login to put your cookies)

Sadly, I don't have a PC. I think I may just be stuck with this for exhentai.

**Comment by Turhvjbufv** [comment]
Hmm
Try Firefox nightly with a cookie manager addon

**Comment by jobobby04** [comment]
Have you tried logging in a VPN? Exhentai is known to shadowban some countries if you login there.

**Comment by PhantomNimbi** [comment]
I more or less have up on this. The E-Hentai plugin works without issues, so I swapped back to the regular Tachiyomi. 

ExHentai is simply more hassle than it's worth.

**Comment by jobobby04** [comment]
Regular E-Hentai also works on SY, but w/e
