### ISSUE TITLE
[Bug] <Manga description beside cover in a library no longer shows last updated and start date>

### ISSUE THREAD

**Issue by crusaside** [jobobby04/TachiyomiSY#94]
## Device information
* Tachiyomi version: tachiSY preview r222
* Android version: 10, realme UI 1.0
* Device: realme 3 Pro

## Steps to reproduce
1. First step - click any title in your library
2. Second step - look at the information beside manga cover

## Issue/Request
The area beside cover only shows manga name, author, whether ongoing or completed, and extension source. Earlier it used to show the start date and last updated date as well. please add that back if it's intended. 
It helps us to know whether we should begin reading a manga by looking at the credibility of the source and the frequency of updating chapters. Thanks!

**Comment by joseph619** [comment]
This is the same as the main app, not a Sy issue. I suggest you close this ticket and post it in main app repo.

**Comment by crusaside** [comment]
uh. ok i will, thanks for notifying:)

**Comment by crusaside** [comment]
> This is the same as the main app, not a Sy issue. I suggest you close this ticket and post it in main app repo.

ok i will, thanks for notifying:) but what should i write in the tachiyomi version in the main app issue section??

**Comment by joseph619** [comment]
The same as this one. Now please close the ticket again
