### ISSUE TITLE
E(x)-Hentai not in extension list, causes minor management issue

### ISSUE THREAD

**Issue by JaitinPrakash** [jobobby04/TachiyomiSY#947]
### Steps to reproduce

go to browse section, long press exhentai source and disable. go to extension list.

### Expected behavior

see exhentai in list, enable source, continue with day.

### Actual behavior

no extension listed, cannot fix disabled extension except maybe with full reset.

### Tachiyomi version

Preview r530

### Android version

Android 13

### Device

Note 20 Ultra

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Click the filter button at the top of the source list, you can re-enable it there.
