### ISSUE TITLE
lewd filter does not work on statistics

### ISSUE THREAD

**Issue by Turhvjbufv** [jobobby04/TachiyomiSY#954]
### Steps to reproduce

Add some lewd entries and turn on the "x" on lewd filter in the library(to not show lewd entries) but if you go to statistics, the lewd entries show there in the "in library" and "completed series"(if you have one) and more... 

### Expected behavior

Filter statistics based on if filter is on, off or only lewd

### Actual behavior

Shows lewd entries in statistics 

### Tachiyomi version

tachiyomisy r530

### Android version

Android 12

### Device

s10

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Not sure why you expected lewd filter to work there, it doesn't consider library filters there at all.

**Comment by Turhvjbufv** [comment]
So is there any chance to implement a lewd filter for statistics?

**Comment by jobobby04** [comment]
🤷‍♂️
