### ISSUE TITLE
TachiyomiSy preview r531 crash

### ISSUE THREAD

**Issue by Turhvjbufv** [jobobby04/TachiyomiSY#962]
Open a random entry, read it, exit it and press on the "expand tags and more"  button(kinda look like an arrow pointed down) 
Crash does not always happen, I hope crash logs will help
Android 12 
S10

![tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/12880609/tachiyomi_crash_logs.txt)

Edit:Closing as I don't have the same setup anymore and therefore cannot help

**Comment by JaitinPrakash** [comment]
also experiencing node not yet measured related crashes
