### ISSUE TITLE
Pages preview suddenly not appearing

### ISSUE THREAD

**Issue by patros36** [jobobby04/TachiyomiSY#969]
### Steps to reproduce

Open any entry in exhentai

### Expected behavior

Normally like a week ago, all exhentai mangas had the first 10ish pages as a preview when you opened a manga entry.

### Actual behavior

No entries

### Tachiyomi version

preview r531

### Android version

android 10

### Device

xiaomi mi mix 2s

### Other details

This didn't happen after an update or anything, just from one start to another I noticed the previews disappeared. Didn't see anything in the setting where i could turn this function on/off.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Update.

**Comment by patros36** [comment]
Got it, working now. Thanks!
