### ISSUE TITLE
Mangalib login

### ISSUE THREAD

**Issue by Accaccucka** [jobobby04/TachiyomiSY#973]
### Describe your suggested feature

Add login and sync function for mangalib similar to mangadex

### Other details

Mangalib is one of the largest sites with manga in Russian. Many translation teams upload their projects exclusively to this site. It would be great if it was possible to synchronize bookmarks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/8941

**Comment by e-shl** [comment]
> mangadex

1) there is an API 
2) multilingual and really popular 
*3) indirectly related to the recommendation function

> Mangalib is one of the largest sites with manga in Russian. Many translation teams upload their projects exclusively to this site. It would be great if it was possible to synchronize bookmarks.

1) What other sources have you tried to use to compare?
2) There is no api, but there are admins who struggle with parsing and periodically turn on antiddos. Users are having problems with images, and now.

There are many sources in tachi, and I'm sure everyone wanted their permanent source to be track. But it should be even more amazing.
