### ISSUE TITLE
Restore fail

### ISSUE THREAD

**Issue by suhaien** [jobobby04/TachiyomiSY#982]
### Steps to reproduce

1. Make a backup
2. Clear data
3. Restore backup

### Expected behavior

Backup should restore read chapters, trackers and categories.

### Actual behavior

Only titles are restored. Trackers, categories, reading progress, history fail to restore.
Every title fails with "FOREIGN KEY constraint failed (code 787)".

### Tachiyomi version

Preview r532

### Android version

LineageOS 20 (Android 13)

### Device

Samsung S9

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ruudschouten** [comment]
I'm having the same issue, but I was able to somewhat circumvent it by;
1. importing the backup
2. go through default category and click on every single title until chapters are loaded
3. import the backup again

This should place the manga in the correct categories and set progress and trackers
