### ISSUE TITLE
split tall images does not work with bandwidth hero

### ISSUE THREAD

**Issue by AhmedSamir899** [jobobby04/TachiyomiSY#986]
### Steps to reproduce

when download chapter with my local bandwidth hero sever it does not split it

### Expected behavior

split it if it's tall

### Actual behavior

does not split it

### Tachiyomi version

1.94

### Android version

android 13

### Device

redmi note 10s

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Probably fixed with other changes.
