### ISSUE TITLE
Backups Manually

### ISSUE THREAD

**Issue by KasukeLp23** [jobobby04/TachiyomiSY#987]
### Steps to reproduce

create backup

### Expected behavior

backup is created

### Actual behavior

The application closes unexpectedly

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/13802147/tachiyomi_crash_logs.txt)

### Tachiyomi version

1.9.4 - Preview build: 536

### Android version

Android 13

### Device

Redmi 11s

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Main tachi bug, fixed in the next build
