### ISSUE TITLE
[Bug] Not getting all updates

### ISSUE THREAD

**Issue by vipzzx** [jobobby04/TachiyomiSY#99]
## Device information
* Tachiyomi version: r229
* Android version: Android 10
* Device: Note9

## Steps to reproduce
1. Update library
2. 

### Expected behavior
All manga should be checked and updated if there is an update.

### Actual behavior
A lot of manga not being updated and I have to manually refresh when I notice it in latest update in a source. 

## Other details
![20200912_021956](https://user-images.githubusercontent.com/59638889/92989343-b57cfa00-f4a1-11ea-843e-ab0a664eb74b.jpg)

![Screenshot_20200912-024512_Gallery](https://user-images.githubusercontent.com/59638889/92989392-11478300-f4a2-11ea-93ab-586768b41317.jpg)

**Comment by jobobby04** [comment]
This seems to be a device issue, going to close, and reopen if someone can reproduce it
