### ISSUE TITLE
Feed refreshes after opening any series

### ISSUE THREAD

**Issue by DatHypnoboi** [jobobby04/TachiyomiSY#990]
### Steps to reproduce

1. If you have no sources in the feed, add one
2. Open and close any series from a source in the feed

### Expected behavior

The feed should stay loaded

### Actual behavior

The feed has to refresh every time you open a series from it

### Tachiyomi version

1.9.4 Preview r538

### Android version

Android 14

### Device

Google Pixel 6a

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by iusdfbuisdbfuoduiofwefhwen89w** [comment]
I just updated to the newest preview version (r539) and it happens to me as well. I think I was previously using r536, or maybe a slightly earlier release, and it worked fine. Really annoying bug.

**Comment by Akshat-Shukla** [comment]
Opening any title OR even Source still results in the feed reloading

**Comment by iusdfbuisdbfuoduiofwefhwen89w** [comment]
Feed is still broken in the new updates
