### ISSUE TITLE
Unable to swipe down to refresh extension screen when the list is empty

### ISSUE THREAD

**Issue by ShiroeHikari** [jobobby04/TachiyomiSY#994]
### Steps to reproduce

1. Open app and head to Browse>Extension
2. With an empty list (due to the extension removal), unable to swipe down to refresh the list

ps. swiping down works if the list isnt empty first but will not update to show self added extensions

### Expected behavior

Should be able to swipe down to refresh the page for any self added extensions

### Actual behavior

Unable to swipe down to refresh the extension page when empty

### Tachiyomi version

Stable 1.9.4

### Android version

Android 13

### Device

Redmi Note 12 Pro+

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
https://tachiyomi.org/news/2024-01-09-extensions-removal

**Comment by deepakkumar-n** [comment]
i have done exactly as told in the guide but It's not working for me i have uninstalled all the installed extensions and pasted keiyoushi/extensions for tachiyomisy like mentioned still no extension available i am getting failed to get extensions list please help

![Screenshot_2024-01-09-16-02-40-794_eu kanade tachiyomi sy](https://github.com/jobobby04/TachiyomiSY/assets/154119645/e96726dc-ac3f-4788-b260-7932416b4942)
![Screenshot_2024-01-09-16-02-44-660_eu kanade tachiyomi sy](https://github.com/jobobby04/TachiyomiSY/assets/154119645/b719226e-fd47-4692-802a-3c8d5f1250cb)

**Comment by jobobby04** [comment]
https://github.com/jobobby04/TachiyomiSY/issues/993#issuecomment-1882424718
