### ISSUE TITLE
Failed to get extension list

### ISSUE THREAD

**Issue by SaadKhalid96** [jobobby04/TachiyomiSY#996]
### Steps to reproduce

1. open app 
2. then goto entension list
3. it says Failed to get extension list

### Expected behavior

Failed to get extension list
i have tried lagacy installer but it doesnt work

### Actual behavior

it was working a while back as extension pop outs

### Crash logs

not present

### Tachiyomi version

tachiyomisy 1.9.4

### Android version

android 13

### Device

poco x3

### Other details

this same issue is happening in all other forks

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
https://tachiyomi.org/news/2024-01-09-extensions-removal

**Comment by SaadKhalid96** [comment]
hey thanks for quick reply 
kindly can u  suggest another solution fo this

**Comment by jobobby04** [comment]
Nah

**Comment by jobobby04** [comment]
> Some Recent Frequently Asked Questions
> - Extensions won't be coming back [besides the self hosted ones](https://tachiyomi.org/extensions).
> - This is a permanent change, and will not be reverted.
> - The app is still planning updates.
> The app supports 3rd party repositories of extensions, however exercise caution as there could be malicious actors making those extensions. You as the user need to verify the security and that you trust any repo or extension.
> - We provide no support of the actual 3rd party repositories, or unofficial extensions, or obsolete extensions.

**Comment by Lolen10** [comment]
Wouldn't it be better to remove the preconfigured repository in the next release? Because of this error I can't get other repositories to load. One of the two I tried was already installed before the shutdown of the official repository and It worked like a charm. After the shutdown the custom repository won't load for me anymore.

**Comment by jobobby04** [comment]
Known and fixed for the next build/release
