### ISSUE TITLE
Translate exhentai/e-hentai tags using an external file

### ISSUE THREAD

**Issue by huajideshutiao** [jobobby04/TachiyomiSY#997]
### Describe your suggested feature

Some repositories are built in or allow the user to customize the tags language displayed by exhentai using certain files (such as https://github.com/EhTagTranslation/Database/tree/master/database).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
Wow that's a good idea 🫡
I need it too 🤩
